keybase/kbfs

kbfstool/md_force_qr.go, kbfstool/md_reset.go, libkbfs/conflict_resolver.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/journal_md_ops_test.go, libkbfs/keybase_daemon_local.go, libkbfs/md_journal_test.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/root_metadata_test.go, libkbfs/test_common.go, tlf/id.go
Also fix (de)serialization of team TLF IDs.
Issue: KBFS-2192
=> root_metadata: set latest key gen for team TLF successors

libkbfs/folder_branch_ops.go, libkbfs/state_checker.go, test/simple_test.go
During SyncAll(), we don't want to bother adding resolved paths for
nodes that have already been unlinked, as this will result in the
folderUpdatePrepper attempting (and failing) to find their current
directory entries.
Fixing this exposed an issue with the StateChecker: if a node is
added, modified and removed within a batch, there may be some ops that
have "updates" for BlockPointers that only existed during the batch,
and thus will never make it to the BlockPointer.  It would be better
to somehow edit the list of ops to not reference these blocks, but
that's fairly tricky given that nodes within removed directories could
have moved out before the parent was deleted, and we still need a
record of the original create somewhere.  The self-updates are pretty
harmless, so for now just …
=> folder_branch_ops: don't collect resolved paths for unlinked nodes

libkbfs/delayed_cancellation_test.go
The test passed `repeat 100 ./libkbfs.test -test.run=TestDelayedCancellationEnabled` on my machine, so I assume this is just due to CI slowness (or high parallelism). This PR increases the delayed duration so the flake is less likely to happen. It increases (the major wait time of) the test from 15ms to 50ms, which is not too bad for a single test.
But in the future if this is still flaky, and we don't want to bump it to e.g. 200ms, we should probably just skip this test.
=> increase duration in EnableDelayedCancellationWithGracePeriod

libkbfs/tlf_handle.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, test/dsl_test.go, test/engine.go, test/engine_common.go, test/engine_fs_test.go, test/engine_libkbfs.go, test/teams_test.go, tlf/handle.go, tlf/handle_test.go
This adds handle and DSL tests for single team TLFs, including some new error checking code for handle creation.
Issue: KBFS-2238
=> improve testing for single-team TLFs

libkbfs/block_journal.go, libkbfs/keybase_daemon_rpc_test.go, libkbfs/keybase_service_base.go, libkbfs/reporter_kbpki.go, libkbfs/tlf_journal.go
As of keybase/client#7270, the client no longer uses this field, and
we need to remove it from the protocol now that team TLFs are a thing.
This removes KBFS usage, so that we can remove it from the protocol in
a future PR.
Issue: KBFS-2116
=> libkbfs: don't set the PublicTopLevelFolder arg anymore

libkbfs/keybase_daemon_rpc.go
This just wastes battery on mobile, where the service is in the same
process as KBFS.
Issue: KBFS-2250
=> keybase_daemon_rpc: no need to run keepalives in minimal mode

libdokan/common.go, libdokan/fakeroot.go, libdokan/fs.go
Provides a fake root directory for different SIDs. Should help with:
https://github.com/keybase/client/issues/5490 and more recent issues.
The basic issue is with corporate AV products doing:
1) try to access K:
2) access denied because AV running with different user/permissions
3) goto 1 in a hot loop
To test this patch using  `-mount-flags 0` when mounting kbfsdokan + switch user is the simplest way.
@zanderz is the error folder name ok for you?
=> libdokan: Provide fake root directory for other SIDs

libkbfs/md_ops.go, libkbfs/md_ops_test.go
When trying to verify the MD update that the final update was copied
from, we need to instruct processMetadata to allow unverified keys,
since the last writer user may have been reset.  Do this by altering
the context, because plumbing a boolean through would be too messy.
The included test fails without the rest of the fixes in this PR.
Issue: KBFS-2226
=> md_ops: when a TLF is finalized, always allow unverified keys

libkbfs/rekey_fsm.go
The paper key prompt spamming is because when FBO concludes it would need paper key for rekey to proceed, it not only requests for the paper key, but also writes a MD to mdserver with rekey set at the same time. This causes the mdserver to call `FoldersNeedRekey` into KBFS client, which sends another rekey request into the rekey FSM, which kicks off the FSM into `rekeyStateStarted`. This PR makes sure `prmoptPaper` is not set before possibly shortening the rekey wait timer.
Also I found a bug with `atomic` usage for closing the `reqs` channel. Should've used `CompareAndSwapInt32`. This PR changes it to use a `RWMutex` which is less likely to become a foot gun.
=> fix paper key prompt spamming and race condition during shutdown

libfuse/folderlist.go, libfuse/fs.go
If something on the client tries to make a metadata file under
/keybase or /keybase/{private,public}, it will fail.  But there's no
reason to bother the user with a notification about that, so just
return the bare error code instead of the typed error that will cause
a notification.
Issue: keybase/client#7306
=> libfuse: don't send error notifications for ._ files

kbfstool/md_common.go, kbfstool/md_force_qr.go, kbfstool/md_reset.go, libkbfs/file_data.go, libkbfs/file_data_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/md_util.go, libkbfs/root_metadata.go, libkbfs/util.go
In KBFS-2217, we decided that only root teams would have quotas, and all subteams would share that quota.  Since subteams aren't going to be implemented on the core side for a while, this PR only supports team TLFs, charging all blocks in the team TLF to the team.
Currently the server will reject these requests, since it checks that the chargedTo ID matches the session ID.
Issue: KBFS-2217
=> libkbfs: team TLF blocks should be charged to teams

libdokan/journal_control_file.go, libfs/journal_control_file.go, libfuse/journal_control_file.go, libkbfs/journal_block_cache.go, libkbfs/journal_block_server.go, libkbfs/journal_block_server_test.go, libkbfs/journal_md_ops.go, libkbfs/journal_md_ops_test.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go, test/engine_libkbfs.go, test/teams_test.go
In a future PR, the `tlfJournal` will need to know the team ID
corresponding to a single-team TLF, so that it can check the team's
quota when limiting space, rather than the user's quota.
Unfortunately, getting the team ID here is not very convenient.
This PR plumbs it through when the journal is created in the first
place, if possible.  If not possible, it trusts the MD server to
provide the handle, given a TLF ID.  It saves the team ID to the
journal info file on disk, so it can be used without needing server
access after a restart.
Issue: KBFS-2217
=> tlf_journal: enable single-team journals with team ID

dokan/cgo.go, dokan/filesystem.go, dokan/testfs_test.go, libdokan/fs.go
With this the opened source file is passed from dokan to libdokan.
Makes trying to move invalid sources error out earlier and adds a little extra safety net.
=> libdokan, dokan: Pass opened dokan.File to MoveFile

libkbfs/backpressure_disk_limiter.go, libkbfs/backpressure_disk_limiter_test.go, libkbfs/config_local.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_limiter.go, libkbfs/init.go, libkbfs/journal_block_server_test.go, libkbfs/journal_md_ops_test.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/kbfs_cr_test.go, libkbfs/quota_usage.go, libkbfs/semaphore_disk_limiter.go, libkbfs/semaphore_disk_limiter_test.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go, test/engine_fs_test.go, test/engine_libkbfs.go
So that we can compute pressure differently for private TLFs vs team TLFs.
The `tlfJournal` now stores a `ChargedTo` field, rather than a `TID`, so we can treat private TLFs and team TLFs symmetrically.
Also adds team quota support to the quota usage helper class.
Issue: KBFS-2217
=> backpressure_disk_limiter: track quotas by UserOrTeamID

libkbfs/reporter_kbpki.go
I think maybe the Dolphin windows manager or Nautilus does automatic
lookups on /keybase/private/folder when you click open a folder
through the GUI.
Issue: keybase/client#7304
=> reporter_kbpki: avoid notification for "folder" user

test/teams_test.go
At the end of the `as` clause, bob does a SyncAll.  But we also need
to do a flush before alice can see the new data, since bob is using a
journal.
Issue: KBFS-2260
=> test: wait for journal to flush in TestTeamsTwoWritersJournal

libkbfs/folder_branch_ops.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go, test/simple_test.go
Once we clear the cache info for the file, they shouldn't be considered dirty anymore.
Also add test infrastructure to be able to check dirty paths from the DSL tests.
Issue: KBFS-2272
=> folder_branch_ops: remove unlinked files from dirty list

libkbfs/identify_util.go, libkbfs/keybase_daemon_local.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, vendor/github.com/keybase/client/go/libkb/assertion.go
@maxtaco says it's better if we always resolve/identify team names with a "team:" prefix, to make things easier for the service, and to allow us to split the namespaces someday in the future if we want.
Also adds a hack in vendor that we need until CORE-5376 is complete (at which point I'll revert the hack's commit and revendor libkb).
Issue: KBFS-2275
=> libkbfs: identify/resolve team names with a "team:" prefix

Jenkinsfile, libkbfs/block_ops.go, libkbfs/block_ops_test.go, libkbfs/block_retrieval_queue.go, libkbfs/block_retrieval_queue_test.go, libkbfs/block_retrieval_worker.go, libkbfs/block_retrieval_worker_test.go, libkbfs/disk_block_cache_test.go, libkbfs/init.go, libkbfs/kbfs_ops_test.go, libkbfs/prefetcher_test.go, libkbfs/test_common.go
I believe this is ready for review. I refactored the code a bit to spawn fewer goroutines in general, and I made the channel semantics more sane. The worker actually does the work now.
I'm also running the tests a bunch of times to minimize the likelihood of flakes.
=> [KBFS-1895] Prefetching Workers

libkbfs/folder_branch_ops.go, libkbfs/key_manager_test.go, libkbfs/rekey_fsm.go
Approach as discussed on [slack](https://keybase.slack.com/archives/C055SBA3H/p1497911382463613).
Also, remove the explicit rekey cancellation in key manager tests.
=> unset paperkey prompt if another deivce has serverd the rekey request

libkbfs/kbfs_ops.go
Even on a status error (which is ignored otherwise).  Otherwise the
listeners won't get notifications when the status changes, and they
won't force-fast-forward cleared folders when a login happens.
Issue: keybase/client#7475
=> kbfs_ops: Status() should always return the status channel

libkbfs/config_local.go
So it doesn't waste CPU on mobile.
Suggested by patrickxb.
Issue: KBFS-2288
=> config: turn off the metrics registry in minimal mode

ioutil/write_serialized_file.go, kbfscodec/codec.go, libkbfs/disk_journal.go
ioutil.WriteFile can lead to empty files if there's a crash or a disk
error (like out of space) at the wrong time.  Instead, overwrite and
truncate the existing file.  This has the same risk of partial OS
writes leading to corrupted files, without the risk of truncating a
non-empty file.
Issue: KBFS-2289
=> ioutil: add WriteSerializeFile helper function

libkbfs/md_ops.go, libkbfs/md_util.go
MDs fetched from remote servers are already cached in
`MDOpsStandard.processMetadata()`, and if the MDs are fetched from our
local journal, we risk a race condition by caching them here.  (See
details in KBFS-2224.)
Also add some debugging to `MDOpsStandard` to see the MD ID of a
newly-put revision.
Issue: KBFS-2224
=> md_util: don't cache MDs in `getMDRange()`

libkbfs/dirty_bcache.go, libkbfs/dirty_bcache_test.go, libkbfs/folder_block_ops.go
KBFS-2295 details a race that happens when `CreateFile` calls `folderBlockOps.Write()` while holding `mdWriterLock` and blocks due to a full dirty bcache, and the background flusher can't sync anything because it needs to grab `mdWriterLock`.  This PR fixes it two ways:
* Blocked writes now time out based on contexts timing out (not sure how we missed this before).
* 0-byte writes, like the ones made from `CreateFile`, don't need to block at all.
I toyed with the idea of moving the `Write` call outside of the `CreateFile`, but a bunch of stuff depended on transactional semantics there and it seemed too complicated.
Issue: KBFS-2295
=> libkbfs: avoid deadlock between `CreateFile` and `backgroundFlusher`

libfuse/dir.go, libkbfs/bare_root_metadata_v2.go, libkbfs/bare_root_metadata_v3.go, libkbfs/data_types.go, libkbfs/folder_block_manager.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/kbpki_client_test.go, libkbfs/key_manager.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/md_journal.go, libkbfs/md_journal_test.go, libkbfs/mdserver_local_shared.go, libkbfs/mdserver_memory.go, libkbfs/mdserver_tlf_storage.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/root_metadata_test.go, libkbfs/test_common.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
Both KBFS and the service have team caches.  Cached info is generally invalidated by lazy messages sent via the server, but these may not arrive in time or at all in some scenarios.  In those cases, the client can specify exactly what information it is trying to validate, and if that info doesn't match what's in the cache, it can force the service to check with the server to get the most up-to-date information.
In particular:
* When trying to decrypt a team TLF MD encryted with a particular keygen, we need to check whether that's a known keygen yet.
* When trying to verify that a user + verifying key is a valid writer for a team TLF, we need to verify both that the verifying key is currently valid for the user, _and_ that the version of the user that contains that verifying key is a …
=> keybase_service_base: use refreshers to bust service and local team caches

kbfssync/semaphore.go, libkbfs/backpressure_disk_limiter.go, libkbfs/backpressure_disk_limiter_test.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_limiter.go, libkbfs/semaphore_disk_limiter.go, libkbfs/semaphore_disk_limiter_test.go, libkbfs/tlf_journal.go
This cleans up the disk limiter to be less tightly coupled to its usage.
* Methods now take as a parameter the tracker type they affect, and have been renamed to describe what they do to the tracker rather than where they are called.
* Some methods have been consolidated so that we don't have duplicated functionality across tracker types.
* There is now an overall tracker that tracks overall Keybase usage. This means trackers no longer depend on each other, instead treating the `overallTracker` as a single source of truth for the aggregate Keybase data usage.
Sorry this took so long; I had lots of corner case accounting bugs that I needed to fix because I put too many changes in at once before testing (consolidating and introducing the overall tracker accounting).
=> [KBFS-2291] Disk Limiter Refactor

libkbfs/count_meter.go, libkbfs/count_meter_test.go, libkbfs/disk_block_cache.go, libkbfs/meter_snapshot.go
This correctly tracks disk block cache stats over the past 1, 5, 15 minutes, and overall.
=> [KBFS-2309] Count Meter

libkbfs/backpressure_disk_limiter.go, libkbfs/disk_block_cache.go, libkbfs/disk_limiter.go, libkbfs/interfaces.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go, libkbfs/quota_usage.go, libkbfs/semaphore_disk_limiter.go
This fixes two quota issues noticed by @jzila:
1. The very first call to `EventuallyConsistentQuotaUsage.Get()` wasn't blocking when `blockTolerance` is very high.
2. If `.kbfs_status` was checked before any writes, the quota status wouldn't be filled in.
Issue: KBFS-2314
=> libkbfs: fix two quota issues on startup and first block put

libkbfs/data_types.go, libkbfs/dir_entry_test.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/kbfs_ops_test.go, libkbfs/prefetcher_test.go
To help track which user wrote which file in a team TLF.
Noticed by @jzila.
=> data_types: add `EntryInfo.TeamWriter` field

libkbfs/kbpki_client.go, libkbfs/keybase_service_base.go
Just noticed we're iterating over a user's map of revoked keys for no reason.
=> kbpki_client: clean up revoked keys usage

libkbfs/journal_server_test.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_util.go, libkbfs/mdserver_remote.go
In at least two user reports, the client has gotten into a state where
journaling is not enabled, because the journal thinks it doesn't have
a current UID even though the user is logged in. This happens when
the KBFS init code can't connect to the service to check the current
session (e.g., because the service is still restarting or down/slow
for some reason). Later when KBFS does connect to the service, there
is no "logged in" notification (because the user was already logged
in), and so journal-enabling is never reenabled.
This PR executes the logged-in code whenever a new session is noticed,
not just when a new "logged in" notification comes in.
Issue: KBFS-2315
=> keybase_service_base: call `serviceLoggedIn` on new session

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit_android.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit_nix.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit_windows.go, vendor/vendor.json
This pulls in the changes that call `libc::res_init` on DNS failure, to avoid getting stuck in the `host not found` loop.
r? @strib
=> govendor update rpc and add resinit

libkbfs/interfaces.go, libkbfs/journal_md_ops.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mdcache.go, libkbfs/tlf_journal.go
We hit a test flake where the journal contained an unmerged MD update that conflicted with the server's MD update (but the conflict wasn't yet known).  Then the test infrastructure called `kbfsOps.getMaybeCreateRootNode`, which called `JournalMDOps.GetForHandle()`, which fetched the server's version for that revision and overwrote the value we had already cached.  Then CR ran and based the new branch on the server's MD by reading it out of the cache, even though it should have been based on the local version, and there was a failure.
This PR deals the problem in two different ways.
1. `JournalMDOps.GetForHandle` shouldn't cause the server's MD to be cached when it's just trying to look up the TLF ID.
2. We shouldn't overwrite existing items in the cache that were created locally; upper …
=> journal_md_ops: be careful with caching in `GetForHandle`

libkbfs/bare_root_metadata_v2.go, libkbfs/bare_root_metadata_v3.go, libkbfs/data_types.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/md_journal_test.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go
Instead of just the seqno, which can be predicted/guessed.
This PR assumes we want to include the merkle root in the MD ID forever.  If this goes in, a future PR (for KBFS-2271) will add an "eventually consistent" caching layer for the merkle root to avoid a server RTT when setting this fields during foreground writes, in most cases.
Issue: KBFS-2296
=> libkbfs: store the full Merkle root in the MD update

libdokan/fs.go, libfuse/fs.go, libkbfs/kbfs_ops.go, libkbfs/md_ops.go
This "soft-launches" teams by making it possible to `cd` into `/keybase/team` if you know it's there, but `ls /keybase` still won't show it.  Additionally, this enables manual favoriting of team directories.  (The server already auto-favorites for team members, but maybe someone will delete a team favorite and want to re-add it.)
Also, this turns off team-membership-checking on MD updates that have been fetched from the server, until our merkle story is implemented.  This matches what chat does for team membership checking.
Issue: KBFS-2319
=> teams: allow `/keybase/team` lookup and don't check team membership for fetched MDs

libkbfs/fetch_decider.go, libkbfs/fetch_decider_test.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/keybase_service_base.go, libkbfs/merkle_root.go, libkbfs/quota_usage.go, libkbfs/util.go
This PR factors out the existing logic in `EventuallyConsistentQuotaUsage` into a common helper struct, and uses it to construct a cache for the service Merkle root.  The goal is to keep the server RTT for fetching the merkle root from blocking foreground writes.  Currently, `SyncAll` absorbs this RTT when the service needs to fetch from the server, and `SyncAll` blocks foreground writes.
This also improves the fetching logic by making sure there's only ever one outstanding fetch; subsequent blocking fetches wait for the outstanding fetch to complete.
`folderBranchOps` signals that it needs the merkle root as soon as a write comes in.  Hopefully, 1 second later when `SyncAll` is called, the merkle root will be in the cache and ready to be used.
Issue: KBFS-2271
=> libkbfs: introduce eventually-consistent merkle root cache

libkbfs/folder_branch_ops.go
The previous one was just supposed to be a placeholder; it only tracks
the actual update time if the root directory was updated (and the
user's clock is synced).
Issue: KBFS-2321
=> folder_branch_ops: fix the timestamps in update history

libfuse/folderlist.go
Otherwise, certain errors can cause a panic.
Found by @modalduality.
=> libfuse: handle singleTeam type in  `PathType`

libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go
The rename fix is a long-existing bug I just noticed.
Issue: KBFS-2340
=> folder_block_ops: don't list .kbfs_git entry, and don't allow renames to prefixes

libkbfs/conflict_resolver_test.go, libkbfs/folder_block_manager.go, libkbfs/folder_branch_ops.go, libkbfs/folder_branch_status_test.go, libkbfs/interfaces.go, libkbfs/journal_md_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/md_journal.go, libkbfs/md_journal_test.go, libkbfs/md_ops.go, libkbfs/md_util.go, libkbfs/mdcache.go, libkbfs/mdcache_test.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/tlf_journal.go
Previously, we were relying on the last writer's device key, and whether or not journaling was enabled, to decide whether an MD had been fully merged to the server.  But once we have multiple processes writing to the same TLF, using the verifying key will no longer be an effective way to decide whether the MD has been merged to the server or not.
Instead, keep track of this status in a local field in each `ImmutableRootMetadata`, which can be set to `false` for MDs written to or read from the journal, and switched to `true` once the MD is successfully put to the server.
Issue: KBFS-2341
=> libkbfs: use field in `ImmutableRootMetadata` to track whether an MD has been put

libkbfs/data_types.go, libkbfs/folder_branch_ops.go, libkbfs/init.go, libkbfs/md_util.go, libkbfs/mdserver_remote.go, libkbfs/tlf_edit_history.go
This mode is to be used by standalone KBFS programs, like the upcoming git remote helper, that don't need to keep a TLF update to date or rekey anything.
"single op" mode differs from default mode by:
* Not subscribing to folder updates.
* Not checking for rekeys.
* Not suppressing prefixes that are normally disallowed, on the assumption that the names will be controlled by the program implementing the single operation.
Issue: KBFS-2342
=> libkbfs: add a new "single op" init mode

libkbfs/config_local.go, libkbfs/data_types.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/kbpki_client.go, libkbfs/keybase_service_base.go, libkbfs/mocks_test.go, libkbfs/tlf_handle.go, libkbfs/tlf_handle_test.go, libkbfs/util.go, test/engine_common.go, test/teams_test.go
* The `chargedTo` of a subteam TLF is the subteam's root team ID
* When using libkb to parse subteam names, they must be prefixed with "team:", otherwise the parser gets confused since usernames can't have dots in them.
=> libkbfs: support subteam TLFs

libkbfs/mocks_test.go
This is what broke our master builds I think. I just did `go get -u github.com/golang/mock/gomock github.com/golang/mock/mockgen` and re-ran `./gen_mocks.sh` in `libkbfs`
=> update gen_mock since upstream mock generator has updated

libfs/file_info.go, libfs/fs.go, libfs/fs_test.go
Symlinks complicate all the other path-based operations, so this
involved a bit of a refactor.
Issue: KBFS-2338
=> libfs: symlink support in the billy FS layer

libkbfs/bare_root_metadata_v2.go, libkbfs/bare_root_metadata_v3.go, libkbfs/root_metadata_test.go
Oops.
The test fails without this fix on the final line.
Issue: KBFS-2381
Issue: keybase/client#8188
=> root_metadata: fix v2->v3 upconversion for conflict TLFs

kbfsgit/fs_test.go, kbfsgit/git-remote-keybase/main.go, kbfsgit/runner.go, kbfsgit/runner_test.go, kbfsgit/start.go, kbfsgit/storer.go
This may not cover all corner cases, but it works for simple cases. It sets the local repo as a "remote" in the bare repo, and pushes from the bare repo into this "remote".  go-git requires pushing to a ref name, but `git` gets upset if you push into the refname it's expecting, so we have to use a temporary name and then delete it afterwards.
Issue: KBFS-2353
=> kbfsgit: support list and simple fetches

Jenkinsfile
There seems to be a go build parallelism issue when both the `git-remote-helper` and `kbfsgit` directories are built in parallel.
=> Jenkins: prebuild gogit dependencies

kbfsgit/git-remote-keybase/dup_stderr_dummy.go, kbfsgit/git-remote-keybase/dup_stderr_nix.go, kbfsgit/git-remote-keybase/dup_stderr_windows.go, kbfsgit/git-remote-keybase/main.go, kbfsgit/runner.go, kbfsgit/runner_test.go, kbfsgit/start.go
Git remote helpers can print status messages on stderr that will be
displayed to the user.  This should have been easy, but
`client/go/logger` duplicates and closes the stderr file descriptor
that the program starts with.  So, before that happens,
`git-remote-keybase` needs to duplicate the original stderr in a
platform-specific way, before it gets redirected into a log file.
A future PR will print more useful status messages (e.g., "M/N objects
uploaded", etc).  But these simple messages are still useful.  Example
output on Linux:
```
$ KEYBASE_RUN_MODE=staging git clone keybase://private/strib/test12
Cloning into 'test12'...
Initializing KBFS... done.
Syncing to Keybase... done.
Fetching data from Keybase... done.
Checking connectivity... done.
```
Issue: KBFS-2385
=> kbfsgit: simple status messages during operation

libkbfs/path.go, tlf/id.go
Steve's KBFS was in a crash loop. He said he revoked a device hours ago. I think this is the correct fix for the crash as shown in the log, but I'm not sure if it'd crash somewhere afterwards.
Log send: https://keybase.io/_/admin/logdump_viewer?39510239#acad1c98d3388ec687e99b1c
=> fix panic during conflict resolution

kbfsgit/runner.go, vendor/gopkg.in/src-d/go-git.v4/options.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile/encoder.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/common.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/encoder.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/revlist/revlist.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/status.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/object.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/server/server.go, vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/writers.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go, vendor/vendor.json
This prints out progressive counters in the terminal during kbfsgit operations.  It's not perfect, but it help shows what kbfsgit is spending time on.
Note that the go-git changes aren't committed or code-reviewed by anyone there, and might need to change significantly in the future. But I think we can commit them here for now to help make kbfsgit more usable for dogfooding.  (No need to review those vendored changes here, unless you want to.  I'll get people on that project to take a look.)
A push now looks like this (the numerators increase during operation):
```
$ KEYBASE_RUN_MODE=staging git push
Initializing Keybase... done.
Syncing with Keybase... done.
done.
Counting 2 objects... done.
Preparing: 2/2 objects... done.
Indexing hashes: 2/2 objects... done.
Indexing CRCs: 2/2 …
```
=> kbfsgit: progress status messages for fetch and push

libkbfs/bcache.go, libkbfs/block_ops.go, libkbfs/block_retrieval_queue.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/folder_block_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
This PR passes through whether prefetches for a block are done.
It's not pretty, but to make it nice it'll need a much larger refactor where we combine the block retriever and prefetcher. The components are too tightly coupled right now and there's too much back-and-forth.
Missing:
* Persisting the sync state for a TLF (incoming PR soon)
* Correctly updating the `finishedPrefetch` state of a block when it wouldn't trigger prefetches itself (as in unsynced TLFs). This is not as high priority because blocks in the unsynced disk cache can be deleted arbitrarily.
=> [KBFS-2364] Track whether prefetches are done for a block

libkbfs/disk_block_cache.go
This is needed to make the sync cache work properly for people with content in their working set disk cache.
=> [KBFS-2402] Fix working set cache status

kbfsgit/git-remote-keybase/main.go, kbfsgit/runner.go, kbfsgit/runner_test.go, libkbfs/journal_server.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
Single op mode allows an application to tell the journal not to flush any blocks until after the application has signalled its work is finished.  It may flush blocks in the meantime.  Then, the MDs and remaining blocks are squashed into a single revision and put to the server, so all the changes in the single op show up atomically to other TLF readers.
Using this mode in `kbfsgit` ensures that no partially-written git states are seen by other readers, and also waits for any conflict resolutions to complete.
Issue: KBFS-2379
=> tlf_journal: add single op mode and use it in kbfsgit

Jenkinsfile, appveyor.yml, kbfsgit/runner.go, libgit/config.go, libgit/id.go, libgit/repo.go, libgit/repo_test.go
This PR refactors the kbfsgit code a bit to move repo directory creation into its own library, because that part will likely be used by the kbfsfuse/kbfsdokan binaries upon a request from the GUI to create a repo.
The service also requires a stable random ID per repo, and KBFS will be the source of truth for that ID.  So we write that ID to a new config file in the repo, so we can always retrieve it.
This also adds some restrictions on repo names, and normalizes names by lower-casing them.  It preserves the original casing of the name in the kbfs repo config file, in case we want to display it that way in the GUI.
Issue: KBFS-2389
=> libgit: generate repo IDs and check repo names

kbfsgit/runner.go, kbfsgit/runner_test.go, kbfsgit/start.go
With these changes, if '-q' is given to a git command, git-remote-keybase will print (almost) nothing to stderr.  If '-v -v' is given, it will print timing measurements after each phase, to help with debugging.
Sample clone output with '-v -v':
```
KEYBASE_RUN_MODE=staging git clone -v -v  keybase://private/strib/test12
Cloning into 'test12'...
Initializing Keybase... done.
Syncing with Keybase... done. [1.803462194s]
Counting: 36 objects... done. [944.830662ms]
Reading: 36/36 objects... done. [58.81333ms]
Sorting... done. [111.516µs]
Calculating deltas: 36/36 objects... done. [165.307µs]
Fetching: 36/36 objects... done. [10.526864ms]
Checking connectivity... done.
```
=> kbfsgit: support verbosity and progress options, and print timing

libkbfs/bcache.go, libkbfs/block_ops_test.go, libkbfs/block_retrieval_queue.go, libkbfs/disk_block_cache.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_status.go, libkbfs/kbfs_ops_test.go, libkbfs/prefetcher.go
Do this so the monitoring doesn't get canceled.
=> block_retrieval_queue: Monitor prefetches in a separate context

vendor/gopkg.in/src-d/go-git.v4/config/config.go, vendor/gopkg.in/src-d/go-git.v4/options.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/encoder.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit_walker.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/revlist/revlist.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/server/server.go, vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/gopkg.in/src-d/go-git.v4/repository.go, vendor/vendor.json
* Speeding up "Counting" phase: src-d/go-git#586
* Allowing us to skip delta compression (not used yet): src-d/go-git#587
=> vendor: pull in more go-git optimizations

kbfsgit/runner.go
If you tried to push more than one branch/tag at once, kbfsgit would hang because after the first refspec, the statusChan would get a Done event and stop processing more events, eventually causing go-git to block.
Instead let's just push the whole batch at once, like we're supposed to.  I was previously worried that this would mean we wouldn't have a unique error for each branch, but now I don't think that's a big deal. We'll just use the same error for all destinations in a batch.
=> kbfsgit: push multiple refspecs in a batch, fixing hang

kbfsgit/start.go, libkbfs/config_local.go, libkbfs/folder_branch_ops.go, libkbfs/folder_branch_status.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/journal_server_test.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go, libkbfs/quota_usage.go
The journal also needs to calculate its limits based on the default block type.
kbfsgit uses the GIT block type as its default.  Everything else uses DATA.
Note that this shouldn't get merged until keybase/kbfs-server#383 is merged and deployed.  But it can be reviewed now.
Issue: KBFS-2366
=> libkbfs: allow a default block type and use everywhere

kbfsgit/runner.go, kbfsgit/runner_test.go
The only reliable way to tell if the calling `git` process has been ctrl-c'd is if `stdin` is killed.  If that happens before the remote helper gets a blank line command, then the remote helper should exit immediately.
Accomplish this by processing individual commands in a separate goroutine (via a channel), and interrupt that goroutine when EOF is read from stdin.
The added test hangs without the rest of the commit.
Issue: KBFS-2408
=> kbfsgit: interrupt on `git` control-C when stdin is closed

kbfsgit/git-remote-keybase/main.go, kbfsgit/runner.go, kbfsgit/start.go, libdokan/start.go, libfuse/start.go, libgit/config.go, libgit/init.go, libgit/repo.go, libgit/repo_test.go, libgit/rpc.go, libkbfs/init.go, libkbfs/keybase_daemon.go, libkbfs/keybase_daemon_rpc.go, libkbfs/keybase_service_base.go, libkbfs/util.go, tlf/id.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/git.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
This implements the new `CreateRepo` RPC expected by the service, which creates a repo and errors if the repo already exists.  This is to be served by the existing kbfsfuse/kbfsdokan daemon.
To avoid blocking on any big transfer currently in the journal, this spins up a completely new `Config`, with a journal in a temporary directory, just like the `git-remote-keybase` command does.  This PR refactors some of that code to share between the two paths.
To avoid import cycles, I needed to use the same trick as `SimpleFS` to pass an RPC interface creation hook to the keybase daemon, rather than importing `libgit` directly.
I also added some extra data to the config file that seems like it would be useful to record in the long run, and we're now marshaling it with indentation so it's easier to …
=> libgit: implement CreateRepo RPC

libgit/repo.go, libgit/repo_test.go
Looks like the UI will recommend people put this in their clone URLs, like GitHub does.  Just ignore it.
=> libgit: ignore ".git" suffix

kbfsgit/git-remote-keybase/main.go
And warn if running in a non-prod mode.
=> git-remote-keybase: default to production run mode

libfs/fs.go, libfs/fs_test.go
Apparently go-git assumes this, but it's not documented anywhere. Without this change, we're unable to push branches with "/" in their names.
Issue: KBFS-2430
=> libfs: OpenFile should create any missing parent directories

libfs/file.go
These are very frequent, and pretty useless compared to the KBFS debugging.  Removing them reduces the "Preparing" time of a push by 30% in my test.
Issue: KBFS-2390
=> libfs: remove file debugging messages

libgit/init.go, libkbfs/init.go
With this commit, you can turn off KBFS debugging by setting
KBFSGIT_DEBUG=0 in your environment.
Note I had to move the `NewWithCallDepth` line below the
`SetLogFileConfig` line, because the latter call erases all the
default INFO levels set by the keybase logger whenever a new log is
made.
Turning off debugging completely reduced the time of the "Preparing"
phase by 52% (31% compared to #1176), but I don't think we want to do
this by default until we're more comfortable with git.
Issue: KBFS-2390
=> kbfsgit: allow debugging to be turned off with an env var

kbfsgit/runner.go
@malgorithms and @songgao suggested some tweaks to the output the user sees.  Here's what things look like now:
Clone:
```
Cloning into 'test20'...
Running in staging mode
Initializing Keybase... done.
Syncing with Keybase... done.
Counting: 64.03 MB... done.
Cryptographic cloning: (56.97%) 36.48/64.03 MB... 
```
Push:
```
Initializing Keybase... done.
Syncing with Keybase... done.
Syncing data to Keybase: (100.00%) 21.22/21.22 KB... done.
Counting and decrypting: 35.38K objects... done.
Preparing and encrypting: (100.00%) 35.38/35.38K objects... done.
Indexing hashes: (100.00%) 35.38/35.38K objects... done.
Indexing CRCs: (100.00%) 35.38/35.38K objects... done.
Indexing offsets: (100.00%) 35.38/35.38K objects... done.
Syncing data to Keybase: (100.00%) 1.04/1.04 MB... done.
To …
```
=> kbfsgit: humanize byte and object counts, add percentages, and tweak stderr wording

kbfsdokan/defaults_production.go
This keeps the split installer, currently shipping, from working.
@taruti 
Tagging @maxtaco because @strib is away.
=> Don't default to force mount in production for kbfsdokan

libkbfs/folder_branch_ops.go
@mmaxim found out this one; As mentioned in keybase chat:
> without some kind of change there, chats that need rekey will just be slower to update, since when we get this notification, we fail to load the chat, and we just have to rely on our timer to pick up the success later
(Using `rekeyDone` instead of `!stillNeedsRekey` because I think with read-only shares it's possible that rekey has been done on a device, but we still need some work from another device.)
=> avoid sending notification to service if we only set rekey bit

libdokan/start.go, libfuse/start.go, libgit/rpc.go
Mobile doesn't set the run mode environment variable, but passes it directly in via a context.  So libgit shouldn't rely on env.NewContext() for the right context, it should be passed in.
We will need to update `client/go/bind/keybase.go` to call the new constructor once this is merged.
Issue: KBFS-2458
=> libgit: allow caller to pass in a context, instead of using env

Jenkinsfile
CI messed up something, disable Linux tests until I can investigate. macOS tests are still running.
=> jenkinsfile: Disable linux tests for now.

kbfsgit/runner.go, kbfsgit/runner_test.go
If a repo is empty, then the HEAD symref file points to a ref that
doesn't exist yet (refs/heads/master).  We need to suppress that
symref during a list, otherwise git will get confused.
Issue: KBFS-2460
=> kbfsgit: handle empty git repos by not listing symrefs

libgit/repo.go, libgit/repo_test.go
This will catch an empty name before we try to create any blocks for it.
Issue: KBFS-2466
=> libgit: check for valid repo name earlier

kbfsgit/on_demand_storer.go, kbfsgit/runner.go, kbfsgit/runner_test.go, libfs/file.go, libfs/fs_test.go, libkbfs/folder_branch_ops.go, libkbfs/mdserver_memory.go, libkbfs/tlf_journal.go, vendor/gopkg.in/src-d/go-git.v4/options.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/encoder.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/object.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/reference.go, vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/gopkg.in/src-d/go-git.v4/repository.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/reference.go, vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go, vendor/gopkg.in/src-d/go-git.v4/worktree.go, vendor/vendor.json
go-git depends on getting on error from `EncodedObject()` when an object is missing, especially when constructing the set of "ignored" objects.  This is the set of objects that the local git repo already has. and there's no need for them to exist in the kbfs git repo. go-git allows objects to be missing when constructing that ignored list, but we were hiding that error in onDemandObject.cache(). Instead, we should surface it during `EncodedObject`, but without fully reading all object data from disk, which would negate the point of previous optimizations.
This is based on #1188, which vendors in go-billy master.  This also vendors in go-git master, which pulls in the locking code, requiring a small `folderBranchOps` fix.
Issue: KBFS-2445
=> kbfsgit: enable non-force pushes, and onDemandStorer shouldn't hide missing obj error

libkbfs/block_retrieval_queue.go
@jzila: any ideas about this?  I'm not happy that I couldn't figure out the exact reason for the leak, but I can reproduce it consistently without this fix, and can't repro it with the fix.
---------
I noticed a pretty massive leak in KBFS when retrieving blocks from the server.  The heap looked like this:
```
(pprof) top5
2525.69MB of 2578.60MB total (97.95%)
Dropped 959 nodes (cum <= 12.89MB)
Showing top 5 nodes out of 47 (cum >= 20.54MB)
flat  flat%   sum%        cum   cum%
1682.43MB 65.25% 65.25%  1682.43MB 65.25%  github.com/keybase/kbfs/libkbfs.(*FileBlock).DeepCopy
815.25MB 31.62% 96.86%   815.25MB 31.62%  github.com/keybase/kbfs/vendor/github.com/keybase/go-codec/codec.decByteSlice
28.01MB  1.09% 97.95%    28.01MB  1.09% …
```
=> block_retrieval_queue: clear references to requested blocks

kbfsgit/runner.go, libfs/file.go, libfs/fs.go
This PR adds status message in the last step of `git push` where we are flushing data to the server. When pushing a commit that adds a 64MB file, it looks like this now:
```
$ git push origin master
Initializing Keybase... done.
Syncing with Keybase... done.
Counting and decrypting: 3 objects... done.
Preparing and encrypting: (100.00%) 3/3 objects... done.
Indexing hashes: (100.00%) 3/3 objects... done.
Indexing CRCs: (100.00%) 3/3 objects... done.
Indexing offsets: (100.00%) 3/3 objects... done.
Syncing data to Keybase: (100.00%) 63.25/63.25 MB... done.
To keybase://private/songgao,t_alice/git-test
855f70d..9c3108c  master -> master
```
Note that it shows a slightly lower size than the actual data size, because journal flush happens before we start printing status. However to fix this …
=> print "Synching data to Keybase ..." in push

libkbfs/folder_block_manager.go
Otherwise an ill-timed QR MD update can break the journal, which
assumes there will only be no more MD updates once the single op is
marked as finished.
=> folder_block_manager: turn off QR in single op mode

kbfsgit/git-remote-keybase/dup_stderr_windows.go
Bash shells on Windows seem to behave slightly different from the
regular windows shell, in terms of duplicated file handles.  Giving
the new handle the same access as the old handle seems to work well in
both environments.
Issue: KBFS-2481
=> git-remote-keybase: fix windows dup handle for git bash shell

kbfsgit/runner.go, kbfsgit/runner_test.go, libfs/fs.go, vendor/gopkg.in/src-d/go-git.v4/options.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/reference.go, vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/reference.go, vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go, vendor/vendor.json
This PR adds optimizations for the case where the user has a local repo with a lot of references, and then runs a `git push --mirror` or `git push --all` to initialize a new KBFS repo from this local repo.
`--mirror` syncs every single local ref to the remote, and so we can optimize by just copying all the objects/refs/packed-refs files themselves, rather than going through expensive go-git computation.  If there is a packed-refs file, this allows us to avoid having a ton of individual refs files, which is slow and might break KBFS's dir size limitations.
`--all` syncs every branch and tags (i.e., `refs/heads` and `refs/tags`). If these are the only types of refs in the local repo, then this is equivalent to `--mirror`.  If not, we can't use the above optimization because there may be …
=> kbfsgit: optimizations for large `push --mirror/--all` initializations

kbfsgit/runner.go, kbfsgit/runner_test.go, libfs/file.go, libfs/fs_test.go, libgit/repo.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/vendor.json
We need to take a lock before creating the repo, when generating the repo ID, so there are no conflicts.  Use ._kbfs_config as the lockfile.
Also, any time we're pushing to a repo we think is empty, we need to create a packed-refs file, even if it's only a single branch, so that we can take a lock on the packed-refs file and ensure the repo only gets that initial push once.
Finally, it turns out that calling WaitForBlockFlush() isn't enough when in single-op mode, because the subsequent call to SyncFromServerForTesting won't bother fetching anything from the server when the local journal still has data in it.  So we have to finish a complete single op, flushing all object files, before taking a lock.
Note that I tried for a long time to come up with a good test for concurrent repo …
=> kbfsgit: lock during repo creation and on packed-refs creation

kbfsgit/runner.go
The object count was printed wrong, and sometimes the stage desc can be empty (e.g., for StatusDone).
=> kbfsgit: fix the "Entering stage" log message

kbfsgit/runner.go
=> kbfsgit: allow lazy repo creation for TLFs with unresolved writers

vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/vendor.json
If the user is doing a push to a branch in the KBFS repo, and the KBFS repo has extra commits not known to the local repo (i.e.., the local user has forked), then go-git was causing way too much data to be transferred because it doesn't fully negotiate the common commits between the two repos.  It simply sends the commits representing all references known by the KBFS repo; the local side wouldn't recognize the new commit from the KBFS branch, and would therefore conclude the user needs to push all commits in its history.  (Note: if the KBFS repo has multiple branches, and at least one of which has a reference with a common commit, then the entire history isn't sent, only the commits up to that common commit, which is still wasteful.)
The right way to improve this is to implement the …
=> vendor: update go-git, so we don't over-transfer on a push

libkbfs/folder_branch_status.go, libkbfs/folder_branch_status_test.go
A user pointed out there was no way to see a team's git usage status. And even for the regular KBFS quota, this is nicer than looking in the limiter status.
Issue: KBFS-2490
=> folder_branch_status: include usage stats

dokan/cgo.go, dokan/error_file.go, dokan/filesystem.go, dokan/testfs_test.go
This is the last piece before the dokan bindings should go to a separate repo.
=> dokan: Use stdlib context package

kbfsgit/config_without_remotes_storer.go, kbfsgit/runner.go, kbfsgit/runner_test.go, libfs/fs.go, libgit/repo.go, libkbfs/test_common.go
This required a few small changes:
* Ignore go-git's attempt to flush the Config file if it hasn't changed from what's already on disk.
* libfs.FS.MkdirAll ignores write-access errors if the dir being created already exists.
Issue: KBFS-2491
=> kbfsgit: allow readers to clone/fetch from repos

kbfsblock/id.go, libdokan/prefetch_file.go, libfuse/prefetch_file.go, libkbfs/block_ops.go, libkbfs/block_retrieval_queue.go, libkbfs/bserver_remote.go, libkbfs/channels.go, libkbfs/config_local.go, libkbfs/data_types.go, libkbfs/disk_block_cache.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go, test/engine_libkbfs.go
This rewrites prefetching. Design is detailed in KBFS-2417, and comments in code extensively detail the cases being handled.
Short story: all prefetches are now triggered and tracked in the primary `blockPrefetcher.run()` goroutine. There are no more goroutines spawned by the block retrieval queue.
Suggested review order:
* prefetcher.go (you may need to view both the raw file and the diff)
* block_retrieval_queue.go
* prefetcher_test.go
* everything else
=> [KBFS-2417] De-duplicate prefetches

appveyor.yml, kbfsgit/git-remote-keybase/dup_stderr_windows.go
And make sure we compile it in appveyor.
=> kbfsgit: fix windows compile for git-remote-keybase

kbfsgit/runner.go
Opening a Repo means trying to unmarshal the local config file, and the scanner used by go-git doesn't seem to be able to scan all valid config files.  Luckily we don't need a Repo, we just needed the Storer, so everything works out for the best.
Issue: KBFS-2497
Issue: keybase/client#8812
=> kbfsgit: avoid opening a Repository for local git dirs

Jenkinsfile, docker.build.jenkins
because `git-remote-keybase` can't rely on `kbfsfuse.sh` to populate it.
Related: https://github.com/keybase/kbfs-server/pull/404
=> populate KEYBASE_TEST_ROOT_CERT_PEM

libkbfs/folder_branch_ops.go, test/complex_test.go
When checking whether or not a node needs to be unlinked on an rmOp or renameOp, `getUnlinkPathBeforeUpdatingPointers()` needs to look at the original dir block, before the update happened, and see whether there's a matching entry or not.  To do this, we need to find the correct block pointer corresponding to the original block.  If this is part of a set of operations that include a `resolutionOp`, we may need to "back up" the block pointer listed in the op itself to find the original block pointer, since the resolutionOp may have changed it.
However, this is only relevant if the op being processed is actually part of the MD; if it's actually a cached dir op instead, and not listed in the MD itself, then the resolutionOp is irrelevant and should be ignored since the pointers in the op …
=> folder_branch_ops: don't back up ptr on unlink for cached dirOp

libkbfs/bserver_remote.go, libkbfs/mdserver_remote.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/vendor.json
so that we don't have multiple `rpc.Connection`s for the same service.
Depends on https://github.com/keybase/go-framed-msgpack-rpc/pull/125
=> use rpc.Connection.ForceReconnect

kbfsgit/runner.go, libgit/repo.go, libgit/repo_test.go, libgit/rpc.go
Run it after every git operation, rather than periodically, because it would be difficult and expensive to build something that crawls *every* TLF for a user to look for repos to delete.
When a repo is deleted, this schedules a background task to clean up the repo after a set amount of time.  If KBFS is shut down before that scheduled task, any other git operation in that folder will trigger a cleanup.  However, if the cleanup blocks a git operation, it is time-limited, and will only delete as many files as it can within a 2 second timeout, so as not to block foreground operation for too long. Subsequent operations will clean up more data, etc, until the full repo is gone.
Issue: KBFS-2442
=> libgit: introduce deleted-repo cleaner

libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go
And if renaming within a directory, only check the difference in the name sizes.
Issue: KBFS-2456
=> folder_branch_ops: check dir size during a rename

libkbfs/disk_block_cache.go, libkbfs/leveldb.go
After writing a 120MiB file:
```
bash-4.3$ cd ~/.local/share/keybase.devel/kbfs_block_cache/v1/diskCacheBlocks.leveldb/
bash-4.3$ ls -lh
total 130292
-rw-r--r--    1 keybase  keybase    50.2M Oct 10 23:43 000077.ldb
-rw-r--r--    1 keybase  keybase     3.5M Oct 10 23:43 000079.ldb
-rw-r--r--    1 keybase  keybase    50.4M Oct 10 23:43 000080.ldb
-rw-r--r--    1 keybase  keybase     3.8M Oct 10 23:43 000082.ldb
-rw-r--r--    1 keybase  keybase    13.2M Oct 10 23:43 000083.ldb
-rw-r--r--    1 keybase  keybase     2.5M Oct 10 23:44 000084.log
-rw-r--r--    1 keybase  keybase     3.6M Oct 10 23:43 000085.ldb
-rw-r--r--    1 keybase  keybase       16 Oct 10 23:37 CURRENT
-rw-r--r--    1 keybase  keybase        0 Oct 10 23:37 LOCK
-rw-r--r--    1 keybase  keybase    16.6K Oct 10 23:43 LOG …
```
=> [KBFS-2513] Allow a bigger leveldb file size for the block db.

libgit/repo.go
We weren't correctly setting the repo ID as the lock namespace when returning an FS for a newly-created.  That would only affect the first push of public and multi-user TLFs that are lazily-created.
Also, factor out the taking of the lock config file into a separate function for clarity, and reuse in a later PR.  Verify that the lock namespace is what we expect it to be, to make sure a bad FS isn't passed in by accident.
Issue: KBFS-2439
=> libgit: always set namespace for returned FS, and refactor a bit

kbfsgit/runner_test.go, vendor/gopkg.in/src-d/go-git.v4/options.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/revlist/revlist.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/common.go, vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/gopkg.in/src-d/go-git.v4/worktree.go, vendor/gopkg.in/src-d/go-git.v4/worktree_status.go, vendor/vendor.json
This change also includes several src-d master fixes.
The go-git PR fixing the packed-refs deletion logic is here (self-reviewed): keybase/go-git#11
Issue: KBFS-2509
=> kbfsgit: update go-git to fix ref deletion from packed-refs, and add test

libfs/fs.go, libgit/repo.go, libgit/repo_test.go
We follow github's logic here:
* Create a symlink from the old repo name to the new name
* However, if someone tries to create a repo using the old name, we
overwrite the symlink.
Issue: KBFS-2439
=> libgit: implement rename repos

libkbfs/backpressure_disk_limiter.go, libkbfs/block_retrieval_queue.go, libkbfs/block_retrieval_queue_test.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
Add a test that regresses KBFS-2499, and fix the failure.
As a bonus, we now have a test that tests the prefetcher and disk cache combined.
=> [KBFS-2499] Don't sync when there's a full cache

kbfsgit/runner_test.go, libfs/fs.go, libkbfs/folder_branch_ops.go
* #1263: add `gitExec` test function
* #1260: clean subdir in `NewFS` if needed
* #954: when removing block states, allow cap of 0
=> kbfs: fix a few nits in git and FBO suggested on other PRs

env/context.go, kbfsgit/git-remote-keybase/main.go
Dialing it seems to be the best platform-agnostic way to check for a running service.  Just checking for the socket file doesn't work on Windows.
If the service isn't running, the user will see:
```
git-remote-keybase error: (1) The Keybase service is not running for this user.
```
cc: @malgorithms 
Issue: KBFS-2514
=> git-remote-keybase: check for a running service

kbfsgit/git-remote-keybase/main.go
Suggested by @malgorithms.
Issue: #1273
=> git-remote-keybase: add platform-specific "missing service" errors

libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops.go
We don't want to return keys to chat that haven't yet been accepted by the server.
Issue: KBFS-2553
=> folder_branch_ops: always send the initial MD straight to server

kbfstool/common.go, libdokan/folderlist.go, libfuse/folderlist.go, libkbfs/data_types.go, libkbfs/key_manager_test.go, libkbfs/tlf_handle.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, simplefs/simplefs.go, test/engine_fs_test.go, tlf/errors.go, tlf/handle.go, tlf/name.go, tlf/name_test.go
... to tlf.
Also move splitTLFName and ReaderSep.
This is so that server code can use this without depending on libkbfs.
=> Move FavoriteNameToPreferredTLFNameFormatAs

libfs/mount_interrupter.go, libfuse/mounter.go
Specifically,
1) Unmount on SIGINT multiple times in case of open file handle. We already try to do this in [`libkbfs.Init`](https://github.com/keybase/kbfs/blob/d1ef47bfbd9135be64da20ea21f80e9098e99bba/libkbfs/init.go#L467-L479). This fixes the MountInterrupter to honor that.
2) Try unmounting and mounting again if initial mounting fails. Previously we only do it when the mount type is force. However, if process is SIGKILL-ed, or we have some bug that crashes the process, we can leave a broken mount point and if we try to mount again we may get an error. So try unmounting it if we get an error regardless. If we fail again, we return the error. The `force` mount type is still useful since it makes us error out and exit as long as mounting fails, while the default one runs without the …
=> mounter changes

libkbfs/journal_server.go
We require a handle to be passed in when enabling a journal for a team TLF, since otherwise we'd have to talk to the (untrusted) server to look up the `chargedTo` ID for the folder.  Previously we panicked when the caller didn't provide a handle.
However there are legitimate callers, like `folderBranchOps.getJournalPredecessorRevision()`, which might try to inadvertently enable a journal without passing in a handle, if they happen to be called before some other `folderBranchOps` function. These callers generally expect an error if the journal is not 
enablable.  So let's turn the panic into an error instead.
Issue: KBFS-2563
=> journal_server: error, instead of panic, if no handle given

kbfsfuse/defaults_production.go, kbfsfuse/main.go, libfuse/mounter.go
In https://github.com/keybase/kbfs/commit/39534e4a6ffe95f84a5480d60b3606112fa93206 , we made default mounter do unmount-then-mount in case of failure too. So the only difference between the default mounter and the force mounter now is the force mounter returns an error causing `kbfsfuse` to exit in case of a mount failure. 
This PR changes the default mount type for production build from `force` to `default` so that we don't get stuck in a crash loop in case of mount failures.
In addition, if mount fails with the unmount-then-mount-again approach too, on darwin we call the installer to reinstall the mountdir and try again. This should cover the case where `/keybase` permission is messed up preventing us from mounting.
=> use default mount type by default and reinstall mountdir if needed

kbfsblock/bserver_constants.go, kbfsmd/server_constants.go, libkbfs/bserver_remote.go, libkbfs/mdserver_remote.go
This is so that servers can use them without depending on
libkbfs.
=> Move server constants out of libkbfs

kbfsgit/on_demand_delta_object.go, kbfsgit/on_demand_storer.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/diff_delta.go, vendor/vendor.json
This adds a custom layer for accessing "delta" git objects, without keeping all the data in memory for the lifetime of the object.  It will be useful once we have git garbage collection, but currently won't be used by `git-remote-keybase` because we set `pack.window = 0` for all kbfs git repos, and so diffs aren't used for pulls at all.
This also vendors in some changes from our fork of `go-git`, which help keep memory stable during delta compression (also not used currently in `git-remote-keybase`).  With these changes I was able to keep memory usage at less than 1.7 GB for the keybase/client repo when calculating diffs, as opposed to 3-4 GB of usage without it.
=> kbfsgit: add on-demand delta objects, and update go-git vendor for memory fixes

libkbfs/folder_branch_ops.go
If `Lookup` returns early, it could write to the return param `node`. But the internal goroutine might still be running, which also tried to write to the `node` param.  This leads to a possible (but really rare) data race.
Instead, have the goroutine write to a temp variable, which is only returned when the `Lookup` is successful.
Issue: KBFS-2579
=> folder_branch_ops: avoid data race in `Lookup()`

libkbfs/mdserver_memory.go
In order to test locking, we need to track which `MDServerMemory` instance took the lock, and block other instances from taking the lock until the holder releases it (or it expires).
Tests that use this behavior will come in subsequent PRs.
Issue: KBFS-2484
=> mdserver_memory: check the lock holder and block lock calls

kbfsgit/runner.go, kbfsgit/runner_test.go, libkbfs/test_stallers.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/reference.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/reference.go, vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go, vendor/vendor.json
* One where a second client updates a reference during ref-packing.
* Another one where a second client deletes a reference during ref-packing.
This adds a `runner.packRefs()` method for now, that is only invoked by testing.  A later PR will call this as part of a larger GC operation.
(Depends on #1302 and keybase/go-git#13.  Will update the commit hash once the latter is merged.)
Issue: KBFS-2517
=> kbfsgit: concurrent PackRefs test

kbfsgit/runner.go, kbfsgit/runner_test.go, libgit/git_config_without_remotes_storer.go, libgit/repo.go
This will eventually be called by a `keybase git gc` command that we will recommend users to run when their repos get too unwieldy.
Unfortunately this drags the go-git dependency into the main kbfsfuse process, but I don't see a way around that.
Depends on #1303 (review that one first!).
Issue: KBFS-2540
=> libgit: add a function for repo garbage collection

libkbfs/bserver_remote.go, libkbfs/init.go, libkbfs/mdserver_remote.go, libkbfs/test_common.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/remote.go, vendor/vendor.json
depends on: https://github.com/keybase/go-framed-msgpack-rpc/pull/126
=> add proritized round robin address list for bserver and mdserver

kbfsgit/runner.go, kbfsgit/runner_test.go, libgit/repo.go
For now, we just check if:
* GC hasn't been run on the repo in the last week.
* There are more than 50 loose refs.
If the check is taking more than a second, it prints "Checking repo for inefficiencies... " to stderr as a progress indicator.
If GC is needed, it prints something like:
```
Tip: this repo could be sped up with some garbage collection. Run this command:
keybase git gc repo
```
Issue: KBFS-2539
=> kbfsgit: check if GC is needed on every fetch/clone/push

kbfsgit/git-remote-keybase/main.go
`git ls-remote` is allowed to be executed outside of a local git directory, so it's wrong to verify the git dir too early.  Instead, rely on `git` itself failing if it executes a command that requires a git dir, outside of a local repo.
Issue: #1325
=> git-remote-keybase: don't check the git dir before taking commands

libkbfs/init.go, libkbfs/keybase_service_util.go
Fix race where service notifications could arrive before the MDServer/BlockServer were initialized.
=> [KBFS-2574] init: Fix service notification race

libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/kbfs_ops_test.go
This PR does a couple different things:
* `folderBranchOps.getMDForReadLocked` doesn't actually require any locks to be taken, so rename it.
* use cached root node in `kbfsOps.getMaybeCreateRootNode` if possible.  `git-remote-keybase` calls this function several times (each time it constructs a `libfs.FS` instance), and there's no reason to check with the servers each time.
* don't fetch unmerged MDs when initializing a TLF in single op mode, because there's basically no way for a TLF to start off as unmerged when in single op mode.
These optimizations bring a simple git push down from 12-14s to 9-10s.
=> kbfs_ops: some optimizations for single op mode (and some cleanup)

libkbfs/init.go
This removes the old server addresses (mdserver.kbfs.keybase.io and bserver.kbfs.keybase.io) from clients, so that they only connect through new addresses. We should get this into an admin release soon, so that next public release will start migrating off the old server addresses.
=> remove old {b,md}server addresses

libkbfs/folder_branch_status.go
Getting the journal status can end up calling into `folderBlockOps` and taking `blockLock`, in order to populate unflushed paths.
However, `folderBranchStatus.rmNode()` can also be called while holding `folderBlockOps.blockLock`, via `folderBlockOps.UpdatePointers()`.  Thus, these two things can interleave and cause a deadlock.
There's no reason to hold the status lock while calling into the journal, so refactor things a bit to avoid this deadlock.
Issue: KBFS-2614
=> folder_branch_status: don't hold locks while accessing journal

libkbfs/folder_branch_ops.go
Fast-forward while dirty can cause the device to unlink unflushed nodes that have been made while disconnected, but it won't actually delete the dir entries from the dirty blocks.  So when the flush finally happens, the journal will reference non-existent blocks, and all hell will break loose during CR.
Issue: keybase/client#9566
=> folder_branch_ops: don't fast forward while dirty

Jenkinsfile, kbfsblock/bserver_constants.go, kbfsmd/server_constants.go
This needs to be vendored into the servers and deployed before any clients start sending such expire times, otherwise clients will get errors.
=> [KBFS-2570] Increase bserver and mdserver token expiry times

test/engine_fs_test.go, test/engine_libkbfs.go
Just something I noticed while debugging something else.
=> test: cancel SyncAll contexts properly

libkbfs/interfaces.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mocks_test.go, libkbfs/test_stallers.go, libkbfs/tlf_handle.go
This PR doesn't populate the TLF ID yet, only adds it to the data structures and adds the method for getting it.
This is PR 2/3 for the implicit team handle stuff.
=> libkbfs: add tlfID to TlfHandle, and an ID-getting interface

libkbfs/identify_util.go, libkbfs/identify_util_test.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go
This also gets rid of `iteamHandler` in favor of using existing interfaces, to avoid passing around an extra object for no reason.
Please review after #1345, this depends on that one and its parents.
=> identify_util: call IdentifyImplicitTeam when needed

libkbfs/journal_md_ops.go
If `journalMDOps` doesn't have access to the handle before the `GetForTLF` call comes in, it won't be able to enable the journal for team folders.  So override `GetIDForHandle` and use it to start up the journal using the handle.
Issue: #1352
=> journal_md_ops: enable journal in `GetIDForHandle`

libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go
Chat will never ask us for the handle of an implicit team.
=> tlf_handle_resolve: revive implicit team check, but not for chats

libkbfs/errors.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mdcache.go, libkbfs/mocks_test.go
`GetIDForHandle` is called frequently by chat now that we need to get the ID when parsing a handle, so cache it so we don't end up having to go to the journal/server to get the ID.
cc: @mmaxim I believe this gets us back to the previous performance levels for everything but the first `GetTLFCryptKeys` call for a given TLF, which involves server RTTs anyway.
=> md_ops: use a cache for handle->ID mappings

kbfsmd/metadata_ver.go, kbfsmd/root_metadata.go, kbfsmd/root_metadata_v3.go, kbfsmd/root_metadata_v3_test.go, libkbfs/data_types.go, libkbfs/init.go, libkbfs/key_manager_test.go, libkbfs/mdserver_remote.go, libkbfs/root_metadata_test.go, test/dsl_test.go
This adds a new metadata version (4) that is data-compatible with v3
and uses the same struct.  It only uses the new version for
i-team-backed TLFs, otherwise it continues to use v3.  For now, prod
still uses v3 no matter what, until we get a little more testing done.
Issue: KBFS-2621
=> kbfsmd: add a new ImplicitTeamsVer (MDv4!)

kbfsgit/runner.go, kbfsgit/runner_test.go, libgit/ephemeral_git_config_with_fixed_pack_window.go, libgit/on_demand_delta_object.go, libgit/on_demand_object.go, libgit/on_demand_storer.go, libgit/repo.go, libgit/rpc.go
It's turned off for now by always passing in `MaxObjectPacks=-1`, but once more re-packing testing has been done, we'll flip it on.
Issue: KBFS-2627
=> libgit: get ready for object-repacking during GC

libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops.go
We need the handle to tell if a TLF is team-backed or not, we can't just go off the TLF ID type anymore.
Issue: KBFS-2601
=> kbfs_ops: handle TeamNameChanged notifications for i-teams

libkbfs/key_manager.go, libkbfs/key_manager_test.go
Miles let me know that random users won't be able to read the dummy crypt key from a public i-team's sigchain.
=> key_manager: use a dummy crypt key for public i-team TLFs

kbfstool/main.go, libkbfs/init.go, libkbfs/keybase_daemon_rpc.go
The logger package was fixed so that this isn't needed anymore.  This makes KBFS logging great again.
=> libkbfs: no longer init loggers with extra depth

libkbfs/bserver_remote.go, libkbfs/mdserver_remote.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/vendor.json
r? @songgao @jzila 
There are upstream API changes that we're vendoring in here, so I think CI will break for this PR and for https://github.com/keybase/client/pull/9720 until both of them land at the same time.
=> revendor go-framed-msgpack-rpc

libkbfs/mdserver_remote.go
As suggested by @strib in https://github.com/keybase/client/issues/9312 . 
I didn't add it in `getFoldersForRekey` so that the background rekey timer shouldn't trigger it. Let me know if anybody thinks otherwise.
=> WithFireNow in CheckForRekeys

kbfsmd/server_errors.go, libkbfs/mdserver_memory.go, libkbfs/tlf_journal.go
It's easiest if we return the same error for 1) git lock missing; and 2) migration lock is blocking rekey, since we wouldn't need to lookup DB to determine what's prevent the row to be inserted (in the server PR I'm about to put up). So this PR just renames the error into a more generic one.
Since the status code is preserved, I don't *think* this breaks anything. The error's `Name` field is changed, but it seems it's not used anywhere in Go code. But please let me know if you think otherwise.
=> rename ServerErrorRequiredLockIsNotHeld to ServerErrorLockConflict

libkbfs/config_local.go, libkbfs/config_mock_test.go, libkbfs/init.go, libkbfs/interfaces.go, libkbfs/mdserver_remote.go, libkbfs/mocks_test.go, libkbfs/test_common.go
Now that everything in `rpc` is back to Debug level again, we won't get any `rpc` logging on mobile. This forces the Debug logging in `rpc` package on mobile.
=> update vendor and force debug logging for rpc package in KBFS

kbfsgit/runner.go, libgit/rpc.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/root_metadata.go, libkbfs/util.go
So we don't create worthless on-disk journals for public TLFs, etc.
Issue: KBFS-2643
=> journal_server: check for writership before creating journal

libkbfs/block_retrieval_queue.go, libkbfs/block_retrieval_queue_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
OK I added a bunch of tests as part of finding the repro.
This happened because of a bug that occurred when a block in the middle of the prefetch tree was evicted and got its prefetch canceled. The next time such a block was re-requested, it would get added back into the tree but its children still thought they knew about it, so the prefetcher used the wrong value in accounting the size of the subtree for the new block. I've fixed this accounting by tracking whether a block is newly being added to the tree, in which case it'll always use its children's block values.
=> [KBFS-2588] prefetcher: Add test for simple prefetching and fix a race.

libkbfs/config_local.go, libkbfs/config_mock_test.go, libkbfs/init.go, libkbfs/interfaces.go, libkbfs/mdserver_remote.go, libkbfs/mocks_test.go, libkbfs/test_common.go
The LogLevel is global rather than component-wide, so there's no way to turn on debug only for a particular logger.
https://github.com/keybase/client/blob/773a0c3acab154cfa5e2a6f426401f6b32c5b838/go/logger/standard.go#L312
=> revert forcing debug logging

libkbfs/interfaces.go, libkbfs/journal_server_test.go, libkbfs/kbfs_ops.go, libkbfs/kbpki_client.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/md_ops_test.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_memory.go, libkbfs/mocks_test.go, libkbfs/root_metadata_test.go, libkbfs/test_common.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, test/engine_common.go, tlf/id.go, tlf/id_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/kbfs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
If the mdserver returns a null TLF ID when responding to a get-by-handle request for a non-existent TLF, the client will now create an implicit team and deterministically generate a TLF ID and store it in that team's sigchain (via the service).
This mode is now enabled in the DSL implicit team tests.
Issue: KBFS-2621
=> libkbfs: make the client create an implicit team TLF ID if the server refuses to

libkbfs/journal_md_ops.go, libkbfs/md_ops.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_memory.go
I forgot that mdserver returned an error, instead of just a null ID, in that case.
=> mdserver: respond correctly when the server supports iteams

kbfsmd/root_metadata.go
If the mdserver turns on support for iteams, but we are running without that support turned on yet (i.e., in prod mode), we should return a NewMetadataVersionError instead of a generic error, so that the user will get a popup about needing to upgrade instead of just a plain EIO.
Issue: KBFS-2621
=> kbfsmd: return version error if incorrectly asked to make iteam MD

libkbfs/folder_branch_ops.go
Once iteams are enabled and TLF IDs are stored in the team's sigchain, `KBFSOpsStandard` will be able to create a `folderBranchOps` without ever passing the TLF's handle through `journalMDOps`.  This is a problem, because the handle is required to enable a journal.  Without this, the journal won't get created until the first MD put with a revision > 1, which is too late because that will happen when the TLF is locally dirty, and we can't enable journals then.
So instead, enable the journal (if needed) the first time a head is set inside the FBO.
Issue: KBFS-2621
=> folder_branch_ops: enable journal when setting first TLF head

libkbfs/block_retrieval_queue.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go
* We no longer store actual block data in the prefetcher so it doesn't run out of memory. Instead, we store an empty block of the correct type.
* To facilitate this, I made a new API for `BlockRetriever` that allows the prefetcher to fetch a block on-demand without triggering prefetches when the block is available in one of the caches.
* Added an API to remove blocks from the prefetcher without automatically canceling their parent blocks.
* Consume that API in `updatePointer`, to remove old blocks still being prefetched.
* In-flight prefetches get automatically canceled by the prefetch context being closed.
=> [KBFS-2650, KBFS-2651] Don't store actual block data in the prefetcher

kbfsgit/runner_test.go, libgit/worktree.go, libgit/worktree_storer.go, libgit/worktree_test.go
This function "clones" a repo from a billy filesystem, into another billy filesystem.  However, it doesn't make a true git clone, for two reasons.
1. This will be used to clone KBFS repos, and go-git doesn't natively understand the keybase:// protocol.  There might be a way around this with the `InstallProtocol` go-git method, but I haven't investigated that yet and it would be some extra work.
2. These clones are intended for autogit, which will display them as read-only directories.  They do not need to be real git repos, and so there's no need to copy object files or much else in the .git repo. All we really need is an index, to compute the differences.  Making a full git clone, or even a "shallow" git clone, would be wasteful in that it would read and write way more data than we …
=> libgit: implement a Clone function

kbfsgit/runner_test.go, libgit/worktree.go, libgit/worktree_test.go
Turns out that, from the perspective of the worktree, there's no real difference between clone and pull for autogit, now that we're just doing a hard reset to do the checkout.  So rename and add tests.
A later PR will still distinguish between clone and pull at a higher level, within the autogit manager.
Issue: KBFS-2673
=> libgit: change Clone() to Reset() and add tests

libkbfs/md_ops.go
TLF type, not keying type, is what matters.
Issue: KBFS-2652
=> md_ops: don't look up session for public implicit team TLFs

libpages/config/acl_checker_v1.go, libpages/config/config.go, libpages/config/config_test.go, libpages/config/config_v1.go, libpages/config/config_v1_test.go, libpages/root.go, libpages/server.go, libpages/site.go
Also made some changes to the Config package to support `realm`, which is needed for HTTP Basic Authentication, as an identifier for resources sharing the same credentials.
I updated the staging instance and did some simple test and it seems to have worked well. The config I'm using for kbp-test2.song.gao.io for now is:
```json
{
"version": "v1",
"users": {
"alice": "$2a$10$XDG6k7.k3942gm4pY42oJeJl//HeiNr5X9GgF9AzonNzyKuhFq6ra",
"bob": "$2a$10$KBzG6TTGkCRr7ZEm6Z7RVOICrOfunmyiLZC6X4uLkEgx5yAWPBAnu"
},
"acls": {
"/alice-and-bob": {
"whitelist_additional_permissions": {
"alice": "read,list",
"bob": "read"
},
"anonymous_permissions": ""
},
"/bob": {
"whitelist_additional_permissions": {
"bob": "read,list"
},
"anonymous_permissions": ""
},
"/bob/dir/deep-dir/deep-deep-dir": { …
```
=> implement access control using HTTP basic auth

kbfsmd/errors.go, kbfsmd/id.go, kbfsmd/root_metadata.go, kbfstool/md_check.go, kbfstool/md_common.go, kbfstool/md_dump.go, kbfstool/md_dump_common.go, kbfstool/md_force_qr.go, kbfstool/md_reset.go, libkbfs/md_util.go, libkbfs/ops.go, libkbfs/root_metadata.go
In particular, have it dump:
- MD timestamps,
- Name/KID of last modifying device
- Block pointers in ops.
Also decode old MDs with the keys from the most recent one.
Don't make so many calls to the service when looking up usernames / keys.
Also add support for ranges, and process those efficiently. Make 'md check' also use ranges.
I keep forgetting that 'md dump' can't take MD IDs as input (since the server can't)
so detect those and print out a specific error message for that case.
=> Make 'kbfstool md dump' dump more info

libpages/server.go
Sorry for multiple nit fixes. I just recalled being bitten by this before. Since we are not using ELB in front of this, timeouts are important. Otherwise we'll run out of file descriptors pretty soon especially if there are many mobile requests.
=> add timeouts for http.Server in case no ELB is in front

libkbfs/kbfs_ops_concur_test.go
These tests measure precisely the order in which MDs are read, and the prefetcher running async in the background can cause flakes.
=> kbfs_ops_concur_test: disable prefetch during sensitive tests

libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/node.go, libkbfs/node_cache.go, libkbfs/node_cache_test.go
This PR adds a way to "wrap" Nodes as they get created by the `NodeCache`.  The idea is that this will allow us to add custom behavior to each Node, which can be controlled from outside of the `libkbfs` package.  The caller can add a root wrapper function that can transform a root node whenever one is created.  Then, that wrapper can choose to transform any child nodes that are created, via the `WrapChild` function.  And so on, down the tree of nodes, as needed.
This will be used by the autogit implementation in the `libgit` package, to control Node properties that will be added in future PRs: read-only-ness, and hooks for reads, updates and lookup misses which will automatically kick off clones and pulls.  (See KBFS-2654 for the design.)
Issue: KBFS-2675
=> node_cache: add Node wrappers for custom behavior

libfuse/errors.go, libkbfs/config_local.go, libkbfs/errors.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/node.go
This will be used by autogit in a future PR, to make everything under the .kbfs_autogit directory read-only unless it's being accessed by the autogit manager itself.
Also add a global list of root node wrappers in the Config object, that are applied automatically to every newly-created node cache.
Issue: KBFS-2676
=> libkbfs: add a way to mark nodes as read-only

libpages/config/acl_checker_v1.go, libpages/config/config_v1.go, libpages/config/config_v1_test.go
So we've been auto-populating permission for root (`/`) with `"read,list"` if it's not defined in the config file. Now that we have the CLI, this seems redundant and doing more harm than good, since the default config it first writes can have that root permission populated. So this PR changes the ACL constructors to not give root any permissions at all if 1) config file is present; and 2) root doesn't appear in the config file. This is easier to understand by user I think.
If the config file is missing, ACL constructors will continue making a default one which has `"read,list"` for root.
=> require explicitly setting / permission

kbfsgit/runner.go, kbfsgit/runner_test.go, kbfstool/git_rename.go, libdokan/start.go, libfuse/start.go, libgit/autogit_manager.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go, libgit/repo.go, libgit/repo_test.go, libgit/rpc.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/node.go
This PR does a few things:
* `folderBranchOps` has a check for disallowed prefixes when creating new directory entries, currently just ".kbfs" is disallowed.  We had an override for SingleOp mode to allow `.kbfs_git` to be auto-created, but now that we need a second name to be auto-created, I've changed this to be overridable with a context value rather than using the mode.
* The `Node` interface now has a `ShouldCreateMissedLookup` function, which allows `Node` implementations to cause the auto-creation of a directory entry when a lookup misses.
* `kbfsfuse` and `kbfsdokan` now enable several layers of the basic autogit directory structure via different `Node` implementations.  For now, it autocreates up to the TLF name, e.g. `.kbfs_autogit/private/strib`.  A future PR will add repo …
=> libgit: allow auto-creation of basic autogit directory structure

libfs/fs.go, libgit/autogit_manager.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go, libkbfs/node.go
This PR:
* adds a `Node.ShouldRetryOnDirRead` function. This method instructs folderBranchOps about whether or not a re-read is needed after a `GetDirChlidren` or `Lookup` call.  It will be used in future commits to allow autogit to auto-clone and auto-pull repos on the first access to a directory.
* adds a `KBFSOps.GetTLFHandle` function. This allows translating a `Node` object into a `TlfHandle` for the corresponding TLF.
* fixes a small nit in libfs to support the new write error on read-only nodes.
* adds auto-cloned/pulled autogit repo nodes. Currently this just clones or pulls, as needed, a repo during the first access to a `.kbfs_autogit/tlftype/tlfname/repo` directory.  It blocks until the clone/pull is complete, or until a 10-second timeout is hit, whichever comes first. A future …
=>  libgit: support auto-clone and auto-pull of repos

libkbfs/folder_branch_ops.go
Avoid `runUnlessCanceled` and the goroutine it spawns trying to write to the same `err` variable.
Causing some test failures, like: https://ci.keyba.se/job/kbfs/job/PR-1433/1/execution/node/301/log/
=> folder_branch_ops: fix Lookup data race

libkbfs/folder_branch_ops.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
If we use `MDOps()` on a folder that's transitioning to be a conflict folder, we could end up looking up a now fully-resolved handle that matches the handle of the winning, non-conflict folder, and getting back the wrong TLF ID.
Also use one in `tlfJournal` because it's safer and faster, and why not?
Issue: KBFS-2708
=> folder_branch_ops: use `constIDGetter` for `ResolvesTo()`

libfs/file_info.go, libfs/fs.go, libfs/httpfs.go, libfs/mode.go, libfuse/dir.go, libfuse/file.go, libfuse/symlink.go
If a node is read-only, it shouldn't look writable to the OS.
Issue: KBFS-2678
=> libfs: use `Node.Readonly()` to determine FS permissions

libdokan/dir.go, libfs/fs.go, libfuse/dir.go, libgit/autogit_manager.go, libgit/autogit_node_wrappers.go, libkbfs/config_mock_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_cr_test.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/mocks_test.go, libkbfs/node_cache.go, libkbfs/observer_list.go
This PR lets TLF observers see the complete set of nodes that have been updated.  Previously, the observer could only see nodes that had operations done directly on them (like a write, create, etc).  Now the observer can also see nodes that had their underlying blocks updated, even if that didn't result in user-visible changes (e.g., `mkdir a/b/c` affects the underlying data of node `a`).
Then we use that in autogit to watch the entire top directory for a repo to see when something changed, rather than watching just the branch reference node.  That's because the branch ref could be in `packed-refs`, and moreover it could jump back and forth for the lifetime of the repo.
The downside is now we will check for updates whenever _anything_ changes in the git repo directory, which will result …
=> libgit: use node ID updates to figure out when a repo was updated

libgit/autogit_manager_test.go
These are pretty disk intensive and can lead to timeouts when CI
machines are loaded I think.
Hopefully future autogit optimizations will improve performance here.
=> libgit: increase timeout for autogit manager tests

libgit/autogit_manager.go, libgit/rpc.go
Pointed out by jzila on #1427.
=> libgit: prevent goroutine leaks by canceling contexts

kbfsgit/runner_test.go, libdokan/mount_test.go, libdokan/sync_from_server_file.go, libfs/file.go, libfuse/mount_test.go, libfuse/sync_from_server_file.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers_test.go, libkbfs/conflict_resolver_test.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_cr_test.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/kbfs_ops_test.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_rpc_test.go, libkbfs/mocks_test.go, libkbfs/tlf_edit_history_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
Now that we're using it liberally in non-test situations.
Issue: KBFS-2678
=> *: promote `SyncFromServerForTesting`

libgit/autogit_manager.go
Otherwise you couldn't autogit repos that start with "kbfs", because ".kbfs" is a reserved prefix.
=> libgit: a better autogit lock name prefix

libgit/autogit_manager.go
Resets can take way longer than the server lock expiration time.  So just lock while creating a "working" file, and set the mtime on that file to our best estimate of a common time derived based on our time offset with the mdserver we're connected to.
Then resets can take up to an hour, and when they're done the worker can delete the file and write any errors into a new "lasterr" file.
=> libgit: don't lock during the whole reset, just make a file

libgit/repo.go, libgit/repo_test.go
Because libfs.Create doesn't return an error if the file already exists, it succeeds silently.
Issue: keybase/keybase-issues#3157
=> libgit: check existence of config file directly when creating repo

kbpagesd/main.go, libpages/server.go, vendor/golang.org/x/crypto/acme/autocert/autocert.go, vendor/vendor.json
Also remove the option to disable HTTP->HTTPS redirection since we'd
need to listen on :80 for http-01 anyway, and there's not much use for
disabling the redirection.
=> kbp: update vendor to support http-01

libfs/fs.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers_test.go
When go-git calls `OpenFile` on an object file, they expect to get back a not-exists error if the object doesn't exist.  However, if the object's parent directory didn't exist, we were trying to create it automatically (which go-git _also_ expects to happen, *if* the file is successfully created).  If the source repo is read-only (say, someone else's public directory), this doesn't work because `OpenFile` returned a `WriteAccessError` instead of a non-exists error.
This commit fixes that issue by returning a not-exists error in that case.  It also splits up the autogit update tests to have a separate read-only test, and makes that read-only test repack the objects and delete the object directories in order to repro the problem.  The test fails without this fix.
=> libgit: fix autogit updating when source repo is read-only

kbfsgit/runner.go, libgit/repo.go
Early repos may have been created before the check for "." was done on create, and go-git could have caused it to be created.  Then when cloning, the recursive byte count function would enter an infinite loop.  So just ignore "." during any recursion.
Issue: keybase/client#10189
=> kbfsgit: avoid infinite loops when a "." entry is present

libfs/file_info.go, libfs/fs.go, libfs/fs_test.go
=> libfs: explicitly pass name to FileInfo, so that symlinks work

libgit/autogit_manager.go, libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/node.go
This PR allows you to remove autogit repo directories via `rmdir` in the filesystem.  It launches the removal in the background, and blocks for 10s waiting for it to finish, returning with no error if it doesn't finish in time.
It adds another function (`RemoveDir`) to the node interface to allow for custom deletions.
Issue: KBFS-2681
=> libgit: allow autogit removal via rmdir

libfs/httpfs.go
This is a bug reported in keybasefriends, where we are reporting `text/plain` for css resources.
The `name` field here is used eventually in `.Name()` which is used by `http` package to determine the mime type. I forgot to populate it when implementing the wrapper for `http.FileSystem` in the first place and missed this bug in testing because of my browser cache ...
Tested on staging to make sure it fixes the mime bug.
=> populate basename to fix mime type

libfuse/tlf.go
In particular, specify a set of directory entry names that should NOT cause a TLF to be fully loaded and identified on a lookup.  If the directory is not yet loaded and one of these names are looked-up, then ENOENT will be returned automatically.  This is to avoid unnecessary loading and tracker popups when listing the folder list directories. For example, when macOS finder opens `/keybase/private`, it looks up `.localized` in every TLF subdirectory to see if it should translate the TLF folder name or not, which can cause a tracker popup storm
Issue: KBFS-2649
=> libfuse: avoid doing full TLF loads when `.localized` is requested

kbpagesconfig/editor.go, kbpagesconfig/editor_test.go, libpages/config/acl_checker_v1.go, libpages/config/config.go, libpages/config/config_v1.go, libpages/config/config_v1_test.go, libpages/dns.go, libpages/server.go, libpages/server_test.go
Sorry for adding out-of-sprint stuff for review! I've made a few small changes for keybase pages over the weekend, mainly:
1. When `.kbp_config` doesn't have more permissive permissions defined for a given path, it's not possible to get the required permission even with authentication. So return 403 rather than 401. ([more](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) on MDN)
2. I noticed a bug where we were logging status code 200 and reporting 200 to stathat for non-200 responses generated by `http.FileServer`. This PR introduces a simple wrapper around `http.ResponseWriter` to make sure we are getting correct status code for logging and stats.
3. Added boilerplates for server.go tests.
It might be easier to look at individual commits rather than the whole thing …
=> kbp: 403 instead of 401 when appropriate; add a simple test; status code logging/stat fix

libkbfs/keybase_daemon_rpc.go
so it can be more like other platforms, for cleaner shutdown and updating.
The separate NotifyServiceHandler seemed necessary because there already was a Shutdown() (no argument) satisfying some other interface.
Related to DESKTOP-5956, which will be blocked until this is merged.
Tested in a few production builds today.
@taruti @maxtaco @jzila
=> Exit kbfs when service shuts down, even with no fs mount

libpages/dns.go
This is to get around domain registrars that disallow underscores in the middle of the name.
=> libpages: Add a new possible record prefix

simplefs/simplefs.go, simplefs/simplefs_test.go
I tried to keep it as backwards- and bug-compatible as possible for now, though in the future we'll probably want to have better support for symlinks, and faster/atomic moves within a TLF.
I re-ordered many of the functions for readability, so that might make viewing the diff a bit hard.  You might consider reviewing the entire `simplefs.go` file from top to bottom, rather than using the diff.
Issue: KBFS-2661
=> simplefs: refactor to use libfs

libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/mocks_test.go, libkbfs/root_metadata_test.go, libkbfs/tlf_handle.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, tlf/handle_extension.go, tlf/handle_extension_test.go
* Get TLF IDs for regular, non-implicit teams from the sigchain via the service.
* Always use a number at the end of a conflict suffix, i.e. "(conflicted copy 2016-03-14 #1)" instead of "(conflicted copy 2016-03-14)", because that's how the API server does it now.
* Fix some handle resolution issues for team-backed handles.
Issue: KBFS-2652
=> libkbfs: misc fixes needed for implicit teams

libfs/fs.go, libpages/root.go, libpages/server.go, libpages/site.go
This fixes a bug that `e38383` reported in keybasefriends. In short, if the directory corresponding to the site root is moved or removed, kbpagesd kept track of the old `Node` that doesn't represent the real site root anymore, thus serves outdated data.
I tried to use the `libkbfs.Observer` but it seemed fairly complicated since I'd need to keep track of all intermediate nodes too. So this PR just changes the `Site` to cache a `*libfs.FS` of either the TLF, or the `<tlf>` dir in autogit, instead of the actual site root. The server does a `chroot` on each request. This way it always gets the newest site root. I don't think this handles TLF resets yet, which is tracked in a different ticket (KBFS-2657).
Let me know if you guys have better ideas!
=> lazy loading site root to avoid caching obsolete Node

simplefs/simplefs.go, simplefs/simplefs_test.go
This is KBFS side of [KBFS-2781](https://keybase.atlassian.net/browse/KBFS-2781) where we return an empty result for Readdir on non-existent TLFs. A separate client side PR will fix displaying empty folders.
=> show non-existent TLF as empty dir in simplefs

Jenkinsfile
It's happened twice that `libpages.test` just times out. It runs within 0.01s on my laptop, so not sure how it could happen.
I reduced the `test.timout` to 10s, but not sure if it helps with this particular case since the test on Jenkins just runs over 1m30s while the test it self is run with a 30s timeout. But the retry should hopefully get it eventually to pass.
Update: added a new commit to build test binaries first before running all tests in parallel
=> Jenkins changes

libpages/config/config_v1_test.go
Not sure if this is really gonna help with CI flake which I still don't understand, but there's no harm in using `MinCost` in test which should make bcrypt faster in tests.
=> use MinCost for bcrypt in test

kbpagesconfig/editor.go, kbpagesconfig/editor_test.go, libpages/server_test.go
This decreases the time for running `kbpagesconfig` tests on my laptop from 0.39s to 0.01s. So hopefully it'll help with the CI flake.
=> use MinCost for bcrypt in kbpagesconfig test as well

kbfsmd/root_metadata_v2.go, kbfsmd/root_metadata_v2_test.go
Turns out this is only used in a single place.
Add TODO to remove omitemptycheckstruct once we use a newer version of
go-codec that supports omitempty for structs.
=> Add test for omitempty for structs (WriterMetadataV2)

libkbfs/journal_server.go, libkbfs/journal_server_test.go
Otherwise one TLF can prevent new writes to a second TLF from enabling the journal for the second TLF.
Issue: KBFS-2809
=> journal_server: track dirty ops per TLF, not globally

redirector/go/main.go
Since this is a suid binary, allowing arbitrary mountpoints is dangerous.
Suggested by oconnor663.
=> redirector: restrict mountpoints to /keybase*

redirector/go/main.go, vendor/bazil.org/fuse/options.go, vendor/bazil.org/fuse/options_darwin.go, vendor/bazil.org/fuse/options_freebsd.go, vendor/bazil.org/fuse/options_linux.go, vendor/vendor.json
Otherwise, the kernel will cache symlinks for a long time.
=> redirector: turn off local caches on osx

libfs/fs.go, libfs/fs_test.go
This fixes a bug where `autogit` fails to checkout if there's symlink inside a directory by itself. The parent directory doesn't get created, and `go-git` fails on the `Symlink()` call trying to grab its parent directory.
Thanks @strib for spotting the root cause!
=> libfs: create parent dirs when needed (disovered by strib)

libfs/file.go, libgit/autogit_manager_test.go, libkbfs/config_local.go, libkbfs/config_mock_test.go, libkbfs/conflict_resolver.go, libkbfs/data_types.go, libkbfs/folder_block_manager.go, libkbfs/folder_branch_ops.go, libkbfs/init.go, libkbfs/interface_test.go, libkbfs/interfaces.go, libkbfs/journal_server.go, libkbfs/kbfs_ops.go, libkbfs/keybase_daemon_rpc.go, libkbfs/md_util.go, libkbfs/mdserver_remote.go, libkbfs/mocks_test.go, libkbfs/modes.go, libkbfs/rekey_queue.go, libkbfs/test_common.go, libkbfs/tlf_edit_history.go, libkbfs/tlf_journal.go
This cleans up all the scattered mode cruft into an interface, and puts all the behaviors of each mode into a single struct for easier reference and maintenance.
It also adds a new "constrained" mode, with behavior matching what jzila wrote in #1486.
Issue: KBFS-2744
=> libkbfs: introduce a new InitMode interface, and a new "constrained" mode for mobile KBFS

libkbfs/folder_branch_ops.go
Otherwise we'd fall into this case here: https://github.com/keybase/kbfs/blob/2cc8f8832ed876f51044ddefe7edb5e57bef5432/libkbfs/rekey_fsm.go#L386-L395 and schedule another rekey in `rekeyRecheckInterval` which is 30s. With the added error check in this PR, we'd continue with a rekey scheduled in `r.fsm.fbo.config.RekeyWithPromptWaitTime()` which is 10min for now.
=> don't error on InputCanceledError

redirector/main.go
So instead of checking that "Keybase" is necessarily the last thing in the path, maybe sure it's at least followed by a space.
Issue: KBFS-2820
=> redirector: handle mountpoints like  `/Volumes/Keybase (user)`

libkbfs/journal_server_test.go
If the journal is empty, then after a restart it gets automatically cleaned up, leading to a test failure.
Issue: KBFS-2794
=> journal_server_test: pause work so journal doesn't become empty

libkbfs/folder_branch_ops.go
If we can't put a block in the transient block cache, no big deal, just log it and move on.  For example, there's no reason to fail a big CR on this just because the CR has filled up the allocated cache size with a bunch of permanent blocks.
Issue: KBFS-2822
=> folder_branch_ops: don't fail on transient bcache puts

libfs/file_info.go, simplefs/simplefs.go, simplefs/simplefs_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/stellar.go, vendor/vendor.json
Get this info by using the `os.FileInfo.Sys()` generic interface, and introducing a new type of interface that the `Sys()` return value can implement.  That way we don't try to get the last writer when using a local disk file system.
Note: this won't return the last writer for symlink directory entries. I assume that's ok, but if not we can figure out a different way of doing this.
This will break CircleCI until keybase/client#10948 is merged.
Issue: KBFS-2836
=> simplefs: return the last writer of a directory entry

libkbfs/impatient_debug_dumper.go, simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
Uses a new instance of the impatient debug dumper, without any background goroutines, to make this happen.
Issue: KBFS-2746
=> simplefs: support new debug-dumping RPC

vendor/github.com/keybase/saltpack/README.md, vendor/github.com/keybase/saltpack/armor62_encrypt.go, vendor/github.com/keybase/saltpack/armor62_signcrypt.go, vendor/github.com/keybase/saltpack/common.go, vendor/github.com/keybase/saltpack/const.go, vendor/github.com/keybase/saltpack/encoding/basex/bases.go, vendor/github.com/keybase/saltpack/encoding/basex/stream.go, vendor/github.com/keybase/saltpack/encrypt.go, vendor/github.com/keybase/saltpack/key.go, vendor/github.com/keybase/saltpack/nonce.go, vendor/github.com/keybase/saltpack/packets.go, vendor/github.com/keybase/saltpack/rand.go, vendor/github.com/keybase/saltpack/signcrypt_open.go, vendor/github.com/keybase/saltpack/signcrypt_seal.go, vendor/vendor.json
Notable changes:
- Hardcodes field order for encryption, so that fixes to the codec
library won't change it.
- Make receiver shuffling unbiased, even on go <1.10.
- Bump CurrentVersion to Version2 (although keybase already always uses
Version2).
=> Vendor saltpack

fsrpc/path.go, libdokan/folderlist.go, libfuse/folderlist.go, libkbfs/tlf_handle.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, libkbfs/util.go, test/engine_libkbfs.go, tlf/name.go
When someone passes a TLF name like "a,b,c (conflicted copy 2018-03-22 #1)" to FUSE, we need to figure out if it's canonical, but it's hard, because the "#1" is needed for implicit teams, but during the initial parsing we don't know yet whether the folder is team-backed or not without making expensive service calls.
So this PR does makes the right suffix when it knows for sure about the team-backed-status of the TLF; otherwise, if the user passed in a "#1", it assumes the user (likely a KBFS server test) already knows that it should be an implicit team TLF.
Also it wrap the TLFNameNotCanonical error with a stack, because this was really hard to debug without that.
Issue: KBFS-2652
=> tlf_handle_resolve: use the team suffix when checking canonicals

kbfstool/md_dump_common.go, libkbfs/data_types.go, libkbfs/kbpki_client.go, libkbfs/kbpki_client_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_daemon_rpc_test.go, libkbfs/keybase_service_base.go
We previously had no way of getting all the pre-reset keys of a user, which led to situations where team folders are unreadable when they are last written by a user who then reset their account.
The service started exposing a V2 RPC that gives us all past incarnations of the user, so we can check all their keys, using the "reset" time as the revocation time.
Issue: KBFS-2842
=> keybase_service_base: call new service RPC to get ALL revoked keys

libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/keybase_daemon_rpc.go, libkbfs/keybase_service_base.go, libkbfs/mocks_test.go
When a user resets, their implicit teams will be abandoned, and we have to update all our caches.
I wasn't able to test this yet because the staging server isn't up-to-date enough, but it's simple enough.  I'll test it manually before we turn on implicit team TLFs.
Issue: KBFS-2601
=> libkbfs: handle TeamAbandoned notifications

libkbfs/keybase_service_base.go
`processKey` is shared by both the code that filters live keys and the code that filters revoked keys.  Oops!
Issue: KBFS-2851
=> keybase_service_base: fix key revocation check

libfuse/alias.go, libfuse/dir.go, libfuse/file.go, libfuse/folderlist.go, libfuse/fs.go, libfuse/mount_test.go, libfuse/symlink.go, libfuse/tlf.go
Otherwise, bazil.org/fuse assigns inodes based on hash(parentInode, name), and if a file gets moved it can end up having the same inode as a new node that took its old name.
This instead has the *FS object keep a monotonically-increasing uint64 and assigns a new inode to every new node, excepting those special files and aliases that can't actually be renamed and cause problems.
Issue: KBFS-2853
=> libfuse: assign constant inodes to each node

libkbfs/conflict_resolver.go, test/cr_basic_conflicts_test.go
If a file was modified then removed in the merged branch, those syncOps shouldn't be counted as conflicts against modifications of the same file in the unmerged branch.  Doing so leads to a crash, because the final path won't be set in the merged syncOp.
Without the fix, the new test fails in exactly the same way as the client in keybase/client#11318.
Issue: keybase/client#11318
=> cr: fix crash when modified file was removed on the merged branch

libkbfs/keybase_service_base.go
Identifying a deleted user (with no keys) should be treated like a no-op, since the concept of a deleted user is based entirely on server trust anyway.
Issue: KBFS-2852
=> keybase_service_base: ignore identify errors for deleted users

libfuse/mounter.go, redirector/main.go
This shows up when browsing the root disk of the local computer in Finder, and it's confusing if it says "keybase-redirector". "keybase-redirector" will still show up in `mount` though.
Also, the favorite was showing up as "Keybase (strib)" instead of just "Keybase".  This fixes that as well.
cc: @mlsteele 
Issue: KBFS-2866
=> redirector: fix volume and favorite names in macOS

vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/vendor.json
If conflict files ended up in `objects` or `objects/pack`, go-git would still try to treat their full names as hashes, and end up trying to access a file named by the 0 hash, which would fail.  Instead, just skip files like that.
Issue: keybase/client#11366
=> kbfsgit: update go-git to avoid failing on conflict files

kbfsmd/root_metadata.go, kbfsmd/root_metadata_v2.go, kbfsmd/root_metadata_v3.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/kbpki_client.go, libkbfs/keybase_daemon_rpc.go, libkbfs/keybase_service_base.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/tlf_handle.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go, tlf/handle.go, vendor/github.com/keybase/client/go/protocol/keybase1/common.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/implicit_team_migration.go, vendor/github.com/keybase/client/go/protocol/keybase1/metadata.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
When the service is ready to migrate a TLF to an implicit team, it can call `FinalizeMigration`.  This re-resolves the handle of a TLF using the implicit team, and then generates a new MD for the TLF using team-keying.
When setting the MD successor, we check that the migration is valid: that is, the new implicit team has the same writers, readers, and canonical name as the original MD.
Issue: KBFS-2606
=> libkbfs: implement migrating TLFs to implicit team TLFs

kbfstool/md_dump_common.go, libkbfs/data_types.go, libkbfs/kbpki_client.go, libkbfs/kbpki_client_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go
In the future this will let us order MD writes against key revokes/resets with less server trust.
Issue: KBFS-2890
=> libkbfs: cache merkle roots for revoked and reset keys

libkbfs/conflict_resolver.go, test/cr_complex_test.go
A user hit an issue where they deleted a file and several of its parent subdirectories in the merged branch, but re-created that file and the parent subdirectories in the unmerged branch.  They did this for several files, across multiple subdirs.
This triggered a bug related to the fact that action updates to files actually affect their parent directories, and so parent directories can be processed twice during the action loop.  If the parent directory is being recreated, we could end up making two new blocks for it, and the second one would overwrite any changes that we already made to the first one, leading to the error.
Instead, make sure we only make new blocks once, while still preserving the previous correct behavior that a recreated directory block should always start out empty, …
=> cr: fix bug with recreated file and subdirectory

dokan/cgo.go, dokan/filesystem.go, dokan/testfs_test.go, libdokan/dir.go, libdokan/empty_folder.go, libdokan/fakeroot.go, libdokan/folderlist.go, libdokan/fs.go, libdokan/profilelist.go, libdokan/tlf.go, libfs/mount_interrupter.go
When a file is opened with FILE_OPEN_IF with Dokan and the file
exists it should be returned, but additionally ErrObjectNameCollision
should be returned.
Fixes KBFS-2812 and Fixes #1494
This ended up requiring quite a lot of restructuring code since
we need to pass up whether a file was created or an existing
one is returned. Doing this on all the return sites would have
been even more messy.
=> Fix file truncation on Windows with bash

libfs/file_info.go, libkbfs/folder_branch_ops.go
There was a bug in some very old team folders where the last writer of a file might be unset.  Previously it ended up defaulting back to the team ID, which caused an error to surface in the GUI.  Instead, just use a blank string/ID.
Issue: KBFS-2939
=> libfs: don't error on fileinfo when last writer is a team

kbfsmd/errors.go, kbfsmd/merkle_hash.go, kbfsmd/merkle_leaf.go, kbfsmd/merkle_root.go, libkbfs/interfaces.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_memory.go, libkbfs/mdserver_remote.go, libkbfs/mocks_test.go, libkbfs/reporter_kbpki.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/metadata.go, vendor/vendor.json
This PR adds the `FindNextMD` call, and the various merkle data structures needed to use it.  It will be used in a future PR.
Issue: KBFS-2904
=> mdserver: add FindNextMD RPC support for remote

tlf/name.go, tlf/name_test.go
New test fails without the fix.
=> [KBFS-2953] tlf: Reorder readers for preferred names

kbfsmd/root_metadata_v2.go, kbfsmd/root_metadata_v2_test.go
This is in preparation for a go-codec update.
=> Use omitemptyrecursive with omitemptycheckstruct

libkbfs/file_data.go
This occured on 32 bit builds.
If `nextBlockOff - off` overflowed a 32 bit signed integer, then room ended up being negative. Which was smaller than max, and thus max got an invalid value.
=> Avoid rare overflow in file offsets on 32-bit builds.

kbfsmd/root_metadata_v2.go, kbfsmd/root_metadata_v2_test.go
This reverts commit 5cae975949afcbcff4355b8ad89ac463e290b0da.  That commit broke writer MD verification for `/keybase/public/airthom` (at least).  See #1578.  Reverting the commit fixes it again.  I guess we needed those structs to be non-empty for verification to pass.
=> Revert "Use omitemptyrecursive with omitemptycheckstruct (#1572)"

libhttpserver/content_type_utils.go, libhttpserver/server.go, libmime/patch.go, libpages/server.go
This should entirely eliminate the possibilities of returning `text/javascript` or `test/html` to front end. We can add other sensitive mime types later if we want.
I'll have a follow-up PR in client to make GUI always use this interface to determine the mime type, either through HEAD or GET.
=> move the mime type overrider into a ResponseWriter wrapper

libkbfs/errors.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/kbpki_client_test.go, libkbfs/key_manager.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/md_util.go
[This shouldn't be merged until we deploy the FindNextMD RPC.]
The algorithm is:
* Make a preliminary check against the untrusted server timestamps, as before.  If that fails, fail the verification.
* Fetch the merkle info from the mdserver, using the key revocation merkle root.
* If the server doesn't return anything, verify that the revision has a valid chain of updates up to the current head of the TLF.  If everything checks out, consider it valid. TODO in a future PR: make sure there's not a big merkle time gap between the revision and the head, or else the server might be lying.
* Otherwise, for private and team folders, we need to decrypt the merkle leaf, but we don't know what key generation was used for it. So, starting at the revision we care about, iterate forwards and try each …
=> md_ops: check revoked keys using the merkle tree

kbfscrypto/encrypted_data.go, kbfsmd/merkle_leaf.go, libkbfs/crypto_client.go, libkbfs/crypto_client_rpc.go, libkbfs/crypto_client_test.go, libkbfs/crypto_local.go, libkbfs/interfaces.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mocks_test.go, libkbfs/test_common.go, libkbfs/tlf_journal_test.go
(Note: this depends on #1569, which is blocking on a server deploy.)
If a team MD was written by a revoked device and we need to decrypt the Merkle leaf, this PR calls out to the service to get it done (since only the service has access to the team's per-key-generation private key).
If refactors the `kbfsmd.EncryptedMerkleLeaf` class a little to move the actual decryption into `kbfscrypto`, to match some of our other encrypted data types.
Issue: KBFS-2963
=> md_ops: decrypt team Merkle leafs

libkbfs/folder_block_manager.go, libkbfs/keybase_daemon_local.go, libkbfs/md_ops.go
Apparently some users have sigchains with revocations that are missing the root sequence number of when the revocation happened.  In this case, the service tells us they were revoked at seqno 0.  The API server rejects this as an invalid seqno, and gives back an opaque error type, which the mdserver sends back to the client.  A background process like QR treats this as a transient error and tries the TLF again, over and over.
This issue will go away once the service lands CORE-7806, but for now we can prevent this from happening forever by catching the problem early and returning a specific error type that will stop QR early.
=> libkbfs: stop QR early when an unverifiable TLF

libkbfs/keybase_service_base.go, vendor/github.com/keybase/client/go/protocol/keybase1/account.go, vendor/github.com/keybase/client/go/protocol/keybase1/ephemeral.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/user.go, vendor/vendor.json
Instead of relying on the `PrevMerkleRootSigned` field in the revocation (which is the seqno that the client performing the revocation saw before pushing it), use the service to look up the exact merkle root that first contains the revocation.
This is more accurate and gets around the issue where some old revocations have a 0 root seqno.
Issue: keybase/client#12101
=> keybase_service_base: use `FindNextMerkleRootAfterRevoke`

libkbfs/keybase_service_base.go, libkbfs/md_ops.go
Also don't try to FindNextMD in that case either.  Old revoke sigchain entries just don't have enough information for us to check the merkle info when verifying writes by revoked devices, so we have to rely on server trust.
=> keybase_service_base: don't refine revoked merkle root when prev=0

libkbfs/data_types.go, libkbfs/keybase_service_base.go
The `FindNextMerkleRootAfterRevoke` is expensive, so this commit only calls it for a key that's being explicitly asked for by the user (say, to read an MD update written by that key).
cc: @maxtaco 
Issue: KBFS-3009
=> keybase_service_base: fill in revoked merkle info on demand

libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/md_journal_test.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_memory.go, libkbfs/mdserver_remote.go, libkbfs/merkle_checker.go, libkbfs/mocks_test.go, libkbfs/util.go, vendor/github.com/keybase/go-merkle-tree/README.md, vendor/github.com/keybase/go-merkle-tree/interfaces.go, vendor/github.com/keybase/go-merkle-tree/mem.go, vendor/github.com/keybase/go-merkle-tree/tree.go, vendor/vendor.json
So far, we've been trusting the merkle data returned from the mdserver in `FindNextMD`.  In this PR, we start verifying it.  We call into the service to verify that the global root we have is legitimate and contains the KBFS root we expect it to.  And then we check the nodes of the KBFS merkle tree to make sure they contain the merkle leaf it is supposed to have.
Issue: KBFS-2954
=> libkbfs: verify the merkle root and KBFS merkle nodes returned by FindNextMD

libkbfs/md_ops.go
Forgot to set the next MD when iterating in a loop to try to decrypt a Merkle leaf.  This caused infinite loops whenever we were trying to verify an MD written by a revoked key, and the leaf we were using to verify it was encrypted for a key generation that was more than 10 MD updates away from the MD being verified.
Issue: KBFS-3019
=> md_ops: iterate correctly when decrypting merkle leaf

libkbfs/data_types.go, libkbfs/keybase_service_base.go, vendor/github.com/keybase/client/go/protocol/keybase1/gregor.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_ctl.go, vendor/github.com/keybase/client/go/protocol/keybase1/user.go, vendor/vendor.json
Just like we did for revokes, we also need to get the next Merkle root following an account reset (which effectively revokes all the old devices).
Tested it manually with a TLF containing a write by a pre-reset device.
Issue: KBFS-3029
=> keybase_service_base: fetch the merkle root following a reset

libkbfs/folder_branch_ops.go
Otherwise `LastWriterUnverified` won't be set until the blocks are flushed via the `folderUpdatePrepper` after the batch is ready.
Issue: KBFS-3037
=> folder_branch_ops: set the TeamWriter for new create entries

libkbfs/cr_chains.go, libkbfs/data_types.go, libkbfs/md_util.go, libkbfs/md_util_test.go, libkbfs/ops.go
We relied on decoding a BlockChanges clobbering any existing Info,
which would not be true if the omitempty tag on Info were actually respected
(which the upstream version of our codec library (buggily!) does).
So add a test that catches this, and make it so that we decode into an empty
BlockChanges and then assign.
Also, remove omitempty from Info in BlockChanges. We can't turn it back on
until old clients with the buggy behavior all disappear.
=> Fix a latent bug with reembedBlockChanges

libkbfs/ops.go
It wasn't actually being applied, anyway.
=> Remove omitempty from blockUpdate

kbfsmd/merkle_leaf.go, kbfsmd/merkle_leaf_test.go, libkbfs/merkle_checker.go
Upstream codec decodes into a []byte only up to its existing length; see
https://github.com/ugorji/go/issues/249 .
=> Return a *[]byte from {,Encrypted}MerkleLeaf.Construct()

libkbfs/journal_server.go, libkbfs/journal_server_util.go, libkbfs/tlf_journal.go, vendor/github.com/vividcortex/ewma/LICENSE, vendor/github.com/vividcortex/ewma/README.md, vendor/github.com/vividcortex/ewma/ewma.go, vendor/vendor.json
This adds an exponentially-weighted moving average for estimated upload speed in bytes per second to each TLF journal, and adds an end time prediction to the journal status based on that estimate.  For the overall journal status, it uses the latest end-time estimate among all the TLFs.
If the status is obtained before any uploads for that TLF have completed, it predicts an arbitrary end estimate of 10 seconds from now.
If multiple TLFs are uploading at the same time, the hope is that their bandwidth estimates will decrease because of the increased competition for the TCP channel among the TLF journals.  If this doesn't work well, we change this to have a system-wide bandwidth estimate, but since all the TLFs upload data in parallel, it's not clear exactly how this should work.
Note that a …
=> tlf_journal: return an estimated end time for flushing bytes

kbfsedits/data_types.go, kbfsedits/prepare.go, libkbfs/chat_local.go, libkbfs/conflict_resolver.go, libkbfs/conflict_resolver_test.go, libkbfs/cr_chains.go, libkbfs/cr_chains_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/keybase_daemon.go, libkbfs/ops.go, libkbfs/ops_test.go, libkbfs/test_common.go, vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go, vendor/github.com/keybase/client/go/protocol/chat1/common.go, vendor/github.com/keybase/client/go/protocol/chat1/extras.go, vendor/github.com/keybase/client/go/protocol/chat1/gregor.go, vendor/github.com/keybase/client/go/protocol/chat1/local.go, vendor/github.com/keybase/client/go/protocol/chat1/notify.go, vendor/vendor.json
This PR prepares chat messages for all the ops in a flushed MD, to be sent on a writer-specific channel in the kbfs-edits chat corresponding to the TLF.  Right now, it only actually sends the chat messages if we're in test mode, because I haven't yet been able to test it in staging or production.  But I wanted to get the reviews started on it now, while I work on the testing issues.
Other small things added in this PR to support making these notifications:
* Add the entry type of removed files to `removeOp`s, so we can get more details in the notifications.
* Add a path for the "old" directory in a `renameOp`, so we can give the full path of the old file location in a rename notification.
Issue: KBFS-2994
=> libkbfs: prepare chats for edit notifications on each MD flush

libkbfs/chat_local.go, libkbfs/chat_rpc.go, libkbfs/connection_status.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/keybase_daemon_rpc.go, libkbfs/keybase_service_base.go, libkbfs/mocks_test.go
(Based on #1610, which needs to be merged first.)
This registers KBFS for kbfs-edits notifications, and adds the interface methods needed to invalid local edit notification state (including gregor reconnects).
Issue: KBFS-2995
=> chat: register for new channels and messages

kbfsmd/root_metadata_v3.go
Older versions of go-codec didn't respect them for
TLF*KeyBundleID, so now we're stuck without them, lest
verification (which re-encodes the metadata) fail.
=> Remove more useless omitempty tags

libkbfs/interfaces.go, libkbfs/md_ops.go, libkbfs/mocks_test.go, libkbfs/test_stallers.go, libkbfs/tlf_handle_resolve.go
When chats got migrated to implicit teams, the current TLF ID got written into the iteam sigchain.  KBFS uses that ID in the sigchain, if it's available, in preparation for when we turn on KBFS iteams. However, if the TLF gets finalized (because a user resets), the old ID remains in the sigchain and KBFS will use it even when looking up the non-finalized TLF ID.
We can fix this more permanently when we migrate existing KBFS TLFs to iteams; at that point we can override the TLF ID using a new sigchain link.
Issue: KBFS-3045
=> tlf_handle_resolve: don't use finalized TLF IDs from iteam info

libhttpserver/server.go
With curl, when it makes a reqeust
```
GET public/songgao/index.html?token=blah
```
and get a 301 to "./?tokan=blah", it'd make a follow-up request
```
GET public/songgao?token=blah
```
instead of
```
GET public/songgao/?token=blah
```
This commit is for fixing this particular scenario.
Note that this isn't required for fixing KBFS-3028 on desktop (which is handled in https://github.com/keybase/client/pull/12399), since Electron does redirect with the trailing backslash. I haven't tried RN yet, so not sure if RN needs this. But either way it's good to make it compatible with other clients too.
=> fix redirect with some HTTP clients

Jenkinsfile, appveyor.yml, kbfsedits/data_types.go, kbfsedits/tlf_history.go, kbfsedits/tlf_history_test.go
This introduces `kbfsedits.TlfHistory`, which receives raw notification strings from a caller for each writer in a TLF, and constructs the edit history from each writer (up to `maxEditsPerWriter` edits each), up to `maxWritersPerHistory` writers per TLF.
The collected sets of per-writer edits in the history are sorted in reverse order, by the most recent revision from each writer.  Within each set, a writer's edits are sorted in reverse order by revision.
The constructed history only includes creates and modifies of files (no directories or symlinks).  If a file was modified and later renamed, the notification for the modify shows the new file name.  If a file was modified but later deleted, it doesn't appear in the history.  Each writer only has the most recent modification or create for …
=> kbfsedits: add a class that can construct per-TLF edit histories

circle.yml
Also use go 1.10.3.
Sync with circle.yml from client, but remove node and yarn.
=> Migrate to CircleCI 2.0

libkbfs/keybase_daemon_rpc.go
It's possible that `AddProtocol` is called after we iterate protocols in
`OnConnect`, but before it manages to finish everything and assign
the `(*KeybaseDaemonRPC).server`, so `AddProtocol` would find `server`
to be nil, and skips registering additional protocols. So just do a full
lock at the beginning of `OnConnect` to avoid this race.
Also add logging for each registered protocol to help with debugging.
=> lock better and log better

libkbfs/node_cache_test.go
Apparently go1.10 can optimize away the old `func` trick for keeping references around.
This way works for both go1.9 and go1.10.
=> node_cache_test: use `runtime.KeepAlive` for GC test

libkbfs/file_data.go
=> file_data: remove log line that's too verbose

libdokan/fs.go, libdokan/user_edit_history.go, libfs/user_edit_history.go, libfuse/special_files.go, libfuse/user_edit_history_file.go, libkbfs/chat_rpc.go, libkbfs/config_local.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_daemon_rpc_test.go, libkbfs/ops.go, redirector/main.go, test/dsl_test.go, test/edit_history_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
(Depends on #1629.)
Also add DSL tests for the user edit history and fix a few small bugs:
* Use the full canonical path to the filenames in the edit notifications, like we do for the journal unflushed paths.
* Always set the topic name in `NewConversationLocal`.
* kbfs-edits conversations can legitimately have some weird messages and states, so don't error on those.
* A notification about a new channel should launch the corresponding FBO, if one doesn't exist yet.
* Send edit notifications in a goroutine when journaling is enabled, to avoid deadlocks.
Issue: KBFS-2999
=> libfuse/libdokan: expose user history in root .kbfs_edit_history

kbfsedits/user_history.go, libdokan/fs.go, libdokan/user_edit_history.go, libfs/user_edit_history.go, libfuse/special_files.go, libfuse/user_edit_history_file.go, libkbfs/chat_local.go, libkbfs/chat_rpc.go, libkbfs/config_local.go, libkbfs/folder_branch_ops.go, libkbfs/init.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_daemon_rpc_test.go, libkbfs/ops.go, redirector/main.go, test/dsl_test.go, test/edit_history_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
(Depends on #1628.)
Also, causes a notification about a new channel to fire if we get a new message on a conversation we haven't yet subscribed to.  That way we can launch a new `folderBranchOps` for a TLF that was written to but didn't previously appear high enough in our inbox.
Re-initialize the FBOs after each re-connect and re-login as well.
Issue: KBFS-2996
=> kbfs_ops: use inbox to initialize FBOs needed to construct the edit history

libkbfs/unflushed_path_cache.go
I guess this got triggered by simple FS starting to call for the status all of the sudden?  Still investigating how it could get into this state, but this should stop the panics.
Issue: KBFS-3101
=> unflushed_path_cache: check for nil channel before closing

kbfsedits/tlf_history.go
=> kbfsedits: avoid unneeded writer name assignments

kbfsedits/data_types.go, kbfsedits/prepare.go, kbfsedits/read.go, kbfsedits/tlf_history.go, kbfsedits/tlf_history_test.go, kbfsedits/user_history.go, kbfsedits/user_history_test.go, libdokan/user_edit_history.go, libfs/user_edit_history.go, libfuse/user_edit_history_file.go, libkbfs/chat_local.go, libkbfs/chat_rpc.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/keybase_service_util.go, libkbfs/mocks_test.go, test/edit_history_test.go, test/engine_libkbfs.go
(Depends on #1631.)
This is the first attempt at making sure your own recent write history appears in the overall edit history, even if they were a long time ago.  The desired behavior, for now:
* Make sure there are always 3 TLF-writer clusters for yourself in the list.
* Sort them into the list according to the regular algorithm -- i.e., if they happened a long time ago, they will still appear at the bottom.
* Don't do anything special for the public folder -- if it happens to be one of the top-3 self-clusters, it will make the list; if not, it won't.
To make this happen, this PR:
* Creates a special "#self" kbfs-edits notification channel in the logged-in user's private conversation.
* On every "normal" notification, it writes the name and type of the TLF into this "#self" channel.
* …
=> kbfsedits: includes at least 3 self-clusters in the overall user history

libkbfs/keybase_service_base.go
Make the codebase 8 bytes larger. https://github.com/keybase/client/blob/master/go/libkb/errors.go#L1769
=> Use UserDeletedError in place of DeletedError

libkbfs/folder_branch_ops.go, simplefs/simplefs.go, simplefs/simplefs_test.go
Also, `folderBranchOps.GetEditHistory` should wait on outstanding edits, so make sure we return the most recent history, including the initialization.
A separate client PR will add these RPCs to the protocol, and eventually I'll vendor that into KBFS, but it's not strictly required yet.
Issue: KBFS-2997
=> simplefs: RPCs to get user and TLF history

kbfsmd/root_metadata_v3.go, libkbfs/data_types.go, libkbfs/errors.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mocks_test.go, libkbfs/test_common.go
This PR checks, if the writer of an MD is not currently a writer of the team, that the user _was_ a writer at the "time" the revision was made.  Here "time" is defined by the merkle trees, just as it is with checking revoked devices.  We ask the service for the merkle root following when the user was last downgraded from being a writer, and then we use that to call `FindNextMD`.  This required some refactoring to share that code with the device-revocation-checking code.
Two notes:
1. Currently, the service can only tell us about writership downgrades, not readership downgrades.  Our MD validators call `IsTeamReader` for the last modifying user, since a reader is allowed to copy a writer's MD to make a rekey request.  So the best we can do now is just fake it, which should be fine since a) …
=> md_ops: check historic team writership

libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/kbpki_client.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/md_journal_test.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_memory.go, libkbfs/mdserver_remote.go, libkbfs/merkle_root.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/test_common.go
(Note: this depends on #1569, which is blocking on a server deploy.)
This adds interface methods fetch timestamps for both global and KBFS Merkle roots, and uses that to make sure that a) if the mdserver doesn't return any Merkle info after a revoke, that the gap since the last merkle root hasn't been too big; and b) if it does return a Merkle root, there wasn't too big a gap since the revoke happened.
Issue: KBFS-2956
=> md_ops: check merkle time gaps when verifying a revoked key

libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/modes.go, libkbfs/rekey_fsm.go, libkbfs/rekey_queue.go
Launching a goroutine for rekey requests when the queue is full doesn't make a lot of sense if we're trying to conserve memory (like on a phone), since it probably uses a lot more memory than just expanding the queue.  So this PR just drops requests when the queue is full, and increases the queue size on desktop to handle more requests at a time.  Any dropped requests will get processed again at the next rekey interval.
This only changes behavior for people with more than 2K TLFs, which is probably only two users.
Issue: KBFS-3072
=> rekey_queue: put queue size into mode, and drop reqs when full

kbfsedits/tlf_history.go
=> kbfsedits: ignore more macOS filenames

libkbfs/config_local.go, libkbfs/config_mock_test.go, libkbfs/conflict_resolver_test.go, libkbfs/folder_block_manager.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go, libkbfs/init.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/modes.go, libkbfs/state_checker.go, libkbfs/test_common.go
Once mobile devices can write, we don't want them wasting cycles cleaning up after other device writes (which would have happened after 24 hours if the other device didn't do it first).
Instead, move all the QR stuff into the mode, and make sure mobile devices (running in constrained mode) only run QR when the latest writer was the local device.
Issue: KBFS-3121
=> libkbfs: turn on QR for mobile, but limit it to self-QR

libkbfs/config_local.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_util.go
`serviceLoggedIn` can be called as a side-effect of the mdserver `OnConnect` call, if that is the first time the current session is discovered.  Initializing FBOs depends on the mdserver, and so that can lead to a deadlock.
Instead, initialize them in the background in that case, while the other cases can still wait for the initialization to complete.
Issue: KBFS-3155
=> keybase_service_util: don't block on initializing FBOs on login

libkbfs/folder_branch_ops.go, libkbfs/journal_server.go, libkbfs/kbfs_ops.go
Just start up the chat monitoring, so we don't trigger any unintended popups.
If there are unflushed journals for some TLFs, we could theoretically trigger popups for them since they are initialized differently, but in that case the user would probably have recently written to the TLF and so would have already gone through the identify flow.
Also, remove a `folderBranchOps` function that's been unused for a long time, and confused me.
Issue: CORE-8290
=> kbfs_ops: on TLF history init, don't run TLF identifies

libkbfs/chat_local.go, libkbfs/kbfs_ops.go, libkbfs/mdserver_memory.go
Previously, I fixed the case where kbfs edit channels were causing tracker popups on startup for no reason.  Unfortunately, this can also happen after startup, if some other device writes to the folder and causes your local device to make an FBO for it.  Fix it by just monitoring the chats, not creating the FBO.
=> kbfs_ops: avoid tracker popups on new writes post-startup

libkbfs/block_journal.go, libkbfs/block_journal_test.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
Take into account the time spent during the current block flush batch when computing the end estimate.  Otherwise, we just add a constant amount to the current time for every status call made during a single batch.
Issue: KBFS-3176
=> tlf_journal: improve journal flush end estimate

libkbfs/chat_rpc.go
For example, you might have written to a team folder that you're no longer a member of (or for which the team got deleted).  When looking up the last self-written TLFs, don't treat errors like that as fatal.
cc: @mmaxim
=> chat_rpc: ignore errors for inbox items that can't get handle

libdokan/fs.go, libfuse/fs.go, libkbfs/backpressure_disk_limiter.go, libkbfs/bserver_remote.go, libkbfs/folder_branch_status.go, libkbfs/journal_server_test.go, libkbfs/kbfs_ops.go, libkbfs/quota_usage.go
Hopefully right now this is zero for most users, though old bugs could have left some archived bytes around.  This will be more interesting once #1675 is live.
Issue: KBFS-3187
=> kbfs_status: show archived bytes

libkbfs/folder_block_manager.go, libkbfs/modes.go
This also increases the QR period to a full hour instead of one minute, since it seems unreasonable to check every minute if blocks are sticking around for a full 2 weeks.  But it tempers that by a) running QR immediately on startup rather than waiting for one period, and b) shortening the period to one minute if it knows there is more QR left to do.
(I won't merge this until the bserver quota changes are deployed.)
Issue: KBFS-3186
=> modes: increase block archival period to 2 weeks

libgit/autogit_node_wrappers.go, libkbfs/readonly_node.go
They will be useful for viewing archived data.
Issue: KBFS-3189
=> libkbfs: promote read-only nodes into libkbfs

simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
Also vendors in the protocol change from keybase/client#12831.  (I'll merge the correct commit hash in as soon as that client PR is merged.)
Note that to get the quota, we make an explicit RPC to the server.  Unlike with the Finder integration, I don't think we'll be getting constant GUI requests for this, so this should be ok, plus it allows us to easily reuse the code that adds journal usage into the quota usage.
Issue: KBFS-3188
=> simplefs: add a way to get quota usage for the logged-in user

libkbfs/conflict_resolver.go, libkbfs/conflict_resolver_test.go, libkbfs/folder_branch_ops.go, libkbfs/test_common.go
In several places in FBO, we were referring to "branch" and "master branch" in a limited way that referred only to the merged status of the TLF.  "Branch" is actually meant to be a broader term, also encompassing archived views of a TLF.  So make the current uses a bit more explicit.
Issue: KBFS-3203
=> folder_branch_ops: rename branch-related stuff to avoid confusion

libkbfs/conflict_resolver.go, libkbfs/folder_block_manager.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/readonly_node.go, libkbfs/rekey_fsm.go
Archive FBOs turn off all background work, and make the whole TLF read-only. 
In a future PR, `KBFSOpsStandard` will create these according to a revision number encoded in the branch name, and set the "head" of the FBO to that exact revision.
Issue: KBFS-3203
=> folder_branch_ops: support "archive" FBOs

libkbfs/cr_chains.go
If an entry is created and then renamed within a single journal update, `crChains` ends up collapsing the [`createOp`,`renameOp`] into a single `createOp`, but with `createOp.renamed = true`.
This confused the `revertRenames` function, because it couldn't find a matching `rmOp` for the given `renameOp`.  But that's valid, so we can just leave that `createOp` un-reverted.  Otherwise, we'll have a `renameOp` without a valid `oldFinalPath`, and we'll crash.
Issue: keybase/client#12817
=> cr_chains: don't revert rename op if it was just created

libdokan/dir.go, libdokan/file_info_file.go, libfs/file_info_file.go, libfuse/dir.go, libfuse/file_info_file.go, libkbfs/config_local.go, libkbfs/cr_actions.go, libkbfs/data_types.go, libkbfs/dir_entry_test.go, libkbfs/folder_update_prepper.go, libkbfs/kbfs_ops_test.go, libkbfs/prefetcher_test.go, libkbfs/prev_revisions.go, libkbfs/prev_revisions_test.go, test/cr_basic_conflicts_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go, test/simple_test.go
This tracks the MD revision numbers for revisions of a file (or directory) in a skiplist-like fashion, basically giving pointers into places in the file's history, which will allow for easier access to past versions of the file.
To account for the extra metadata in the fileinfo, this also increases the max directory size by 50%.
For testing, this exposes the PrevRevision list in the `.kbfs_fileinfo` file (along with some refactoring to clean that up a bit and avoid kernel caching issues), and adds a few very simple checks to some DSL tests to make sure it shows the right number of revisions in the basic cases.
(This isn't strictly needed for time travel M1, but the earlier we get it in, the more useful it will be for people later on.)
Issue: KBFS-3194
=> data_types: add a PrevRevisions skiplist to EntryInfo

libkbfs/tlf_journal.go
`TlfJournal` creates an `info.json` file when it is first constructed. But whenever it finishes completely flushing, it removes ALL files in its directory, including `info.json`.  If more data comes into the journal after that, the `info.json` file was not re-created.  If KBFS then restarts, it won't be able to re-enable that journal since `info.json` is missing, and the data won't be flushed (and the user will see the server's view of the folder, instead of the journal view) until the user actually visits the folder.
This bug must have been present forever, but we never noticed it!
cc: @akalin-keybase
=> tlf_journal: re-create info.json file when journal gets more data

libkbfs/tlf_handle_resolve.go
We can avoid making any implicit-team-related calls to the service for single-team TLFs, since they are definitely non-implicit teams.
Issue: KBFS-3246
=> tlf_handle_resolve: avoid i-team resolution for single teams

libdokan/dir.go, libdokan/tlf.go, libfs/archive_util.go, libfs/constants.go, libfuse/errors.go, libfuse/tlf.go, libkbfs/errors.go, libkbfs/folder_branch_status.go, libkbfs/kbfs_ops.go, test/archive_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
If the revision has already been GC'd, libkbfs returns a nice error (which libfuse interprets as ENOENT).
Also prints the last gc'd revision to a TLF's `.kbfs_status`, for easier debugging.
Also also, adds a simple DSL test to check that archived revisions work on all platforms.
Depends on #1686.
Issue: KBFS-3205
=> libfuse/libdokan: expose `.kbfs_archived_rev` at the root of a TLF

libkbfs/journal_md_ops.go, libkbfs/key_manager.go, libkbfs/md_ops.go, libkbfs/md_util.go, libkbfs/tlf_journal.go
`handle.IsReader` crashes if you try to call it on a team-based handle.
Issue: KBFS-3253
=> md_util: check readership correctly after a decryption error

libkbfs/data_types.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_test.go
This PR introduces branch names that can refer to a specific revision, and `KBFSOpsStandard` respects that when creating FBOs.  It includes the first successful test of a time-travelling TLF!
It depends on #1685, which should be merged first.
Issue: KBFS-3204
=> kbfs_ops: support revision branch names

libkbfs/identify_util.go
An implicit team name can change (due to SBS resolution) between when we start an identify and when we get the result back.  I guess something changed in the timing of our tests recently to make this likely.
(This should fix the `TestSBSMultipleResolutions` flake.)
=> identify_util: don't require that i-team names match

libkbfs/cr_chains.go, libkbfs/state_checker.go
Also, catch this in the state checker, in case we ever figure out a test that can repro the issue.
Issue: KBFS-3258
=> cr_chains: ignore unrefs for ptrs that have already been updated

kbfsgit/runner_test.go, libfs/fs.go, libfs/fs_test.go, libgit/autogit_manager.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers_test.go, libgit/repo.go, libhttpserver/server.go, libpages/root.go, simplefs/simplefs.go, simplefs/simplefs_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/appstate.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/identify.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go, vendor/vendor.json
This uses keybase/client#12957 -- it should be reviewed and merged first.  CircleCI will break until then.
This PR also adds support for custom branch names to `libfs.NewFS`.
Issue: KBFS-3206
=> simplefs: support by-revision archived paths

simplefs/simplefs.go
Local paths need to be manipulated using the `path/filepath` package, not the `path` package.
=> [KBFS-3240] Fix windows uploads

libdokan/archive_reltime_file.go, libdokan/tlf.go, libfs/archive_util.go, libfs/constants.go, libfuse/archive_reltime_file.go, libfuse/tlf.go, test/archive_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
This depends on #1707, and won't pass circle until keybase/client#12850 is merged.
This adds support for a file like `.kbfs_archived_reltime=5m` at the root of a TLF, that will contain the name of the by-revision archive directory name, corresponding to a revision of the TLF that was live at the given relative time (e.g., 5 minutes ago, in the example).
It's a file, rather than a symlink, because if it were a symlink it would form a non-universal path that you wouldn't be able to send to other users or save for later use, without risking changing the revision you are pointing to.
The relative time is any string that can be parsed by `time.ParseDuration`.
Issue: KBFS-3211
=> libfuse/libdokan: file for by-relative-time archives

simplefs/simplefs.go, simplefs/simplefs_test.go
Depends on keybase/client#13025 and #1709.
Issue: KBFS-3212
=> simplefs: support by-rel-time archive paths

libkbfs/prev_revisions.go, libkbfs/prev_revisions_test.go
If the prev revisions list is full of revision numbers that are less than the new number `r`, we were clearing out the entire list without leaving an extra slot.  I think this can happen when squashing many journal revisions together into one, where the squashed one has a equal or lower revision number than the others.
Issue: keybase/client#12174
=> prev_revisions: avoid panic when squashing all revisions in list

simplefs/simplefs.go, simplefs/simplefs_test.go
When a revision is garbage-collected, all of the blocks live at the time of the GC are, of course, still alive.  So any version of a file alive at the time of the last GC is still accesible.
However, the previous revisions list drops any revisions numbers that are less than or equal to the revision number that was last GC'd.  It does this for simplicity, because it is hard to figure out, because without a full TLF history/skiplist scan it's hard to figure out if the revision was deleted before or after that GC'd revision. Unfortunately, this meant the `GetRevisions` code might not return all the available revisions, since the oldest one might be missing from the previous revisions list.
Instead, have `GetRevisions` check the revision _before_ the oldest revision in the list, in case it …
=> simplefs: `GetRevisions` should try to include oldest revision

kbfsmd/server_errors.go
The bserver needs to distinguish a missing folder handle from other types of errors, to support implicit teams.
Issue: KBFS-3284
=> kbfsmd: new server error for a missing folder handle

circle.yml
(This is a port of a PR from client.)
The main problem was that
~/.gradle/caches/transforms-1/files-1.1/keybaselib.aar is a
cached directory that stores every new keybaselib.aar build.
But we don't really need to be caching anyway. It seems that CircleCI already
does some sort of download caching. So just nuke caching entirely.
Also fix build breakage when there is no cache -- we'd previously run into
it periodically.
=> Remove CircleCI cache

libkbfs/kbfs_ops.go
=> kbfs_ops: fix log message, all team types get TLF IDs

libkbfs/block_tree.go, libkbfs/block_types.go, libkbfs/crypto_common_test.go, libkbfs/file_data.go, libkbfs/file_data_test.go, libkbfs/folder_block_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/prefetcher_test.go
When we introduce indirect directory blocks, we'll want to reuse the logic for navigating a tree of blocks.  Do this by adding generic offset types and some new helper functions to the Block interface, and refactoring functions from `fileData` into a new generic `blockTree` struct that can operate on any type of block.
This commit shouldn't change any logicc, it's just a refactor
Issue: KBFS-3299
=> file_data: generalize functions for getting blocks

libkbfs/block_types.go, libkbfs/dir_data.go, libkbfs/dir_data_test.go, libkbfs/folder_block_ops.go
This PR introduces a `dirData` class that can understand multi-block directories, and it implements read-only operations on it and tests for them.  (But it's not in use in the rest of the code yet.)
A future PR will implement the more complicated modifying methods.
Depends on #1732 and #1734.
Issue: KBFS-3301
=> dir_data: implement the read-only methods

circle.yml
This image uses go 1.10.3.
Also, the current image mistakenly uses an r11 NDK. This image uses
an r15 NDK.
=> Use latest circleci-kbfs Docker image

libkbfs/block_tree.go, libkbfs/block_types.go, libkbfs/crypto_common_test.go, libkbfs/dir_data.go, libkbfs/dir_data_test.go, libkbfs/file_data.go, libkbfs/file_data_test.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
In a future PR, `dirData` will start using these methods.
Also, a few other cleanups:
* Separate the indirect pointer methods of blocks out into their own interface, so we don't have to implement them in `CommonBlock` and test block types.
* Have `dirData` and `fileData` use the fields of `blockTree` for most of their internal fields, to simplify things and avoid unnecessary overhead.
Issue: KBFS-3301
=> block_tree: refactor tree update methods out of fileData

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/tlf_journal.go, libkbfs/unflushed_path_cache.go
And use this in `crChains`.
It seems kind of random, but this will be needed in an upcoming PR when we need to replace some of directory entry cache stuff in `folderBlockOps` with `dirData`.
=> root_metadata: add an interface for KeyMetadata + root dir entry

libkbfs/block_tree.go, libkbfs/block_types.go, libkbfs/bsplitter_simple.go, libkbfs/bsplitter_simple_test.go, libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, libkbfs/dir_data.go, libkbfs/dir_data_test.go, libkbfs/file_data_test.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/kbfs_cr_test.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/kbfs_ops_test.go, libkbfs/md_journal_test.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/test_common.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go, libkbfs/unflushed_path_cache.go
This adds a `BlockSplitter` function for splitting up directory blocks that get too big, and implements `addEntry`, `removeEntry` and `updateEntry` methods for `dirData`.
It also adds a bunch of tests for these new methods in `dir_data_test.go` (which github has collapsed).
The basic algorithm is the same as for files.  If a leaf directory block has more child entries than it can handle, traverse up the path of the block tree until we find a parent with an empty indirect pointer slot, and add a block to the right.  (If no parent has room, add another layer of indirection at the top.)  Then shift the new block over at its level in the tree, until reaching the place where its offset fits in.
Note that this builds on #1736, and also modifies the existing block-shifting code a bit because, …
=> dir_data: implement dirblock-splitting and add/remove/update methods

libkbfs/conflict_resolver.go, libkbfs/dir_data.go, libkbfs/dir_data_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/node_cache.go, vendor/github.com/golang/mock/gomock/call.go, vendor/github.com/golang/mock/gomock/callset.go, vendor/github.com/golang/mock/gomock/controller.go, vendor/vendor.json
`deCache` has been outdated for a while now.  It used to be important when we allowed files to be synced individually, so that one file's directory entry changes could be preserved in memory, while flushing only another file's entry in the same directory.  Now that we only support `SyncAll`, it can be removed in favor of just keeping a single view of dirty `DirBlock`s in the dirty block cache.
The transition to `dirData` seemed like a good time to do this, so I combined the two.  Now all changes to directories are synced to the dirty blocked cache, and all changed to the root directory entry are kept in memory in the `folderBlockOps` instance.  This allowed a bunch of code to be simplified or removed.
Note that this doesn't yet allow for multi-block directories to be written.  The next PR …
=> folder_block_ops: use `dirData` and get rid of `deCache`

libkbfs/dir_data.go
Before the previous commit that got rid of `deCache` in favor of `dirData`, `folderBlockOps.getDirtyEntryLocked` used `blockLookup` as the request type when reading blocks.  This was to make sure we did not release `blockLock` when making network accesses to fetch blocks, like we normally do with `blockRead`.  It's a minor optimization, but if we do that while creating an entry, we could end up in a bad race situation where two Nodes are created for the same entry name.
So revive those old semantics so that race doesn't come back to haunt us.
Commit 1a9a77ed3a91f05fbcf2b7fd932cd494b78e8a14 has a few details about it.
=> dir_data: fix lookup semantics

vendor/vendor.json
No changes, just pointing to the right place now that we updated
go-codec master.
=> Update vendored go-codec to point to master

libkbfs/block_tree.go, libkbfs/block_types.go, libkbfs/dir_data.go, libkbfs/file_data.go, libkbfs/folder_block_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
This updates `folderUpdatePrepper` to use `dirData` when updating dir entries, and to ready any dirty blocks within the directory when prepping the paths for commit.
The ready path() isn't yet exercised in any tests though; a future PR may end up having to fix bugs here.  It's split out in this way, pre-testing, for ease of review.
In addition, this PR:
* refactors ready functions out of `fileData` into `blockTree` (no behavior change)
* makes `blockTree` use a restricted interface for checking dirtiness, to make it easier to pass in other kinds of dirty-block-holders, like `localBcache`.
=> folder_update_prepper: use `dirData` when prepping paths

libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go
This PR removes all the rest of the direct usage of `DirBlock` from `folderBranchOps` and `folderBlockOps`.  This includes:
* Renames.
* Searching for nodes.
* Fast-forwarding.
* Simple existences checks in `folderBranchOps`.
* `SyncAll`.
=> folder_branch_ops: remove almost all direct uses of `DirBlock`

libkbfs/reporter_kbpki.go, simplefs/simplefs.go
The NotifySync notifications tend to come in clustered (up to more than 10 within a second), so this seems pretty helpful.
This will need to go in at the same time as https://github.com/keybase/client/pull/13408
=> throttle NotifySync and NotifyPathUpdated to one per second

libfuse/folderlist.go
There's no reason to look up implicit teams and TLF IDs before removing a favorite.  And if it's a pre-reset folder, that might cause a failure because the MDs can't be read by the current device.
Issue: #1759
=> folderlist: use "quick" parsing when ignoring a favorite

libkbfs/conflict_resolver.go, libkbfs/cr_actions.go, libkbfs/cr_chains.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
This removes all direct uses of directory blocks from the conflict resolution process, and replaces them with `dirData` uses that support multiple levels of indirection in directories.
Note that this probably won't do block pointer accounting correctly when there are levels of indirection.  I'll do that in a followup PR.
=> cr: replace `DirBlock.Children` uses with `dirData`

libkbfs/folder_block_ops.go, libkbfs/reporter_kbpki.go, libkbfs/util.go
Also, make sure directory out of date errors get the right path attached to them.
Issue: KBFS-3369
=> reporter: don't filter error notifications

libkbfs/folder_block_ops.go, libkbfs/folder_update_prepper.go
When undoing a dir entry operation, we need to un-dirty any blocks that had been dirtied for the first time, by removing them from the dirty block cache.
Also, when deleting big dir trees, make sure the unrefs propagate all the way down to the remaining parent, so they can be counted in the final resolution.
Finally, move the unref accounting to the top of the prep loop, to make sure the first passed-in block gets properly accounted for.
=> folder_block_ops: better unref management for dirty dirs

libkbfs/folder_update_prepper.go, libkbfs/ops.go, libkbfs/ops_test.go
When we run through conflict resolution, sometimes we need to unref blocks that have been pushed to the bserver, but not actually committed as part of any MD because _another_ conflict was hit before we could put the MD.  These blocks are special because they still need to be marked as unreferenced in the next successful PR (so they can be archived/deleted from the bserver), but without actually counting their bytes toward the TLF byte usage stored in the MD update.
So this PR introduces a new field in `resolutionOp` to track these blocks separately, so we can tell whether or not to count their bytes on a future resolution.
=> ops: track "uncommitted" unrefs in `resolutionOp`

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, libkbfs/folder_block_ops.go, libkbfs/folder_update_prepper.go
When fetching child directory blocks in parallel in `dirData` (via `blockTree`), we need to hold `blockLock` the whole time.  That means we have to lock `blockLock` when we create the `dirData`, and release it when we're done with that instance.
So if it's not already locked, have the `dirData` constructor method return an undo function that must be called when the `dirData` goes out of scope, which unlocks `blockLock`.
And fix up all other `folderBlockOps` calls that previously locked it during the course of conflict resolution.
=> folder_block_ops: improve locking situation with dirData

libkbfs/conflict_resolver.go, libkbfs/cr_actions.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
(Depends on #1768.)
And during the resolution process, make sure we account both for these unrefs, and dir block refs/unrefs that occurred in previous resolutionOps that haven't made it to the server yet.
=> cr: collect dir block unrefs while applying actions

libkbfs/block_types.go, libkbfs/folder_update_prepper.go
Now that dirs can have multiple levels of indirection, it doesn't make sense to always use the plain (encoded, but not encrypted) size of the top block as the `DirEntry.Size`.  But it's probably too expensive to download all leaf blocks, and encode them, to find out the "correct" value during every folder update.
Instead, use a simple heuristic based on the number of indirect pointers that isn't great, but probably good enough.
Issue: KBFS-3305
=> folder_update_prepper: estimate directory size of indirect blocks

libkbfs/block_tree.go, libkbfs/dir_data_test.go
While debugging new multi-block directory tests, I noticed some `blockTree` errors.  I added a `String` method to help with debugging, and fixed two bugs:
* If a block got shifted all the way to the left side of an existing block, and that was its final location, we were failing to update the new parent pointers to that block.  Instead, update those pointers at the top of the loop, before breaking when we figure out that it's in the right location.  This PR adds a new test that fails without the fix.
* `shiftBlocksToFillHole` was dropping some of the unref pointers when setting parent offsets.  This will be tested in a future PR that adds more multi-block dir DSL tests.
Issue: KBFS-3304
=> block_tree: fix shifting logic, and add a useful String method

kbfscrypto/auth_token.go
`GOOS` shows `darwin` for both macOS and iOS.  If we want to distinguish stats from these two on the server side, we should do what the service does and use `libkb.GetPlatformString()` instead, which override `GOOS` with "ios" if it's been compiled for iOS.
Issue: KBFS-3010
=> kbfscrypto: distinguish between "darwin" and "ios" in AuthToken

libkbfs/block_disk_store.go, libkbfs/block_ops.go, libkbfs/block_ref_map.go, libkbfs/bserver_disk.go, libkbfs/bserver_measured.go, libkbfs/bserver_memory.go, libkbfs/bserver_remote.go, libkbfs/folder_block_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
(I won't merge it until the corresponding kbfs-server work is merged and deployed.)
We can check with the server to figure out whether a block is "live" or not, and if not, we can avoid counting its size in the sum.  This is then used by the `folderUpdatePrepper` to know exactly which blocks need to have their sizes included in the "unref" sum, so that the MD byte counts can be managed correctly.  This will matter when other PRs start including dirData refs and unrefs in `resolutionOp`s.
=> folder_block_ops: option for excluding non-live blocks from sums

ioutil/os_wrap.go
TestJournalCoalescing* tests have a problem where sometimes `os.MkdirAll()` calls return a "No such file or directory", which doesn't make much sense.  I suspect it's a race where a directory exists, but then is wiped before the next child can be made, or something like that.  I don't know what is deleting those directories though, whether it's something in Jenkins or something in the code or test.
For now, let's try re-trying the `MkdirAll` call once, to see if it helps.  If not, we can drill deeper into exactly what's going on.
Issue: KBFS-3245
=> ioutil: quick workaround to try to reduce test flakes

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go
I've been unable to get good logs that reproduce this issue, and it seems safe to just ignore the case where CR is trying to change an original between two identical pointers.  This probably indicates something like the device putting an MD, but failing before it finds out that the put succeeds. Then later it tries to resolve the conflict against itself.  In theory, we have other protections against this, and it would be nice to figure out why it's causing problems in this case, but it's probably best to paper over it for now and just give the user a smoother experience.
It's possible that when the CR finally succeeds, it will end up with a bunch of conflict files, which might get the user's attention quickly and entice them to send logs soon (thus capturing the original source of the …
=> cr: ignore `changeOriginal` call between two same pointers

libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go
Otherwise the caller doing a DeepCopy might trigger a concurrent hashmap issue due to a parallel write operation that modifies the same block.
Issue: KBFS-3407
=> folder_block_ops: copy dirty dir while under block lock

test/run_fuse_test.go
When launching darwin fuse DSL tests, we were calling `FS.WithContext()` to created the context that gets passed to `FS.LaunchProcessor()`.  The context therefore got stuck with a 19-second per-operation darwin timeout.  So if the overall test took more than 19s, the goroutine that processed invalidation notifications would exit, and the kernel cache would stop getting updates, leading to weird, rare data failures.
Instead, just make a context with the required properties, without the actual timeout (or an unnecessary FID tag).
Issue: KBFS-3394
=> test: don't set darwin timeout on overall test context

libkbfs/data_types.go, libkbfs/keybase_service_base.go
Make a copy of the UserInfo before we modify it, in case multiple goroutines are modifying/accessing it at the same time.
I think this was why this function returns a different UserInfo object in the first place, but I forgot to do the actual copy.
=> keybase_service_base: avoid concurrent map access panic

kbfsmd/server_errors.go
It's possible that the user actually sees this message in some rare cases.
Issue: KBFS-3407
=> kbfsmd: improve `ServerErrorLockConflict` error message

libgit/rpc.go
Give the return params different names, so we don't try to access them when they're explicitly set to nil on an error return.
Issue: KBFS-3415
=> libgit: avoid using nil return values in deferred function

libgit/autogit_manager.go, libgit/repo.go, libgit/util.go
Instead, refactor the autogit strategy and only create a "working" file while holding the lock.  If another worker has already created the file and is within an hour time limit according to the timestamp on the file, just return `nil` to avoid showing an error to the user. If the other worker fails, they'll get another message about doing GC on a later repo operation.
Issue: KBFS-3407
=> libgit: don't hold server locks for GC for too long

libkbfs/cr_actions.go, test/cr_basic_conflicts_test.go
When the merged user sets the mtime and moves a file across directories, and the unmerged user just sets the mtime, we weren't issuing the correct local op notifications to the unmerged user after conflict resolution.  Previously, the notifications made it look like the unmerged file was moved somewhere else, and the file would appear to be missing on a subsequent lookup.
To fix, detect the situation explicitly and update the notifications to make it look like a new file (the renamed merged file) is being created instead.
Note that this doesn't solve KBFS-3408, it's just a test I tried adding while debugging that issue.  The test fails to repro that issue though, but it's worth fixing in its own right.
Issue: KBFS-3408
=> cr_actions: add test and fix on setmtime + merged rename conflict

libkbfs/cr_chains.go
When an entry is both created and deleted within a set of operations across a set of MD updates, we won't be able to find its corresponding `rmOp` using the `mostRecent` pointer, because that pointer doesn't need to be unreferenced.  Instead, just use a default using the root pointer.
An op without a path can lead to a crash in conflict resolution and/or while getting the journal status.
Issue: KBFS-3408
Issue: KBFS-3414 (maybe)
=> cr_chains: use default path for unknown, deleted-chain ops

libkbfs/tlf_handle_resolve.go
During migration, when the members in the old handle doesn't match the users in a new implicit team, we should be returning the partially resolved handle and explicitly returning a nil error, to allow for better error reporting and avoid a panic in the caller.
(Note that this came about because PUK-less users are not full members of an implicit team, and thus aren't listed in the membership list even when they do exist in the old handle.  This fix just avoids a crash in this case, but there's an open question about how we should deal with those migrations that should be addressed later.)
Issue: KBFS-3437
=> tlf_handle_resolve: return partial handle when team doesn't match

libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/node.go
This will let the future Autogit browser circumvent the normal block-based data access layer using custom Nodes.
Issue: KBFS-3422
=> interfaces: add methods to `Node` for direct FS data access

libgit/browser.go, libgit/browser_file.go, libgit/browser_file_info.go, libgit/browser_test.go
`Browser` uses the gogit `Tree` instance to navigate directories and read files directly from a dotgit directory, without requiring an explicit checkout.
This will be used in future commits as the basis for the new `.kbfs_autogit` directory.
The test provided is pretty simple but covers the basics.  I'm happy to add more stuff to the test if there are specific things you think would be good to add.
Issue: KBFS-3421
=> libgit: add a git browser that doesn't require a checkout

libdokan/start.go, libfuse/start.go
If for some reason the service doesn't get started, KBFS will try to write a file to this directory before it exists, and will fail in a loop.
Issue: KBFS-3450
=> libfuse/libdokan: ensure runtime exists before writing it

libkbfs/keybase_service_base.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
The previous team refresher would not work with keys offset by the saved KBFS crypt key generation, so it could give stale results for upgraded TLFs.
=> use new team refresher that is aware of saved KBFS crypt keys CORE-9030

kbpagesd/main.go, libgit/autogit_manager.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go, libgit/browser.go, libgit/repo_test.go, libgit/rpc.go, libgit/util.go, libkbfs/folder_branch_ops.go, libkbfs/node_cache.go, libpages/root.go
This also changes the directory structure, so there's no more need for the `tlf_type/tlf_name` prefix in the autogit path.  You can browse repos under TLFs for which you don't have write access.
However, this does NOT yet support invalidating kernel caches when the commits happen to the underlying repo.  So we shouldn't yet update kbpbot after this is merged, until subsequent PRs are also merged.
Due to some nasty potential deadlocks, I had to rework the way that NodeCache wraps its children, to make sure it happens without taking a lock.
Issue: KBFS-3425
=> libgit: autogit browses git repos directly, without a checkout

libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go, libgit/browser.go, libgit/browser_test.go
With the root of an autogit repo, you can now navigate to the branch of a version by using `.kbfs_autogit_branch_<name>`.  Branch names can contain slashes, so you can stack these.  For example, to navigate to a branch a/b/c in repo "test", use this path:
```
.kbfs_autogit/test/.kbfs_autogit_branch_a/.kbfs_autogit_branch_b/.kbfs_autogit_branch_c/
```
It's a bit unwieldy, but it will be fine for GUI-based browsing, and I don't see a good alternative for CLI-based browsing, besides shortening the prefix somehow.
If the branch names doesn't start with "refs/", then "refs/heads/" is prepended to it.  But e.g. tags can be shown with a full path like "refs/tags/v2.6.0".
Issue: KBFS-3426
=> libgit: support for browsing branches

libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/node_cache.go, libkbfs/node_cache_test.go
This function returns all the children of the current node.  It will be useful to figure out which autogit nodes need to be invalidated, after a repo is updated.
This implementation iterates through all nodes, and back through all parents, to figure out which nodes to return.  A better implementation might track the a node's children directly, but that will be a bit tricky to get right, so let'd try this for now and see if it's good enough.
Issue: KBFS-3427
=> node_cache: add and implement AllNodeChildren function

libkbfs/folder_branch_ops.go
We should treat a migration like a rekey, so there aren't any unwanted tracker popups.
Issue: KBFS-3441
=> folder_branch_ops: avoid identify during migration

libgit/autogit_manager.go, libgit/autogit_node_wrappers.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go, libkbfs/node_cache.go
When the root of a .kbfs_git repo is updated, invalidate the associated autogit root node, and any cached subnodes below it.  Achieve this by:
1. In `AutogitManager`, tracking the association between a `.kbfs_git` repo root node, and the associated `.kbfs_autogit` repo root node.
2. When the former is updated, ask `folderBranchOps` to invalidate all nodes associated with the latter.
3. `folderBranchOps` gets all of the autogit nodes for that repo from the node cache.  (This isn't optimally implemented, but it's probably good enough for now.)
4. `folderBranchOps` sends invalidation notifications for all of those nodes, which get delivered to the kernel in the usual way.
I've tested the invalidation by hand, and I plan to write a kbfsdocker autogit test in the future, which will exercise it …
=> autogit: invalidate all AG nodes associated with an updated repo

libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/mocks_test.go, libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go
There's no need to explicitly check team membership while migrating an existing folder to an implicit team, because the name of the folder is already validated against the folder's current MD update during `MDOps.GetIDForHandle()`.
Plus, checking the membership here needlessly fails in some cases, such as for PUK-less members who appear in the team name, but would not be reported by the service as resolved team members.
Issue: KBFS-3441
=> tlf_handle: don't explicitly check team membership while migrating

libfs/fs.go, libgit/autogit_manager.go, libgit/repo.go
Whenever a repo is accessed within a particular TLF, delete all old checkouts in that TLF.
Also, remove self-checkouts on first autogit access to ANY repo, because some users (like kbpbot) only checkout repos from other TLFs, and use their own private folder as the destination.
To enable this, we allow for "unwrapped" FSes, to avoid getting entangled in recursive node wrapping.
Issue: KBFS-3431
=> autogit: remove old autogit checkouts when a repo is accessed

libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go
Because ':' is a bad character on Windows paths.
(Open to other suggestions.)
=> autogit: use '^' as branch separator

libkbfs/chat_rpc.go, vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go, vendor/github.com/keybase/client/go/protocol/chat1/common.go, vendor/github.com/keybase/client/go/protocol/chat1/extras.go, vendor/github.com/keybase/client/go/protocol/chat1/local.go, vendor/vendor.json
Otherwise it would send 0 over on the subsequent pages and get 0 results.
Also, do we really need the entire thread? Can we check in this loop to see if we have enough data to reasonably render the widget? It seems like we can abort out of this loop and save a bunch of traffic.
=> always set the number on pagination param when fetching chat threads CORE-9096

libkbfs/tlf_handle_resolve.go
For non-single-team folders, we should always check whether something is an implicit team, now that we've started migrating TLFs.  This was originally intended to avoid extra implicit team calls for chat, but now that chat is all upgraded, it almost never calls into KBFS, so this shouldn't change the behavior at all.
Issue: KBFS-3480
=> tlf_handle_resolve: never skip implicit team resolution

libkbfs/identify_util.go, libkbfs/keybase_service_base.go
Otherwise, the original identifier will hang because `makeTlfBreaksIfNeeded` won't return.
Issue: KBFS-3480
=> keybase_service_base: on an identify error, notify user breaks

libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go
Previously, if the sync cache was full, the overall cache put would fail (without logging an error, due to the unnamed return param). However, this means that when your synced directory is bigger than your disk cache, performance crawls to a halt in that directory because all new blocks need to be fetched again, even if there's room in the working set cache.
So, if the sync cache put fails, just put it in the working set and let eviction take care of it later.
=> disk_block_cache: put blocks in working set if sync cache is full

libkbfs/identify_util.go, libkbfs/identify_util_test.go, libkbfs/keybase_daemon_rpc_test.go, libkbfs/keybase_service_base.go
And check context for cancellation on all paths as well.
The new widget behavior of use CHAT_GUI identify behavior on SimpleFSStat() calls, as the initializing call into a KBFS folder, was exercising new paths in the identify code that lead to deadlock. Specifically:
* When calling `IdentifyLite` on single-team folder names, we weren't passing any track-break messages back to the goroutine waiting for them.
* When trying to resolve implicit teams, if there were no track breaks, we weren't passing any track-break messages back to the goroutine either.  And now that we're trying to resolve implicit teams for all private and public folders, this was always happening.
Put these two together, and every type of folder was getting deadlocked if the widget stat'd it before its first access via …
=> identify: call userBreak callback on all paths

kbfscrypto/crypto_key_types.go, kbfscrypto/encrypted_data.go, kbfscrypto/encrypted_data_test.go, kbfscrypto/errors.go
This introduces a new encryption scheme for blocks, that derives both the encryption key and nonce from a function of the TLF crypt key and server-side key half.
In the existing version 1 encryption scheme, we xor the TLF crypt key and server-side key half together to use as the block crypt key, and generate a nonce randomly.  This scheme has a few weaknesses though, in the case when an evil client and an evil server can collude against a second, unsuspecting client, to serve it bad data.  In particular, an evil client could choose two different server-side key halves that transform the encrypted data into two different plaintext outputs, and instruct the server to give different keys out to different clients.  This works because the server-side key has no relationship with the overall …
=> kbfscrypto: add new encryption scheme that derives nonce from key

kbfsblock/id.go, libkbfs/block_ops.go, libkbfs/block_ops_test.go, libkbfs/chat_local.go, libkbfs/config_local.go, libkbfs/init.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
And use it in `BlockOpsStandard` to choose the hash type for the block.  Tested on a local instance of KBFS.
This also includes a small fix in `ChatLocal` to avoid a panic when starting up in local mode.
Issue: KBFS-3459
=> init: add command line flag for setting encryption version

kbfsblock/id.go, kbfscrypto/encrypted_data.go, kbfscrypto/encrypted_data_test.go, kbfshash/hash.go, libkbfs/block_disk_store_test.go, libkbfs/block_journal_test.go, libkbfs/block_ops.go, libkbfs/block_util.go, libkbfs/bserver_remote_test.go, libkbfs/crypto_common.go, libkbfs/crypto_common_test.go, libkbfs/folder_branch_ops.go, libkbfs/journal_block_server_test.go, libkbfs/journal_server_test.go, libkbfs/tlf_journal_test.go
And make hash type dependent on encryption type.
This is cleanup suggested by @akalin-keybase in #1836, #1837 and #1838.  It shouldn't change any logic.
=> kbfscrypto: move encryption version switch to lower-level logic

libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/root_metadata.go
The unresolved users are now part of the implicit team.  Keeping them in the MD confuses the MD, and causes it to not return `TeamKeying` as the keying type.
=> root_metadata: clear unresolved users from MD on migration

libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go
An `ls /keybase/team` results in a `Lookup()` call for each team in your favorites list.  This in turn requires parsing the TLF handle. The folderlist already uses `libfs.ParseTlfHandlePreferredQuick()`, which sets the `idGetter` to `nil` to skip looking up TLF IDs for private/public folders.  But team TLF IDs were treated differently, since they don't use `idGetter`.
Instead, if `idGetter` is `nil`, use that as a signal to skip looking up the team TLF ID, to make stats much faster in the team folder list.
=> tlf_handle_resolve: don't fetch team TLF ID if idGetter == nil

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, libkbfs/folder_block_ops.go
Even if the `getPaths()` caller doesn't explicitly request the paths of created chains, we still need to fill in the final paths on the ops of those chains, because they might be used later (for example, in the case where the same directory is created in both the unmerged and merged branches, and the child entries need to be compared for conflicts).
Also, to test this and help prevent all similar issues like this in the past, when in test mode the code now first clears all paths, and afterwards checks that paths were set on all ops.  Before this PR, this resulted in several test failures that are now fixed.
Issue: KBFS-3493
=> cr: fill in final paths for ops on created chains

kbfscrypto/encrypted_data.go, kbfscrypto/encrypted_data_test.go
Otherwise there's a panic when sending the error back over RPC.
Issue: KBFS-3514
=> kbfscrypto: set a Cause on libkb.DecryptionErrors

libkbfs/block_tree.go, libkbfs/block_tree_test.go, vendor/github.com/gammazero/deque/LICENSE, vendor/github.com/gammazero/deque/README.md, vendor/github.com/gammazero/deque/deque.go, vendor/github.com/gammazero/deque/doc.go, vendor/github.com/gammazero/deque/go.test.sh, vendor/github.com/gammazero/workerpool/LICENSE, vendor/github.com/gammazero/workerpool/README.md, vendor/github.com/gammazero/workerpool/doc.go, vendor/github.com/gammazero/workerpool/go.test.sh, vendor/github.com/gammazero/workerpool/workerpool.go, vendor/vendor.json
rewrite BlockTree.getBlocksForOffsetRange to be iterative and
worker-pool based instead of recursive, so as to limit the
number of goroutines spawned.
=> Rewrite bt.getBlocksForOffsetRange to avoid spawning too many goroutines

libgit/autogit_node_wrappers.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/node.go, libkbfs/node_cache.go, libkbfs/node_cache_test.go
There was an issue where `repoDirNode.WrapChild` was calling back into the FS to get the type of the child.  But `WrapChild` happens under `folderBlockOps.blockLock`, and getting the type of the child might also require getting `blockLock`, so it would hit a deadlock.
This fixes it by just tracking the type of the `Node` in the node itself, and using that in `WrapChild` instead of needing to call back into `folderBranchOps` and friends.
Also, I noticed another similar situation in `autogitRootNode`, so I fixed that as well.
=> autogit: avoid FS access during `WrapChild` calls to avoid deadlock

libkbfs/config_local.go, libkbfs/count_meter.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/disk_md_cache.go, libkbfs/disk_md_cache_test.go, libkbfs/errors.go, libkbfs/interfaces.go, libkbfs/leveldb.go, libkbfs/mocks_test.go
The cache has a Stage+Commit flow, instead of the usual Put, because according to the KBFS Offline design, we might not want to cache the MD right after learning about it.  Instead, we might want to wait until syncing is done, or until the user actually accesses it for the first time.  In the meantime, the MD must be stored in encrypted form somewhere, so this cache stages them in memory until they are fully commit to disk or unstaged.
Issue: KBFS-3504
=> disk_md_cache: introduce disk cache for the last known MD heads

libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
This will let a future PR take an action when a TLF is fully synced. (They will have to verify the block's prefetch status is indeed `FinishedPrefetch` after the channel is closed, of course.)
Issue: KBFS-3505
=> prefetcher: allow caller to wait for a block prefetch to complete

libkbfs/reporter_kbpki.go
Now that we show errors again, we've gotten some complaints about shell trickery that triggers these errors by looking up certain files along the path of the current working directory.  We've been getting along fine without this type of errors for a while, so suppress them again.
=> reporter: suppress "user not found" errors

packaging/linux/systemd/kbfs.service
Useful to unmount kbfs in no thrills way. It is important to have this posibility since active fuse mounts cause laptop suspend failures (as of linux kernel 4.18 at least).
=> kbfs.service: support stop action.

libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_remote.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
The sync cache will keep track of the last revision for which all the unreferenced blocks have been deleted from the disk cache.  A future PR will introduce a background goroutine that uses this to clean the cache, without relying on being online to process MD updates in real time.
Issue: KBFS-3507
=> disk_block_cache: add a db for tracking the last unref revision

libkbfs/backpressure_disk_limiter.go, libkbfs/config_local.go, libkbfs/conflict_resolver.go, libkbfs/folder_branch_ops.go, libkbfs/folder_branch_status.go, libkbfs/init.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/mdserver_remote.go, libkbfs/prefetcher.go
`mdserverRemote` now reads the latest TLF revision from the disk when possible, and stages commits that are get/put from the remote server.
FBO nows commits staged MDs for synced TLFs to disk once one of the following conditions is met:
1) The new revision is fully prefetched.
2) The new revision has been read by the user.
In addition, FBO won't even show a downloaded revision to the user until at least the root block for the revision has been prefetched.
All of this is to ensure that a synced TLF contains at least some data if the user suddenly loses connectivity, or restarts in offline mode.
Also fix a few bugs, and initialize the disk MD cache on startup.
Issue: KBFS-3505
=> folder_branch_ops: commit MDs to disk after reading/prefetching

libkbfs/state_checker.go, test/run_fuse_test.go
* Properly cancel FUSE background context in DSL tests; the parent context wasn't getting canceled.
* state_checker: when checking GC last data, don't create new ops. Because this happens during shut down, the new ops will never be cleaned up!  We only care about ones that actually ran GC here, so no need to create new ones.
cc: @jakob223 these are a few leaks I found.  Maybe there are more, but this should be a good start.  (I don't think they were related to the timeouts we saw earlier though.)
=> test: clean up some goroutine leaks

kbfscrypto/crypto_key_types.go, libkbfs/crypto_client_test.go
I don't think this was causing any actual errors, but @maxtaco says it's a bug not to set the `Cause` on a `DecryptionError`.
Issue: KBFS-3588
=> kbfscrypto: add a cause to a few DecryptionErrors

kbfsgit/runner.go
When we construct the ref-data-by-name map to `libgit.UpdateRepoMD`, we were erroring out when trying to look up the hash corresponding to symbolic references like "HEAD".  We should resolve those before we look up the hash.
Also, we were putting the _source_ reference name as the key to the map, rather than the dest name.  That meant if someone pushed from a local branch directly to master, that would not be recorded as a master push in the server's DB.  Fix that by always using the destination ref name instead.
Issue: keybase/client#14423
=> kbfsgit: resolve sym refs and use dest ref names in ref data map

libkbfs/folder_block_manager.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go
A synced TLF needs to be able to clean up old cached blocks, even if it is offline when the block is unreferenced by a different device. So we track the last unref'd revision for each synced TLF, fetch each merged revision since the last one, and delete all the unreferenced blocks from it.
Issue: KBFS-3507
=> folder_block_manager: background cleanup of the sync cache

libkbfs/favorites.go, libkbfs/keybase_daemon_rpc.go
This commit changes the favorites cache to not refresh until it is invalidated instead of refreshing every time.
Relevant PRs:
- https://github.com/keybase/client/pull/14370
- https://github.com/keybase/keybase/pull/3059
=> libkbfs: actually keep a favorites cache

libkbfs/favorites.go, libkbfs/keybase_daemon_rpc.go
Reverts keybase/kbfs#1870
Needed because this can't merge until after https://github.com/keybase/client/pull/14554 does
Sorry..
=> Revert "libkbfs: actually keep a favorites cache"

kbfsedits/tlf_history.go, kbfsedits/tlf_history_test.go
Otherwise, conflicted copies will show up.
Issue: KBFS-3609
=> tlf_history: treat files to ignore as prefixes

libkbfs/favorites.go, libkbfs/keybase_daemon_rpc.go
This is the same as a previous PR that was reverted because the corresponding PR in `client` was not yet approved.
=> Use the KBFS favorites cache

libkbfs/errors.go, libkbfs/interfaces.go, libkbfs/md_ops.go, libkbfs/md_ops_test.go, libkbfs/mdcache.go, libkbfs/mdserver_remote.go, libkbfs/mocks_test.go
In #1888, a user is doing way more work than necessary to validate a bunch of MDs written by a revoked device, during garbage collection.  We can improve that a small amount of caching:
This PR:
* Moves verification of KBFS Merkle nodes into the mdserver remote, so they can be cached more effectively.
* Adds a limited size LRU cache for the (validated) results of `FindNextMD`.
* Tracks the chain of MDs that have been validated up to a given revision (the one immediately following the revoke in the Merkle tree).
This should eliminate most of the redundant work that was happening when verifying lots of MDs written by the same revoked device, as in garbage collection.
Issue: KBFS-3581
Issue: #1888
=> md_ops: add caching to improve validation of MDs written by revoked devices

libkbfs/config_local.go, libkbfs/disk_md_cache.go
Otherwise each singleop git operation will leave one open.
=> config_local: shutdown disk md cache

libkbfs/conflict_resolver.go, libkbfs/folder_branch_ops.go
This fixes a test flake, where MDs could be commited during the part a `SyncFromServer` call that did a `SyncAll`.  The test's timing depends on the commit call happening only while fetching the updates from the server.
And committing only on reads is what we want anyway -- once the changes have been seen by the user, they should be committed.  But writes don't count for that (and they'll be producing a new revision anyway).
=> folder_branch_ops: only commit MDs to disk on a read

libkbfs/config_local.go, libkbfs/disk_md_cache_test.go, libkbfs/disk_quota_cache.go, libkbfs/disk_quota_cache_test.go, libkbfs/errors.go, libkbfs/folder_branch_status.go, libkbfs/init.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go, libkbfs/quota_usage.go
This introduces a new disk-based cache for quota infos (keyed by `UserOrTeamID`).  The eventually-consistent quota fetcher uses the disk-cached value, if the current quota can't be fetched from the server within a small amount of time (500ms).
Issue: KBFS-3506
=> disk_quota_cache: cache quotas to disk, and use when needed

libkbfs/block_tree.go
If the context is cancelled at an inconvenient time, one worker
could submit more tasks after another has stopped the worker
pool. To fix this, let the workerpool drain on context
cancellation, which will cancel the workerpool when the call to
`wg.Done()` returns.
=> block_tree: fix race condition

libfs/sync_control_file.go, libkbfs/config_local.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_remote.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/folder_block_manager_test.go, libkbfs/interface_test.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
This vendors in keybase/client#14666, and supports setting/getting the sync config for individual TLFs.
It also starts deleting blocks asynchronously when a TLF is unsynced, to clear space in the disk block cache.  Though if KBFS crashes before all the blocks are cleared, it doesn't try to restart the deletion; the user must re-enable then re-disable the TLF to clear all the blocks again.  (We can fix that in a future PR, if needed.)
Will fail CircleCI until keybase/client#14666 is merged; will revendor when it is.
=> simplefs: support sync methods and clear blocks for unsynced TLFs

libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_remote.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
Instead of canceling prefetches when the disk is almost full, reschedule them (starting with the top-most block) using an exponential-backoff timer.  This way, the user can see a warning that the disk is full, make some space, and the prefetches will automatically resume (eventually).
If needed in the future, we can add a background process that checks for more disk space and then reschedules them immediately.  But I worry about racing with other processes needing the disk more immediately, so let's see how this works for now.
To get a reliable test, I had to move the space function into the `DiskBlockCache` interface.
@jzila this one could use your attention specifically!  I'm not 100% sure this is the best approach.
Issue: KBFS-3519
=> prefetcher: reschedule prefetches with backoff when disk is full

libhttpserver/content_type_utils.go
This refines our support for displaying different file types.
Some notes:
+ Test files are inside <team>/filetype-test
+ SVG (and some more exotic image types) as attachments (regardless of filename).
+ JS/XML/HTML/CSS/XHTML/ATOM handled
+ Handle some additional source code files as plain text
+ Simplify logic and get rid of the string.Contains match
+ Video files not yet refined, mime types and extensions are not enough for them. They work as before.
=> libhttpserver: Get mime types right for even more filetypes

libkbfs/mdserver_remote.go
=> mdserver_remote: better err when no revision is found by timestamp

libfs/sync_control_file.go, libkbfs/config_local.go, libkbfs/data_types.go, libkbfs/disk_block_cache_test.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go, libkbfs/interface_test.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/prefetcher_test.go, simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
[CircleCI depends on keybase/client#14780, which is vendored here and will be updated with the correct hash when it is merged.]
We want to cache the list of partially-synced paths in an encrypted block on disk.  Since that has to happen in folderBranchOps, this moves the main interface for setting/getting sync config into the KBFSOps interface.  (Of course the paths, including this exact sync config list, is still logged, but at least logs can be easily deleted without side effects, while the sync config DB cannot.)
In the lower-level interface, we move from storing the keybase1 sync config object in the DB (which contains the plaintext path list) to storing a new struct which contains a block pointer, buffer, and key half.  This struct is backwards compatible with any current sync …
=> folder_branch_ops: support partial sync config

libkbfs/config_local.go, libkbfs/folder_block_manager.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go
Any time `folderBranchOps` learns about a newly merged revision, and the TLF is configured in partial-sync mode, kick off a partial sync. Also, kick one off when the sync config is changed.
For each partially-synced path, do a solo-sync-fetch of each parent block, and then deep-sync the final element in the path.
Deleting blocks from unsynced paths will happen in a future PR.
Issue: KBFS-3523
=> folder_branch_ops: support partial syncs

libkbfs/block_ops.go, libkbfs/block_retrieval_queue.go, libkbfs/block_retrieval_queue_test.go, libkbfs/block_retrieval_worker_test.go, libkbfs/data_types.go, libkbfs/disk_block_cache_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
Introduce new action types to avoid overloading the queuing priority to be a prefetching indicator.  Now there are action types for the different combinations of:
* Prefetching.
* Writing blocks to the sync cache.
* Tail-prefetching
* That is, blocks that are tracked by the prefetcher, but do
not themselves trigger prefetches.
This will also be useful for partial prefetching, when we will need to fetch and sync parent blocks of partially-synced paths, without triggering a full deep-sync prefetch from those parents.
Issue: KBFS-3523
Issue: #1925
=> block_retrieval_queue: decouple priorities from prefetching

kbfsfuse/kbfsfuse.sh, libkbfs/folder_branch_ops.go, libkbfs/journal_md_ops.go
Three things here:
1. Allow kbfsdocker tests to turn on journaling via an environment variable, because...
2. When journaling is turned on, we can skip checking the mdserver for unmerged MDs (and we don't/can't cache the absence of these, so otherwise it blocks TLF access if the mdserver if offline)
3. Use a simpler mdserver connectivity check in `SyncFromServer` to avoid extra checks while offline, because the "services" map takes much longer to be updated.
With these changes, the mdserver offline test now passes.
Issue: KBFS-3622
=> Fix offline mode when mdserver is disconnected

libkbfs/keybase_service_util.go
We don't want to block a `CurrentSession` call just because one of the KBFS servers in unreachable.  This fixes one of the offline tests.
Issue: KBFS-3653
=> keybase_service_util: don't block on auth token refreshes

libfs/fs.go, libgit/autogit_node_wrappers.go
autogit should never be writing anything, and it avoids a slow IsWriter check in the service.
=> autogit: open .kbfs_git directory as read-only

libkbfs/config_local.go, libkbfs/interface_test.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go
To make sure the user has the latest data ready and synced before they look at the folder.
Issue: KBFS-3525
=> kbfs_ops: initialize syncing TLFs on startup

libkbfs/config_local.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_remote.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/folder_block_manager.go, libkbfs/folder_block_manager_test.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go
And remove cache types from `DiskBlockCacheLocal`, which doesn't need to implement the main interface.
This will be useful in future PRs when tracking last-unref'd revision in the working set cache, and checking for space in the working set cache.
Issue: KBFS-3525
Issue: KBFS-3527
=> disk_block_cache: refactor interface to use cache types more

libkbfs/block_retrieval_queue.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
This fixes two issues when using the prefetcher with TLFs that contain deduplicated blocks (i.e., they were written by a client that didn't have journaling enabled):
1. If one directory contains multiple references to the same block ID, the block ID will only be prefetched once, but the parent block's count will be incremented multiple times, leading to a situation where the prefetch of the parent never seems finished.  This PR addresses that by tracking the unique IDs seen in each parent block and only incrementing the count once for each unique ID.
2. If one reference of an ID gets archived, its prefetch is canceled by `folderBlockOps`.  However, there could be a different reference that's still live and part of a valid prefetch tree, with a different set of parents.  That other …
=> prefetcher: handle de-duplicated blocks

libkbfs/journal_server_test.go
1) Execute the function.
2) The number of dirty ops should be 0, actually, since the shutdown that was waiting on it to become 0 finished.
=> journal_server_test: fix bad dirty ops check

libkbfs/kbfs_ops_test.go
`newBlockRetrievalQueue()` already makes a prefetcher, so use that one for the test.  And make sure to shut it down after the test, to avoid goroutine leaks.
=> kbfs_ops_test: make only one prefetcher, and shut it down

libkbfs/kbfs_ops_test.go
The existing `append` actually counts as a write against `block1.Contents`.  So use `copy` instead to avoid manipulating `block1`, which is a clean block in the cache and could be in use elsewhere.
=> kbfs_ops_test: fix data race in TestKBFSOpsWriteOverMultipleBlocks

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, test/cr_basic_conflicts_test.go
And wrap NoChainFound errors with a stack to make debugging easier.
Issue: KBFS-2883
=> cr_chains: update rename infos with changed original pointer

libkbfs/block_ops.go, libkbfs/data_types.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/modes.go
But add a new mode setting that will trigger prefetches on normal block fetches, and turn that off on mobile.
Issue: keybase/client#15087
=> modes: use one prefetch worker on mobile

libdokan/mount_test.go, libfuse/mount_test.go, libkbfs/block_retrieval_worker_test.go, libkbfs/block_types.go, libkbfs/crypto_common_test.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/folder_block_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
Consider this simple scenario:
* Blocks a -> b -> c
* User requests block a, which is fetched with a `BlockRequestWithPrefetch` action.
* Block a is fetched, triggering a prefetch of b with a `BlockRequestPrefetchTail` action.
* When the b request is handled by the main prefetcher loop, it skips further prefetching because the action says it should stop.
That's all correct, but then the prefetch requests for b and a both stay in `p.prefetches` forever!  If a is never requested again, it is never removed from that map, causing a memory leak (including a pointer to the assembled block).
Moreover, if someone has requested the prefetch wait channel for a and is waiting on it, they'll wait forever since it'll never be closed. The correct behavior is for the channel to be closed whenever all …
=> prefetcher: fix memory leak and possible hang when skipping fetch

libkbfs/folder_branch_ops.go
A user could have an old rekey request hanging around for a TLF that was migrated to a team, and would crash if it tries to rekey it.
Issue: KBFS-3694
=> folder_branch_ops: don't rekey team folders

libkbfs/data_types.go, libkbfs/disk_block_cache.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_test.go, libkbfs/prefetcher.go, libkbfs/state_checker.go
This PR enables the deep-prefetching of recently-edited files on TLFs into the working-set cache, as per design's request.  To make this work:
* Introduce a new block request action flag that stops a prefetch completely as soon as the cache is full.  This is different from how deep-sync caches work, which need to be rescheduled.
* These new "stop-if-full" requests trigger deep-prefetches, just like a "deep-sync" request does. (At least until the cache fills up.)
* Whenever loading a TLF for prefetching (including for synced folders), suppress identify popups and errors so that the user doesn't get random popups.  If the user tries to access data in these TLFs, they should get the popup and errors.
* Change the partial sync code so that if it receives a config with a DISABLED mode, but …
=> libkbfs: prefetch recently-edited files for non-synced TLFs

libkbfs/kbfs_ops_test.go
For partial syncs based on recent edit activity, there's a race between the MD update getting delivered and the edit history being processed.
=> kbfs_ops_test: fix TestKBFSOpsRecentHistorySync flake

libkbfs/disk_block_cache_remote.go
If kbfsgit tried to do a prefetch, it would crash here due to the recent changes to control prefetches to the working set cache.  For now, just make it always look like there's space, since those kinds of fetches won't be coming over the remote protocol.
Issue: keybase/client#15162
=> disk_cache_block_remote: always pretend the cache has space

libkbfs/disk_block_cache.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/key_manager.go
Some nits found in libkbfs while doing an unrelated things.
This contains:
+ Handle some unhandled error returns
+ Remove a unused variable in folder_branch_ops
+ Fix bug in select in folder_block_ops, this original code broke only from the inner select.
=> Unused return value etc bugs

kbfsedits/user_history.go, libkbfs/favorites.go, libkbfs/favorites_test.go
When KBFS becomes aware that a TLF is no longer a favorite, tell the
kbfsedits.UserHistory to delete it.
This is important because it prevents a recently edited file from appearing in the
history in the widget, which causes that TLF to be readded to favorites.
Issue: KBFS-3689
=> favorites: remove unfavorited TLFs from edit history

dokan/bridge.c, dokan/bridge.h, dokan/loaddll.go
=> dokan: Use uintptr_t instead of pointers on the C side for cgo pointer rules

libkbfs/block_types.go, libkbfs/crypto_common_test.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go
We don't actually use the contents of the block in the request; we only use it to generate a new block.  So just store the function for generating the new block instead, to be more explicit.
Also, don't pass the same block used to make that function to the `Request()` function, which fills in the block.  I suspect that was a memory leak.
Issue: #1958
=> prefetcher: avoid mem leaks by not storing block in request

libkbfs/block_journal.go, libkbfs/block_journal_test.go, libkbfs/block_put_state_memory.go, libkbfs/block_tree.go, libkbfs/block_util.go, libkbfs/conflict_resolver.go, libkbfs/dir_data.go, libkbfs/file_data.go, libkbfs/folder_block_manager.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
And move the current implementation to `blockPutStateMemory`.  Future work will make a disk-based `blockPutState`, so the new interface takes contexts and returns errors whenever it would make sense for the disk.
This also changes the memory-based implementation to use a map instead of a slice for block states, so blocks can be looked up more easily through the interface.
Issue: KBFS-3679
=> interfaces: make interface for `blockPutState`

libkbfs/block_tree.go, libkbfs/conflict_resolver.go, libkbfs/dir_data.go, libkbfs/dir_data_test.go, libkbfs/dirty_bcache.go, libkbfs/dirty_bcache_test.go, libkbfs/dirty_file.go, libkbfs/file_data.go, libkbfs/file_data_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/folder_update_prepper.go, libkbfs/interfaces.go, libkbfs/journal_dirty_bcache.go, libkbfs/kbfs_ops_test.go, libkbfs/md_util.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go
And add ctx to the `Get` and `Put` methods. This is in preparation for building a disk-based dirty block cache.
This is a very mechanical PR with no logic changes.
Issue: KBFS-3679
=> interfaces: make simple DirtyBlockCache interface

libkbfs/bcache.go, libkbfs/block_retrieval_queue.go, libkbfs/config_local.go, libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/folder_branch_status_test.go, libkbfs/interface_test.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
Now that blocks can move from the working set cache to the sync cache (which changes the block's prefetch status), it's hard to keep a synchronized view of the prefetch status in memory.  So, just rely on the disk cache entirely for the prefetch status.
Note this contains a bit of a hack for storing the prefetch status in the block retrieval queue when there's no disk block cache.  I couldn't find a more elegant way of doing it that didn't require splitting up the disk cache lookup into two calls, so I thought this was better.
Issue: KBFS-3644
=> bcache: stop tracking prefetch status in memory

kbfsblock/protocol_utils.go, libkbfs/block_disk_store.go, libkbfs/block_ops.go, libkbfs/block_ref_map.go, libkbfs/bserver_disk.go, libkbfs/bserver_measured.go, libkbfs/bserver_memory.go, libkbfs/bserver_remote.go, libkbfs/disk_block_cache_remote.go, libkbfs/disk_block_cache_service.go, libkbfs/disk_block_cache_test.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/folder_block_manager.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go
If a block is deduped and has multiple references to it (as can happen when the writer of a TLF isn't using the journal), we need to check with the server before deleting it from the sync cache.  Otherwise, we could be missing a block from the sync cache if the user goes offline.
Also, this changes the disk block cache to only delete from a specific cache if a specific type is passed in, since the sync cache and working set cache now have different delete policies.  (It's fine and more performant to evict dedup'd blocks from the working set cache even if they still have references left.)
Issue: KBFS-3661
=> folder_block_manager: check blocks for liveness before deleting from sync cache

libkbfs/favorites.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go
This will hopefully fix the `EditHistory` fails seen here: https://ci.keyba.se/job/kbfs-server/job/PR-609/40/
=> favorites/kbfs_ops: refresh edit histories on added favorites

libkbfs/config_local.go, libkbfs/favorites.go
Ran staticcheck while doing an unrelated stuff and these came up.
=> libkbfs: Do propagate errors correctly
