keybase/kbfs

- .travis.yml
Use https for client repo, since travis is doing public builds now.
> travis: fix osxfuse tests

- libkbfs/data_types.go
- libkbfs/folder_block_manager_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/ops.go
- libkbfs/root_metadata.go
@aalness noticed that one user has been getting constant errors from the MD server when trying to run QR on a change list that is too big to be embedded in the MD block.  Turns out we weren't properly estimating the size of a `gcOp`, so we weren't unembedding the block change list.
This PR fixes that, and another bug it exposes, and adds a test.
> QR: account for gcOp size correctly, to be sure big block changes aren't embedded in the MD

- libdokan/common.go
More leeway to avoid context deadline exceeded errors.
> libdokan: raise timeout to 29 seconds

- libkbfs/conflict_resolver.go
- libkbfs/folder_block_ops.go
If the passed-in node cache isn't the global cache, we don't
necessarily expect the root node to always exist.  This ensures that a
reference to it will exist throughout the call for SearchForNodes.
Issue: KBFS-1096
> folder_block_ops: SearchForNodes should create root nodes sometimes

- libkbfs/conflict_resolver.go
- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
This tracks the state each block is in for a file that's been written to.  In addition, it notes when a block is done syncing, even if the overall sync isn't finished yet.  In future commits, this will let us new Writes proceed as buffer space gets freed up.
Issue: KBFS-1104
> folder_block_ops: introduce a dirtyFile type

- libkbfs/folder_branch_ops.go
- libkbfs/key_manager.go
- libkbfs/key_manager_test.go
If a reader handled a rekey request by setting the rekey bit, but
there was work it couldn't do on behalf of itself (like incrementing
the key generation due to a revoked device), it could enter into a
loop of continuous Put/SendRekeyNeeded messages back and forth with
the server.
Instead, detect if the rekeyer made any useful revisions, and if not,
don't bother putting a new revision.
Issue: KBFS-1119
> libkbfs: avoid rekey loops on incomplete rekeys

- libkbfs/bserver_memory.go
- libkbfs/bserver_remote.go
- libkbfs/bserver_remote_test.go
- libkbfs/bserver_tlf_storage.go
- libkbfs/crypto_key_types.go
- libkbfs/errors.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/mdserver_remote.go
- libkbfs/tlf_id.go
This fixes a latent bug where getting a dedup-ed block
might fail.
Add regression test.
Clean up some conversions to and from RPC types.
> [KBFS-1134] Always use creator in BlockIdCombo

- libdokan/updates_file.go
- libfuse/updates_file.go
- libkbfs/conflict_resolver.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/key_manager_test.go
- libkbfs/md_util.go
- libkbfs/stallers_test.go
- libkbfs/test_common.go
- test/engine_libkbfs.go
I hit a CR data loss problem in the wild (description in JIRA).  The problem was that we were modifying our only copies of unmerged MD updates, and when the resolution was canceled, we were re-using those modified copies (which contained operations with modified block pointers) and weren't able to completely resolve everything, leading to data loss.
This also uncovered the fact that we don't clean up blocks after a failure, which was being tracked in a different issue.
Issue: KBFS-1133
Issue: KBFS-921
> CR: fix data loss and block state issue when resolutions are canceled

- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
Previously, we put the new block directly into the dirty cache.
However, with the new dirtyFile organization, we first check if it was
dirty before caching it, and the dirtyFile thought it was still marked
as dirty and so didn't re-cache the new indirect block.  As a result,
the sync got the old, direct block out of the cache and sync'd that.
The file size in the direct entry was roughly correct though, so any
reader would see zeroes when they read past the end of that block.
Issue: KBFS-1138
> folder_block_ops: when creating indirect block, mark it not dirty

- libkbfs/bserver_memory.go
- libkbfs/bserver_remote_test.go
- libkbfs/bserver_tlf_storage.go
- libkbfs/bsplitter_simple_test.go
- libkbfs/crypto_client.go
- libkbfs/crypto_common.go
- libkbfs/crypto_common_test.go
- libkbfs/crypto_local.go
- libkbfs/interfaces.go
- libkbfs/mocks_test.go
Also move out pure crypto functions into
cryptoPure interface, which is embedded
by Crypto.
This makes testing some stuff easier, as
now you don't have to build a full Crypto
object for some tests.
> Clean up CryptoCommon constructors

- libkbfs/key_manager.go
> key_manager: libkb.NoSecretKeyError indicates a rekey is needed.

- libkbfs/kbfs_ops_test.go
Temporarily, some of our backend servers rely on an exact value for
this constant.
Issue: KBFS-1144
> kbfs_ops_test: find out if the empty block size ever changes

- libkbfs/errors.go
- libkbfs/key_manager.go
- libkbfs/tlf_handle.go
- libkbfs/tlf_handle_test.go
Apparently, I forgot to do this in
an earlier PR where I noticed this.
> Compare ConflictInfos properly

- libkbfs/config_local.go
- libkbfs/conflict_resolver_test.go
- libkbfs/dirty_bcache.go
- libkbfs/dirty_bcache_test.go
- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
And use these counts to control when writes are allowed to proceed.
I did my best to explain what's going on in the new comment above `folderBlockOps`, but please let me know if you need more clarification!
Issue: KBFS-1105
Issue: KBFS-1106
Issue: KBFS-1107
> dirty_bcache: track unsynced and total dirty bytes, system-wide

- libfuse/dir.go
- libfuse/folderlist.go
- libkbfs/favorites.go
- libkbfs/favorites_test.go
On OS X, the OS helpfully issues a `stat` call after the `rmdir`.  If you've already opened the TLF, this will cause the favorite to be re-added, because it doesn't fake out the attribute, to gets the real one via KBFSOps.  Instead, clear out the stored TLF Dir object on favorite removal, which will make it go back to faking out the attribute until the TLF is deliberately opened again.
Also, the API server now rejects public TLFs with readers, so we can no longer delete the old-style "#public" favorite names.  We'll have to do it manually in the DB if there are any left.
Issue: KBFS-1045
Issue: keybase/keybase-issues#2282
> Fixes for favorite removal

- libdokan/fso.go
- libdokan/tlf.go
This adds support for chtimes on TLFs in addition to files/directories inside them.
> libdokan: SetFileTime for TLFs

- libkbfs/tlf_handle_extension.go
- libkbfs/tlf_handle_test.go
Going to be using this in server tests too...
> libkbfs: make TlfHandleExtensionStaticTestDate an exported constant

- env/context.go
- kbfs/main.go
- kbfsdokan/main.go
- kbfsfuse/context.go
- kbfsfuse/main.go
- libdokan/start.go
- libfuse/start.go
- libkbfs/bserver_remote.go
- libkbfs/context.go
- libkbfs/crypto_client.go
- libkbfs/init.go
- libkbfs/keybase_daemon_rpc.go
- libkbfs/mdserver_remote.go
- libkbfs/shared_keybase_transport.go
- libkbfs/test_common.go
Removes a direct dependency on GlobalContext for libkbfs package.
This is important for mobile which has issues with the libkb.G global and GlobalContext.
- Replaces libkb.GlobalContext with libkbfs.Context interface
- Replaces access of libkb.G with passed in var (context interface)
- Move construction of context (from GlobalContext) to alternate package (env), since it's used in kbfsfuse, kbfsdokan main packages (and test)
- The impl wraps GlobalContext (implementation hiding) for easy refactoring in the future
In general, we should be using interfaces for library packages like this rather than direct dependencies on something like GlobalContext which itself has a ton of dependencies.
In general we should be deprecating direct use of GlobalContext.
@strib 
cc @maxtaco
> Remove direct use of GlobalContext from package (use an interface)

- libkbfs/folder_block_manager_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/stallers_test.go
Spotted on https://travis-ci.org/keybase/kbfs/jobs/138941150
Fixes a data race in testing code.
> libkbfs: Protect staller block ops delegate by a lock in tests

- vendor/github.com/keybase/go-framed-msgpack-rpc/connection.go
- vendor/github.com/keybase/go-framed-msgpack-rpc/server.go
- vendor/github.com/keybase/go-framed-msgpack-rpc/transport.go
- vendor/vendor.json
For gomobile bind client+kbfs, need to have compatible vendoring.
`govendor update github.com/keybase/go-framed-msgpack`
@maxtaco or @strib
> Update go-framed-msgpack to match keybase/client/go

- libkbfs/config_local.go
- libkbfs/dirty_bcache.go
- libkbfs/dirty_bcache_test.go
- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/test_common.go
Adds a sync buffer that is adjusted automatically, similarly to the congestion window during TCP's slow start.
When the sync buffer is full, we delay writes by applying backpressure proportional to the amount of the maximum buffer size we've filled so far.
Also, increase the number of parallel block puts to 100.
With this, I was able to upload a 128 MB file over a decent connection to prod in about 17s (down from ~30s).  Moreover, when I artificially delayed each block put in serial by 1s, there were no timeouts.
Other things of note:
* This PR exposes KBFS-1193 in one of the tests.  For now I'm just skipping the broken, as the issue is totally unrelated.  I'll work on fixing it soon.
* The PR also adds support for tracking the number of bytes currently syncing to the server.  We don't …
> dirty_bcache: auto-adjusted sync buffer size with backpressure

- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_ops.go
- libkbfs/mdserver_local.go
- libkbfs/root_metadata.go
We check RootMetadata validity in a few places, all
slightly differently. Consolidate that into
RootMetadata.CheckValidSuccessor().
Also add helper functions to wrap around
FBO.setHeadLocked().
> [KBFS-1159] Consolidate RootMetadata checks

- libkbfs/conflict_resolver.go
- test/cr_simple_test.go
* Fix the ptr update map for chains that were updated in both branches, even for directories that aren't changed in the resolution.
* Don't reference bytes for useless same-pointer updates.  If it was really a new block, there will have been a proper update or ref in an earlier op.
* Fix up parent of renamed setattr operations
Issue: KBFS-1178
> cr: fix block accounting for unmerged-setattr, merged-rename files

- libkbfs/conflict_resolver.go
- test/cr_complex_test.go
> cr: mark setattr file actions moved, so they don't get moved again

- libkbfs/dirty_bcache.go
- libkbfs/errors.go
- libkbfs/favorites.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_cr_test.go
- libkbfs/mdserver_local.go
(by letting devices track latest merged revision on server)b
> stop devices from continuously registering and fetching merged updates

- libkbfs/dirty_bcache.go
> dirty_bcache: always hold lock over logLocked

- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- test/cr_basic_conflicts_test.go
- test/cr_simple_test.go
- test/simple_test.go
Also, remove support for renaming over files of different types, that
seems silly and isn't supported by the higher FS levels anyway.
Issue: KBFS-1176
> folder_branch_ops: allow a rename over an empty directory

- libkbfs/conflict_resolver.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_block_manager_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/md_util.go
- libkbfs/state_checker.go
This ensures the private metadata won't change once it is initially
decrypted, avoiding possible races.
Suggested by @akalin-keybase.
Issue: KBFS-1207
> md_util: re-embed block changes in decryptMDPrivateData

- libdokan/unstage_file.go
- libfs/unstage_file.go
- libfuse/unstage_file.go
- libkbfs/interfaces.go
This is for when normal unstaging takes too
long and times out.
> [KBFS-1203] Add async unstaging method

- libkbfs/mdserver_memory.go
- libkbfs/mdserver_test.go
It was calculating ranges indices incorrectly.
Modify tests to catch this.
> Fix bug with MDServerMemory.GetRange

- .travis.yml
- libkbfs/bserver_disk.go
- libkbfs/bserver_tlf_journal.go
- libkbfs/bserver_tlf_journal_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/md_ops.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_test.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/root_metadata.go
Split up MDServerDisk into per-TLF objects (mdServerTlfStorage).
Make those objects store RootMetadataSigned objects in flat files.
They will eventually store the rest of the data (currently in
levelDBs) in a journal.
Fix up naming in bserver_disk.go and bserver_tlf_journal.go.
Also check for shutdown only in public BServer/MDServer
methods.
Make md.MetadataID() take only a crypto object.
Make MDServer.GetForHandle serialize TLF ID creation.
> [KBFS-1185] Use per-TLF storage for MDServerDisk

- libkbfs/errors.go
- libkbfs/favorites.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops.go
I hit a KBFS hang when Emacs canceled a context while KBFS was trying to send a favorites request onto the channel, leaving it in the `inFlightAdds` map forever and blocking and future requests for that same folder.  This PR cleans up the map in that case.
Also, a user noticed that they couldn't delete certain favorites.  It turns out that can happen when a `folderBranchOps` is made, but `head` is never set (e.g., due to identify or MD fetch errors)
@songgao: want to try reviewing?
Issue: KBFS-1235
Issue: keybase/client#3263
> favorites: fix a possible hang, and handle deletions better

- libkbfs/kbfs_cr_test.go
This properly tests https://github.com/keybase/kbfs/pull/98
> TestCRFileConflictWithMoreUpdatesFromOneUser: sync every time a write happens

- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_cr_test.go
also a small fix in `TestCRSyncParallelBlocksErrorCleanup`
> make sure setLatestMergedRevision does not go backward

- libkbfs/root_metadata_test.go
- libkbfs/tlf_handle_extension.go
- libkbfs/tlf_handle_extension_test.go
- libkbfs/tlf_handle_test.go
This changes the format of finalized handle extensions from `alice,bob#charlie (finalized 2016-03-14 #2)` to `alice,bob#charlie (files before bob account reset 2016-03-14 #2)` or in the case of a single participant `bob (files before account reset 2016-03-14)`
> tlf_handle_extension: more descriptive suffix string

- libkbfs/config_local.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
> delete blocks in a constantly running goroutine; also use a `chan` instead of a `map` for blocks to be deleted

- libkbfs/folder_branch_ops.go
Also only call it after the head is properly set in
one case.
Put headLock-protected variables together.
> Always lock before calling setLatestMergedRevisionLocked

- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/cr_actions.go
- libkbfs/cr_chains.go
- libkbfs/cr_chains_test.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_ops.go
- libkbfs/ops.go
- libkbfs/ops_test.go
- libkbfs/root_metadata.go
Also add various functions to check the validity of
ops.
Check ops before pushing an MD to the server.
> [KBFS-1262] Ignore invalid ops when unstaging

- dokan/bridge.c
- dokan/bridge.h
- dokan/cgo.go
This allows for more freedom in specifying the location of dokan1.dll
> dokan: Load dokan1.dll dynamically

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
- vendor/github.com/golang/mock/LICENSE
- vendor/github.com/golang/mock/gomock/call.go
- vendor/vendor.json
When removing a file, we need to retrieve its top block
in order to account for any other indirect blocks. Also,
when removing a dir, we need to retrieve it in order to
make sure it is empty. In either case, if the block doesn't
exist, go ahead with the removal.
We should still figure out what's causing these bad
pointers, but we shouldn't prevent people from removing
those bad files/dirs.
> Handle block get errors gracefully in file/dir removal

- libkbfs/folder_block_ops.go
- libkbfs/kbfs_ops_test.go
Otherwise the file is not marked as dirty, and background syncs won't
happen.
Split out from #134.
> folder_block_ops: make a deCache entry even for overwritten files

- libkbfs/mdserver_disk.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mdserver_tlf_storage_test.go
This is redundant, since the branch ID is already passed
in. I just forgot to remove it.
> Remove deviceKID arg from mdServerTlfStorage

- libkbfs/conflict_resolver.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
This PR contains two file-sync-failure-related fixes that were exposed by the changes in #134:
1. We need to treat recoverable vs. unrecoverable errors differently when counting dirty blocks, since with the latter the dirty blocks still contain the data from the deferred writes, and will be part of the next sync.
2. A retry after a failed sync may contain some of the same blocks from the previous failed attempt, so we shouldn't blindly try to clean up failed blocks; we need to check first if they were part of the eventual successful put or not.
We add an extra Sync at the end of `TestKBFSOpsErrorOnBlockedWriteDuringSync` to make sure block accounting is enabled (because there are no outstanding dirty files) at the end of the test, which exposes both of these issues.
Issue: KBFS-1261
> Fixes for handling failed syncs

- libkbfs/bare_tlf_handle.go
- libkbfs/config_local.go
- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbpki_client.go
- libkbfs/kbpki_client_test.go
- libkbfs/keybase_daemon_local.go
- libkbfs/keybase_daemon_measured.go
- libkbfs/keybase_daemon_rpc.go
- libkbfs/keybase_daemon_rpc_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/tlf_handle.go
- libkbfs/tlf_handle_test.go
This along with https://github.com/keybase/kbfs-server/pull/64 fixes issues seen when integration testing in the staging environment.
Note: It's not obvious from the diff but when the API server returns unverified keys they aren't tagged as sibling or subkeys so I needed to stop filtering them as such (they all ended up as subkeys w/filtering.)
> TLF reset bug fixes

- libkbfs/folder_block_ops.go
- libkbfs/kbfs_ops_test.go
If a new Write comes in right between the calls to `startSyncWrite` and `makeLocalBcache`, a newly-made block could be added to the unrefs list of the syncInfo, which could get it to be unref'd as part of the same sync where it's being put to the server.  This causes the DiskUsage of the resulting MD to be off by one block.
Instead, just use the syncInfo (and dirty directory entry) returned by `startSyncWrite`, instead of the ones from the unrefCache and deCache, which may have been modified by an intervening deferred write.
I also renamed `startSyncWrite` since it doesn't depend on the lock being taken before it is called.
This was exposed by running `BenchmarkWriteBigFileBigBandwidth` a bunch of times.  I wanted to write an explicit test for it, but it would involve hacking something …
> folder_block_ops: avoid race that causes new block to be unref'd

- libdokan/journal_control_file.go
- libfs/constants.go
- libfs/journal_control_file.go
- libfuse/dir.go
- libfuse/journal_control_file.go
- libkbfs/init.go
- libkbfs/journal_server.go
- libkbfs/journal_server_util.go
Add a command-line switch to permit per-TLF write
journals.
Add special files to turn on, flush, and disable
write journals.
Add a JournalServer that interposes itself between
BlockServer and MDOps and manages the (currently
empty) per-TLF journals.
> [KBFS-1099] Add scaffolding for write journals

- libfuse/mount_test.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
This should solve the issue with null BlockPointers in `setAttrOp`s.
Issue: KBFS-1114
> folder_branch_ops: gracefully handle set attrs on unlinked files

- test/qr_test.go
If a Lookup gets issued from outside the test (by Finder?)
concurrently with the Remove, it could end up adding the file name
back into the osxfuse lookup cache, and a subsequent lookup by the
test can succeed incorrectly when it hits the cache.
This PR works around that by simply using a unique name for each
iteration, while looking into the osxfuse issue separately.
Issue: KBFS-1253
> qr_test: add workaround to TestQRLargePointerSet for osxfuse bug

- dokan/bridge.c
- dokan/bridge.h
- dokan/cgo.go
- dokan/dokan.go
- dokan/filesystem.go
- dokan/testfs_test.go
- kbfsdokan/main.go
- libdokan/fs.go
- libdokan/start.go
This disables timeouts on the Dokan level - they are still handled with context.
`-mount-flags` as follows:
0 - nothing
3 - extra debugging
32 - removable
64 - mount manager
128 - only current session
Can be combined: e.g. removable + mount manager + only current session = 224.
> dokan*: Disable timeouts and allow customizing mount options from command line

- libkbfs/cr_actions.go
- test/cr_multi_blocks_test.go
It turns out our test for CR for indirect block files had a bug, and so it wasn't being tested (and was broken of course).
Issue: KBFS-1193
> cr: track refs/unrefs resulting from syncOps on newly-created, unmerged files

- libkbfs/config_local.go
This should fix https://ci.appveyor.com/project/keybase/kbfs/build/1.0.4659
> [KBFS-1293] wait for block deletion in parallel test

- libdokan/folderlist.go
- libdokan/mount_test.go
- libfuse/folderlist.go
- libfuse/mount_test.go
Tested locally in my zsh with `syntax-highlighting` enabled. Resolves https://github.com/keybase/client/issues/3503
> revert the behavior that Lookup handler adds TLF to favorite

- libkbfs/keybase_daemon_rpc.go
- libkbfs/keybase_daemon_rpc_test.go
> keybase_daemon_rpc: use KeyFamilyChanged instead of UserChanged

- kbfsdokan/main.go
Allow `kbfsdokan -dokan-dll C:\foo\bar\dokan1.dll Q:` to make it easier to install beside the application.
> kbfsdokan: Allow loading dokan dll from custom paths via cmdline

- libkbfs/favorites.go
- libkbfs/favorites_test.go
- libkbfs/kbfs_ops.go
And use that to fix a flaky test.
Issue: KBFS-1298
> favorites: allow waiting for outstanding requests

- libkbfs/interfaces.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mocks_test.go
- vendor/github.com/keybase/client/go/protocol/metadata.go
- vendor/vendor.json
This will let us figure out how "old" a server-timestamped MD update is.
I expect the docker tests to fail until the corresponding server update is merged.
Depends on keybase/client#3569.
Issue: KBFS-1312
> mdserver: calculate the time offset from the local md server

- libkbfs/bare_root_metadata.go
- libkbfs/bserver_remote_test.go
- libkbfs/bserver_tlf_journal_test.go
- libkbfs/bsplitter_simple_test.go
- libkbfs/crypto_client.go
- libkbfs/crypto_client_test.go
- libkbfs/crypto_common.go
- libkbfs/crypto_common_test.go
- libkbfs/crypto_local.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_ops_test.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_test.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mdserver_tlf_storage_test.go
- libkbfs/root_metadata.go
- libkbfs/test_common.go
Add IsValidAndSigned() function to BareRootMetadata
and RootMetadataSigned, which is a port of the existing
server-side validation code. But also add some other
simple checks to it.
Clean up Crypto interfaces and implementations a bit.
In particular, stop logging verify.
> [KBFS-1265] Port metadata validator from server

- libkbfs/bserver_errors.go
- libkbfs/folder_branch_ops.go
Add a new error when there are too many references to a block
> add new bserver error maxrefexceeded

- libkbfs/conflict_resolver.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status.go
If CR is stuck, we don't want to block the only way for users to
figure out if they're running CR.
However, we don't want to open ourselves up to races on the crChains
object, which could change after `setCRChains` is called.  So instead
just save the summary in the status object, instead of the full chain.
This doesn't cost us anything extra, since the summaries are already
being logged as part of every CR run.
Issue: KBFS-1315
> folder_branch_ops: don't block folder status on CR

- libkbfs/conflict_resolver.go
- libkbfs/cr_actions.go
- test/cr_simple_test.go
Without this, we can delete the top-level block of a file that was
created, and then renamed, while the client is unmerged.
Issue: KBFS-1319
> cr: count blocks belonging to file created+renamed while unmerged

- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_cr_test.go
This is meant to be a nuclear option.  In the future, maybe we should
consider throttling unmerged writes a little more nicely, proportional
to how far past the branch point we are.
Issue: KBFS-1310
> cr: block md writes if the state to resolve gets too large

- libkbfs/bare_root_metadata.go
- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_cr_test.go
- libkbfs/key_manager_test.go
- libkbfs/test_stallers.go
If a PutUnmerged is canceled or errors out in some other ambiguous
way, then the device can be behind the server's view of the branch by
a single commit.  Force a sync up to the real head and retry the
PutUnmerged in that case.
Issue: KBFS-1315
> folder_branch_ops: force a sync after a PutUnmerged rev conflict

- libkbfs/bare_root_metadata.go
- libkbfs/block_ops.go
- libkbfs/block_ops_constrained.go
- libkbfs/block_ops_test.go
- libkbfs/conflict_resolver.go
- libkbfs/data_types.go
- libkbfs/errors.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_bundle.go
- libkbfs/key_manager.go
- libkbfs/key_manager_test.go
- libkbfs/md_journal_test.go
- libkbfs/md_util.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
- libkbfs/state_checker.go
- libkbfs/test_stallers.go
This replaces a good chunk of the ReadOnlyRootMetadata
parameters. This is safer, since you can't accidentally
write through the KeyMetadata interface.
Fix one place where we were accidentally writing through
a ReadOnlyRootMetadata object.
Also move the quota error check from BlockOps into
FolderBranchOps.
> [KBFS-1326] Make a KeyMetadata interface and use it

- libkbfs/data_types.go
- libkbfs/keybase_daemon_rpc.go
- `SessionInfoFromProtocol` method to convert protocol `Session` to `libkbfs.SessionInfo` (put in `data_types.go`)
- `UserInfoFromProtocol` method to convert protocol `UserPlusKeys` to `libkbfs.UserInfo` (put in `data_types.go`)
- Make ConvertIdentifyError public
> Mobile needs a few methods from KeybaseDaemonRPC to be made available

- libkbfs/conflict_resolver_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status_test.go
- libkbfs/journal_md_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_journal.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/md_util.go
- libkbfs/mdcache_test.go
- libkbfs/mdserver_memory.go
- libkbfs/root_metadata.go
We'll need this to determine how old a given change is, first for the
TLF edit history.  It should also be useful for quota reclamation.
Issue: KBFS-1301
> root_metadata: track the local timestamp of every immutable MD

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/cr_chains_test.go
A future PR will need to access the local timestamp of the
RootMetadata, which will only be available in the
ImmutableRootMetadata (see #204).  It would be nicer if it was a
ReadOnlyRootMetadata, since in one place we pass a non-final MD into
newCRChains, but the timestamp will only be available in
ImmutableRootMetadata, so in that place we have to fake out the MD ID.
Issue: KBFS-1301
> cr_chains: take ImmutableRootMetadatas when making chains

- libkbfs/keybase_daemon_rpc.go
I thought that registering for a specific notification protocol was
enough to receive the notifications, but apparently we also have to
explicitly subscribe to the right notification channels.
Issue: KBFS-1341
> keybase_daemon_rpc: oops, we have to register for notifications!

- libkbfs/conflict_renamer.go
- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/cr_chains_test.go
- libkbfs/data_types.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/mocks_test.go
- libkbfs/ops.go
- libkbfs/ops_test.go
- libkbfs/tlf_edit_history.go
- libkbfs/tlf_edit_history_test.go
This provides users of the `KBFSOps` class a way to grab the last 20 file creates/edits for each writer of a TLF.  In the future, we may implement this class a client of chat/gregor.  For now, we'll do it the slow way: derive the edit list by downloading RootMetadata updates until the list is complete (or until we hit some maximum number of downloaded RMDs).
In a future PR I'll expose this list via a virtual file and an RPC from the GUI.  At that point I'll probably add DSL tests for more complicated scenarios.  For now the tests are fairly basic.
Adding @jzila as well as @akalin-keybase as reviewers, to hopefully spread more expertise about ops stuff around the group.
> tlf_edit_history: find the last 20 file creates/edits for each writer of a TLF

- libkbfs/cr_chains.go
- libkbfs/tlf_edit_history.go
Some things I noticed when trying to use this on real data:
* Without caching, reading it through the file system is awful.  So this allows us to cache it for up to a minute.
* Some (hopefully) old conflict resolution bugs didn't always properly mark block pointers as removed, and `crChains.getPaths()` weren't properly removing those chains.
* If a file was created, but only has a `setAttrOp`, its `createOp` would get skipped and then it would never be added a notification since there was no `syncOp`.
> tlf_edit_history: some fixes

- libdokan/dir.go
- libdokan/tlf_edit_history_file.go
- libfs/constants.go
- libfs/tlf_edit_history_file.go
- libfuse/dir.go
- libfuse/tlf_edit_history_file.go
`.kbfs_edit_history` in any TLF will show the history.
Contains #218 and #217, so if you review before those are merged, only look at the `libfs`, `libfuse`, and `libdokan` changes.
Issue: KBFS-1303
> fs: expose TLF edit history as a file

- libkbfs/block_ops_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
Otherwise, fetching the block changes for MDs with unembedded blocks in a range takes a long time because they all happen in serial.
I'm not 100% sure this is the best way to do it, but it was the simplest I could think of.  Let me know if you can think of anything better.
> md_ops: parallelize MD decrypts

- libkbfs/keybase_daemon_rpc.go
- libkbfs/keybase_service_base.go
This cut and pastes non-RPC behavior from KeybaseDaemonRPC into a KeybaseServiceBase (base) class.
_No behavior should be changed by this. It's only moving code._
This allows us to construct a non-RPC based implementation and talk directly to the client engine package (which implements all the protocol/keybase1 client interfaces directly),  with all the behavior that KBFS expects from a  KeybaseService like caching.
By RPC I mean connection based RPC behavior. The protocol is the source of truth, is the API, is a layer we shouldn't bypass.
The allows us to go from:
```
go -> protocol -> msgpack -> connection -> msgpack ->  protocol -> go 
```
to:
```
go -> protocol -> go
```
> Separate non-RPC behavior from KeybaseDaemonRPC

- libkbfs/folder_branch_ops.go
- libkbfs/tlf_edit_history.go
- libkbfs/tlf_edit_history_test.go
This PR adds a background processor to `TlfEditHistory` that processes batches of `RootMetadata`s and updates the cached edit history in response, if one has already been cached.  It adds edits for newly-created and newly-edited files, and it also removes deleted files and renames moved files.
Issue: KBFS-912
> tlf_edit_history: update cached history in response to new MD updates

- libkbfs/block_journal.go
- libkbfs/disk_journal.go
- libkbfs/journal_server.go
- libkbfs/md_id_journal.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
Without this fix, it's possible to get into a state
where one picks up a new branch ID if the journal
is completely flushed.
Also fix a few more places to use CDebugf.
> [KBFS-1344] Fix journal race with branch IDs

- libkbfs/bserver_errors.go
- libkbfs/mdserver_errors.go
Make it so that we know the exact BServer/MDServer
error type from logs.
> [KBFS-1342] Make BServer and MDServer errors unambiguous

- libkbfs/folder_block_ops.go
- test/engine_fs_test.go
- test/multi_blocks_test.go
If a series of writes exactly fills up a one-block file, and then a
new write comes in, we transition to an file with a top-level indirect
block, that has two direct file blocks under it -- the original direct
file block, plus a new empty one that receives the write.  However, we
were failing to mark this new block as dirty, because in this case
nCopied == 0 on the first write attempt (because the original block
was full).
In this case, we should dirty that first block, since it needs to be
re-uploaded under a new BlockPointer.
Noticed this while running our benchmark tests.
Issue: KBFS-1364
> folder_block_ops: fix missing block when switching to indirect

- libkbfs/dirty_bcache.go
- test/benchmark_test.go
If the sync was smaller than the current buffer size, it doesn't
really convey any info about how much data the connection can handle.
Add a benchmark that mixes big and small files, which fails without
this change.
Issue: KBFS-1316
> dirty_bcache: don't increase buffer size on small syncs

- libkbfs/bare_root_metadata.go
This used to be GetCryptPublicKeys, which is
actually still used by server code.
Also fix object type for HasKeyForUser.
> Add GetDeviceKIDs to BareRootMetadata

- libkbfs/init.go
- libkbfs/journal_block_cache.go
- libkbfs/journal_block_server.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server.go
Specifically, the fact that it doesn't handle
re-putting a block. Do so by stubbing out the
block cache and turning off block dupe detection.
> [KBFS-1366] Work around block server behavior

- libfs/journal_control_file.go
- libkbfs/init.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
This makes journals actually behave
persistently.
Also fix JournalServer logs to use a context.
> [KBFS-1345] Read existing journals on start

- libkbfs/folder_branch_ops.go
- libkbfs/md_id_journal.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
This handles the case where we interrupt an MD put
into the journal. We can safely replace the head
since it hasn't been pushed to the server yet.
> [KBFS-1398] Allow head replacement in mdJournal

- libdokan/start.go
The same as the libfuse change.
> libdokan: Handle InitLog error as in PR#243

- libkbfs/conflict_resolver_test.go
- libkbfs/cr_chains.go
- libkbfs/reporter_kbpki.go
- libkbfs/tlf_edit_history.go
This PR:
* Defines notification constructors for each type of edit.
* Sets timestamps on the rm/create halves of split rename ops in `crChains`.
* Caches ops during the initial edit construction, so we can get the full path for new edist.
* But don't bother saving the ops in the cached copy, they aren't otherwise needed.
* Send create/modify/delete/rename notifications.
* Fix a minor bug in `crChains` I noticed when getting a complete history over a TLF that ran QR with an old version of the QR code that unref'd full `BlockPointer`s.
Issue: KBFS-913
> tlf_edit_history: send edit notifications

- libkbfs/folder_branch_status.go
- libkbfs/journal_server.go
- libkbfs/kbfs_ops.go
- libkbfs/md_journal.go
Add root dir and journal count to top-level .kbfs_status,
and add revision start/end and block op count to
per-folder .kbfs_status.
> [KBFS-1280] Add journal status info to .kbfs_status

- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
Check if the MD has already been put, and go on
if so.
> [KBFS-1399] Handle version conflicts during journal flushes

- libkbfs/bcache.go
The deadlock:
* golang-lru takes its internal lock, calls b.onEvict, which takes bytesLock
* b.makeRootForSize takes bytesLock, calls cleanTransient.Len(), which takes
the golang-lru internal lock.
Instead, only access cleanTransient.Len() outside of the bytesLock
critical section.
Issue: KBFS-1336
> bcache: avoid deadlock between makeRoomForSize and onEvict

- libdokan/fs.go
Any access to K:\.kbfs_unmount will cause os.Exit(0)
> libdokan: Add .kbfs_unmount to root

- libkbfs/bare_root_metadata.go
- libkbfs/errors.go
- libkbfs/interfaces.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
In particular, the verification done in MDOps.
Split off IsLastModifiedBy from IsValidAndSigned.
Fix checks to account for final revisions.
> Make everything use {B,}RMD.IsValidAndSigned

- test/cr_complex_test.go
[I wrote this test while trying to repro KBFS-1357, and figured it is worth keeping around.]
Issue: KBFS-1357
> test: an unmerged renamed write of a removed file

- libkbfs/bsplitter_simple.go
- libkbfs/conflict_resolver.go
- libkbfs/data_types.go
- libkbfs/folder_block_manager_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/journal_md_ops.go
- libkbfs/kbfs_cr_test.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/ops.go
CR and QR didn't properly unembed big block changes, because they add pointers directly to ops, rather than going via the MD accessors, resulting in an incorrect block change size estimate.
Instead, let's calculate the block change size by iterating over all the ops after the MD is complete.
Also, fixing this exposes a few other issues: 1) CR was leaving unmerged block changes pointers as ref pointers in the original ops, and 2) CR and Rekey weren't properly swapping block changes back into the expected place in the MD object after putting it to the mdserver.
Issue: KBFS-1338
> libkbfs: fix CR and QR block change unembedding

- libkbfs/conflict_resolver.go
- libkbfs/cr_actions.go
- libkbfs/folder_branch_ops.go
- test/cr_complex_test.go
resolutionOps may delete entire directory trees but only include the top-most rmOp.  This means that another resolution may encounter a node that has been deleted, without its parent having any listed ops in the merged chain.  In that case, avoid an infinite loop since we don't actually need to remove the corresponding rmOps from the merged chain (since there are none).
Will track separate issues for the other issues this exposes:
1. the previous resolution should probably contain all rmOps (KBFS-1424)
2. rmOps shouldn't cause the parent directories to be recreated (KBFS-1423)
Issue: KBFS-1357
> cr: fix infinite loop when a previous resolution didn't include all rmOps

- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops.go
This fixes non-creation of TLFs in certain cituations. KBFS-1157 was broken by rebases.
> libkbfs: Fix non-creation of empty TLFs

- libdokan/dir.go
- libdokan/file.go
- libfuse/dir.go
- libfuse/file.go
+ Cleanup code in libdokan and libfuse
+ Ensure special files set `resp.EntryValid = 0` in `libfuse/dir.go`
+ Add `isNoSuchNameError` helper to libfuse to avoid some type assertions
> lib{dokan,fuse}: Small cleanup

- libkbfs/folder_block_manager.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
Revision is now a function, so we need to call it.
> Fix Revision calls in logs

- libkbfs/kbfs_ops.go
This was erroneously causing KBFSOps.Status calls
to fail when the journal is disabled (the default).
> Fix accidentally-shadowed variable

- libkbfs/kbfs_ops.go
Otherwise the service could allocate multiple invites for an SBS user.
This came about when we started allowing empty TLFs for read
operations when the TLF hadn't yet been created.
Issue: keybase/client#4082
> kbfs_ops: don't "create" a favorite except on TLF initialization

- libkbfs/bare_root_metadata.go
- libkbfs/keybase_service_base.go
This is basically just another path for sharing before signup.
> keybase_service_base: ignore Identify2 NoSigChainErrors

- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/tlf_journal_test.go
makeMDJournal has to load MDs to set its branch ID,
but doing so checks the loaded MDs against the
(empty) branch ID, so if the journal is on a
branch, it would refuse to load.
Also fix an incorrect path for the tempdir used
in branch conversion, and guarantee that it's
cleaned up.
Add regression tests for both.
Clean up md_journal_test.go a bit.
> Fix overly-aggressive check in makeMDJournal

- libkbfs/kbfs_cr_test.go
For some reason on 386 platforms, the CR revision is less than 256
bytes, but on x64 platforms it's more.  Handle both by dropping the
limit down to 128 bytes.
Issue: KBFS-1480
> kbfs_cr_test: fix unembedded test on 386 platforms

- libdokan/dir.go
> libdokan: protect Cleanup log messages from nil FileInfo

- libkbfs/flag_size.go
- libkbfs/flag_size_test.go
- libkbfs/init.go
flag.go was creating a zero value from each flag type,
which was causing a panic in FlagSize.
Also set the string value of FlagSize to be "0"
(instead of "0t").
Also fix a few typos in init.go.
> Fix crash on kbfsfuse --help

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/journal_server.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
For now, don't count addRefOps as having block bytes, even though they
have blocks on disk, since they won't actually be transferred in most
cases.
Also, roll all journal blockBytes into the overall KBFS status file.
Issue: KBFS-1411
> block_journal: track the number of block bytes in a TLF's journal

- libkbfs/tlf_journal.go
This will make it easier to debug different operations both locally
and on the server.
> tlf_journal: unique debug tags for each background operation

- libkbfs/config_local.go
- libkbfs/folder_branch_ops.go
- libkbfs/init.go
- libkbfs/journal_server.go
- libkbfs/state_checker.go
- libkbfs/tlf_journal.go
- test/dsl_test.go
- test/engine.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
- test/journal_test.go
This will be useful in upcoming PRs for KBFS-1267 and KBFS-1268.
Note that once #295 is in, we can hopefully remove the new StateChecker-skipping code.
> dsl_test: allow journaling

- libkbfs/block_journal.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
This allows the TLF journal to push all block puts in parallel, and
then all addRefs in parallel.  (AddRefs might refer to puts in the
same journal, so we can't parallelize the two types together easily.)
Other operations such as archiveRefs and removeRefs are still done in
serial for now.
When putting 20 20-MB files into a folder, this reduces the background Put time from 5m55s to 1m52s.
Issue: KBFS-1275
> tlf_journal: parallelize flushing put/addRef block ops

- libkbfs/journal_md_ops.go
- libkbfs/journal_md_ops_test.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
Enumerate in detail the cases the mdJournal.put expects
to handle, and have journalMDOps.PutUnmerged simply forward
to mdJournal.put.
Add test coverage for all cases in mdJournal.put. Add more
test coverage for journalMDOps.PutUnmerged.
> [KBFS-1489] Fix tricky edge cases in journalMDOps.PutUnmerged

- libkbfs/config_local.go
- libkbfs/conflict_resolver.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/kbfs_ops.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/mdcache.go
- libkbfs/mocks_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- test/dsl_test.go
- test/engine.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
- test/journal_test.go
To get CR working with journaling, this PR:
* Pushes resolution ops directly to the KBFS server, bypassing the journal, since otherwise it will be treated as unmerged since the branch hasn't yet been pruned.
* Flushes the journal when CR starts, since the resolution op goes straight to the server.
* Fixes `mdJournal` to clear out converted-to-branch revisions, since otherwise they will prevent the client from fetching the actual merged revisions with those revision numbers from the server.
* `tlfJournal` now notifies the corresponding `folderBranchOps` when branch conversion happens, so that it can kick off conflict resolution immediately instead of waiting to hear about the next update.
* Allow the DSL tests to pause/resume journal syncing.
> cr: co-exist peacefully with journaling

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/block_ref_map.go
- libkbfs/bserver_disk.go
- libkbfs/bserver_errors.go
- libkbfs/bserver_memory.go
- libkbfs/config_local.go
- libkbfs/disk_journal.go
- libkbfs/errors.go
- libkbfs/journal_block_server.go
- libkbfs/md_id_journal.go
- libkbfs/state_checker.go
- libkbfs/tlf_journal.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
Add a tag field to blockRefMap and populate it with
the ordinal. Use that to efficiently remove map
entries on a flush.
Move BlockServerDisk-specific logic out of blockJournal,
and remove more BlockServer-isms in it.
Clean up block_journal_test.go.
Move shutdown logic out of blockJournal and into
tlfJournal and BlockServerDisk.
> [KBFS-1439] Sync blockJournal's in-memory map properly

- libkbfs/folder_block_manager_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/key_manager_test.go
- libkbfs/test_stallers.go
- test/dsl_test.go
Otherwise if more than one expected `maybeStall` call happens at once, one of the sends onto stallCall could get dropped.
Note: Maybe a better solution is to not have a default case in the send in `maybeStall`?  But I can't remember if there's a good reason for doing that, so this seemed safer.  Happy to change it though if others disagree.
Issue: KBFS-1505
> test_stallers: allow more than one stall to happen in a test

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
This allows us to treat inconsistent end parameters in the block
flushing code as errors.
Note: I tried to do a similar thing for `mdJournal` but the `tlfJournal` flushing code relies on getting a `nil` error when trying to read past the end of the log, so I left it as is for now.
> tlf_journal: lock over whole flush

- libkbfs/conflict_resolver_test.go
- libkbfs/folder_block_manager_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager_test.go
- libkbfs/key_server_local_test.go
- libkbfs/keybase_daemon_rpc_test.go
- libkbfs/rekey_queue_test.go
- libkbfs/tlf_edit_history_test.go
CR contexts are still not cleaned as they are longer term runners
> cleanup cancellation delayer in tests

- env/context.go
- libkbfs/context.go
- libkbfs/init.go
@akalin-keybase did you have something else in mind?  This seems like the simplest thing.  I think we can turn this on by default now, without the warning, since there's an extra step to enable it per-TLF.  What do you think?
----
Issue: KBFS-1362
> init: initialize journal directory using the env data dir

- libkbfs/block_id.go
- libkbfs/hash.go
This lets us output BlockIDs as JSON values in the new
.kbfs_fileinfo_$FILE virtual file.
Issue: KBFS-1513
> block_id: implement encoding.json.Marshaler

- libkbfs/conflict_resolver.go
- libkbfs/folder_branch_ops.go
- libkbfs/journal_server_util.go
- libkbfs/kbfs_ops.go
This changes the onMDFlush code to make sure that we handle all
archive events before shutting down in tests.
> folder_branch_ops: SyncFromServer should wait for md flush calls

- libkbfs/config_local.go
- libkbfs/dirty_bcache.go
- libkbfs/dirty_bcache_test.go
- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_dirty_bcache.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
This will prevent journaled writes from messing up the buffer counts and backpressure for synchronous writes.
Most of the line changes are due to adding a new `TlfID` parameter to the `DirtyBlockCache` methods, so we can direct calls to the appropriate DirtyBlockCache.
We also need to prevent journal enabling/disabling while there is, or might be, dirty data coming in to the dirty block cache.  For now, if there are any outstanding operations that might dirty data on ANY TLF, or if there is any dirty data already, don't allow any TLF to switch its journaling status, because it will mess up the state of the DirtyBlockCache.
Issue: KBFS-1266
> libkbfs: add a journaling-specific dirty block cache

- libkbfs/delayed_cancellation.go
- libkbfs/delayed_cancellation_test.go
When calling `EnableDelayedCancellationWithGracePeriod` the second time, if it's already past grace period since last time `EnableDelayedCancellationWithGracePeriod` was called, a `context.Canceled` would be returned even if parent context has not been canceled yet.
This is an issue for e.g. `Flush()` since we enable the context delayer in `libfuse`, and the enable function is called again in `finalizeMDWriteLocked`. For a real server over network, this can cause a lot of cancellations for slow writes.
Resolves https://github.com/keybase/client/issues/4254 (hopefully)
> fix a bug in cancellation delayer

- libkbfs/bare_root_metadata.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/data_types.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_bundle.go
- libkbfs/key_bundle_test.go
- libkbfs/key_bundle_v3.go
- libkbfs/key_manager.go
- libkbfs/key_manager_test.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mdcache_test.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mdserver_test.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
- libkbfs/test_common.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
This is a WIP PR but I do intend to merge it. Having both metadata versions co-exist is going to span a couple more PRs. The motivation for this half-baked PR is that I want to both get some feedback earlier vs. later and spare myself some merge pain. MDv3 should not be active yet and only initial keying is partially working with no rekey support yet. The `BareRootMetadata` interface is most certainly still going to change. I literally dropped what I was doing and cleaned this up enough for review so it's not a complete thought.
> libkbfs: add v3 metadata (WIP)

- libdokan/dir.go
- libdokan/tlf.go
- libfuse/tlf.go
If someone tries to write to a non-existent TLF, we should report a "write" error, instead of a "read" error.
Issue: KBFS-1521
Issue: DESKTOP-1868
Issue: keybase/client#4271
> fs: report correct error mode for non-existent TLF errors

- libkbfs/config_local.go
Noticed this in local testing.
> config_local: on shutdown, wait for second round of archives

- libkbfs/folder_branch_ops.go
- libkbfs/journal_block_server.go
- libkbfs/journal_md_ops.go
- libkbfs/journal_server.go
- libkbfs/tlf_journal.go
Exclusive writes need to flush the journal and then disable it to ensure they write directly to the servers. But between the flush and the disable, other operations (like block archives or deletes) can sneak in, causing the disable to fail.
To fix this, we need to somehow guarantee that they will flush all their current data before they are shutdown.  But since those are two separate calls, another write could sneak in between the flush and the shutdown, causing an error.  We can't prevent this with more locking in tlfJournal, because there might already be a reference to the tlfJournal floating around (e.g., in JournalServer), and if we blindly shut down, the code holding that reference will hit an error instead of being passed through to the real servers while the journal is disabled. …
> journal: fix race between flushing and disabling

- libkbfs/conflict_resolver.go
- test/journal_test.go
Since the journal block server doesn't support adding block references (see KBFS-1149), and conflict resolution doesn't retry block puts when it gets a non-existent block error back on an add reference, we need to explicitly add duplicate blocks for file with child pointers when journaling is enabled.
Issue: KBFS-1531
> cr: don't add block references when journaling is enabled

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/config_local.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/keybase_service_base.go
- libkbfs/keybase_service_util.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
Store uid and verifying key (representing device)
in mdJournal. Handle user switching at the
JournalServer level.
Make uid and verifying key KID part of the path.
Add a "v1" path component. [KBFS-1524]
Clean up tests a bit.
> [KBFS-1212] Make journal handle user switching

- libkbfs/folder_branch_ops.go
- libkbfs/journal_md_ops.go
- libkbfs/md_ops.go
- libkbfs/test_stallers.go
- libkbfs/tlf_handle.go
- libkbfs/tlf_journal.go
- test/dsl_test.go
- test/engine_libkbfs.go
- test/journal_test.go
Rekeys need to go straight to the real MD server -- if it ends up in a conflict branch, our key cache will be wrong.
Also, `journalMDOps` needs to check for handle resolution the same way as `MDOpsStandard`.
To build the test, I needed to do two extra things:
1. Return early from `SetInitialHeadFromServer` if the head is already set.  `EngineLibkbfs` calls this function on every operation, and if it gets to the point where it takes `mdWriterLock`, it deadlocks with other stalled operations.
2. Stall delegate MD ops, if journaling is on.
Issue: KBFS-1497
> libkbfs: support rekeys when journaling is enabled

- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
- libkbfs/kbfs_ops_concur_test.go
Previously, this sequence of events left the dirty block cache in a bad state:
1. A Sync starts.
2. A block is dirtied.
3. The Sync fails with a recoverable block error.
4. The recovery Sync starts.
5. The recovery Sync fails due to an unrecoverable error (say a timeout or ctx cancel).
6. Later, another Sync completes successfully.
This left unaccounted bytes and dirty blocks in the dirty block cache.  This PR fixes it by:
* On an unrecoverable error, subtract newly-dirty child block bytes from the waitBuf count; they're not considered dirty anymore since the block has been finalized and the blocks are clean (but living in the bps, rather than the dirty block cache).
* On an unrecoverable error, delete these orphaned blocks from the dirty block cache as well.
* Move deferral work into a …
> folder_block_ops: fix dirty block accounting after double error sequence

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/block_types_test.go
- libkbfs/md_id_journal.go
- libkbfs/md_id_journal_test.go
- libkbfs/md_journal.go
- libkbfs/mdserver_tlf_storage.go
Have blockJournalEntry support unknown fields.
Have mdIDJournal store a struct (with unknown
field support) instead of just an MdID.
Have mdJournal store MD data in a file in a
per-MD directory. In the future, the directory
might have other files (e.g. to store the
version).
> [KBFS-1525] Support unknown fields in journals

- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops.go
Also, track branch changes more carefully and wait on them while
syncing.
This fixes a flaky journal test.
Issue: KBFS-1545
> folder_branch_ops: don't cancel onMDFlush context early

- libkbfs/bare_root_metadata.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/config_local.go
- libkbfs/crypto_common.go
- libkbfs/interfaces.go
- libkbfs/key_manager.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mdserver_tlf_storage_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/tlf_journal.go
With this change I can get through most of the tests with MDv3 enabled. I think I'll need to put up 2 more PRs though. Currently the following tests fail with MDv3:
1. Rekey-specific tests
2. Journaling tests
> libkbfs: changes to support local use of MDv3

- libkbfs/config_local.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_block_manager_test.go
- libkbfs/interfaces.go
- libkbfs/mocks_test.go
- libkbfs/test_common.go
To avoid causing conflicts for active writers on other devices.
Also, while we're in this code, we can use the true server timestamp to decide when a revision is old enough for QR, rather than resolving on the root directory mtime (which might not have been updated, see KBFS-821, KBFS-902).
Issue: KBFS-1429
> folder_block_manager: don't run QR if the head is too new

- libkbfs/md_id_journal.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
In particular, when converting to a branch.
Don't preserve unknown fields when replacing
the head, though, as that is semanitically a
brand-new entry.
> [KBFS-1525] Preserve unknown fields in mdJournal

- libkbfs/conflict_resolver.go
- test/cr_complex_test.go
Otherwise a setAttr could end up using an old, unfixed pointer that is
updated in a syncOp.  folderBranchOps.syncBlock doesn't add the update
because in CR, file updates are just directory actions and the file
itself is never updated through a syncBlock call.
Issue: KBFS-1534
> cr: include updates from syncOps when fixing op pointers

- libkbfs/bserver_remote.go
Without this, if something is doing a bulk put, a small read could get
blocked behind the slow large block transfers.  With separate TCP
connections, the read finishes quickly.
Note that this will double the number of bserver connections, and
increase the amount of token signing done on the client.  It also
means that the bserver must not apply any per-device optimizations
that assume gets and puts from the same device reach the same bserver
(as far as I know, it makes no such assumptions today).
Issue: KBFS-1546
> bserver_remote: use separate connections for gets and puts

- kbfsdokan/main.go
- kbfsfuse/main.go
- libdokan/mounter.go
- libfuse/mounter.go
- libfuse/start.go
This will let us easily enable mountless KBFS daemons on systems where mounting isn't possible due to incompatibility, but we still want to run KBFS for rekey/chat purposes.
cc: @maxtaco 
Issue: KBFS-1560
> Add "none" mount-types for kbfsfuse and kbfsdokan

- circle.yml
This arg makes it use existing KBFS in go path.
> Fix gobuild to use local KBFS in Circle CI

- libkbfs/folder_block_manager.go
- libkbfs/folder_branch_ops.go
This gets us into a bad state, since
the BlockServer rightly returns an error
that the blocks in question aren't
archivable.
> [KBFS-1581] Don't archive GC ops

- libfs/remote_status.go
* Make it behave like ExtraFileName
* It was reported on irc and traced the problem to this
> libfs: fix RemoteStatus.ExtraFileNameAndSize

- libkbfs/mdserver_remote.go
Don't push the connection status error down if it is just throttling.
> libkbfs: Throttling should not cause error state

- libkbfs/conflict_renamer.go
- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/cr_chains_test.go
- libkbfs/data_types.go
This will be used in a later PR when a `crChains` is used to track outstanding journal writes, in order to remove the operations corresponding to a given revision once it has been flushed.
Issue: KBFS-1473
Issue: KBFS-1474
> cr: tags ops with revision, and allow op removal by revision

- libkbfs/folder_block_ops.go
- libkbfs/kbfs_ops_concur_test.go
Otherwise a block that carries over from one failed sync to another could get incorrectly deleted if the first failed sync actually succeeded on the master branch.
Also, deep-copy the bps when saving a MD to clean.  Otherwise if a future sync also fails, the blocks from that failed sync will also appear in the bps of the previous failed sync, and will get incorrectly cleaned up with the policy of the first failed sync.
Issue: KBFS-1569
> folder_block_ops: clean up blocks based on policy of first failure 

- libkbfs/folder_branch_ops.go
- libkbfs/test_stallers.go
We did this under journaling when there was a branch change, because
it's hard to know the right merged revision number in that code.
However, this messes up the registration code, and can cause the
client to fetch ALL revisions for no good reason.
Instead, `handleMDFlush` should be in charge of setting the latest
revision number for MDs flushed by this device, and `setHeadLocked`
should only set them for other devices, when journaling is enabled.
Issue: KBFS-1590
> folder_branch_ops: don't set latest merged revision to 0 

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
Limit the number of blocks we process at once during a flush, and when that's done, move onto flushing whatever MDs we can.
Issue: KBFS-1564
Issue: KBFS-1575
> journal: interleave blocks and MDs, and limit block parallelism

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- test/cr_multi_blocks_test.go
- test/cr_simple_test.go
Also fix a bookkeeping issue exposed by this -- if a block has been overwritten already on the merged branch, it shouldn't be unreferenced again in the resolution.
Issue: KBFS-1603
> cr: ignore renames if the whole chain has been deleted

- libkbfs/conflict_resolver.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status.go
- libkbfs/folder_branch_status_test.go
- libkbfs/journal_server.go
- libkbfs/tlf_journal.go
I'm not totally happy with the callstack flow for this; let me know if you can think of a better way to organize it.
Issue: KBFS-1475
> tlf_journal: expose unflushed paths in .kbfs_status

- libkbfs/kbfs_ops.go
- libkbfs/kbfs_ops_test.go
This test tried to get around the fact that reidentifies were
asynchronous by sending twice on the reidentify channel.
Unfortunately, that led to a race, where identifyDone could be set
back to false by the second send, after the final identify was done.
Instead, the reidentify loop can explicitly signal when it's finished.
Issue: KBFS-1553
> kbfs_ops_test: fix ReIdentify test flake

- libkbfs/folder_branch_ops.go
- libkbfs/identify_util.go
- libkbfs/identify_util_test.go
- libkbfs/kbfs_ops.go
- libkbfs/keybase_service_base.go
- vendor/github.com/keybase/client/go/protocol/keybase1/extras.go
- vendor/github.com/keybase/client/go/protocol/keybase1/tlf.go
- vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/errgroup/errgroup.go
- vendor/vendor.json
This is my 2nd take on https://github.com/keybase/kbfs/pull/406; I also added a simple test that practices part of the new code
> use context for alternative identify behavior

- README.md
it has been changed in https://github.com/keybase/kbfs/commit/3cf9045546540bb72435bb48cd53471773a46c76 but URL didn't updated.
> Update kbfstool URL

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_util.go
- libkbfs/root_metadata.go
- libkbfs/state_checker.go
- test/cr_multi_blocks_test.go
If conflict resolution, for example, makes a large change block, we risk going over the block server maximum if we put it all in one block.
I was going to bump up the data version for this change, but unfortunately in older versions we only check the data version on lookup, which doesn't help for unembedded block changes (or the root pointer, for that matter).  Sigh.  So I added that check as part of this PR for the future.  Older clients will unfortunately see a cryptic error, and if they already have the folder cached they will simply fail to update, and keep showing the old version.
Issue: KBFS-787
> libkbfs: child block support for change blocks

- libkbfs/cr_chains.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/journal_server.go
- libkbfs/key_manager.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/md_util.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
A future commit will need to cache the unflushed paths within the `tlfJournal` struct, and add/remove from it as the journal changes.  So this PR moves the logic to build the complete unflushed paths into tlfJournal, as a step in that direction.  However, since `tlfJournal` doesn't have access to a complete `Config`, this required a bunch of refactoring:
* Break one function off the `KeyManager` interface.
* Change `decryptMDPrivateData` to not rely on a full `Config`, but instead on individual interfaces.
* Refactor the code in `crChains` a bit to not rely on a full `Config` when just adding ops to the chains -- much of the stuff dependent on other parts of the config isn't needed for this use case.
* Add a way for `tlfJournal` to get a view of the journal MD range that guaranteed to be …
> journal: move unflushed paths logic into tlfJournal

- Makefile
Specifically, allow context.Context to not be
the first argument in test files. Usually,
testing.T is a better first argument.
> Add exception for golint warnings about context

- dokan/cgo.go
- dokan/filesystem.go
- libdokan/dir.go
- libdokan/folderlist.go
- libdokan/fs.go
- libdokan/profilelist.go
- libdokan/tlf.go
+ Sometimes returning either a file or directory is ok
+ Sometimes returning only a file is ok
+ Sometimes returning only a directory is ok
Thus:
+ Add extra checks for debug builds
+ Add two helper methods to dokan
+ Add more checking to libdokan
> Dokan be stricter about files vs directories

- libdokan/fs.go
- libfs/constants.go
- libfs/journal_control_file.go
- libfuse/special_files.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
This PR lets you turn on journaling for all TLFs, in a way that survives restarts by writing to a journal server config file on disk.  After enabling auto-journaling, all future TLF accesses will go through a journal.
When disabling auto-journaling, newly-accessed TLFs will no longer create a journal; however, existing journaled TLFs need to be disabled one-by-one if desired.
Introduces control files `/keybase/.kbfs_enable_auto_journals` and `/keybase/.kbfs_disable_auto_journals`.
Issue: KBFS-1622
> journaling: option to enable automatic journaling

- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/journal_server_util.go
- libkbfs/kbfs_ops.go
- libkbfs/keybase_service_base.go
- libkbfs/tlf_journal.go
This calculates the unflushed paths for all journals in parallel, and adds them together in the overall KBFS status.
Issue: KBFS-1630
> journal_server: aggregate the unflushed paths for overall status

- libkbfs/folder_branch_ops.go
Otherwise, after a restart when journaling is on, if you were the last
writer to the folder, you will never set the revision and you'll keep
registering with a revision of 0.
Issue: KBFS-1638
> folder_branch_ops: always set latest merged rev when initial head

- kbfscodec/codec.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mdserver_tlf_storage_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
This makes it possible to store V3 MD objects in
MDServerMemory, MDServerDisk, and mdJournal.
Test coverage will be added in a future PR.
> [KBFS-1526] Store MD version numbers and extra fields

- libkbfs/journal_md_ops.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mdcache_test.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/root_metadata.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
I missed a few places in my last PR (#430).
Make ImmutableBareRootMetadata have an
ExtraMetadata field.
Add constructor for RootMetadata (to avoid
dropping fields).
Also add checks for wkbID and rkbID being either
both nil or both non-nil.
> [KBFS-1526] Plumb through ExtraMetadata some more

- libkbfs/unflushed_path_cache.go
> unflushed_path_cache: addUnfushedPaths should always make rev map

- libkbfs/folder_branch_ops.go
We need to use the server's notion of the merged head when the journal
is empty.
> folder_branch_ops: fix latest merged rev when journal is empty

- libkbfs/conflict_resolver_test.go
- libkbfs/delayed_cancellation.go
- libkbfs/folder_block_manager_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager_test.go
- libkbfs/key_server_local_test.go
- libkbfs/keybase_daemon_rpc_test.go
- libkbfs/rekey_queue_test.go
- libkbfs/tlf_edit_history_test.go
- libkbfs/tlf_journal_test.go
In particular, the ones that use the kbfsOpsInit,
kbfsOpsInitNoMocks, and kbfsOpsConcurInit functions.
Wait on ctx.Done() in key manager tests to avoid
hanging the whole test run.
> [KBFS-1641] Add individual test timeouts for some tests

- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/cr_chains.go
- libkbfs/cr_chains_test.go
- libkbfs/crypto_common.go
- libkbfs/crypto_common_test.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/key_manager.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/md_util.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/tlf_edit_history.go
- libkbfs/tlf_journal.go
- libkbfs/unflushed_path_cache.go
Define types with restricted interfaces instead.
This removes the need to create fake
IRMD objects to pass into crChains, and will
make a future PR easier.
Restrict some other interfaces also, in particular
in folderBlockOps, and remove
some spurious `md.ReadOnly()` calls.
> Remove dependency on IRMD from crChains

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/mocks_test.go
- libkbfs/test_stallers.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- libkbfs/unflushed_path_cache.go
This is Phase 1 in speeding up CR under journaling and coalescing journal entries together.  It allows the upper layers to specify a revision that completely replaces the current conflict branch, and avoid flushing blocks that have since been deleted.  This involves:
* Replace the current MD conflict branch with a journal that contains only one MD representing the resolution.
* Mark certain block journal entries as ignorable.
The next phase will use `ResolveBranch` from the conflict resolver, and turn off journal flushing when on a conflict branch.  This should significantly speed up CR since everything needed to run it is guaranteed to be locally available, and will also reduce the number of blocks we have to flush.
After that, the journal will start "faking" conflicts in order to …
> journal: add an MDOps.ResolveBranch function for squashing branches

- libkbfs/folder_branch_ops.go
- libkbfs/tlf_edit_history.go
Because CR goes directly to the server when journaling is on (until
KBFS-1637 is in), we can safely update the latest merged revision.  If
we don't, and the TLF isn't accessed through its handle before a
journal flush ends up triggering CR (e.g. because of QR), we could end
up in a situation where head is set, but the latest merged rev is not
(which eventually leads to a panic in the fast-forward code).
Issue: KBFS-1663
> folder_branch_ops: update latest merged revision on CR

- libkbfs/ops.go
- libkbfs/ops_test.go
Otherwise the OldDir in the new renameOp will be very wrong.
Issue: KBFS-1676
> ops: inverting a rename needs to check for an empty newdir

- libkbfs/folder_branch_ops.go
We must always unembed block changes when unstaging, otherwise the resolution put will get rejected.
Also, I noticed we weren't caching put blocks in a few places (most notably after CR!), so this fixes that up too.
Issue: KBFS-1676
> folder_branch_ops: unembedded block change fixes

- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager.go
- libkbfs/md_util.go
- libkbfs/reporter_kbpki.go
- libkbfs/root_metadata_test.go
- libkbfs/tlf_handle.go
- libkbfs/tlf_handle_test.go
We show the path that failed to read in the notification. This includes it in the ReadAccessError.
> Include filename in ReadAccessError

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/bserver_disk.go
- libkbfs/bserver_measured.go
- libkbfs/bserver_memory.go
- libkbfs/bserver_remote.go
- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server.go
- libkbfs/journal_md_ops.go
- libkbfs/journal_md_ops_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/md_ops.go
- libkbfs/mocks_test.go
- libkbfs/ops.go
- libkbfs/root_metadata.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- test/dsl_test.go
- test/journal_test.go
This PR enables a journaled TLF to use only local information during conflict resolution, and completely avoids creating a conflict branch on the servers.  Getting there required quite a few changes (let me know if you'd prefer them broken out into separate PRs):
- `tlfJournal` pauses flushing as soon as it notices a conflict.
- `conflictResolver` figures out which blocks don't need to be uploaded, and passes that to `MDOps.ResolveBranch` so the journal can ignore them.
- We now write the resolution MD to the journal, rather than directly to the server (due to the `ResolveBranch` semantics).
- Since the journal might have uploaded some blocks before discovering a conflict, `BlockServer` now has an `IsFlushed` method that the `conflictResolver` can use to tell which blocks have already …
> cr: speed up while journaling by avoiding extraneous block uploads and downloads

- libkbfs/journal_server_test.go
Also swap the expected vs. got values for require.Equal to fix error
messages.
Issue: KBFS-1581
> journal_server_test: flush journal between restarts

- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/journal_md_ops.go
There might be a bug where the unmerged list of revisions is missing
the earliest revision; this is to help us find it.
Issue: KBFS-1664
> cr: check that branch point is really the unmerged successor

- kbfsfuse/main.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/config_local.go
- libkbfs/init.go
- libkbfs/interfaces.go
This actually does 3 things:
* Fixes a bug where we were dereferencing nil `ExtraMetadata` for public folders.
* Adds a cmdline option for which metadata version to use
* Makes the default version of the above v3 when connecting to staging.
> libkbfs: use MDv3 in staging env

- libkbfs/coalescing_context_test.go
Fix for https://ci.keyba.se/job/kbfs/job/master/1219/execution/node/231/log/
We shouldn't have been checking here for `NoError`, since as soon as `cf2` is called, the `CoalescingContext` `cc.Done()` will begin racing to complete.
r? @strib
cc @maxtaco
> coalescing_context: remove racy check in coalescing_context_test

- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/mdcache.go
I have a theory that the client in KBFS-1664 experienced a race where
it pulled in a revision from the master branch right before it
converted a local journal into a branch, overwriting the local
revision in the cache with the "master" MD and then replacing that
master MD into the cache under the branch ID.  This would royally
screw up conflict resolution, among other things.
Issue: KBFS-1664
> md_journal: make sure entries match before replacing in cache

- libkbfs/path.go
- libkbfs/reporter_kbpki.go
Sends full canonical path for FSNotifications.
The desktop app has a fix to use this since it knowns FSNotification.Filename is always the full canonical path: https://github.com/keybase/client/issues/4833
> FSNotification filename should use canonical path

- libkbfs/conflict_resolver.go
- libkbfs/cr_actions.go
- libkbfs/cr_chains.go
- libkbfs/folder_block_ops.go
- libkbfs/ops.go
- libkbfs/ops_test.go
- test/cr_basic_conflicts_test.go
Previously we didn't handle the situation where two users modify a
file (either by writing to it or modifying its attributes), but only
one of them renames it.  In that case, we've decided to keep both
versions of their files, under their names in their respective
branches.  E.g.:
* alice and bob have a shared folder with a file "foo"
* alice writes data into "foo"
* at the same time, bob writes different data into "foo" AND renames "foo" to "bar"
* after resolution, there will be both "foo" and "bar"
Issue: KBFS-1650
> cr: fix situations where a conflicting file is renamed

- libdokan/mount_test.go
- libfuse/mount_test.go
- libkbfs/conflict_resolver_test.go
- libkbfs/folder_block_manager_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager_test.go
- libkbfs/keybase_daemon_rpc_test.go
- libkbfs/rekey_queue_test.go
- libkbfs/test_common.go
- libkbfs/tlf_edit_history_test.go
This ensures that those functions obey the test timeout.
> [KBFS-1641] Plumb through ctx to GetRootNode{ForTest,OrBust}

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
Otherwise, blocks that were put after the save but before the next MD
flush would never be GC'd.
Issue: KBFS-1692
> block_journal: if a save journal is present, append to it as well

- libkbfs/block_ops.go
- libkbfs/block_ops_test.go
- libkbfs/block_retrieval_queue.go
- libkbfs/config_local.go
- libkbfs/init.go
- libkbfs/test_common.go
This is to avoid cluttering up stack
traces, e.g. when a DSL test times out.
Also clean up ConfigLocal constructors a bit.
> [KBFS-1693] Have fewer blockRetrievalWorkers for tests

- kbfsfuse/main.go
- libfuse/debug.go
- libfuse/mount_test.go
- test/run_fuse_test.go
In particular, Statfs and Access calls, which
for some reason are called very frequently on
OS X.
> Hide some spammy logs

- libkbfs/block_disk_store.go
- libkbfs/block_disk_store_test.go
- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/block_ref_map.go
- libkbfs/bserver_disk.go
- libkbfs/bserver_memory.go
- libkbfs/folder_block_manager_test.go
- libkbfs/interfaces.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/kbfs_ops.go
- libkbfs/keybase_service_base.go
- libkbfs/md_journal_test.go
- libkbfs/state_checker.go
- libkbfs/tlf_journal.go
Introduce a new blockDiskStore type to store
block data (including refs) on disk. Use it
in blockJournal and BlockServerDisk.
Remove the in-memory ref map from blockJournal,
and rely on blockDiskStore instead. This removes
the need for the scan on startup.
Track unflushed bytes via an aggregate_info file.
> [KBFS-1688] Avoid initial block journal scan

- libkbfs/block_journal.go
...to block_aggregate_info. The journal dir
is shared with the MD journal, so it's worth
adding the qualifier.
> Rename block journal aggregate_info file

- libkbfs/keybase_daemon_rpc.go
- vendor/github.com/keybase/client/go/protocol/chat1/common.go
- vendor/github.com/keybase/client/go/protocol/chat1/extras.go
- vendor/github.com/keybase/client/go/protocol/chat1/gregor.go
- vendor/github.com/keybase/client/go/protocol/chat1/local.go
- vendor/github.com/keybase/client/go/protocol/chat1/notify.go
- vendor/github.com/keybase/client/go/protocol/chat1/remote.go
- vendor/github.com/keybase/client/go/protocol/gregor1/extras.go
- vendor/github.com/keybase/client/go/protocol/keybase1/constants.go
- vendor/github.com/keybase/client/go/protocol/keybase1/session.go
- vendor/vendor.json
OnConnect is called lazily when a reconnection is triggered by an
outgoing RPC, and we need to send HelloIAm calls as soon as we can
after the connection is re-established.  So instead of waiting for
KBFS to make a call, have one going proactively in the background at
all times.
Issue: KBFS-1671
> keybase_daemon_rpc: keep the conn alive with CurrentSession calls

- README.md
I'm not sure if much else requires 1.7, but context didn't get moved from golang.org/x/net/context to the stdlib as 'context' until 1.7, and it is used as such in the current source.
eg: https://github.com/keybase/kbfs/blob/master/libkbfs/ops.go#L8
ref: https://tip.golang.org/doc/go1.7#context
> Bump Go version requirement to 1.7

- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
This is SA2002 from staticcheck.
> Fix all t.Fatal{,f} calls from goroutines

- libkbfs/branch_id.go
- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/cr_actions.go
- libkbfs/cr_chains.go
- libkbfs/crypto_common.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/tlf_journal.go
- libkbfs/unflushed_path_cache.go
- test/journal_test.go
This PR squashes together a set of journal commits if the length of the journal exceeds some threshold ( hardcoded to 20 updates for now).  It does this by:
* Converting the journal to a branch, using a special reserved branch ID.
* CR handling an empty merged set and making sure pointers are all fixed up even when no explicit actions are involved.
* Making sure the branch updates are cleared from the MD cache after a resolution, since we can now re-use branch IDs.
* Tracking the most recent `BlockInfo` is `crChains` so we can get the encoded size of a root block during CR.
Note that I'll disable coalescing by default when I commit this because it currently does nothing to recognize if there are already squashes in the earliest journal slots, and thus too many updates can end up getting …
> journal: coalesce updates together

- libkbfs/block_types.go
- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
- libkbfs/kbfs_ops_test.go
This will make it easier to add support for multiple levels of
indirection in a future PR.  Note that this just moves code around, it
shouldn't change behavior at all.
Issue: KBFS-35
> folder_block_ops: refactor file data logic into its own struct

- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
In preparation for when we support multiple levels.
Issue: KBFS-35
> file_data: getFileBlockAtOffset should return all parents

- libkbfs/conflict_resolver.go
- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
This is just a refactor that moves everything related to indirect pointers out of `folderBlockOps` and into `fileData`.  There shouldn't be any behavioral changes.  This is in preparation for multiple levels of indirection, and by moving everything into one place, it'll make that easier to write and unit test.
Note there's a bit of weirdness below in that sometimes the `fileData` methods return data even when `err != nil`, and that data is used by the caller.  This is to preserve existing behavior in `folderBlockOps` whenever possible.  It's possible we might be able to eliminate some of these cases in the future but I didn't want to change behavior in this PR.
Issue: KBFS-35
> file_data: move all indirect pointer access out of folderBlockOps

- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/interfaces.go
- libkbfs/key_bundle.go
- libkbfs/key_bundle_v3.go
- libkbfs/key_manager.go
- libkbfs/key_manager_test.go
- libkbfs/keycache_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata_test.go
The Merkle tree builder only needs the
current one, and we weren't maintaining the
list properly, anyway.
Also fix some redundant KeyGen casts.
> [KBFS-1720] Store only the current TLFPublicKey

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
Otherwise there can be a race where the lookup gets the path, and then
we hear about a change for that child node.  But since the child isn't
in the node cache yet, the change doesn't update the pointer.  Then
the lookup makes a new node for the child using the old pointer, and
the node never gets updated by subsequent changes.
Note that the new test, as is, won't repro the original problem
exactly, because it depends on locking behavior.  The first version of
the test I wrote does repro the problem, but due to different locking
behavior it would hang now.  The test is probably useful on its own
though, to make sure a concurrent Lookup and Sync work correctly.
Issue: KBFS-1717
> folder_block_ops: do lookups while holding blockLock

- libkbfs/branch_id.go
- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/cr_actions.go
- libkbfs/cr_chains.go
- libkbfs/crypto_common.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/journal_md_ops_test.go
- libkbfs/md_id_journal.go
- libkbfs/md_id_journal_test.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/tlf_journal.go
- libkbfs/unflushed_path_cache.go
- test/journal_test.go
This avoids squashing previous squashes into new squashes, by skipping them during branch conversion.  This allows the journal to have a mix of merged and unmerged entries, which complicates some of the `journalMDOps` logic, but it doesn't seem too bad.
Also, the `unflushedPathCache` reinitialization logic had to change a bit since a branch resolve doesn't necessarily clear the whole branch, so we have to keep around the revisions that were earlier than resolution revision.
Issue: KBFS-1653
> md_journal: don't convert local squashes to new squash branch

- libkbfs/journal_md_ops.go
- libkbfs/journal_md_ops_test.go
- libkbfs/tlf_journal.go
(@akalin-keybase this is a high priority review, should be pretty fast though.)
---
GetForHandle doesn't know the branch ID yet, so must pass in
NullBranchID.  So if there's a branch, we have to look up the right
branch ID first in that case, now that `getHead` requires it.
Issue: KBFS-1732
> journal_md_ops: fix GetForHandle(Unmerged) for journal branches

- kbfstool/md_common.go
- kbfstool/md_force_qr.go
- kbfstool/md_main.go
- kbfstool/md_reset.go
Needed to repair throttle-causing TLFs that were broken due to the
lack of KBFS-1734.
Issue: KBFS-1735
> kbfstool: make a forceQR command for short-circuiting QR

- kbfstool/md_force_qr.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_branch_ops.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
Instead of scanning backwards until we find the latest GC op, we
instead use a field embedded in the private metadata if it's
available.
Note that we still have to scan to find the most recent old-enough
revision, but we now limit that scan.  And that's much less of a
problem, since it's guaranteed that as soon as the client stops
writing for 5 minutes it will be able to find an old-enough revision.
And it /really/ shouldn't be a problem since clients won't even do QR
if the head is too recent anyway.
Issue: KBFS-1734
> folder_block_manager: use LastGCRevision instead of scanning

- kbfscodec/codec.go
- kbfscodec/codec_msgpack.go
- kbfscodec/codec_msgpack_test.go
- kbfscodec/codec_test.go
- libkbfs/block_disk_store_test.go
- libkbfs/journal_md_ops_test.go
Fortunately, it turns out we don't actually do this
(at least in tests).
> Forbid encoding nil values

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
If a file handle to a removed file gets one of its attributed set, it
will have a deCache entry even though the file itself might not be
dirty.  Then if a Sync happens, it won't count as dirty since no
blocks are dirty, and the sync won't clear out the deCache entry,
leading to a panic in the background flusher.
Issue: KBFS-1743
> folder_block_ops: any file with a dirty deCache entry is dirty

- libkbfs/block_retrieval_queue.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/block_retrieval_worker_test.go
- libkbfs/block_types_test.go
Added fix and regression test for retrieving the same block pointer into different block types. The test panics without the fix (with the same error message as Patrick's log), and passes with it.
> [KBFS-1740] Fix common block retrieval panic

- libkbfs/init.go
> Revert "libkbfs: enable mdv3 by default in production"

- libkbfs/bare_root_metadata_v2.go
- libkbfs/root_metadata_test.go
> Avoid returning typed nils

- libkbfs/bare_root_metadata_v2.go
- libkbfs/folder_branch_ops.go
- libkbfs/init.go
- libkbfs/root_metadata_test.go
This reverts commit ac049d0641d4abdf26786f4cef1334b4df4a0438.
> Revert "Revert "libkbfs: enable mdv3 by default in production""

- libkbfs/conflict_resolver.go
When folderBranchOps writes a new unmerged update, it calls
cr.Resolve() while holding mdWriterLock, to let CR know that new data
has been committed to the branch.  This should cause any current CR to
be canceled.  However, that happened via a channel, and so the current
CR could complete, and clear the unmerged branch completely including
the new commit, before it learns about the new input.
To fix the race, this change makes sure that cr.Resolve() cancels any
existing CR before it returns to the caller.  This solves the race
because the existing CR will need to take mdWriterLock before
completing its resolution, and after it takes mdWriterLock it checks
whether it's been canceled or not.
Issue: KBFS-1746
> cr: cancel existing CRs synchronously with Resolve() call

- libkbfs/block_types.go
- libkbfs/dirty_bcache.go
- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/journal_md_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager.go
- libkbfs/md_ops.go
- libkbfs/md_util.go
- libkbfs/tlf_journal.go
This PR was to moves all of the unembedded block change work into `fileData`, for both creation and reading.
While I was working on reading data, I took the opportunity to combine the block change reads with the  `folderBlockOps.Read()` functionality, moved it all into `fileData`, and updated it to a) support multiple levels of indirection, and b) fetch blocks in parallel.
I plan to add a whole slew of `fileData` unit tests in a separate PR once it supports multiple levels of indirection everywhere.  For now, I think the existing tests cover it pretty well.
Issue: KBFS-35
> file_data: use for block changes, and supporting multiple levels of indirection in reads

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/file_data.go
This PR moves all direct usage of `IndirectFilePtr`s away from CR and info `fileData`, so it's all in one place when we add multiple levels of indirection.
This just a refactor, shouldn't introduce any new logic.
Issue: KBFS-35
> fileData: refactor CR IndirectFilePtr usage

- libkbfs/folder_branch_ops.go
- libkbfs/root_metadata.go
- libkbfs/state_checker.go
* `StateChecker` should use it for fetching blocks and block sizes.
* `RootMetadata` should use it when loading unembedded block changes into the reference list.
Note that there is one final direct use of `FileBlock.IPtrs` outside of `libkbfs`, in `kbfstool.md_check`, but it will already work with multiple levels of indirection and I don't really want to export `fileData` at the moment, so I'm going to leave it alone for now.
Issue: KBFS-35
> file_data: use by final libkbfs stragglers

- libkbfs/folder_block_ops.go
Can't figure out KBFS-1764 for the life of me.  Adding this extra debugging to make it easier next time we hit it.
Issue: KBFS-1764
> folder_block_ops: add debugging for invalid block refs

- libkbfs/conflict_resolver.go
If an unreferenced block can't be fetched, we shouldn't kill CR over
that.  It probably means a file/directory with broken/missing blocks
was removed from a TLF, and we should let it go through (with an
incorrect MD usage count for the TLF) just like we do for the
RemoveEntry() call.
Issue: KBFS-1761
> cr: don't let recoverable removal errors kill CR

- libkbfs/conflict_resolver.go
Because it sends bad notifications to the service.  No real need to
notify during conflict resolution at all, in my opinion.
Issue: KBFS-1768
> cr: don't use fake file path when reading blocks

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
Otherwise it can hold the journal lock for too long, blocking access
from foreground file system operations for too long.
Instead, release the lock every once in a while to allow others to
run.
Issue: KBFS-1763
> block_journal: cap number of blocks per onMDFlush call

- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v2_test.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/bare_root_metadata_v3_test.go
- libkbfs/crypto_common.go
- libkbfs/errors.go
- libkbfs/interfaces.go
- libkbfs/key_bundle_cache_test.go
- libkbfs/key_bundle_v2.go
- libkbfs/key_bundle_v2_test.go
- libkbfs/key_manager_test.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
Otherwise, the journal would not be able to
easily serve up MDs with fleshed-out
ExtraMetadata objects.
Use NewExtraMetadataV3 everywhere.
Use TLF{Writer,Reader}KeyBundleV3 instead of
pointers in more places.
Lots of misc. cleanup.
> [MDv3] Remove extraNew in favor of bools in extra

- libkbfs/bare_root_metadata_v3.go
- libkbfs/bare_root_metadata_v3_test.go
- libkbfs/root_metadata_test.go
We were erroneously clobbering the
wkbNew/rkbNew flags, and so we wouldn't
send up the new key bundle properly.
> Fix bug when rekeying after upconvert

- libkbfs/interfaces.go
- libkbfs/md_journal.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_tlf_storage.go
In particular, let GetKeyBundles omit
arguments, and respect wkbNew/rkbNew flags.
> Make local MDServers match MDServerRemote

- libkbfs/conflict_resolver.go
- libkbfs/folder_block_ops.go
If conflict resolution has to fetch a lot of blocks to do block accounting, it's best to fetch them in parallel to make it as fast as possible.
Note that once #579 goes in, this won't be as big an issue when journaling is enabled since all of referenced blocks should be locally available on disk.  However, the unref'd blocks still may be getting fetched from the remote server.
+@jzila as a reviewer since it involves block fetching.
> cr: fetch ref and unref blocks in parallel

- libkbfs/block_disk_store.go
- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
Otherwise, if we have a large MD update (say due to journal coalescing) and we flush all the blocks before finding out there's a conflict, we will have to re-download all those blocks during conflict resolution if they are forced out of the block cache or if there's a restart.
Issue: KBFS-1777
> tlf_journal: always save flushed blocks until the next MD flush

- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status.go
A few fixes for the re-registration issues we saw today:
* Since rekeys bypass the journal, a rekey needs to explicitly set the latest merged version (because `setHeadLocked()` ignores updates from our own device when journaling is on).
* Don't bother re-registering when MD is too new.  We'll never be able to read the MD a folder if we can't understand it. Might as well just stick to the current version, and if there are writes, go onto an unmerged branch.  Set a "permanent error" in the TLF status so we can tell that this happened.
* Add MD version to TLF status.
> folder_branch_ops: fix re-register issues and add MD version to status

- libkbfs/bare_root_metadata_v2.go
- libkbfs/root_metadata_test.go
Since copying writer signatures blindly between versions doesn't work.
Issue: KBFS-1788
> bare_root_metadata_v2: readers shall not upconvert to v3

- README.md
- kbfsdokan/README.md
- kbfsdokan/main.go
- kbfsfuse/kbfsfuse.sh
- kbfsfuse/main.go
- kbfstool/main.go
- libfuse/platform_flags_osx.go
- libkbfs/init.go
- libkbfs/keybase_daemon.go
Remove -server-in-memory and -server-root flags
in favor of just having -bserver and -mdserver
understand "memory" and "dir:/path/to/dir"
arguments. This also lets one use a local
bserver with a production mdserver and vice
versa.
Decouple favorite storage from bserver and
mdserver storage by adding a -local-fav-storage
flag.
Set default flags in DevelRunMode to use all
in-memory servers, for convenience.
Add a few more users to the hard-coded list of
local test users.
Factor out common usage strings.
> Simplify init flags

- libkbfs/config_mock_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager_test.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops_test.go
- libkbfs/mdcache_test.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata_test.go
- libkbfs/safe_test_reporter_test.go
- libkbfs/test_common.go
...on MetadataVer.
Fix tests that break with MDv3.
> [KBFS-1654] Parametrize KeyManager and MDOps tests

- libkbfs/reporter_kbpki.go
To workaround DESKTOP-2442.
Issue: KBFS-1795
> reporter_kbpki: set filename for read timeout errors

- libkbfs/errors_fuse.go
It's confusing to get an EIO error when trying to write to a finalized
TLF.
Issue: KBFS-1800
> errors_fuse: give EACCES code for MetadataIsFinal error

- kbfstool/md_force_qr.go
- kbfstool/md_reset.go
- libkbfs/bare_root_metadata.go
- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/bare_root_metadata_v3_test.go
- libkbfs/conflict_resolver.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops_test.go
- libkbfs/key_bundle_v2.go
- libkbfs/key_bundle_v2_test.go
- libkbfs/key_bundle_v3.go
- libkbfs/md_id_journal.go
- libkbfs/md_id_journal_test.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
Fix up MD journal tests to reveal the bug where wkbNew and
rkbNew aren't preserved.
Also remove dependency on Config from BareRootMetadata
and RootMetadata.
Also add unit test for ToTLFWriterKeyBundleV3 and
strengthen its checks.
> [KBFS-1806] Keep track of wkbNew and rkbNew in MD ID journal

- kbfscodec/codec.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/mdserver_tlf_storage.go
In particular, have it time only the actual put
operation. Also test with varying MD counts, and
have it not reuse the same journal across runs.
Add SerializeToFileIfNotExist helper function
and use it appropriately (although without consistent
speedup).
> Improve MD journal benchmark

- kbfscrypto/crypto_key_types.go
- kbfshash/hash.go
- kbfstool/md_dump.go
- kbfstool/md_force_qr.go
- kbfstool/md_reset.go
- libkbfs/bare_root_metadata.go
- libkbfs/block_id.go
- libkbfs/block_ops_test.go
- libkbfs/bserver_remote.go
- libkbfs/bserver_remote_test.go
- libkbfs/crypto_client_test.go
- libkbfs/crypto_common.go
- libkbfs/crypto_common_test.go
- libkbfs/data_types.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/key_bundle_test.go
- libkbfs/keybase_service_base.go
- libkbfs/root_metadata.go
- tlf/id.go
Instead of manually writing prints, use
the spew library, which we already vendor
anyway, to add various Dump* functions.
Add String() methods to some types, and
clean up some existing String() methods.
Make distinction between publicByte32Container
and privateByte32Container, to avoid
inadvertently dumping/logging sensitive
data.
Make things implement
encoding.Text{M,Unm}arshaler instead of
json.{M,Unm}arshaller.
Also annotate dump with user names and
device names.
> Rework md dump command

- libkbfs/test_dynamodb_runner.go
Because ioutil.Stat returns a wrapped error.
> test_dynamodb_runner: use the ioutil wrapped version of IsNotExist

- libkbfs/mdserver_disk.go
- libkbfs/mdserver_memory.go
GetExtraBundles was RLocking or Locking while
already RLocked, which only hangs intermittently.
This was actually present for a while, since
4c7a78 (Oct. 21), but only presented since we
started testing with MDv3.
Also make isShutdown delegate to
checkShutdownLocked.
> Fix intermittent hang in MDServerDisk

- libkbfs/key_manager_test.go
- libkbfs/md_ops.go
Also fix a possible goroutine leak in key_manager_test.go.
> Make MDOps use errgroup.WithContext

- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops.go
@strib @songgao r?
It seems like the following can happen in the KBFS client when calling `GetTLFCryptKeys`. 
1.) We run`GetTLFCryptKeys` on a TLF with `TLFIdentifyBehavior_CHAT_GUI` on a TLF with a user with a failing tracker statement. In this case, KBFS will seemingly store the folder_branch_ops thing with`identifyDone` set to false.
2.) When we call `GetTLFCryptKeys` again, but this time with `TLFIdentifyBehavior_CHAT_CLI` on the same TLF, then even with the failing tracker statement, we are able to get crypt keys since it will skip the identify after hitting this folder_branch_ops cache.
My change makes it so that if you hit this cache, but `identifyDone` is false we run an identify.
Let me know if this works, I don't know this code very well so I it could be this is the wrong …
> if TLF has not been identified, and we are in AlwaysRunIdentify mode

- libkbfs/bare_root_metadata_test.go
- libkbfs/data_types.go
- libkbfs/test_stallers.go
- test/benchmark_test.go
- test/dsl_test.go
- test/engine.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
- test/run_dokan_test.go
- test/run_fuse_test.go
- test/run_kbfs_test.go
Also run tests over MetadataVer in parallel.
Also clean up Engine interface a bit, and
rename testing.TB vars to tb instead of t.
Fix race with stallers.
> Parametrize DSL tests over MetadataVer

- libkbfs/bare_root_metadata_test.go
- libkbfs/config_local.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_manager.go
- libkbfs/key_manager_test.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops_test.go
- libkbfs/rekey_queue.go
- libkbfs/root_metadata_test.go
- libkbfs/test_common.go
- libkbfs/tlf_journal_test.go
- libkbfs/util_test.go
The background update task always fetches the head
whenever it receives an update, which triggers a rekey
that races with the rekey-with-prompt timer. Fix this
by, instead of waiting for the first rekey and checking
whether the prompt flag is set, waiting for a rekey
with the prompt flag set. At worst, this'll cause the
test to time out.
Set RekeyWithPromptWaitTime to the individual
test timeout for tests.
Clean up various logs.
Fix bug with runTestsWithMetadataVers.
Also run all MDv3 tests in parallel.
> [KBFS-1641] Fix KeyManager test flakes

- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops.go
Otherwise, if chat is the first thing to access a TLF, it could get a `MDWriteNeededInRequest` error (which indicates the request should be retried with the writer lock taken).
Issue: KBFS-1822
> kbfs_ops: retry md reads with identify if this could be 1st access

- test/dsl_test.go
> Make DSL tests not run per-version tests in parallel

- libkbfs/folder_block_manager.go
- libkbfs/folder_block_manager_test.go
With the defaults, this test can take more than 12 seconds on a slow
OSX machine when run with a disk-based bserver.
Issue: KBFS-1774
> folder_block_manager_test: reduce incremental test size

- libkbfs/init.go
- libkbfs/keybase_daemon.go
This was breaking existing workflows.
Also add a missing error check.
> Make default -localuser empty for devel mode

- libkbfs/identify_util.go
As it is now, if you call `getTlfBreakAndClose` more than once you don't get any break results back on the subsequent calls. The `GetTLFCryptKeys` codepath right now calls this guy twice, the second of which fails to load any breaks into the result. With this change, that behavior is fixed, and we check to see if the `tlfBreaks` field has any data before returning an empty result.
cc @maxtaco @chrisnojima
> return TLF breaks even if the channel is already closed

- libkbfs/tlf_journal.go
Try to achieve some fairness with other lock contenders, such as FS
operations.
> tlf_journal: explicit Gosched() during tight lock-unlock loop

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/journal_block_server.go
- libkbfs/tlf_journal.go
This allows us to serve blocks if they are on disk in the journal, even after they have been flushed to the server, mainly as an optimization during conflict resolution.
Issue: KBFS-1777
> tlf_journal: get blocks without specifying a context

- libkbfs/folder_branch_ops.go
- libkbfs/node.go
It's a pain to look up line numbers to figure out
which function a "Done" log corresponds to.
> Print function name and args in FBO on exit

- libkbfs/folder_branch_ops.go
Resolutions no longer skip the journal, so they shouldn't count as the
latest merged revision anymore.
Issue: KBFS-1838
> folder_branch_ops: don't let resolutions update latestMerged

- libkbfs/conflict_resolver.go
- libkbfs/kbfs_cr_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- test/journal_test.go
When doing conflict resolution on an unmerged branch that already contains resolutionOps (e.g., because of local squashes), CR was incorrectly unreferencing live blocks for files that were written/synced within a local squash branch.  This is because `alreadyUpdated` is true, since earlier in `syncBlocks`, these most-recent file blocks are explicitly added into `updates`. To fix, we make sure we don't reference anything that is the most recent block for a chain in the unmerged branch.
A second problem is that `alreadyUpdated` was using update.Unref, but really what we care about is when the original block for the chain has been updated (since update chains are collapsed back to the origin earlier in the function).
To test this reliably, this PR also fixes the `tlfJournal` so that …
> cr: fix handling of previous unmerged resolutionOps

- libkbfs/file_data.go
- libkbfs/kbfs_ops_concur_test.go
getFileBlockAtOffset was always returning wasDirty=false for files
with only one block.  This messes up the dirty bytes calculation in
some scenarios, i.e. when the same section of the block is overwritten
multiple times before the sync happens.
Issue: KBFS-1846
> file_data: return correct dirty status for direct blocks

- kbfsfuse/kbfsfuse.sh
It's almost impossible to figure out chat failures without having debug mode on the service.
cc @patrickxb
> put the service in debug mode

- libkbfs/folder_block_ops.go
- libkbfs/kbfs_ops_concur_test.go
The unrefCache state might get updated while the MD is still being processed, leading to races.
Issue: KBFS-1852
> folder_block_ops: don't share a syncOp between unrefCache and MD

- libkbfs/bserver_disk.go
- libkbfs/bserver_memory.go
- libkbfs/key_server_local.go
- libkbfs/keybase_daemon_local.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_memory.go
- libkbfs/tlf_journal.go
- libkbfs/util.go
Specifically this will help the `tlfJournal` flush loop exit faster
when its context has been canceled.  But it is also the right thing to
do for any test I think, to more accurately reflect the RPC-based
server implementations.
Issue: KBFS-1859
> libkbfs: make test servers more context aware

- libkbfs/bcache.go
- libkbfs/block_ops.go
- libkbfs/block_ops_test.go
- libkbfs/block_retrieval_queue.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/block_retrieval_worker.go
- libkbfs/folder_block_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/prefetcher.go
- libkbfs/prefetcher_test.go
> [KBFS-1842] Initial Fixes

- kbfstool/md_dump.go
- libkbfs/bare_root_metadata_test.go
- libkbfs/bare_root_metadata_test_util.go
- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v2_test.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/bare_root_metadata_v3_test.go
- libkbfs/crypto_common.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/key_bundle.go
- libkbfs/key_bundle_cache_test.go
- libkbfs/key_bundle_v2.go
- libkbfs/key_bundle_v2_test.go
- libkbfs/key_bundle_v3.go
- libkbfs/key_manager.go
- libkbfs/key_manager_test.go
- libkbfs/md_journal_test.go
- libkbfs/md_ops_test.go
- libkbfs/md_util.go
- libkbfs/mdserver_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
...where it causes a new key generation to
always happen.
Also refactor rekeying-related BareRootMetadata
functions.
In particular, replace GetDeviceKIDs
and HasKeyForUser, GetUserDeviceKeyInfoMaps,
and AreKeyGenerationsEqual with
GetUserDevicePublicKeys.
Remove now-unneeded code in key_bundles.go.
Make AddKeyGeneration add and update
the new key generation in one go, and remove
addKeyGenerationForTest.
Change UpdateKeyGeneration to UpdateKeyBundles.
Make PromoteReader take a map of readers, and
rename it to PromoteReaders.
Also add various sanity checks in BareRootMetadataV{2,3}
and the rekeying code.
Also change BareRootMetadata.GetUnresolvedParticipants
to return a single array.
> [KBFS-1744] Fix reader promotion bug

- libkbfs/bsplitter_simple.go
- libkbfs/bsplitter_simple_test.go
- libkbfs/file_data.go
- libkbfs/file_data_test.go
- libkbfs/folder_block_ops.go
- libkbfs/init.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_journal_test.go
- libkbfs/mocks_test.go
- libkbfs/test_common.go
- libkbfs/tlf_journal_test.go
[Sorry about the size of this PR, I can't think of a good way to shrink it and still keep the tests passing.  If you have suggestions, let me know.]
Note that this doesn't yet support syncing those multiple levels of indirection (or CR), so it is turned off for everything but the new fileData tests right now.
We view the data file as a tree of indirect blocks that ultimately point to a set of direct leaf blocks at the bottom level.  Whenever the existing leaf blocks can't accomodate a new write, we append a leaf block.  If the indirect parent can't accomodate a new block (as decided by the BlockSplitter), we add a new indirect block at that level, etc, all the way up to the root.  If the root can't handle a new block, we add a new level of indirection.
If we are writing into a "hole" in …
> file_data: support writes and truncates for >1 indirection levels

- libfuse/dir.go
- libfuse/file.go
- libfuse/folderlist.go
- libfuse/fs.go
- libfuse/mounter_osx.go
This fixes those damaged/corrupted error from Finder on macOS
> Finder likes to use UID 0 so let\'s let it?

- kbfsblock/context.go
- kbfssync/semaphore.go
- kbfssync/semaphore_test.go
- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/config_local.go
- libkbfs/crypto_client_test.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
For now, hard-code it to 10 GB, and use a simple
semaphore to enforce it.
Add a simple Semaphore type to kbfssync.
Plumb up removedBytes count from blockJournal.
Add a diskLimiter interface and use it in tlfJournal.
> [KBFS-1522] Add a basic journal disk limit

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
That just means there's nothing to be done.
Issue: KBFS-1865
> folder_block_ops: don't fail fast-forwarding if there are 0 nodes

- libkbfs/bcache.go
- libkbfs/bcache_test.go
- libkbfs/block_retrieval_queue.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/errors.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/mocks_test.go
- libkbfs/prefetcher.go
- libkbfs/prefetcher_test.go
In this PR:
* The Prefetcher correctly caches the prefetched state of a block.
* `Put`s to the block cache don't trigger prefetches unless they come through via the `Get` path, and they didn't already trigger prefetches before.
* `UpdatePointers` prefetches now only happen when a change comes from the server rather than locally.
> [KBFS-1842] More fixes

- kbfssync/semaphore.go
- kbfssync/semaphore_test.go
The spawned goroutine could run before the release
in the main goroutine happens, leading to a race on
the count field of acquireCall. Fix this by doing the
release first before spawning the goroutine.
This only applies for TestCancel, since all other tests
have a successful acquire, which will then have a
count of 0.
> Fix race in TestCancel in semaphore_test.go

- libkbfs/folder_branch_ops.go
If we learn about something newer than the base of our journal, we
rightly ignore the updates until CR can resolve the issue.  However,
if we don't set our notion of the latest merged revision, we'll keep
re-registering for the same revision over and over, leading to
ugly throttle messages.
Issue: KBFS-1888
> folder_branch_ops: set latest merged head when journal conflicts

- libkbfs/folder_block_manager.go
It's possible that a user can be throttled so much that they can't check with the MD server whether a given revision has been written to the server or not within a reasonable amount of time.  Before, we were just going ahead and assuming the revision never made it to the server, and deleting its blocks.  However, if the revision really did make it to the server, we could be deleting live blocks, and hosing the TLF!
The reason we gave up after 20 seconds before was because we were using `getSingleMD`, which returns an error if no revision is found. However, in this case, knowing that the revision is not found is important information, and allows us to proceed with deleting the blocks.
Instead, switch to using getMDRange, and if there's an error, continue checking the server after a …
> folder_block_manager: never give up trying to check revs to delete

- libkbfs/bcache.go
- libkbfs/block_retrieval_queue.go
- libkbfs/block_util.go
- libkbfs/folder_block_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
This fixes a few things needed to make #663 pass tests.
In block_util, delete cached block when deleting known pointer.
Otherwise dedup code might still try to retrieve the block from the
cache, and the subsequent PutWithPrefetch with re-add the hash to
bcache.ids.
And in bcache, return lifetime from GetWithPrefetch. So the subsequent PutWithPrefetch can use the same lifetime (in the case of PermanentEntry blocks).
> bcache: use same lifetime for PutWithPrefetch, and delete transient block along with pointer

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
`onMDFlush` iterated the full savedUntilMDFlush journal and removed
all entries.  That made sense when we only saved blocks during CR, and
one CR flush cleared the entire journal.  However, now we always save
all blocks until the next MD flush, even without CR, and so when we
flushed one MD and there were still more left in the MD journal, we'd
wipe out the saved blocks for the subsequent MD revisions in the
journal.  Then, on the next flush, `saveBlocksUntilNextMDFlush` would
just repopulate the save journal again with a bunch of entries that
had just been removed, wasting a lot of time.
So this PR does a few things to fix that up:
1. Only remove blocks from the save journal that come before the
marker that signifies the MD revision that was just flushed.
2. When a local squash happens, …
> block_journal: don't remove unflushed blocks from the save journal

- libkbfs/bsplitter_simple.go
- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
- libkbfs/init.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/state_checker.go
- libkbfs/test_common.go
This PR completes support for syncing files with more than one level of indirection, including during conflict resolution and state checking.  It turns on multiple levels of indirection in all tests, but not yet in production (I still want to bump the version number and add the IsDirect flag).
The bulk of the work here adds support for syncing multiple levels of indirection to `fileData`.  There are also some `ConflictResolver` changes to do its file operations through `folderBlockOps`, rather than `fileData`, so that the flow can take `blockLock`.
Issue: KBFS-35
> libkbfs: >1 levels of indirection for file syncing and CR

- libkbfs/block_ops_test.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/block_types.go
- libkbfs/block_types_test.go
- libkbfs/config_local.go
- libkbfs/config_mock_test.go
- libkbfs/data_types.go
- libkbfs/errors.go
- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/init.go
- libkbfs/interfaces.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/reporter_kbpki.go
This PR enables writing files that are bigger than 2 GB, and those which have multiple levels of indirection.
It introduces a new data version for files with multiple levels of indirection, so that older clients won't attempt to read or write them (and will instead see a popup message about needing to upgrade their clients).
It also adds the `BlockPointer.IsDirect` flag, which states definitively whether the block being pointed to is a direct (leaf) block.  If the flag is false, code shouldn't assume the block is indirect (for backwards compatibility reasons with files written by older clients).  This PR uses that flag to not only set the data version correctly, but also to speed up scenarios where all the indirect `BlockInfo`s need to be fetched (e.g., when unlinking a file).
Issue: …
> libkbfs: add `IsDirect` flag, data version for big files, and enable big file support

- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
And re-enable flaky test that was timing out.
The size of block pointers increased since I added a direct type to them, and that caused some tests to exceed the default `BlockSplitterSimple.blockChangeEmbedMaxSize` when they had `BlockSplitterSimple.maxSize = 5`.  That caused a HUGE explosion in the number of blocks being written by the test.
So instead bump up the embed max size, so we don't have to waste test time on unembedded block change blocks.
> libkbfs: don't let block changes blocks explode in test

- libkbfs/folder_block_ops.go
Forgot to do this as part of KBFS-1536.
> folder_block_ops: collapse WriteRange in the syncOp

- libkbfs/folder_branch_ops.go
We don't want to use the KBFS cache on identifies in chat, the hope is the caching in the service will be able to handle the influx of calls. The particular symptom is that if an identify breaks and the service knows it (probably from the background identifier), then we want the chat system to be consistent with that knowledge. 
cc @maxtaco
> GetTLFCryptKeys: don't early out in identifyOnce for chat CORE-4465

- libkbfs/kbfs_cr_test.go
Started fixing it to print errors with %+v, then
figured I may as well use require instead.
Also fix a tmpdir leak in one test.
> Switch kbfs_cr_test.go to use assert/require

- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v2_test.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/bare_root_metadata_v3_test.go
- libkbfs/key_bundle.go
- libkbfs/key_bundle_v2.go
- libkbfs/key_bundle_v2_test.go
- libkbfs/key_bundle_v3.go
- libkbfs/key_bundle_v3_test.go
Only delete a user during rekey if the user
has been deleted from the handle.
Also add regression tests.
> [KBFS-1898] Preserve user when their last key is revoked

- libkbfs/errors.go
Need these on service to tell electron to show a screen to the user on chats that need rekeying. Created [copies in libkb](https://github.com/keybase/client/pull/5589/files#diff-c652ac01349bc77f84f730408c8d9bafR1723). Which is kind of nasty, but maybe the best option?
> Export rekey errors

- libkbfs/folder_branch_ops.go
Older clients might leave unknown fields from old md root pointers set with values from new clients, and thus the full root pointer would not match whatever was in the op update.
---
Note that there's a larger issue here about whether the client should be doing this: https://github.com/keybase/kbfs/blob/c09ee0ca9b0cac9ec84a8295a32a850751d79d23/libkbfs/folder_branch_ops.go#L2008
The problem is that this leaves unknown codec fields in the `DirEntry` set to what they were written to by the previous writer.  `BlockPointer` doesn't support unknown codec fields, but it's embedded in `DirEntry`. So the unknown `DirectType` field got passed along to the md root pointer by an old client, which didn't match the `BlockPointer` added to the op update.  But I don't know if there's a better way to …
> folder_branch_ops: compare md root pointer as block ID

- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/mocks_test.go
- libkbfs/node_cache.go
- libkbfs/node_cache_test.go
Remove operations of multi-block files can have many unref pointers,
with no indication of which one is the "top" block for the file.
Previously, this code looped through each of them and called
`NodeCache.Unlink` with the same `path` instance each time, just
changing the tail pointer for each call.  However, once one of those
succeeds, the other iterations of the loop will be modifying the same
path that's already been cached in the NodeCache.  This means that if
the user has an open file handle to the file, the next time they read
from it, they may try to read from the wrong block.
Instead, we should break the loop as soon as the node cache takes a
reference to the path, so we don't modify it again.  (We could also
make a new childPath for each iteration of the loop, but that seems …
> folder_branch_ops: on unlink, don't user same path for each ptr

- libkbfs/folder_block_ops.go
fileData.undupChildrenInCopy makes and modifies block copies, so the
write lock is required.
Found while writing a regression test for KBFS-1901.
(I only need one review for this, just putting both of you on as an FYI in case both are interested.)
> folder_block_ops: UndupChildrenInCopy needs lock for writing

- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/key_manager_test.go
- libkbfs/keybase_service_util.go
- libkbfs/mocks_test.go
`GetTLFCryptKeys` could fail with a weird error about a directory being uninitialized, when the caller is hoping for a nicer Need*Rekey error.  This happened in `SetInitialHeadFromServer`.  Instead, we can let that function cache the unreadable head, and let `GetTLFCryptKeys` encounter the rekey error later on.
Also, make sure we clear out cached heads on logout, or otherwise a newly logged in user might get the same error from a cached, unreadable head as the old user.
Issue: KBFS-1832
> folder_branch_ops: allow unreadable heads, and clear heads on logout

- libkbfs/cr_chains.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/ops.go
- libkbfs/unflushed_path_cache.go
In almost all cases (with the exception being renames), ops already have paths attached to them, and we don't need to run the expensive path population algorithm when they do.
This is just a simple optimization, but it saves about 9% of the foreground time when copying the go source code into KBFS when journaling is enabled and the journal status has already been viewed once.
Issue: KBFS-1910
> unflushed_path_cache: don't populate paths if we already know them

- libkbfs/cr_chains.go
- libkbfs/folder_branch_ops.go
- test/journal_test.go
The journal can't easily re-embed block changes (since it involves reading and decrypting blocks from disk), so we need to look in cached changes too.
Included is a regression test, but it won't actually test the regression until KBFS-1912 is fixed.  I'll be doing that in a separate PR.
Issue: KBFS-1901
> cr_chains: used cached changes when getting ops, if needed

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/folder_branch_ops.go
- test/cr_multi_blocks_test.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
- test/journal_test.go
It turns out the DSL tests had a problem where the block sizes weren't being properly set for all users after the first one.  Once I fixed it, there was some other fallout that needed fixing:
* When syncOps were collapsed together during CR, the unref pointers from the now-deleted sync ops did not make it to the final resolution.  This would leak quota for the user, and leave defunct blocks unarchived.
* When unflushed blocks were deleted from the journal after CR, we were still leaving them in the resulting `resolutionOp`.  This is harmless in practice except for making the `resolutionOp` larger than necessary.  But in tests, it confused the `StateChecker`.
* Fixing the test issue caused the libkbfs DSL tests to take 3x as long as before, due to all the new blocks.  This was mostly …
> test: set block sizes for all users, and fix resulting bugs

- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mocks_test.go
If we don't, then the next time the head is set we'll have two update goroutines, and will end up panicking in MDServerRemote.
Issue: KBFS-1918
> folder_branch_ops: cancel registration when clearing folder MD

- libkbfs/file_data.go
- libkbfs/file_data_test.go
We were not properly setting the file size when writing to an offset
past the end of the last block of a file.  For example, say we had
2-byte blocks, and the existing file was 5 bytes long.  If we then
wrote 6 bytes starting at offset 10, we would create a new block at
off=10 and count for its new data, and in some cases we'd count for
the new byte that extends the block from 5 to 6, but we wouldn't count
the gap between 6 and 10, and so the file would be reported as size
12, rather than size 16.
This is a general problem, but came up specifically when a write
slipped in between a sync updating a file's path, and the sync
executing the deferred writes for that file.  In that case, even
though it was a contiguous write, it looked like the offset was bigger
than the file since we hadn't …
> file_data: fix file size when writing past the end of last block

- libkbfs/block_types.go
A list of IPtrs in an indirect block can be empty if the file has been
truncated to 0 bytes, since we don't currently remove the level of
indirection in that case.
Issue: KBFS-1924
> block_types: handle data version for an empty iptrs list

- libkbfs/tlf_journal.go
It's possible for the same block to be put multiple times, which
doesn't increase the stored bytes count.  This happens in particular
when a Sync fails because the disk acquire times out, and then the
Sync gets retried.
Issue: KBFS-1926
> tlf_journal: relax stored bytes panic when block already exists

- libkbfs/file_data.go
- libkbfs/file_data_test.go
Since we didn't have multiple levels of indirection before introducing
the direct type.  Without this, a new client removing an old file
needs to download all child direct data blocks, which can be slow.
Also fix temporary block pointers and the fileData test to set direct
types on block pointers, since otherwise we'd violate the above
assumption about multiple levels of indirection.
Issue: KBFS-1924
> file_data: treat unknown children as direct blocks

- libdokan/folderlist.go
- libfuse/folderlist.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/mocks_test.go
On a logout, we now reset the FBO TLF heads.  After the user re-logs
in, if FUSE still holds a reference to some node within the TLF, and
tries a read operation on it, it will fail with a "This request needs
MD write access, but doesn't have it.", because read operations aren't
normally allowed to set the head.
After a re-login, we want to invalidate any nodes that are still being
held, in the same way we do for fast-forwarding, and set the head, so
that the read operations don't need to.
Issue: KBFS-1923
> folderlist: force a fast forward on a new user login

- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
To indicate that the caller needs to initialize the TLF before using
it.  Other get calls don't need this property, since they are internal
to folderBranchOps, and it's assumed the TLF has already been created
by an outsider if they're called.
Issue: KBFS-1929
> folder_branch_ops: the getMD first access call can return empty MD

- libkbfs/block_ops.go
- libkbfs/block_retrieval_queue.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/block_retrieval_worker.go
- libkbfs/block_retrieval_worker_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/prefetcher_test.go
Let's get this refactor in no matter what, because it's better separation of concerns, and will make it easier to add prefetch workers if we still want to.
> [KBFS-1895] Refactor before Prefetching Workers

- vendor/github.com/keybase/client/go/libkb/errors.go
- vendor/github.com/keybase/client/go/libkb/globals.go
- vendor/github.com/keybase/client/go/libkb/identify_outcome.go
- vendor/github.com/keybase/client/go/libkb/interfaces.go
- vendor/github.com/keybase/client/go/libkb/locktab.go
- vendor/github.com/keybase/client/go/libkb/notify_router.go
- vendor/github.com/keybase/client/go/libkb/resolve.go
- vendor/github.com/keybase/client/go/libkb/rpc_exim.go
- vendor/github.com/keybase/client/go/libkb/util.go
- vendor/github.com/keybase/client/go/libkb/vdebug.go
- vendor/github.com/keybase/client/go/protocol/chat1/common.go
- vendor/github.com/keybase/client/go/protocol/chat1/extras.go
- vendor/github.com/keybase/client/go/protocol/chat1/local.go
- vendor/github.com/keybase/client/go/protocol/chat1/notify.go
- vendor/vendor.json
This brings in changes in how IdentifySummaryErrors are
exported/imported, without which we'll garble them in transit.
r? @strib 
@cjb @maxtaco I should've merged this last night, and right now
the errors that roundtrip through kbfs will get garbled. We might
need to restart the build after this goes in?
> govendor updates from client

- libdokan/folderlist.go
- libfuse/folderlist.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
If there's a local journal for it, for example.
As an added measure, don't fast-forward a folder if it wasn't ever
cleared out in the first place.
Also, this reverts the previous revert of fast-forward forcing.  New code for review is in the latest two commits.
Issue: KBFS-1923
> folder_branch_ops: some tlfs can have an FBO without a head

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
Recently we added an optimization in `ignoreBlocksAndMDRevMarkers`
where we'd stop iterating through the journal once we found all the
blocks we were looking for.  Unfortunately we missed an edge case: say
we're squashing revisions 5-15 together into one new revision, 5.  If,
while resolving the squash, we aren't ignoring any blocks from the
original revision 5, we will exit the loop early and never set the
`Ignored` flag on the original md marker entry for revision 5.  When
the flusher sees that unignored marker, it will think it's done with
the blocks for revision 5 early, and put the MD before all the blocks
have been flushed!  At that point, if the client crashes, or if
another device tries to read the folder, they could fail trying to
read a non-existent block.
Instead, don't exit …
> block_journal: be sure to ignore all relevant MD markers

- libkbfs/backpressure_disk_limiter.go
- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/journal_server.go
- libkbfs/semaphore_disk_limiter.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
We forget to release bytes if a duplicate put happens.
> Fix byte count leak on duplicate puts

- ioutil/ioutil_wrap.go
- ioutil/os_wrap.go
- libkbfs/disk_journal.go
Otherwise a crash at the wrong moment can lead to an empty EARLIEST or
LATEST file.
Ideally this would be done using an atomic rename, instead of an
overwrite, but there seems to be a big (~25%) performance penalty for
that.
Issue: KBFS-1887
> disk_journal: overwrite ordinal files without truncating them

- libkbfs/folder_block_ops.go
In case we're dedupping an old BlockPointer.
This can cause a panic on an indirect block where all child blocks are
old dedupped pointers, so none had their DirectTypes set correctly.
Issue: KBFS-1950
> folder_block_ops: set dedup DirectType correctly

- libkbfs/file_data.go
When making a new level of indirection, we were incorrectly setting
the DirectType of the first iptr of the new level -- it should have
the same type as the original top block, before the level was created.
In practice, this didn't cause any issues, because when the DirectType
should have been DirectBlock, it's always dirtied and the block type
recalculated anyway.  So this is just a cleanup to make things more
clear.
Issue: KBFS-1950
> file_data: set direct type correctly on new level of indirection

- libkbfs/backpressure_disk_limiter.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/config_local.go
Set the default to 25%.
Also flesh out disk limiter tests.
> [KBFS-1871] Limit journal disk usage to fraction of free space

- libkbfs/folder_block_manager.go
- libkbfs/folder_block_manager_test.go
- libkbfs/folder_branch_ops.go
This indicates to other devices (and future restarts of this device)
that there's no need to scan that MD range again looking for blocks to
delete.  This can happen for example when there's a range of gcOps
already at the tail of the TLF's history.
Also, we can avoid QR completely if the head consists of a gcOp that
deleted blocks all the way up to the head's parent revision.
Issue: KBFS-1922
> folder_block_manager: push gcOps even when no blocks are deleted

- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
Otherwise the caller could use the nil ID, e.g. in branch conversion.
Issue: KBFS-1955
> md_journal: putMD should return the id even on a dup put

- libkbfs/backpressure_disk_limiter.go
This will make it easier to figure out the state of the system when
backpressure is being applied.
> backpressure_disk_limiter: improve logging

- libkbfs/folder_block_manager.go
Chris saw some random tracker popups that were due to background QR trying to write MD to a finalized TLF.  Attack this in two ways:
* Suppress popups for QR -- right now piggyback on the KBFS_REKEY semantics as a quick fix to avoid changing the protocol.
* If a TLF is finalized, stop QR altogether.
Issue: KBFS-1962
cc: @maxtaco 
[Adding @songgao as a reviewer, since both @akalin-keybase and @jzila are out today.)
> folder_block_manager: suppress identifies and ignore finalized MDs

- kbfsblock/context.go
- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v2_test.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/block_disk_store_test.go
- libkbfs/block_journal_test.go
- libkbfs/block_ops_test.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/block_types_test.go
- libkbfs/bserver_remote.go
- libkbfs/bserver_remote_test.go
- libkbfs/conflict_resolver.go
- libkbfs/file_data.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_server_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/state_checker.go
- libkbfs/tlf_journal_test.go
Note this won't be merged until keybase/kbfs-server#217 is merged and deployed in production.
----
This PR differentiates data blocks and MD blocks, so that we can tell the bserver which is which.  The bserver will no longer charge for MD blocks.  I opted for what I considered the cleanest approach, which is just to store the type in the `kbfsblock.Context` (rather than passing it around explicitly between all the functions that would need it).
To avoid losing information, I also decided to store the bytes associated with the MD in the MD update itself, to aid with debugging or introspection in the future.
Suggested review order:
* `kbfsblock`
* `libkbfs/bserver_remote.go`
* `folder_block_ops.go`, `folder_branch_ops.go`, and `state_checker.go`.
* Everything else is basically boiler plate …
> libkbfs: store block type in context, and track MD bytes separately

- libkbfs/bare_root_metadata_v3.go
As long as the MDRefBytes fields are the same, it probably means that
an old client just copied the value as an unknown field from an MD
written by a new client.
> bare_root_metadata_v3: don't error if MDDiskUsage looks bad

- libkbfs/folder_branch_ops.go
This fixes a race where, if FBO learns about the new branch when doing
a put (rather than through a onTLFBranchChange callback from the
journal), it wouldn't reset the input state in CR.  This causes CR to
ignore the any inputs with a revision number less than the last one it
processed, and it will cease to perform squashing until the revision
number gets back to where it was before.  But, if there are no new
writes, this will never happen, and journal flushing will remain
paused.
Instead, just clear that input state on every branch change.
Issue: KBFS-1969
> folder_branch_ops: always clear the CR branch on a branch change

- libkbfs/folder_branch_ops.go
- libkbfs/tlf_journal.go
Continuous user writes can prevent CR for completing.  CR does lock the `mdWriterLock` on its second attempt to squash a branch, but by then dozens or hundreds more writes could have completed, leading to very large branches which take longer to flush.
Instead, this commit just delays writes until CR completes, to help the common case where the user is issuing writes one-at-a-time.  This limits the number of revisions involved in a squash branch to whatever the `tlfJournal` decides it should be.  In performance testing, this seems to save about 10-15% in foreground time on the Go source benchmark, presumably due to smaller squashes being faster.
Also a new log message to help debugging squash sizes.
Issue: KBFS-1927
> folder_branch_ops: wait for CR if on a pending squash branch

- libkbfs/config_local.go
- libkbfs/md_journal.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- test/journal_test.go
If each revision has lots of big blocks, we want to limit the size of
a squash by bytes as well, not just the number of revisions.
This commit does that by tracking an estimate of the number of bytes
that will be in the squash (though it doesn't account for blocks that
will be deleted and not flushed as part of the squash).  If there is
at least one revision with more than a threshold of bytes associated
with it (currently set to 25MB, or about 2 parallel rounds of flushing
max-sized blocks), it will convert it to a squash branch.
If there's only one revision with that many bytes, it can directly be
turned into a squash branch, without the need for CR at all.
Issue: KBFS-1927
> tlf_journal: limit squash size by estimate of the unsquashed bytes

- libkbfs/mdserver_remote.go
If the device suspends for a while and comes back (without any new
keybase login events), the old mserver connection will disconnect
(resetting the background check-rekey timer to 60min) and it will
immediately try to reconnect.  But that reconnect won't call
`getFoldersForRekey` when it starts up, because `md.isAuthenticated`
is still `true`, even though we aren't really authenticated anymore.
This means that any rekey requests that came into the server while the
device was suspended won't get processed by the device for 60 minutes.
Instead, set `md.isAuthenticated` to false on a disconnect, so that
the reconnect will trigger a `getFoldersForRekey()` call.
Issue: keybase/client#5972
> mdserver_remote: reset auth status on disconnect

- libkbfs/backpressure_disk_limiter.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/config_local.go
- libkbfs/disk_limits_test.go
- libkbfs/disk_limits_unix.go
- libkbfs/disk_limits_windows.go
- libkbfs/semaphore_disk_limiter.go
- libkbfs/semaphore_disk_limiter_test.go
- libkbfs/tlf_journal_test.go
Basically, do what we're doing for bytes, but also with file counts.
Get available file count for Linux from Statfs, but not for Windows
(since NTFS has effectively an unlimited file count).
Set a hard limit of 1.5 million files (based on KBFS-1749).
> [KBFS-1870] Add backpressure based on file count

- libkbfs/bserver_memory.go
- libkbfs/folder_block_ops.go
Otherwise the context could look empty.
Issue: KBFS-1971
> folder_block_ops: fill in UID whenever a BlockPointer is made

- libkbfs/root_metadata.go
Otherwise clients reject it, since the MD usage doesn't match up, and
could try to re-apply operations in it to the node cache.
Issue: KBFS-1976
> root_metadata: set the writer MD copied bit for finalized MDs

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/path.go
Otherwise the user can get flooded with notifications during CR (and
also potentially when reading big unembedded block changes).
Issue: KBFS-1972
> libkbfs: don't send read/write notifications for invalid paths

- libkbfs/block_journal.go
- libkbfs/interfaces.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
Currently, we flush blocks in batches of 25, and only then check for squashability.   An arbitrary number of MD revisions can build up during that time, especially if the flushing is slow.  When squashing does happen, the result will be huge, and require flushing even MORE blocks before the squashed MD is finally pushed, which is the point at which other clients can see the revision.
Not only does this delay other clients from seeing your changes, but it also makes them more likely to start QR and needlessly start conflicting with the writing device.  Also, since we don't delete blocks until the MD is flushed, it means the journal can stay large for longer, leading to unnecessary backpressure and semaphore blocking, which can lead to user-visible errors in the form of timeouts.
Instead, …
> check for branch conversion while flushing blocks

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
This replaces the savedUntilMDFlush block journal.  It's only accessed
during flushing, so it doesn't need to block foreground journal
writes.
Issue: KBFS-1839
> block_journal: use a deferredGC journal

- libfuse/profilelist.go
- libfuse/special_read_file.go
I tried to make the profile data streamable,
but ran into problems. Turns out the current
way has a nice effect of being immune to
OSXFUSE timeouts, anyway. Document all that.
Also remove unneeded type assertions.
> Add comments to timedProfileFile

- libkbfs/crypto_common.go
- libkbfs/crypto_common_test.go
This should save a chunk of CPU time.
Also write to a []byte directly during padding/unpadding
instead of using a bytes.Buffer.
Also add benchmark for block encryption.
> [KBFS-1977] Pad blocks with zeros instead of random data

- libkbfs/block_getter.go
- libkbfs/block_ops.go
- libkbfs/block_util.go
- libkbfs/folder_block_ops.go
- libkbfs/journal_block_server.go
Otherwise, the block could get stuck behind a full queue of prefetching requests, for no reason.
@jzila: it strikes me that the disk cache will have exactly the same problem -- might want to move that logic out of `BlockServerRemote.Get()` and put it in `BlockOps.Get()` instead.
Issue: KBFS-1981
> block_ops: if a block is in the local journal, fetch it directly

- libkbfs/config_local.go
This increases the time for another device to start QRing a TLF, after
one device writes to it.  The problem is that someone could write to a
journal, and then go offline for a while with items still unflushed.
If another device runs QR in the meantime, it will cause an
unnecessary conflict.
(Obviously CR still needs to work well in that case, in case the other
device does a _real_ write instead of just a QR write, but there's no
need to impose that extra burden if we don't have to.)
As long as the writing device is still online, it will be the one
doing QR on the TLF.
Issue: KBFS-1986
> config_local: increase the min head age for QR on other devices

- libkbfs/conflict_resolver.go
- test/journal_test.go
If we unref the original, then a subsequent CR over the resulting `resolutionOp` will think the chain has been deleted, and the ops related to that chain won't get included in the resolution.
Issue: KBFS-1979
> conflict_resolver: don't unref the original half of a resOp update

- libfuse/profilelist.go
Otherwise, a new profile will run into an error.
> Stop the profile on context timeout

- libkbfs/disk_journal.go
- libkbfs/disk_journal_test.go
- libkbfs/journal_md_ops_test.go
- libkbfs/md_id_journal.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
Make diskJournal.move work correctly even if the journal
directory doesn't exist yet.
Fix bug in mdJournal where clear() would remove revisions
from the master branch if the branch is the local pending
squash branch.
> [KBFS-1958] Make diskJournal.clear() nuke the journal dir

- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
Rekey ends up calling getMDLocked and thus we add an identity if we didn't have the md already locally in memory.
> TLF reidentification when needed related to rekey

- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
Reverts keybase/kbfs#538
Master CI fails, will investigate in branch,
> Revert "TLF reidentification when needed related to rekey"

- libkbfs/data_types.go
- libkbfs/errors.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops.go
- libkbfs/keybase_service_base.go
- libkbfs/state_checker.go
It seems using a context key for this makes code easier to understand and maintain, than passing a parameter around.
> don't add TLF to favorite in GetTLFCryptKeys

- libkbfs/bcache.go
- libkbfs/folder_branch_ops.go
I saw some logs when `BlockCache.PutWithPrefetch()` was returning a `cachePutCacheFullError` on a transient put, when there should have been plenty of room in the cache to evict something else since there shouldn't have been many live permanent entries.  I can't tell exactly why this happened, but this PR fixes a few things I noticed while looking at the code:
* Don't let `cleanTotalBytes` wrap in any circumstance.  There is at least one known race that can result in undercounting bytes, so we want to make sure we never get into a situation where it will wrap the unsigned integer.
* When we can't make room for a permanent entry, make sure `makeRoomForSize` still holds the lock while updates `cleanTotalBytes`.
* If `folderBranchOps` does receive a `cachePutCacheFullError`, we should make …
> bcache: fix some possible issues with accounting and with cache-fullness

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
There was a problem where if a journal containing multiple squashes
encountered a conflict on the server, it would run CR over the entire
journal but not mark the squash revision markers as `Ignored` because
they were already marked as `Unignorable` (since they were from
squashes).  However, a real conflict should be able to override this
Unignorability.
Instead, this gets rid of the concept of `Unignorable`, and instead
marks local squashes as such directly.  This is now safe because we
walk the block journal backwards and quit early while ignoring
revisions, and we used to walk it forwards.
Note that I left the `Unignorable` field itself in case existing
journals have entries with it set, but we should remove it soon.
Issue: KBFS-1992
> block_journal: allow CR to mark squash rev markers as `Ignored`

- libkbfs/block_journal.go
- libkbfs/block_ops.go
- libkbfs/conflict_resolver.go
- libkbfs/folder_block_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server.go
- libkbfs/mocks_test.go
- libkbfs/tlf_journal.go
During CR, we need to get the size of all blocks referenced and unreferenced, for block accounting purposes.  Previously, we were doing this by fetching all the blocks in parallel at once, keeping them all in memory until they are all fetched, and then calculating the sum.
Instead, we can just get the sum.  If the block is in the trusted local journal, we don't even have to read the block data from disk, we can just get the size from the file info.  If the block is on the server, we still have to download it since we can't trust the server, but we don't need to keep it in memory afterwards.
I haven't tested the performance improvements yet (will do soon), but it is an obvious win for memory usage during CR.
Issue: KBFS-1974
> libkbfs: add a `BlockOps` method for just getting the size of a block, and use in CR

- libkbfs/tlf_journal.go
> tlf_journal: don't override non-nil errors after block flush

- libkbfs/tlf_journal.go
When there are still blocks remaining to be flushed for the earliest
MD in the journal, we don't need to bother reading it from disk and
signing it, just to decide we aren't going to flush it after all.  Not
sure if this helps performance much, but at least it cuts down log
spam a bit.
> tlf_journal: avoid reading/signing an MD for no reason

- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/disk_journal.go
- libkbfs/disk_journal_test.go
- libkbfs/md_id_journal.go
- libkbfs/md_journal.go
- libkbfs/md_journal_test.go
- libkbfs/mdserver_tlf_storage.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
This makes it possible to not have to tediously
error-check on every ordinal get.
Start journals at 1 instead of 0, so that 0
may in the future be declared invalid.
This reduces the number of reads, also, which may
improve performance slightly (but that's not the main
focus).
> Cache journal ordinals in memory

- libkbfs/cr_chains.go
- test/cr_multi_blocks_test.go
Oops, the refs for all but the last syncOp in a collapsed syncOp were
getting dropped, and the tests weren't catching it because we didn't
have one that wrote sequential blocks of a multi-block file.
Issue: KBFS-2002
> cr_chains: track refs when collapsing syncOps

- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/crypto_common.go
- libkbfs/errors.go
- libkbfs/interfaces.go
- libkbfs/kbpki_client.go
- libkbfs/key_bundle_v2.go
- libkbfs/key_bundle_v3.go
- libkbfs/key_manager.go
- libkbfs/key_ops.go
- libkbfs/key_server_local.go
- libkbfs/key_server_measured.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_local_shared.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/test_common.go
Use CryptPublicKeys instead, to avoid the possibility
of using the wrong key.
> Clean up a bunch of places where we use KIDs

- libfuse/mounter.go
The only case I can reproduced a non-responsive Ctrl-C is when the mount point doesn't exist. In other cases it was pretty responsive for me, with or without service, or with service running then killed (which causes a disconnection).
> don't try to mount unless mount point exists and is a dir

- libkbfs/identify_util.go
- libkbfs/identify_util_test.go
- libkbfs/tlf_handle.go
Pass the username to the identify routines rather than using only uid and getting the username based on that.
> libkbfs: Pass username+uid to identify instead of only uid

- libkbfs/identify_util.go
- libkbfs/identify_util_test.go
- libkbfs/tlf_handle.go
keybase/kbfs#832 was merged due to a misclick. Revert.
> Revert "libkbfs: Pass username+uid to identify instead of only uid"

- Jenkinsfile
- appveyor.yml
- libdokan/start.go
- libfuse/start.go
- libkbfs/errors.go
- libkbfs/init.go
- libkbfs/keybase_daemon.go
- libkbfs/keybase_daemon_rpc.go
- simplefs/simplefs.go
- simplefs/simplefs_test.go
As discussed on Slack.
The instance is passed through InitParams because the connection to service is created before a separate hypothetical SetSimpleFSImplementation could be created. With the current way the simplefs implementation can be present when the connection is opened.
> simplefs: Move out simplefs to separate package

- libkbfs/folder_branch_ops.go
- libkbfs/tlf_journal.go
Something changed where `getAndApplyMDUpdates()` can now return the "Cannot find most recent merged revision while staged" if the journal becomes staged, rather than the `UnmergedError`.  We still need to continue waiting for CR in that case.
Also, on conflict in `tlfJournal`, signal branch change before pausing. If we pause first, then there's a race where folderBranchOps.SyncFromServerForTesting will finish waiting for the journal and then not have anything to CR because the branch change hasn't happened yet.
Issue: KBFS-2017
> folder_branch_ops: SyncFromServer loops on merged rev error

- libkbfs/disk_limits_unix.go
Return math.MaxInt64 for max inodes in that case.
> [KBFS-2018] Detect FSs that don't keep track of inodes

- libkbfs/conflict_resolver.go
This can happen when an aborted sync ends up putting empty BlockPointers in the followup syncOp.
Issue: KBFS-2021
> cr: don't attempt to unreference empty BlockPointers

- kbfsfuse/kbfsfuse.sh
So we don't open the tests up to any races.
> kbfsfuse: turn off journaling as part of the kbfsfuse command

- libkbfs/conflict_resolver_test.go
- libkbfs/md_util.go
A queued CR can run after the local branch is cleared.  When it asks
for the unmerged MDs, folderBranchOps simply calls
`getUnmergedMDUpdates()` with whatever the current BID is -- which is
`NullBranchID`.  This ends up serving merged updates out of the MD
cache, which results in self-conflicts.  Instead, if the BID is null,
always serve back an empty list.
Issue: KBFS-2023
> md_util: don't fetch unmerged MD range when the BID is null

- libkbfs/identify_util.go
- libkbfs/identify_util_test.go
- libkbfs/tlf_handle.go
Passes usernames from TLFs to identify calls rather than using just the UID.
> libkbfs: Pass usernames from TLFs to identifies

- kbfsfuse/main.go
- libfs/constants.go
- libfuse/debug_server_file.go
- libfuse/fs.go
- libfuse/profilelist.go
- libfuse/special_files.go
We need this for the net/trace stuff, since exposing those endpoints
don't work as files (since they use query parameters).
Add net/pprof handlers to the debug server for now.
> [KBFS-2014] Add special file to enable/disable a debug HTTP server

- .gitignore
- libkbfs/backpressure_disk_limiter.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/config_local.go
- libkbfs/disk_block_cache.go
- libkbfs/disk_block_cache_helper.go
- libkbfs/disk_block_cache_test.go
- libkbfs/disk_limiter.go
- libkbfs/init.go
- libkbfs/interfaces.go
- libkbfs/journal_block_server_test.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server.go
- libkbfs/journal_server_test.go
- libkbfs/kbfs_cr_test.go
- libkbfs/keybase_service_util.go
- libkbfs/semaphore_disk_limiter.go
- libkbfs/test_common.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
This PR adds the ability for the journal's `diskLimiter` to also work with the `DiskBlockCacheStandard`. The limit function is as follows:
* min(20GB, 0.1 * free space on drive)
In practice the disk cache will only hit 20GB when the user has >=200GB of available space. We can ship future builds where this will be a tunable parameter.
> [KBFS-1920] Disk Cache Limiter

- libkbfs/block_retrieval_queue.go
- libkbfs/config_local.go
- libkbfs/conflict_resolver.go
- libkbfs/data_types.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_branch_ops.go
- libkbfs/init.go
- libkbfs/interfaces.go
- libkbfs/key_manager_test.go
- libkbfs/md_util.go
- libkbfs/test_common.go
- libkbfs/tlf_edit_history.go
Allow KBFS to be used in a "minimal" mode, which limits the number of background goroutines and eliminates some unnecessary functions when we know data reads and writes won't be happening (e.g., for mobile).  In particular:
* Limit the number of block workers to 2.  (For now we still need some block workers in case the MD head for a folder needs to download unembedded block changes.  I filed KBFS-2026 to fix that at some point.)
* Turn off CR, QR, and other background block processors.
* Turn off edit history updates.
* Turn off journaling.
* Turn off the dirty block cache.
Now, in minimal mode, the KBFS goroutines seem pretty minimal.
Issue: KBFS-1999
> libkbfs: add minimal init mode 

- libkbfs/data_types.go
- libkbfs/folder_branch_ops.go
- libkbfs/journal_md_ops.go
- libkbfs/key_manager.go
- libkbfs/md_ops.go
- libkbfs/md_util.go
- libkbfs/tlf_journal.go
Also don't prefetch the root dir block in minimal mode.
Basically this should avoid any bserver requests in minimal mode.
Issue: KBFS-2026
> md_util: don't reembed block changes in minimal mode

- libkbfs/bserver_remote.go
Need a quick thumb on this before the builds start tomorrow; disk cache won't save any blocks without it. I think I messed up a merge somewhere and `git rerere` got too aggressive.
> Fix bad disk block cache merge

- libkbfs/keybase_service_base.go
- libkbfs/mdserver_remote.go
- vendor/github.com/keybase/client/go/chat/types/interfaces.go
- vendor/github.com/keybase/client/go/chat/types/types.go
- vendor/github.com/keybase/client/go/libkb/globals.go
- vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go
- vendor/vendor.json
If the service gives us some other error message when getting the session (as opposed to `libkb.NoSessionError`), we should retry the connection after a delay using the rpc connection's retry logic.
This also fixes up logging in `MDServerRemote` to be more consistent with the rest of the package.
Also, it re-vendors client to get the most up-to-date content hashes (previously, we had vendored from an unmerged branch).
Issue: KBFS-2031
> mdserver_remote: don't treat random errors as NoCurrentSessionErrors

- libkbfs/util.go
- vendor/github.com/keybase/client/go/logger/standard.go
- vendor/vendor.json
If the service makes any RPC calls to us with debug tags included, this will add them to the context as log tags.  However, right now I don't think it sets any tags during calls (not chat-related calls, anyway).
> util: add log tags from RPC if available

- libkbfs/bserver_remote.go
- libkbfs/connection_status.go
- libkbfs/init.go
- libkbfs/mdserver_remote.go
- libkbfs/pinger.go
- libkbfs/test_common.go
Also add timeout disconnects for mdserver as well, factoring out a bit of common code.
Since bserver actually has two connections, this required a bit of refactoring of bserver connection handling as well.
This helps the case where a (Linux?) device loses its network (e.g., due to a suspend).  Normally it would take a long time (15-20 mins) for the TCP connections to figure out that they need to reconnect.  This brings that down to ~40s.
One downside is that `connection.go` now spams the log every 2 seconds while the device is offline, and before it wouldn't do that until the TCP connection noticed the disconnect.  We might want to suppress some of that logging in a future PR.
Issue: KBFS-1982
> bserver_remote: add pings and disconnect on timeouts

- libkbfs/backpressure_disk_limiter.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/config_local.go
- libkbfs/disk_block_cache_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
I'll be adding more params for quota limits, and this is already getting
quite unwieldy.
Add a few more comments.
> [KBFS-1988] Create a param struct for the backpressure disk limiter

- libfuse/dir.go
- libfuse/file.go
- libfuse/fs.go
- libkbfs/conflict_resolver.go
- vendor/golang.org/x/net/internal/timeseries/timeseries.go
- vendor/golang.org/x/net/trace/events.go
- vendor/golang.org/x/net/trace/histogram.go
- vendor/golang.org/x/net/trace/trace.go
- vendor/vendor.json
Attach trace objects to FUSE requests.
Also attach them to CR.doResolve calls.
Vendor golang.org/x/net/trace.
Log more stuff for Setattr, Read, and Write calls.
This doesn't have any tracing statements yet,
but it does give a picture of the distribution of
request times.
> [KBFS-2014] Add net/trace viewer to debug HTTP server

- libkbfs/folder_branch_ops.go
- libkbfs/journal_md_ops_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
So that we won't run conflict resolution on it while squashing, before
it is flushed.
Issue: KBFS-2048
Issue: keybase/client#6339
> tlf_journal: mark first revision as already squashed

- libkbfs/folder_branch_ops.go
- libkbfs/identify_util.go
- vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go
- vendor/vendor.json
This adds a new keybase1.IdentifyBehavior, CHAT_SKIP.  If present, KBFS will skip identify calls.  Service only sets this in the case of GetTLFCryptKeys where it does the identifies.
cc @mmaxim
> Allow identify skip

- libkbfs/rekey_queue.go
I tested locally using `gops` to make sure there wasn't any left-over routines after `test()` returned. Thanks for discovering this!
> fix routine leak in rekey_queue

- libkbfs/bcache.go
- libkbfs/block_getter.go
- libkbfs/block_ops.go
- libkbfs/block_ops_test.go
- libkbfs/block_retrieval_queue.go
- libkbfs/block_retrieval_queue_test.go
- libkbfs/block_retrieval_worker_test.go
- libkbfs/bserver_remote.go
- libkbfs/config_local.go
- libkbfs/disk_block_cache.go
- libkbfs/disk_block_cache_helper.go
- libkbfs/disk_block_cache_test.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/prefetcher.go
- libkbfs/prefetcher_test.go
> [KBFS-2001] Skip Retrieval Workers for Items in the Disk Cache

- libkbfs/tlf_handle_resolve.go
- libkbfs/tlf_handle_test.go
Resolve2 only checks the first component of a compound assertion, so
as not to rely on server trust.  KBFS was relying on Resolve2 for
compound assertions, and thus was broken.  Instead, call Identify2 for
compound assertions for now, until we can get a better fix with
KBFS-2022.
Issue: KBFS-2068
> tlf_handle_resolve: don't trust Resolve for compound assertions

- libkbfs/backpressure_disk_limiter.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/block_journal.go
- libkbfs/block_journal_test.go
- libkbfs/disk_limiter.go
- libkbfs/journal_md_ops.go
- libkbfs/quota_usage.go
- libkbfs/semaphore_disk_limiter.go
- libkbfs/semaphore_disk_limiter_test.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
Keep track of quota usage and unflushed bytes, and use that to apply
backpressure based on used quota percentage.
Make EventuallyConsistentQuotaUsage.Get take separate tolerance
arguments.
Use Time.IsZero() everywhere.
Remove unused argument from resolveBranch.
> [KBFS-1988] Implement quota-dependent backpressure

- libkbfs/kbfs_ops.go
Otherwise, when the disk limiter triggers an "over quota" error
notification, and the user does a `du`, they could seem to still be
under the limit.
> kbfs_ops: include unflushed bytes in usage bytes for status

- libkbfs/backpressure_disk_limiter.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/disk_block_cache_test.go
...so that quota backpressure kicks in precisely when
we start emitting throttle errors.
Also change tests to use the same min threshold.
> [KBFS-2077] Set quota backpressure min threshold to 100%

- libdokan/mounter.go
At least people will be able to chat and use simplefs if dokan goes all wonky.
> kbfsdokan: don't error out on non-force fs mount failure

- libkbfs/bare_root_metadata_test.go
Otherwise, if we have parallel tests, this wouldn't work
properly.
> Capture range variable in runTestsOverMetadataVers

- libkbfs/config_local.go
- libkbfs/default_blocks_in_mem_cache_386.go
- libkbfs/default_blocks_in_mem_cache_64bit.go
To avoid running into memory issues on Windows.
Issue: KBFS-2088
> config_local: lower default cache size on 32-bit builds

- libfuse/dir.go
- libfuse/file.go
- libfuse/fs.go
- libkbfs/config_local.go
- libkbfs/conflict_resolver.go
- libkbfs/interfaces.go
- libkbfs/mocks_test.go
That way we don't have to worry much about the performance
impact of tracing.
Also move all the trace logic into Config, so that ConflictResolver
(and anything not attached to FUSE requests) can obey tracing
options.
> [KBFS-2014] Only do tracing when debug server is enabled

- libkbfs/interfaces.go
- libkbfs/keybase_daemon_rpc.go
- libkbfs/keybase_service_base.go
- libkbfs/mdserver_disk.go
- libkbfs/mdserver_memory.go
- libkbfs/mdserver_remote.go
- libkbfs/mocks_test.go
The patch does the following:
1.) Implements the `keybase1.ReachabilityProtocol` for the MDServer.
2.) When receiving a `ReachabilityChanged` notification from the service, then we do a basic test (`DialWithTimeout`), to see if we can still reach the MDServer at the network level.
`ReachabilityChanged` is triggered from an OS level update indicating the network state has changed in some way. The service currently uses it to be aggressive about dropping the Gregor connection in response to these updates, and this patch extends that same behavior to MDServer.
> process reachability notifications from the service, and plug MDServer into them

- libdokan/file.go
- libdokan/mount_test.go
- libfuse/file.go
- libfuse/mount_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
Also, reduce the background sync period to 1 second, since we can't rely on closes to sync the data anymore.
Note that this PR changes our durability guarantees a bit, because now if the user doesn't call fsync, there is up to a second after the user closes the file where KBFS can crash and lose the writes that have buffered in memory.  I think this is fine, since applications should know that fsyncs are required for data durability.  But please think critically about this PR and let me know if this is a bad idea.
This improves perceived performance for single file writes by a fair amount, but not for batch file writes, as shown below.  That's because it still blocks the foreground process while doing the same number of syncs, they're just shifted a bit.
```
Sync-on-close, 1 byte file in …
```
> fs: don't sync files on close, only on explicit fsync or background sync

- libkbfs/disk_block_cache.go
- libkbfs/folder_branch_status.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/mocks_test.go
- vendor/github.com/rcrowley/go-metrics/README.md
- vendor/github.com/rcrowley/go-metrics/gauge.go
- vendor/github.com/rcrowley/go-metrics/gauge_float64.go
- vendor/github.com/rcrowley/go-metrics/json.go
- vendor/github.com/rcrowley/go-metrics/log.go
- vendor/github.com/rcrowley/go-metrics/registry.go
- vendor/github.com/rcrowley/go-metrics/runtime.go
- vendor/github.com/rcrowley/go-metrics/sample.go
- vendor/vendor.json
This PR creates some metrics to track disk cache trends, in addition to reporting overall status (max bytes, current bytes, num blocks). Combined with the disk cache status reported inside the disk limiter, this should give us a very complete pictures of what's going on in the cache.
Please review #913 first.
> [KBFS-2037] Disk Cache Status

- libkbfs/file_data.go
- libkbfs/file_data_test.go
- test/truncate_test.go
KBFS-2091 hit a case where a randomly-generated `kbfsblock.ID` was synced as part of a file write to the servers.  That should be impossible; a synced `kbfsblock.ID` should always be a hash of its contents.  It turns out that `fileData.ready()` couldn't figure out that the corresponding block was dirty, and so it never encrypted the block and figured out the new ID.  This rendered the file unreadable and triggered missing block errors.
This affected large files which were written to in the middle of the file, rather than being appended to.  KBFS-2091 caught this issue with `zip` on macOS.
This PR contains two necessary fixes (and regression tests for them:
1. The code that hunted for dirty blocks (`getNextDirtyFileBlockAtOffset`) would do a depth-first search of the file tree, looking for …
> file_data: fixes for finding all the dirty blocks in a file

- libkbfs/tlf_journal.go
Otherwise if a flush takes more than 15 minutes (entirely reasonable
if the user dumps a huge amount of data into the journal at once), and
then the flush hits a failure (e.g., connectivity issues), the journal
will never retry.  I don't see any reason to ever stop retrying.
Issue: KBFS-2101
> tlf_journal: bg work retrier shouldn't have a MaxElapsedTime

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_update_prepper.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- test/benchmark_test.go
- test/engine_libkbfs.go
This PR introduces `KBFSOps.SyncAll`, which syncs _all_ dirty files together to the server in a single MD update.  Note that this PR does *not* enable `SyncAll` use by kbfsfuse yet, it is only used in tests right now.
This breaks up the original `folderBranchOps.SyncLocked` into two parts, so it can be used by `SyncAll`. `SyncAll` uses the chains and prepper code also used by CR to summarize a set of changes into a single MD update and sync them all together.
This ended up exposing some issues in conflict resolution, especially around how it deals with `resolutionOp`s and `syncOp`s that are part of a previous resolution.  I'll try to give some details about each one in PR comments.
Issue: KBFS-2069
> libkbfs: introduce SyncAll for syncing multiple files

- kbfstool/write.go
- libdokan/file.go
- libdokan/mount_test.go
- libfuse/file.go
- libfuse/mount_test.go
- libkbfs/conflict_resolver_test.go
- libkbfs/folder_block_manager_test.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_update_prepper.go
- libkbfs/interfaces.go
- libkbfs/kbfs_cr_test.go
- libkbfs/kbfs_ops.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/ops.go
- libkbfs/tlf_edit_history_test.go
- simplefs/simplefs.go
Syncing a single file doesn't make sense in a world where the
directory operation creating the file hasn't been synced yet.  The
simplest solution seems to be to not allow syncing a single file, and
requiring that all operations are synced together no matter what.
So this PR gets rid of Sync(), and makes all of its callers use
SyncAll() instead.
As part of this I got rid of a bunch of mock-based KBFSOps tests that
would have been a pain in the butt to adapt to SyncAll; the stuff they
covered is covered by other, higher-level tests now (those tests
predate the ability to end-to-end FS operations).
This depends on #909.
Issue: KBFS-2073
> kbfs_ops: eliminate Sync() in favor of SyncAll()

- vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go
- vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/context.go
- vendor/vendor.json
Otherwise if two goroutines are trying to modify these log tags, then you can get concurrent map access panics.
> vendor in changes to copy RPC tags out of context, instead of re-using array

- libkbfs/cr_chains.go
- libkbfs/data_types.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_update_prepper.go
- libkbfs/kbfs_ops_test.go
- libkbfs/root_metadata.go
This PR syncs any outstanding directory operations in a `SyncAll()` call -- but it doesn't actually turn it on in production.  It adds some manual hacky tests to make sure the right thing is happening for basic operations.  A future PR (for KBFS-2076) will have more extensive tests, and will probably remove the hacky ones.
Getting block accounting to work properly required a few scattered changes, I'll comment on those individually.
This depends on #920 (and #909).
Issue: KBFS-2074
> folder_branch_ops: include cached dir ops in SyncAll

- libkbfs/config_local.go
- libkbfs/folder_branch_ops.go
- libkbfs/init.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
This changes the background flusher to flush either a) after a certain amount of time has passed since the last write, or b) after a certain number of directory operations have been buffered.  This should have no effect since we don't currently buffer directory operations (that's what the next PR in the series will do.)
It also makes both these values configurable from the command line, to make performance testing easier.
Issue: KBFS-2075
> folder_branch_ops: limit background batch sizes, and make batch values more configurable

- libkbfs/block_ops.go
- libkbfs/bserver_remote.go
- libkbfs/mdserver_remote.go
- libkbfs/trace_logger.go
Use it to add tracing for remote BlockServer
and MDServer. Also add tracing to BlockOps.
> [KBFS-2014] Add new traceLogger type

- libkbfs/mdserver_remote.go
Calling `getConn()` within a `DoCommand` handler rpc function can
result in getting a different connection that the one `DoCommand` was
originally called on.  This new connection might not be initialized
yet, and so `conn.Server()` might return `nil`.
Instead, just use the same connection, since by the time the
`DoCommand` rpc function is invoke, we know the server will have been
set.  (The connection transport may have been shut down, but that
should error cleanly as we'd expect, and the caller can retry the RPC
over the new connection.)
Issue: KBFS-2130
> mdserver_remote: use same connection in DoCommand handler

- simplefs/simplefs.go
Not sure if this is the right approach but I tried it and it gave a result when a second client process did `fs ps` while another did `fs read`
> Add read/write to GetOps (fs ps)

- libkbfs/ops.go
- libkbfs/ops_test.go
* When collapsing writes, the later truncate always wins.
* When inverting ops, make copies of gcOps and resolutionOps, otherwise we're setting ourselves up for trouble.
> ops: small truncate fixes

- test/dsl_test.go
- test/engine.go
- test/engine_fs_test.go
- test/engine_libkbfs.go
- test/sbs_test.go
A coming PR will require that `SyncAll` is called before directory changes are visible to other users, so this makes that invisible to DSL tests by automatically doing it at the end of every `as` block.
> test: call SyncAll after every `as` block

- libkbfs/cr_chains.go
A few issues found while preparing KBFS-2076 (these will be tested in the final PR in this series):
* When merging an unmerged file with a merged one in a non-conflicting way (for example, because two directories of the same name were created simultaneously and need to be merged), `changeOriginal` should only update the "original" pointer on the chain, not the "most recent" pointer, which should remain whatever it was in the unmerged branch until CR finishes.
* Also, `changeOriginal` doesn't imply that the unmerged branch created the original; it was actually created in the merged branch!
* When trying to find the type of a directory entry and the entry doesn't exist, give up gracefully if it's already been deleted (by some later operation), since we don't really need to know the type and …
> cr_chains: various fixes needed for KBFS-2076

- libkbfs/conflict_resolver.go
- libkbfs/cr_chains.go
A future commit will immediately truncate every newly-created file, in
order to mark it dirty.  To avoid unnecessary conflicts, we should
treat the same file name that's only been truncated as mergeable
everywhere in the CR code, not just during action computation.
> cr: merge new, truncated files

- libkbfs/folder_branch_ops.go
This is a no-op until a later PR cached directory ops in `fbo.dirOps`.
> folder_branch_ops: don't ref/unref pointers within same MD

- libkbfs/keybase_service_util.go
If a non-admin user logged-in after KBFS initialized, they would never
get to use the disk block cache.
> keybase_service_util: un-feature-flag disk block cache on login

- libdokan/fs.go
This function is usually called by the OS/desktop, not the user, so it
doesn't make sense to show an error notification (usually a "read
timeout -- send your logs" type of message) for this.
Issue: KBFS-2103
> libdokan: don't report GetDiskFreeSpace errors

- libkbfs/conflict_resolver.go
- libkbfs/cr_actions.go
- libkbfs/folder_branch_ops.go
- test/cr_basic_conflicts_test.go
#941 makes us depend more on the `NodeCache` when stat'ing files, and that ended up exposing some issues where CR was incorrectly generating local notification op lists that messed up the node cache.  Specifically, when there's a `renameOp` in the local notifications list, several things could have been wrong:
1. CR might also have an `rmOp` in the list for the source of the `renameOp`, and due to golang map reordering, the `rmOp` might come beforethe `renameOp` in the notification list.  This led to the node entry being unlinked before being moved.  This PR makes sure the `renameOp` always comes first in that situation.
2. Sometimes `folderBranchOps.notifyOneOpLocked` needs to use the pointers in the MD ops list to search for the new parent `Node` of a renamed file.  However, during CR, …
> cr: fix rename op handling for local notifications

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/node.go
- libkbfs/node_cache.go
- libkbfs/node_cache_test.go
This PR does two somewhat related things that are needed for the rest of KBFS-2076:
1. It updates the parent mtime/ctime on creates and removes, and stores those changes in the `deCache`.  These changes need to be applied when looking up the directory in the future.  But we might not want to replace the entire `DirEntry` because our cached copy might not have a proper `BlockPointer` or other important data, so update carefully.
2. When a file is unlinked, there might still be a handle lying around for it in some application.  That handle still has a right to the node's DirEntry.  Previously we were storing it in the `deCache`, so a) it would only survive until the next `SyncAll`, even though the handle might live past that, and b) when processing directory adds, we might end up using the …
> libkbfs: fix deCache to update timestamps better, and store unlinked DirEntrys in the NodeCache

- libdokan/mount_test.go
- libfuse/mount_test.go
- libkbfs/conflict_resolver.go
- libkbfs/conflict_resolver_test.go
- libkbfs/folder_block_manager_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/key_manager_test.go
- libkbfs/keybase_daemon_rpc_test.go
- libkbfs/rekey_queue_test.go
- libkbfs/test_common.go
- libkbfs/tlf_edit_history_test.go
This will be needed once we turn on the feature in a future PR.  Note that this PR doesn't update *every* test, especially the complicated ones in `kbfs_cr_test.go` and `kbfs_ops_concur_test.go`, because those will require a bit more work than just a simple call to `SyncAll`.
> tests: add `SyncAll` calls to a bunch of tests that modify directories

- libkbfs/file_data.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_update_prepper.go
Track the pre-ready block pointers in the blockPutState, so that in a
future commit SyncAll can figure out how to call `UpdatePointers` for
blocks that haven't yet been synced (and were given random
BlockPointers when they were created).
> folder_branch_ops: save old block pointers in the blockPutState

- libkbfs/cr_chains.go
- libkbfs/file_data.go
* file_data: even 0-byte writes should dirty the top block.  This will be used in a later commit when 0-byte writes are used to mark newly-created files as dirty, to make sure they are synced.
* cr_chains: implement addNoopChain helper function. To be used by a later commit to introduce chains for blocks that have no real ops, but still need to be readied.
> libkbfs: small file_data and cr_chains fixes needed for dir op batching

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status.go
- libkbfs/path.go
* Make cache/status changes undo-able
* Use the undo functions in folderBranchOps.
* Provide more control over whether to apply cached attributes when
getting directory entries or not.
> folder_block_ops: fixes need for dir op batching

- libkbfs/dirty_bcache.go
- libkbfs/dirty_file.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
`si.unrefs` holds blocks that need to be unreferenced as part of a sync. If a block was created as part of a sync, and put to the bserver, but the MD put failed and the block was then overwritten in the new MD revision that does make it to the mdserver, we would "remove" it from `si.unrefs` by zeroing out the pointer, but we'd keep around the block size info so that it can be properly accounted for.
However, now the `folderUpdatePrepper` explicitly looks up the size of each block, so that accounting is no longer needed, and we can entirely remove the block.  Furthermore, the `folderUpdatePrepper` doesn't like invalid block pointers, so this fixes an "Invalid block ref" error after sync fails a few times.
Also, load unrefs from the current si, not savedSi.  `savedSi` might contain …
> folder_block_ops: fix block accounting issues after a multiblock file fails to sync twice

- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
Since the caller would have gotten the path without holding
`blockLock`, which means it could have changed between then and now.
Issue: KBFS-2155
> folder_block_ops: use Nodes for reading, not paths

- libkbfs/cr_chains.go
- test/cr_simple_test.go
If the parent dir was created as part of a squash/batch, there might not be any update for it, and so it might not appear in the `originals` map.  In that case, we can use the original.
The new test reproduces the failure without the `crChains` fix.
Issue: KBFS-2162
> cr_chains: check createdOriginals for parent dir in identifyType

- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status.go
- libkbfs/folder_update_prepper.go
- libkbfs/kbfs_ops_test.go
This PR does two things:
1. Removes dirty nodes when the entry is removed. A removed dir entry is also removed from the deCache, which means it will never be synced.  Removed files still go through the sync process, so that their state is cleared.
2. Caches block infos during a cached `rmOp`. Otherwise the prepper will fetch all the blocks in order to find out the sizes, which could take a long time and would block writes and leave dirty paths around during the entire download process, until the SyncAll finishes.
The test makes sure extraneous blocks are fetched, and the dirty paths are all cleaned up.
Issue: KBFS-2161
> folder_branch_ops: fix rm'd dirty dirs and rm -rf performance

- libkbfs/errors.go
- libkbfs/errors_fuse.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_test.go
This doesn't seem useful, and will just confuse our dir entry cache.
Issue: KBFS-2161
> folder_branch_ops: disallow dir ops in unlinked directories

- kbfssync/semaphore.go
- libkbfs/backpressure_disk_limiter_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/kbfs_ops_concur_test.go
- libkbfs/semaphore_disk_limiter_test.go
- simplefs/simplefs.go
ctx.Err() is only defined after ctx.Done() is closed,
and in practice it's nil before then.
Audit other misuses of ctx.Err().
> [KBFS-2168] Fix TestSemaphoreDiskLimiterBlockBasic flake

- libkbfs/folder_block_ops.go
BlockServerMemory wraps its errors using pkg/errors.  Doh!
Issue: KBFS-2164
> folder_block_ops: check cause of error when a sync fails

- libkbfs/kbpki_client.go
- libkbfs/kbpki_client_test.go
The mdserver might still allow writes from an online device that's
just been revoked, until it hears about the revocation from the API
server.  One user has TLFs in this state, and our strict check here
means they can't read any data in it.
Eventually we should switch all these to Merkle roots, but that's a
much bigger project (and will also need some concept of slack anyway,
for the same reason).
Issue: keybase/client#6990
> kbpki_client: allow slack time when checking revoke times

- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
If we have a lot of blocks to flush from the journal, we should check
the MD server periodically to see if the next MD we're going to flush
would result in a conflict.
Specifically, if we have already once done CR locally, we might have a
huge set of blocks to flush, and only one MD to flush at the very end.
If we wait to the end to find out if there's a conflict, it could take
a long time for the remote changes (written by another device) to be
reflected in the local view of the TLF.  If instead we force CR
earlier, those changes will become visible earlier.
Issue: KBFS-2106
> tlf_journal: check MD server for conflicts during flush

- libkbfs/errors_fuse.go
So that users get a better error code than simply EIO (in addition to
a nice popup notification with more information).
> errors: return ENOSPC error for disk limit timeout

- libkbfs/folder_branch_ops.go
- libkbfs/node_cache.go
We already return an empty list for GetDirChildren, so refuse lookups to be consistent.
Also cleanup a small thing in `NodeCache` I noticed.
Issue: KBFS-2189
> folder_branch_ops: refuse lookups in unlinked directories

- libkbfs/backpressure_disk_limiter.go
- libkbfs/disk_limiter.go
- libkbfs/reporter_kbpki.go
- libkbfs/semaphore_disk_limiter.go
- libkbfs/tlf_journal.go
`getDiskLimitInfo` was returning the max limit for the journal, rather
than the limit calculated based on available space.  Oops!
Turns out this is a float64, so all those types needed to change
sadly.  When reporting to the user, it formats the float with no
decimals.
> disk_limiter: return currLimit(), rather than limit

- Jenkinsfile
…so they have a much lower probability of failure when macstadium workers are in high contention
> jenkinsfile: Extend libkbfs and libfuse timeouts 

- libfuse/fs.go
Make Linux/macOS work the same way as Windows.  I saw someone complain
about this on Twitter:
https://twitter.com/bytebot/status/865182626977640449
> libfuse: don't try to get quota when disconnected

- kbfstool/md_force_qr.go
- kbfstool/md_reset.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops.go
- libkbfs/journal_md_ops_test.go
- libkbfs/journal_server_test.go
- libkbfs/kbfs_ops_test.go
- libkbfs/md_ops.go
- libkbfs/md_ops_test.go
- libkbfs/mocks_test.go
- libkbfs/test_stallers.go
- libkbfs/tlf_journal.go
- libkbfs/tlf_journal_test.go
- test/journal_test.go
This PR fixes a nasty race:
1. folderBranchOps puts a new MD update X into the journal, but execution doesn't return immediately to FBO.
2. The journal, while flushing, notices a conflict, and converts the journal, including new update X, to a conflict branch. This updates all MDs in the cache with a new branch ID . . . except update X hasn't been put into the cache yet.
3. Execution returns to folderBranchOps, and update X gets put into the cache as a "merged" revision with a null BranchID.
4. Conflict resolution runs, and reads update X as one of the merged revisions, even though the real merged revision X was written by another device and should be fetched from the server.
To fix, I decided to put things in the cache under the same journal lock that puts things in the journal, so we …
> libkbfs: cache MD at the same time it's put to the server

- libkbfs/mdserver_remote.go
Randomize next rekey time. Avoids lots of clients rekeying at the same time.
> libkbfs: Randomize next rekey time

- libfuse/mount_test.go
- libkbfs/folder_branch_ops.go
- libkbfs/folder_branch_status.go
- libkbfs/identify_util.go
- libkbfs/identify_util_test.go
- libkbfs/interfaces.go
- libkbfs/kbfs_ops_test.go
- libkbfs/kbpki_client.go
- libkbfs/kbpki_client_test.go
- libkbfs/kbpki_util_test.go
- libkbfs/key_manager_test.go
- libkbfs/keybase_daemon_local.go
- libkbfs/keybase_daemon_rpc_test.go
- libkbfs/keybase_service_base.go
- libkbfs/keybase_service_measured.go
- libkbfs/md_ops.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata_test.go
- libkbfs/tlf_handle_resolve.go
And also Identify() now calls keybase1.IdentifyLite, since none of the
callers were directly depending on any of the keys being available in
the response.  This will be needed later since teams can't be
identified through Identify2, as their keys are incompatible with that
result data structure.
Note that this depends on keybase/client#7046 and #990.
Issue: KBFS-2185
> interfaces: change KBPKI interface to deal with UserOrTeamID

- libkbfs/disk_limits_unix.go
> disk_limits_unix: on FreeBSD, apparently Bavail is an int64

- libkbfs/mdserver_tlf_storage.go
Otherwise, even if there's already a branch journal on the disk, we won't check it for the head, and it will look like updates don't persist across reboots.
This fixes a bug where using `kbfsfuse` with local disk storage for the MD didn't work after a reboot.
> mdserver_tlf_storage: create branch journal when reading head

- libdokan/fs.go
(I'll fix up #1010 to do this for teams as well, before I merge it.)
Issue: #1010
> libdokan: use ToUpper() instead of redefining folderlist names

- kbfstool/md_force_qr.go
- kbfstool/md_reset.go
- libkbfs/bare_root_metadata_v2.go
- libkbfs/bare_root_metadata_v3.go
- libkbfs/conflict_resolver.go
- libkbfs/data_types.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/journal_md_ops_test.go
- libkbfs/kbpki_client.go
- libkbfs/keybase_daemon_local.go
- libkbfs/keybase_service_base.go
- libkbfs/keybase_service_measured.go
- libkbfs/md_journal_test.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
Though in a live setting, this will actually only stored an omitted 0 for now, since the service doesn't expose this yet.
Issue: KBFS-2185
> libkbfs: save the current Keybase Merkle root in mdv3

- libkbfs/data_types.go
- libkbfs/folder_block_manager.go
- libkbfs/folder_block_ops.go
- libkbfs/folder_branch_ops.go
- libkbfs/interfaces.go
- libkbfs/kbpki_client.go
- libkbfs/key_manager_test.go
- libkbfs/keybase_daemon_local.go
- libkbfs/mocks_test.go
- libkbfs/root_metadata.go
- libkbfs/root_metadata_test.go
- libkbfs/test_common.go
- libkbfs/tlf_handle.go
- libkbfs/tlf_handle_test.go
This PR adds `IsWriter/IsReader` methods to `RootMetadata` to check team membership when appropriate, and uses them (instead of the `TlfHandle` methods) when appropriate.
Note that none of the rekey methods need to use these, since KBFS won't be rekeying team TLFs.  I've intentionally let the rekey methods continue to use the handle methods, to cause a panic if they're ever used for team TLFs.
Issue: KBFS-2185
> libkbfs: check team membership on folder operations
