README.md
=> README: "filesystem" consistency plus image

libdokan/fs.go
Related to https://github.com/keybase/client/issues/2916
=> libdokan: Refuse private directory while errors are present

libkbfs/bcache.go, libkbfs/bcache_test.go, libkbfs/config_local.go, libkbfs/config_mock_test.go, libkbfs/dirty_bcache.go, libkbfs/dirty_bcache_test.go, libkbfs/folder_block_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go
=> libkbfs: separate clean and dirty block caches

libkbfs/tlf_handle.go, libkbfs/tlf_handle_test.go
=> [KBFS-1121] Fix empty ConflictInfo bug

libkbfs/identify_util.go
@akalin-keybase 
minor changes, more info here: https://keybase.atlassian.net/browse/DESKTOP-1183
=> Change copy

libkbfs/bserver_disk.go, libkbfs/bserver_remote_test.go, libkbfs/bserver_tlf_journal.go, libkbfs/bserver_tlf_journal_test.go, libkbfs/bserver_tlf_storage.go, libkbfs/bserver_tlf_storage_test.go, libkbfs/folder_block_manager_test.go, libkbfs/state_checker.go
Store operations in a journal instead of an on-disk
reference map.
=> [KBFS-1097] Change bserverTlfStorage to bserverTlfJournal

libdokan/folderlist.go
=> libdokan: Fix non-creation of special new folders

libkbfs/bcache.go, libkbfs/bcache_test.go, libkbfs/block_types.go, libkbfs/block_types_test.go
An attempt to [KBFSKBFS-1156](https://keybase.atlassian.net/browse/KBFS-1156)
=> [WIP] reduce the number of block hashes

libdokan/fs.go, libfuse/fs.go
If a notification came in after the channel was nilified, and then
someone tried to wait on the fs.notificationGroup, they would wait
forever.
Also, use a defer for the Done to make absolutely sure it always
fires.
Issue: KBFS-1162 (maybe?)
=> libfuse: fix some corner cases with the notificationGroup

libdokan/mount_test.go, libfs/time_equal.go, libfuse/mount_test.go, test/cr_simple_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go, test/simple_test.go
I think this will be needed to repro KBFS-1163.
Issue: KBFS-471
=> test: add get/set mtime checks

libdokan/mount_test.go
Just a new test. Should catch recent regression fixed on friday in master.
=> libdokan: Add test for mkdir new folder

libkbfs/folder_block_ops.go
Make a smaller timeout for the read if there is an existing timeout and it has room for that.
The inner timeout will fire first and Read handles that returning to upstream which still has time in the global timeout and bubbles the short read up.
=> libkbfs: Support short reads rather than hitting the global timeout

libkbfs/dirty_bcache.go
If we block trying to send on decreasedBytes (while holding the lock),
we could get into a deadlock with the permissions-granting goroutine
which both gets the lock and drains the decreasedBytes channel.
=> dirty_bcache: fix deadlock between bg goroutine and full channel

libkbfs/dirty_bcache.go
Callers of RequestPermissionToDirty assume their request will be
counted, so they always decrement the count.  If a request isn't
counted by the time the test shuts down, make sure to do so.
Issue: KBFS-1195
=> dirty_bcache: count bytes for all pending requests on shutdown

libkbfs/md_util.go
Otherwise, we can have a race with multiple goroutines trying to decrypt into the same MD concurrently.
Issue: KBFS-1161
=> md_util: decrypt the private MD into a copy after it's cached

libkbfs/config_local.go
=> config_local: shutdown old dirty block cache on reset

libkbfs/folder_block_ops.go
Otherwise writes will fail needlessly.
Issue: KBFS-1179
=> folder_block_ops: don't notify listeners about recoverable errors

libkbfs/bserver_remote.go
If the network is completely down, this loop will otherwise go forever
since no references will ever be marked as failed and removed.
Issue: KBFS-1236
=> bserver_remote: avoid infinite loop on a complete downgradeRef err

kbfs/write.go, libdokan/dir.go, libfuse/dir.go, libkbfs/conflict_resolver_test.go, libkbfs/data_types.go, libkbfs/errors.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_cr_test.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/kbfs_ops_test.go, libkbfs/key_manager_test.go, libkbfs/mocks_test.go, libkbfs/rekey_queue_test.go, test/engine_libkbfs.go
[KBFS-1217](https://keybase.atlassian.net/browse/KBFS-1217)
=> add isExcl param to CreateFile

libkbfs/bserver_disk.go, libkbfs/bserver_tlf_journal.go, libkbfs/bserver_tlf_journal_test.go, libkbfs/disk_journal.go, libkbfs/mdserver_branch_journal.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_local_shared.go, libkbfs/mdserver_memory.go, libkbfs/mdserver_test.go, libkbfs/mdserver_tlf_storage.go, libkbfs/mdserver_tlf_storage_test.go, libkbfs/tlf_journal.go
Also pull out some shared journalling code into the
diskJournal type.
=> [KBFS-1098] Have per-branch journals for MDServerDisk

libkbfs/folder_block_manager.go
Since that could cause a near-infinite loop, spinning on waiting for
the next update to make it to the server.
=> folder_block_manager: don't re-enqueue deletes immediately

test/engine_libkbfs.go
=> engine_libkbfs: assign a debug tag to each operation

libkbfs/md_util.go
We were deep-copying and caching the wrong
MD object!
=> Fix bug in getMergedMDUpdates with decryption

libkbfs/reporter_kbpki.go
Issue: keybase/keybase-issues#2297
Issue: keybase/client#3158
Issue: keybase/client#2297
=> reporter_kbpki: blacklist more error names we've seen recently

libkbfs/folder_block_ops.go
#134 exposed some issues with `TestSimpleTruncate`, where a file is truncated to a larger size, leaving a hole in the file that is then filled in by subsequent writes.  If the subsequent sync is then retried due to a block archival error, we could accidentally forget to unreference the original "hole" block.
Furthermore, if "hole" writes are deferred, they weren't correctly counting their deferred write bytes, leading to unbalanced `DirtyBcache` counts.
Once this and #150 go in, I'll be able to merge #134.
=> folder_block_ops: fix issues related to writing in a "truncate hole"

libkbfs/test_stallers.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
This PR is pretty much #151 rebased to master, but created against master rather than `songgao/KBFS-1221`.
GitHub, please close #151 when this is merged.
=> add staller support to dsl tests

Jenkinsfile
KBFS-1271 #comment Clear workspace before building KBFS
=> Clear workspace before building

Jenkinsfile
=> Jenkins: Move GOPATH to go/, add BASEDIR variable

libkbfs/crypto_measured.go, libkbfs/folder_branch_status.go, libkbfs/init.go
Also add a metric for MakeMdID calls.
=> Add MD revision to .kbfs_status

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, test/qr_test.go
This is part 1 of the fix for KBFS-1202.
Issue: KBFS-1202
=> cr: don't bother resolving paths that were deleted on both sides

libkbfs/conflict_resolver.go, test/cr_simple_test.go
If the unmerged user removed several layers of directories, the
unreferenced blocks from deep in a tree need to also be unreferenced
in the resolution op.
Part 2 (of 2) to addressing KBFS-1202.
Issue: KBFS-1202
=> cr: unref blocks that were unlinked deep in a recursive rmdir

kbfs/write.go, libdokan/dir.go, libfuse/dir.go, libkbfs/conflict_resolver_test.go, libkbfs/data_types.go, libkbfs/errors.go, libkbfs/folder_block_manager_test.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_cr_test.go, libkbfs/kbfs_ops.go, libkbfs/kbfs_ops_concur_test.go, libkbfs/kbfs_ops_test.go, libkbfs/key_manager_test.go, libkbfs/mocks_test.go, libkbfs/rekey_queue_test.go, test/cr_simple_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go
Relevant JIRA Epic: [KBFS-1216](https://keybase.atlassian.net/browse/KBFS-1216)
=> O_EXCL Create

libkbfs/folder_block_manager.go
It's possible that a local operation was canceled, and never made it
to the service, and then no new operations are made.  So eventually we
need to just accept the fact that the revision never made it to the
server, and proceed with cleaning up the failed blocks.
=> folder_block_manager: don't keep checking blocks to delete forever

libkbfs/keybase_daemon_rpc.go
=> keybase_daemon_rpc: kick off rekeys on a PaperKeyCached message

dokan/testfs_test.go, libdokan/fs.go
Some antivirus products behave better with these flags.
=> dokan*: Change default mount flags

libkbfs/bserver_remote.go
The bug of KBFS-1287 is due to downgrade RPC not retried (when there's only one block nonce in the batch request). I cleaned up the retry logic and am now doing proper exponential backup on throttle error.
I also need to fix a few checks in bserver_test to make sure retried RPCs still result in test passing.
see https://github.com/keybase/kbfs-server/pull/73
=> Retry batchDowngrade in bserver_remote using exponential backoff

Jenkinsfile
Reviewed in keybase/client#3609
=> The mysql docker image sometimes gets corrupted for whatever reason. This is a workaround

kbfsdokan/README.md, libdokan/common.go, libdokan/dir.go, libdokan/folderlist.go, libdokan/fs.go
This should fix https://github.com/keybase/keybase-issues/issues/2248
=> libdokan: Support PRIVATE/PUBLIC for case insensitive link destinations

Jenkinsfile
Reviewed in keybase/client#3704
=> Factor out Jenkins helper methods

docker-compose.yml
=> gregor params

Jenkinsfile
=> Check gofmt in Jenkins

libkbfs/md_journal.go, libkbfs/md_journal_test.go
=> Fix nil dereference bug in mdJournal.clear

libkbfs/disk_journal.go, libkbfs/journal_server.go, libkbfs/md_id_journal.go, libkbfs/md_journal.go, libkbfs/md_journal_test.go
I.e., don't leave part of the MDs on the new branch.
Also, make sure that the branch IDs of the earliest
and latest MD are consistent.
=> [KBFS-1408] Do MD journal branch conversions atomically

libkbfs/folder_block_ops.go
=> folder_block_ops: add debugging for KBFS-1325

libfuse/mount_test.go
Otherwise there could be unexpected conflicts.
Issue: KBFS-1431
=> mount_test: after a create, sync the other user's folder

libkbfs/journal_md_ops.go, libkbfs/journal_server.go, libkbfs/md_journal.go, libkbfs/md_journal_test.go
Also put the currentUID and currentVerifyingKey parameters
first consistently (after ctx).
=> Check user/keys of RMDs retrieved from mdJournal

libkbfs/folder_block_manager.go
This PR is for [KBFS-1369](https://keybase.atlassian.net/browse/KBFS-1369)
=> libkbfs: include BadRequest as permanet error

libkbfs/folder_branch_ops.go
It seems there's a bug that runs into an infinite loop because a Sync
seems to make no progress, and it's instantly retried.  Not sure
what's going on, but it spams the logs and causes them to roll over to
fast to see the debugging.  So detect when it happens and panic
instead.
Issue: KBFS-1332
=> folder_branch_ops: panic if no sync progress

libkbfs/folder_branch_ops.go
Issue: KBFS-1332
Issue: KBFS-1446
=> folder_branch_ops: don't panic when there are no dirty refs!

libfs/remote_status.go
=> libfs: Fix remote status

libdokan/tlf.go
Just makes logging more precise and informative.
=> libdokan: Nicer logging of favorite removals

libdokan/dir.go, libdokan/file.go, libdokan/fs.go
No changes outside more logging on deletions.
=> libdokan: More logging on removals

libfs/remote_status.go
Related to https://github.com/keybase/client/issues/4091
Error out even more eagerly on startup.
=> libfs: Start with more eager errors

libkbfs/keybase_service_base.go
=> Wipe the key cache on logout

libkbfs/dirty_bcache.go, libkbfs/dirty_bcache_test.go
If no sync as large as the current buffer size was completed in the
last five minutes, this will reset the buffer size back to the minimum
and let it grow again according to the normal algorithm.  This lets us
adapt to suddenly changing network conditions (for example, a laptop
going offline and coming back online with a worse network).
Issue: KBFS-1414
=> dirty_bcache: reset sync buf capacity after 5 minutes

libkbfs/md_ops.go
=> Skip unembedded block change check for reader rekeys

libkbfs/md_ops.go
Don't let concurrent goroutines try to fetch the same ranges
concurrently when looking for the original MD that was copied into a
later revision.
Issue: KBFS-1483
=> md_ops: serialize getRange calls in verifyWriterKey

libkbfs/tlf_journal.go
=> tlf_journal: fix data race when flushing block entries

libkbfs/folder_block_manager.go
Random possible issue I noticed while debugging unrelated tests.
=> folder_block_manager: don't block delayed deletes after shutdown

libkbfs/config_local.go, libkbfs/folder_branch_ops.go, libkbfs/journal_block_server_test.go, libkbfs/journal_md_ops_test.go, libkbfs/journal_server.go, libkbfs/journal_server_test.go, libkbfs/journal_server_util.go, libkbfs/kbfs_ops.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
=> folder_branch_ops: when journaling, only archive merged revisions

appveyor.yml, libkbfs/block_id.go, libkbfs/hash.go
Suggested by @akalin-keybase.
Issue: #337
=> hash: fix receiver on UnmarshalJSON

circle.yml
Copy of circle from client, with tiny change to swap repo names
=> Circle CI (for mobile)

libkbfs/init.go
=> Add separate flags for bserver and mdserver existing in memory

libkbfs/config_local.go
Also add a comment about dirty bcache resetting.
FYI: `journalizeDirtyBcache()` is something I added to the `journalDirtyBlockCache` PR after you reviewed it, when I realized a call to `ResetCaches()` would delete the journal dirty bcache entirely.  I just realized we needed the same treatment for the regular bcache as well, so that `CheckForKnownPtr` is still disabled after a reset.
=> config_local: journalize clean block cache as well

libkbfs/block_journal.go, libkbfs/block_journal_test.go, libkbfs/disk_journal.go, libkbfs/md_journal.go, libkbfs/md_journal_test.go, libkbfs/tlf_journal_test.go
Do you think this needs tests?
Issue: KBFS-1410
=> journal: delete old journal entries and blocks

libdokan/mount_test.go, libfuse/dir.go, libfuse/mount_test.go, libkbfs/conflict_resolver.go, libkbfs/kbfs_cr_test.go, libkbfs/test_common.go, test/engine_libkbfs.go
=> delayed_cancellation: clean up stray delay goroutines

libkbfs/folder_branch_ops.go, test/journal_test.go
Otherwise journaling does no good.
=> folder_branch_ops: let excl creates hit the journal

libkbfs/folder_branch_ops.go, libkbfs/md_journal.go, libkbfs/md_journal_test.go, test/journal_test.go
=> journal: clear the mdJournal branchID after CR completes

libkbfs/mdserver_errors.go
=> Added MDServer error for trying to create too many folders

libkbfs/journal_server_test.go, libkbfs/key_manager_test.go, libkbfs/keybase_daemon_local.go
Also clean up favoriteStore implementations
and do operations on them under lock.
=> [KBFS-1543] Add setter for currentUID in KeybaseDaemonLocal

dokan/bridge.c
This is bad. Users really should install security fixes for Windows that are >5 years old.
=> dokan: Try to load dll on ancient machines without KB2533623

libkbfs/conflict_resolver.go, test/qr_test.go
=> cr: fix block unref issue for multi-sync CR, and add test

libkbfs/folder_block_ops.go
=> folder_block_ops: fix missing err check in truncateLocked

libdokan/dir.go, libdokan/file.go, libdokan/fs.go
=> libdokan: Handle deletions after renames properly

libkbfs/keybase_service_base.go
I tested that I still get a tracker popup for an unknown user with this change.
Issue: KBFS-1593
=> keybase_service_base: enable CanSuppressUI for Identify2

libkbfs/folder_branch_ops.go, libkbfs/tlf_journal.go
=> folder_branch_ops: check last flush error when waiting for journal

Jenkinsfile
=> Push KBFS to docker hub if triggered by client master

libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
=> tlf_journal: retry with exponential backoff after a flush fails

dokan/filesystem.go, libkbfs/block_journal_test.go
=> Misc cleanup

libkbfs/tlf_journal.go
Just the quickest fix I could think of.
Issue: KBFS-1615
=> tlf_journal: cap the number of revisions seen for journal status

libkbfs/config_local.go
Journals can reasonably take more than a minute in between MD
revisions.
Issue: KBFS-1625
=> config_local: bump up the QR min head age default

libkbfs/tlf_handle.go, libkbfs/tlf_handle_test.go
Issue: KBFS-1506
Issue: keybase/client#4659
=> tlf_handle: update cached name after updating extensions

libkbfs/tlf_journal.go
=> tlf_journal: always check we're enabled after taking the lock

libkbfs/folder_branch_ops.go
Suggested by @akalin-keybase.
Issue: #444
=> folder_branch_ops: fix setHead when there are no flushed updates

libkbfs/folder_branch_ops.go
=> Add check for journalPred in FBO

libkbfs/folder_branch_ops.go, test/journal_test.go
I noticed this when working on something else (and I think patrick hit it this weekend, though I didn't realize it at the time).  Without this change, if the current journal head gets too far past the latest known merged head, we end up trying to fast forward to the same journal head we already have, which causes a panic.
Also, there's no sense in applying remote updates while we have journaled writes, since they won't cleanly apply until we run CR.
=> folder_branch_ops: fix fast-forwarding and update-fetching when journaled

libkbfs/keybase_daemon_rpc.go, vendor/github.com/keybase/client/go/protocol/keybase1/common.go, vendor/github.com/keybase/client/go/protocol/keybase1/identify_ui.go, vendor/github.com/keybase/client/go/protocol/keybase1/provision_ui.go, vendor/github.com/keybase/client/go/protocol/keybase1/signup.go, vendor/vendor.json
IdentifyUI protocol changed.  This fixes KBFS side.
r? @strib
=> Revendor protocol/keybase1, update daemonIdentifyUI

kbfstool/md_check.go, libkbfs/bcache.go, libkbfs/block_journal_test.go, libkbfs/block_util.go, libkbfs/bserver_disk.go, libkbfs/bserver_memory.go, libkbfs/bserver_remote_test.go, libkbfs/conflict_resolver.go, libkbfs/cr_chains.go, libkbfs/data_types.go, libkbfs/errors.go, libkbfs/folder_block_manager.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/journal_block_server_test.go, libkbfs/journal_server_test.go, libkbfs/kbfs_ops_test.go, libkbfs/mocks_test.go, libkbfs/node_cache.go, libkbfs/node_cache_test.go, libkbfs/ops.go, libkbfs/ops_test.go, libkbfs/root_metadata.go, libkbfs/state_checker.go, libkbfs/tlf_journal_test.go
...and also to check the root blocks of all
non-GCed revisions.
Export a few needed types from libkbfs.
=> [KBFS-1599] Enhance md check tool to check chain

kbfstool/md_dump.go, libkbfs/ops.go
=> kbfstool: dump BlockPointers for md debugging

kbfstool/md_reset.go, libkbfs/bare_root_metadata_v2.go, libkbfs/bare_root_metadata_v3.go, libkbfs/config_local.go, libkbfs/conflict_resolver.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/key_bundle.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/root_metadata_test.go, libkbfs/test_common.go
This handles converting from MDv2 to MDv3.
=> bare_root_metadata: handle upconversion to v3

kbfstool/main.go, libkbfs/config_local.go, libkbfs/init.go, libkbfs/journal_block_server_test.go, libkbfs/journal_md_ops_test.go, libkbfs/journal_server_test.go, test/engine_fs_test.go, test/engine_libkbfs.go
=> [KBFS-1682] Pause journal bg work for kbfstool

libkbfs/conflict_resolver.go, libkbfs/cr_chains.go
If an rmOp only removes blocks that were created within a branch, we
can safely drop it.
A test that exercises this will be coming as part of KBFS-1653, but
isn't easily separated out from that PR.
=> cr_chains: remove rmOps that are entirely inter-branch

test/dsl_test.go, test/engine_fs_test.go, test/run_dokan_test.go
This is a speculative fix for the hang in KBFS-1694.
=> [KBFS-1694] Be careful about user cleanup in DSL tests

libkbfs/interfaces.go, libkbfs/journal_md_ops.go, libkbfs/journal_md_ops_test.go
Add comments to document MDOps/MDServer behavior.
=> [CORE-4114] Fix bug where GetForHandle returns a null ID

test/dsl_test.go, test/engine_fs_test.go, test/engine_libkbfs.go, test/run_dokan_test.go, test/run_fuse_test.go, test/run_kbfs_test.go
Tag contexts with username.
Add descriptions for all file ops and log them.
=> Improve DSL test logging

dokan/winacl/ace.go, dokan/winacl/debug.go, dokan/winacl/winacl.go, libdokan/emptyfs.go
+ Return a short DACL if requested GetFileSecurity
+ Easier debugging of winacl
+ Nothing changes for most things
=> Windows DACLs and winacl debugging

libkbfs/block_journal.go, libkbfs/block_journal_test.go, libkbfs/tlf_journal.go
Also fix up some log messages.
Issue: KBFS-1737
=> tlf_journal: call blockJournal.onMDFlush with the journal lock

libkbfs/folder_branch_ops.go
Looks like chat can send multiple `GetTLFCryptKeys` calls at once, and
they should be idempotent.  Without this change, the loser calls get
an MD conflict error.
Issue: KBFS-1742
=> folder_branch_ops: tolerate multiple racing calls to initMDLocked

libkbfs/md_journal.go
=> md_journal: fix off-by-one error in atLeastNNonLocalSquashes

README.md, vendor/github.com/keybase/client/go/libkb/globals.go, vendor/github.com/keybase/client/go/libkb/home.go, vendor/github.com/keybase/client/go/libkb/util_nix.go, vendor/github.com/keybase/client/go/libkb/util_windows.go, vendor/vendor.json
Depends on the matching core PR. This is for moving the target install/data directory from roaming to local 
@maxtaco @taruti
=> vendor update github.com/keybase/client/go/libkb for zanderz/CORE-3904

libkbfs/folder_block_manager.go
Two MDs may have the same data dir if they are both simple GCs, or one
is a GC and one is a no-op conflict resolution (say because the
unmerged branch contains only a GC).  So the code that checks whether
a canceled MD actually made it to the server should use an actual MD
ID for comparison, rather than the data dir.
Also, even if a GC op legitimately gets canceled and ends up on this
path, we should avoid ever archiving it, since that results in a
panic.
Issue: KBFS-1769
=> folder_block_manager: better check for MD equality

libkbfs/folder_block_ops.go
Use this new type in the Lookup execution flow.  Otherwise, the block
fetcher would r-unlock while fetching a remove block, leading to a
race like KBFS-1717 where the Lookup goroutine has a path that isn't
up-to-date by the time it tries to make a new node cache entry.
Suggested by @akalin-keybase.
Issue: KBFS-1760
Issue: #568
=> folder_block_ops: add blockLookup req type to avoid r-unlocks

libdokan/fs.go
=> libdokan: Log SID mismatch

libkbfs/bare_root_metadata_v2.go, libkbfs/folder_branch_ops.go, libkbfs/root_metadata_test.go
This reverts commit b7e03198929f74379fbf478fa3009e0e90fd7d07.
=> libkbfs: enable mdv3 writes

libdokan/mount_test.go
Otherwise, if we get a driver install error,
we will hang the test executable.
=> Unlock drive letter lock properly in dokan test

kbfstool/md_dump.go, libkbfs/root_metadata.go
In particular, the writer and reader key bundles.
Also have it dump the MD version info.
=> Make 'kbfstool md dump' dump extra metadata info

libdokan/start.go
=> skip mounting when path is 'none'

libkbfs/mdserver_remote.go
Condition the warning on rpc.StartingNonFirstConnection,
similar to other implementations of OnDisconnected.
=> Avoid spurious warning on kbfstool run

libkbfs/interfaces.go, libkbfs/key_bundle_cache.go, libkbfs/key_bundle_cache_measured.go, libkbfs/key_bundle_cache_test.go, libkbfs/md_ops.go, libkbfs/mocks_test.go
Also clarify comments re. cache misses.
=> Remove unnecessary indirection in KeyBundleCache

kbfscrypto/crypto_key_types.go, libkbfs/bare_root_metadata_v2_test.go, libkbfs/bare_root_metadata_v3_test.go, libkbfs/crypto_client_test.go, libkbfs/crypto_common.go, libkbfs/crypto_common_test.go, libkbfs/interfaces.go, libkbfs/key_bundle.go, libkbfs/key_bundle_v2.go, libkbfs/key_bundle_v3.go, libkbfs/key_manager.go, libkbfs/key_manager_test.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go
Also update references to KBFS crypto doc.
=> Split up Crypto.MakeRandomTLFKeys into two functions

libkbfs/kbfs_ops.go
This fixes up the by-favorite ops map when a handle changes due to resolved assertions, conflicts, or finalization.  One specific fix is that it makes sure `GetTLFCryptKeys` will lookup the correct TLF ID for the new folder, after a previous TLF is finalized.
I tried to come up with a good test for this, but since `MDServerLocal` doesn't support handle changes, and there's no good way for the existing kbfsdocker tests to check this, so I'm punting on a test for now.
Issue: KBFS-1802
=> kbfs_ops: process TLF handle changes

Jenkinsfile
Forgot to do this when splitting off
these dirs.
=> Add CI clauses for various new dirs

kbfstool/md_check.go, kbfstool/md_reset.go, libdokan/fs.go, libdokan/prefetch_file.go, libfs/constants.go, libfuse/prefetch_file.go, libfuse/special_files.go, libkbfs/bcache.go, libkbfs/block_ops.go, libkbfs/block_ops_test.go, libkbfs/block_retrieval_queue.go, libkbfs/block_retrieval_queue_test.go, libkbfs/block_retrieval_worker.go, libkbfs/block_retrieval_worker_test.go, libkbfs/block_types.go, libkbfs/dir_entry.go, libkbfs/dir_entry_test.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/md_util.go, libkbfs/mocks_test.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go, test/dsl_test.go, test/engine.go, test/engine_fs_test.go, test/engine_libkbfs.go, test/qr_test.go
This reverts commit ba62c0531e66a6713084e97987110006f7413543, reversing
changes made to b8233c5a108e039d567b6d128e6820be816d20f4.
=> [KBFS-1721] Re-Merge Prefetcher

appveyor.yml
Did this for Jenkins already, forgot to do it
for Appveyor.
=> Add more modules to test in Appveyor

libkbfs/file_data.go
fd.file.tailPointer() -> fd.rootBlockPointer()
Add childIPtr() accessor to parentBlockAndChildIndex.
Issue: #621
=> file_data: cleanup common accessor functions

libkbfs/journal_server.go, libkbfs/journal_server_util.go, libkbfs/tlf_journal.go
=> [KBFS-1522] Display stored bytes in statuses

libkbfs/cr_chains.go, libkbfs/cr_chains_test.go
This will reduce log spam with for big files with consecutive writes
that end up in CR (i.e., because of journal coalescing), and should
also reduce the size of CR MD updates a bit.
Issue: KBFS-1536
=> cr_chains: collapse syncOps into one when creating the chain

libkbfs/test_dynamodb_runner.go
=> Fix dynamo url

libkbfs/block_journal.go, libkbfs/tlf_journal.go
=> Remove disk limit logs

libkbfs/bcache.go, libkbfs/block_retrieval_worker_test.go, libkbfs/prefetcher_test.go
Also fixed a bug with the block cache where byte accounting broke if
permanent entries overfilled the cache.
=> [KBFS-1874] Prefetcher Regression Tests

libkbfs/mdserver_remote.go, vendor/github.com/keybase/client/go/protocol/keybase1/common.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/ctl.go, vendor/github.com/keybase/client/go/protocol/keybase1/identify.go, vendor/github.com/keybase/client/go/protocol/keybase1/metadata_update.go, vendor/github.com/keybase/client/go/protocol/keybase1/saltpack_ui.go, vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go, vendor/vendor.json
Looks like this needs to go in in order for https://github.com/keybase/client/pull/5521 to pass CircleCI
=> Implement MDServerRemote.FolderNeedsRekey

libkbfs/mdserver_remote.go
Nothing else to be done on client side for this ticket it seems?
=> use CDebugf instead of Debug

libkbfs/bcache.go, libkbfs/prefetcher_test.go
=> bcache: fix lifetimes returned by GetWithPrefetch

libkbfs/conflict_resolver.go
If this device has say one unmerged update, but there are 500+ merged
updates and they keep coming, then taking the local lock isn't going
to do any good because it doesn't stop the merged updates from coming.
Also, it might take a while to download those merged updates, and
since we only let ourselves take the lock for 10 seconds, CR will
never complete.
So this PR just doesn't count merged devices when taking a lock.  I
filed KBFS-1896 to explore doing "partial" CRs when the set of merged
updates is too large.
Issue: KBFS-1881
=> cr: don't count merged updates when deciding to take the lock

libkbfs/folder_branch_ops.go, libkbfs/key_manager.go
Since it's not really a "re"key.
Issue: KBFS-1879
=> key_manager: don't send rekey notifications on first key gen

libkbfs/mdserver_errors.go
=> mdserver: add error type for trying to read a finalized TLF

libkbfs/folder_branch_ops.go
Note: I have no way to test this yet, so I won't merge this until #693 is merged and keybase/kbfs-server#213 is merged/deployed, and I can test it against staging.
Issue: KBFS-1401
=> folder_branch_ops: locally finalize TLFs we can't read anymore

libkbfs/errors.go
I goofed and merged  https://github.com/keybase/kbfs/pull/704 into the wrong place, this is the same changeset.
=> Export rekey errors (2)

libkbfs/folder_block_manager.go, libkbfs/folder_block_manager_test.go
Since the QR revision is created and written while holding
mdWriterLock, and QR revisions now go through the journal just like
anything else, there's no point in trying to avoid making conflicts
with our own device.
=> folder_block_manager: don't delay QR when this device wrote head

libkbfs/md_ops.go
=> md_ops: extra GetForHandle debugging

kbfssync/semaphore.go, kbfssync/semaphore_test.go, libkbfs/backpressure_disk_limiter.go, libkbfs/config_local.go, libkbfs/semaphore_disk_limiter.go
Use it in the diskLimiter implementations.
=> Expose kbfssync.Semaphore.Count() method

libdokan/folderlist.go, libfuse/folderlist.go, libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops.go, libkbfs/mocks_test.go
This reverts commit fc1fe01935f1c5ed5a318074c18537adbde872c7.
=> Revert "folderlist: force a fast forward on a new user login"

libkbfs/backpressure_disk_limiter.go, libkbfs/backpressure_disk_limiter_test.go, libkbfs/block_disk_store.go, libkbfs/block_journal.go, libkbfs/block_journal_test.go, libkbfs/journal_server.go, libkbfs/semaphore_disk_limiter.go, libkbfs/tlf_journal.go, libkbfs/tlf_journal_test.go
Plumb it through to the diskLimiter, but don't use that info yet.
=> [KBFS-1869] Keep track of block journal file count

libkbfs/journal_server.go
Add akalin and strib to that list, for now.
=> Add mechanism for turning on EnableAuto based on UID

libkbfs/backpressure_disk_limiter.go, libkbfs/backpressure_disk_limiter_test.go, libkbfs/config_local.go, libkbfs/journal_server.go, libkbfs/semaphore_disk_limiter.go, libkbfs/tlf_journal.go
=> Show disk limiter status in .kbfs_status

vendor/github.com/keybase/client/go/logger/file.go, vendor/github.com/keybase/client/go/logger/formats_nix.go, vendor/github.com/keybase/client/go/logger/formats_windows.go, vendor/vendor.json
Sister PR in client: https://github.com/keybase/client/pull/5837
=> update vendor to include timezone in timestamp in logger

libkbfs/folder_branch_ops.go
Otherwise, if CR starts immediately and tries to look up the range of
unmerged updates, it won't include the (soon-to-be-set) head.  This
can cause CR to crash on an empty unmerged list, but even if we fix
that, it will be problematic because it might do CR over a partial set
of updates.
Issue: KBFS-1954
=> folder_branch_ops: don't start CR until the local head is set

libkbfs/util.go
=> libkbfs: Use base64.RawURLEncoding

libkbfs/keybase_daemon_rpc.go, simplefs/simplefs.go, simplefs/simplefs_test.go
=> Simplefs implementation 1/N

libkbfs/simplefs.go, libkbfs/simplefs_test.go
=> simplefs: Add cancellation delayers

libkbfs/backpressure_disk_limiter_test.go
=> [KBFS-1870] Add more checks in backpressure test

libkbfs/folder_branch_ops.go
This can happen naturally if the journal is really full and flushing
slowly, and we don't want KBFS to completely break in that case.
Instead, print a warning and keep trying, though we should still wait
for the ticker so we don't end up in a tight loop for too long.
(It's been a while since this panic found anything useful, and I really don't want KBFS to crash completely when the journal is full.)
=> folder_branch_ops: don't panic if no sync progress is made

libkbfs/tlf_journal_test.go
In rare cases, `testTLFJournalPauseBlocksAndConvertBranch` can return
before the journal is converted to a branch.  In that case wait
explicitly for the branch change before moving onto the next part of
the test.
cc: @songgao 
Issue: KBFS-1985
=> tlf_journal_test: fix race in TestTLFJournal/*WhileFlushing

libkbfs/conflict_resolver.go
The usage after a squash should be exactly the same as the final
unmerged MD was.
Issue: KBFS-1987
=> cr: avoid fetching any blocks for usage calculation for a squash

libkbfs/backpressure_disk_limiter.go, libkbfs/quota_usage.go
=> Add comments to clarify backpressure fields

libkbfs/folder_block_ops.go, libkbfs/folder_branch_ops.go
So that no file reads or writes can slip in after the pointers have been updated, but before the deferred writes have been applied.
When a write slipped in between the `UpdatePointers()` and `FinishSync()` calls, and there were deferred writes waiting for the same blocks affected by the new write, none of the dirtied blocks were making their way back into the dirty cache.  I wrote a test to reproduce the error on another branch, but with this refactoring the test is no longer valid, and no new tests should be needed.
Issue: KBFS-2004
=> folder_branch_ops: call FinishSync under same lock as updates

libkbfs/init.go
This is just reformatting, no code changes.  I'm going to be touching
this file soon, and was getting bothered by the long lines.
Issue: KBFS-1999
=> init: clean up line lengths

simplefs/simplefs.go, simplefs/simplefs_test.go
=> SimpleFSCheckOp, more testing

libkbfs/conflict_resolver.go
=> cr: avoid panic when unmerged list is empty

libkbfs/config_local.go, libkbfs/folder_branch_ops.go, libkbfs/md_util.go
@akalin-keybase: Sorry for jumping the gun on #849!
Issue: #849
=> libkbfs: implement akalin feedback on minimal mode

libkbfs/init.go
=> disk_block_cache: Start by default for Keybase users.

simplefs/simplefs.go
=> simplefs: Cancelling v1

libkbfs/journal_md_ops.go
We know for sure that all data is available locally.
On my work machine, this reduced the time to copy the Go source into KBFS from 4m50s to 4m25s, though the effect is probably better on slower internet connections.
Issue: KBFS-2038
=> journal_md_ops: avoid remote mdserver calls for squash branches

libkbfs/disk_block_cache.go
=> [KBFS-2058] Compact disk block cache asynchronously

libkbfs/journal_server.go
On my spinning disk, with 86 journals, this saves 15ms out of a total of 95ms. On my SSD it's basically negligible (2ms out of 24ms).  That said I don't see anywhere near the delays that were seen in KBFS-2057, so I'm not sure what this would be like on that device.  Still this doesn't seem like it's worse and doesn't make the code much more complicated, so it seems like it's worth merging.
Issue: KBFS-2057
=> journal_server: parallelize enabling TLF journals

libkbfs/journal_server.go
Since now it might be called in parallel by EnableExistingJournals,
this would cause a concurrent read/write map access failure.  Instead,
return the tlfJournal and have the caller add it to the map under the
lock.
Issue: KBFS-2065
=> journal_server: don't write to tlfJournals in enableLocked

libkbfs/disk_block_cache.go
The change is only in [this](https://github.com/keybase/kbfs/pull/893/commits/36d604e7ffd557e1bf08476b622018aeda60605b) commit. It'll get reduced once the dependent PR gets merged.
=> [KBFS-2066] Do less explicit compaction

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/vendor.json
Reviewed in keybase/go-framed-msgpack-rpc#112
=> Vendor fix for sporadic connection hangs

libkbfs/file_data.go, libkbfs/folder_branch_ops.go, libkbfs/root_metadata.go
To help pin down what's taking so long for a file removal.
Issue: KBFS-2080
=> file_data: extra debugging for getBlocksForOffsetRange

libkbfs/file_data.go
When getting the indirect blocks in a file, no need to iterate all the
children of a particular parent block every time.  If we see one child
more than once, we know we can safely skip to the next block in the
path.
Issue: KBFS-2080
=> file_data: cut out on repeated iterations of the same block

libkbfs/folder_block_ops.go
This was leading to test flakes by leaving around dirty blocks in the
test cache, even after the test did its final sync.
Issue: KBFS-2093
=> folder_block_ops: reset `doDeferWrite` after recoverable error

libfuse/dir.go, libfuse/mount_test.go, libfuse/tlf.go
By simply calling SyncAll() for that TLF.
(Depends on #909.)
Issue: KBFS-2070
=> libfuse: support directory syncing

libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops_test.go
cc: @akalin-keybase -- no need to review, I'll merge on CI passing.
Issue: KBFS-2074
Issue: KBFS-2075
Issue: #924 
Issue: #925
=> Address review feedback on KBFS-2074 and KBFS-2075

vendor/github.com/keybase/npipe/npipe_windows.go, vendor/vendor.json
Matches https://github.com/keybase/client/pull/6787. Upstream fixed a race condition; may help us.
=> merge upstream npipe

libkbfs/conflict_resolver.go, libkbfs/folder_update_prepper.go
If blocks have already been completely deleted on the merged branch, then CR over unmerged branch operations that also delete those same blocks don't need to bother unreferencing them.
This will be tested in a future PR for KBFS-2076.
=> cr: don't unref block IDs that have already been GC'd

libkbfs/folder_branch_ops.go
They're already handled by `folderBlockOps.CleanupSyncState()` (called
via the `cleanup` function returned by `startSyncLocked()`), and some
of those blocks might be re-used by subsequent retries.  So remove
them from the state passed to
`folderBlockManager.cleanUpBlockState()`.
Issue: KBFS-2145
=> folder_branch_ops: in SyncAll, don't clean up file blocks

libkbfs/folder_branch_ops.go
=> folder_branch_ops: trace SyncAll

libkbfs/config_local.go
=> config_local: increase batch size param to 100

libkbfs/folder_block_ops.go
=> folder_block_ops: track added sym links in the cache

libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/node_cache.go, libkbfs/node_cache_test.go
=> node_cache: add a way to undo unlinks and moves

libkbfs/init.go, libkbfs/keybase_service_util.go
Until the admins test it out a bit.
=> init: feature flag directory op batching

libkbfs/folder_block_ops.go
If a write is blocked on waiting for the dirty block cache to release
more bytes that can be dirtied, we have a mechanism where we can error
that write if something fatal and non-recoverable happens to an
existing sync that's currently draining the dirty bytes.  For example,
the user fills up their quota, and the sync fails, there's no reason
to accept the write knowing that it will just fail in the same way.
However, some tests cancels Syncs on purpose, but expect the next
Write to succeed, and there's no good way to tell for sure when the
Sync goroutine that was forked has finished.  (The actual Sync() call
could return earlier with the canceled error.)
We can safely ignore those errors, since the sync failing in that way
doesn't imply anything about syncs failing in the future.
Issue: …
=> folder_block_ops: can't cancel a write due to a sync context err

libkbfs/block_journal.go, libkbfs/block_journal_test.go, libkbfs/block_util.go, libkbfs/config_local.go, libkbfs/conflict_resolver.go, libkbfs/folder_branch_ops.go, libkbfs/journal_block_server.go, libkbfs/journal_md_ops.go, libkbfs/journal_server.go, libkbfs/mdserver_remote.go, libkbfs/tlf_journal.go
Set max trace events to 25, since it's not turned
on by default anyway.
=> [KBFS-2014] Add tracing for journal ops and SyncAll

libkbfs/mdserver_remote.go
Also avoid the need for idOrHandle type.
=> Refactor MDServerRemote get methods

libkbfs/kbfs_ops_concur_test.go
If we call numBlocks after canceling the SyncAll, we race with the
cleanup code that deletes the blocks we just put.  Instead, get the
numBlocks before the cancel.
Issue: KBFS-2131
=> kbfs_ops_concur_test: fix numBlocks race in ParallelBlocksCanceled

libkbfs/bserver_remote.go, libkbfs/bserver_remote_test.go, libkbfs/config_local.go, libkbfs/interfaces.go, libkbfs/mdserver_local_config.go, libkbfs/mdserver_local_config_test.go, libkbfs/mocks_test.go, libkbfs/test_common.go
This is needed to vendor kbfs into kbfs-server.
=> Export CurrentSessionGetter

libkbfs/folder_block_ops.go
There are two places while writes are blocked that can receive an
error from a failed Sync.  This factors out the error-checking code so
it can be used in both places.
Issue: KBFS-2164
=> folder_block_ops: check BOTH err listeners for a context cause

sysutils/pid_path_others.go
Reported by cobaugh.
Issue: #1000
=> sysutils: compile on FreeBSD/amd64

.gitignore, kbfsfuse/main.go, libkbfs/config_mock_test.go, libkbfs/constants.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/mdserver_disk.go, libkbfs/mdserver_memory.go, libkbfs/mdserver_remote.go, libkbfs/mocks_test.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/reconnect_backoff.go, vendor/vendor.json
This is a successor to https://github.com/keybase/kbfs/pull/992
Depends on https://github.com/keybase/go-framed-msgpack-rpc/pull/113
=> add random backoff to MD server reconnects

libkbfs/key_manager.go, libkbfs/key_manager_test.go
=> key_manager: get team TLF keys

libdokan/common.go, libdokan/fs.go, libdokan/mount_test.go
=> libdokan: support top-level team folderlist in devel mode

libkbfs/block_journal.go, libkbfs/reporter_kbpki.go, libkbfs/tlf_journal.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/kbfs_common.go, vendor/github.com/keybase/client/go/protocol/keybase1/paperprovision.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
=> libkbfs: include proper `keybase1.FolderType` field in client notifications

libkbfs/key_manager_test.go
Now that the rekey FSM ignores rekey requests when the promptPaper
flag is already set, it caused some tests to wait for long timeouts
for the events they sent to simulate the server returning their own
rekey-bit-set update.  So instead, don't wait for a complete rekey
event to finish in that case, just wait for the simulation event to be
processed.
=> key_manager_test: fix tests now that some rekey events are ignored

tlf/id.go
As discussed in Slack;
needed by https://github.com/keybase/kbfs-server/pull/322
=> expose tlf.Unknown

libkbfs/reporter_kbpki.go
=> reporter_kbpki: whitelist "Sony PlayMemories Home" lookups

libkbfs/folder_block_ops.go, test/simple_test.go
In a batch update, a file can later be renamed, so use the
setAttrOp.Name field to search for the Node to update doesn't make
sense.  Instead, just use setAttrOp.File, which is the BlockPointer
for the file whose attributes are being changed.
Issue: KBFS-2286
=> folder_block_ops: update attr using the BlockPointer, not name

libkbfs/folder_branch_ops.go
=> folder_branch_ops: extra debugging for TestSimpleTruncate flake

kbfscrypto/root_certs.go, libdokan/fs.go, libfuse/fs.go, libkbfs/kbfs_ops.go, libkbfs/keybase_service_util.go
Also add "core.keybase.io" to the list of prod domains.
=> libfuse/libdokan: enable teams for admins on staging

libkbfs/md_journal.go, libkbfs/tlf_journal.go
=> tlf_journal: more debugging for a test flake

libdokan/fs.go, libfuse/fs.go
And enable them for all users on staging.
(To be merged after we deploy prod.)
=> libfuse/libdokan: enable teams for admins on prod

libfuse/mount_test.go
Since the OS can reinstate a favorite with an ill-timed lookup and
there's not much we can do about it except retry.
I ran the test 10K times on OSX 10.10, and without this PR it reproduces the flake, and with it I couldn't get a reproduction.
Issue: KBFS-1370
=> mount_test: retry TestRemoveTLF a few times on OSX

tlf/id.go
=> tlf: make a panic-free way to access the TLF type

libkbfs/mdserver_memory.go
There were some functions in this struct, especially `Put()`, that
took the lock multiple times and assumed nothing would change between
the locks.  That led to a panic when md updates were put into the
blocklist out of order.
This refactors things a little to hold the lock over a full function,
and renames functions to make it clear when locks would be needed.
Issue: KBFS-2302
=> mdserver_memory: fix locking strategy

libfuse/mounter_osx.go
Most people would want a newer version than 3.2
=> Don't need to recommend specific version

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit_nix.go, vendor/vendor.json
One more callsite for res_init.
r? @strib
=> revendor go-framed-msgpack-rpc

libdokan/fs.go, libfuse/fs.go
@malgorithms wants this on for everyone in today's desktop release.  @jzila @songgao quick review please?
=> libfuse/libdokan: enable `team` in `ls` for everyone

libkbfs/mocks_test.go
=> mocks_test: fix missing interface updates

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit_darwin.go, vendor/vendor.json
Should fix a build break in FreeBSD. See
https://github.com/keybase/keybase-issues/issues/3022.
r? @strib
=> revendor resinit

libkbfs/bserver_remote.go
Otherwise OnConnect -> resetAuth -> CurrentSession() -> resetAuth,
which hangs trying to make an RPC because the RPC client is still
being initialized.
We already fixed this in mdserver_remote, but it's needed here too
because `serviceLoggedIn` also calls
`config.BlockServer().RefreshAuthToken(ctx)`.
Issue: KBFS-2328
=> bserver_remote: disallow resetAuth recursion

appveyor.yml, libdokan/mount_test.go
let's see what happens
@strib @taruti
=> update our Dokany drivers

libkbfs/conflict_resolver.go, libkbfs/folder_block_manager.go, libkbfs/folder_branch_ops.go, libkbfs/keybase_service_base.go, libkbfs/mdserver_remote.go, libkbfs/rekey_fsm.go, libkbfs/tlf_edit_history.go, libkbfs/tlf_journal.go, libkbfs/util.go, simplefs/simplefs.go
=> simplefs: support team paths and make log tag for each new operation

libfuse/dir.go, libkbfs/folder_branch_ops.go
=> debugging: add entry size logs for directory listing

libkbfs/constants.go
After this is publicly released, will increase to 20min. Then next time 1hr.
=> increase backoff window to 5min

libdokan/special_files.go, libdokan/update_history_file.go, libfs/constants.go, libfs/update_history.go, libfuse/special_files.go
Issue: KBFS-2363
Issue: keybase/client#8057
=> libdokan: support for the .kbfs_update_history file

libfs/file_info.go, libfs/fs.go, libfs/fs_test.go, libfs/mode.go, libfuse/dir.go
Depends on #1108.
Issue: KBFS-2338
=> libfs: support FileInfo methods in the billy FS layer

libfs/fs.go, libfs/fs_test.go
=> libfs: add dir-related operations for the billy FS layer

libfs/fs.go, libfs/fs_test.go
=> libfs: support changing attrs in the billy FS layer

libkbfs/config_local.go, libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/ongoing_work_limiter.go, libkbfs/rekey_fsm.go
=> limit number of ongoing rekeys

kbfsgit/runner.go
This improves performance when fetching multiple branches, such as during a clone.
It also avoids using bad characters in temporary refspecs.
=> kbfsgit: batch fetches together and fix int strings

kbfsblock/quota.go, vendor/github.com/keybase/client/go/protocol/keybase1/backend_common.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/vendor.json
I'll update `vendor.json` with the real client hash once I merge keybase/client#8275.
=> kbfsblock: update QuotaInfo for git blocks (and vendor git block type)

kbfsblock/quota.go
=> kbfsblock: fix `UsageStat.AccumOne` for git blocks

vendor/gopkg.in/src-d/go-billy.v3/util/util.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/status.go, vendor/vendor.json
=> vendor: update go-git and go-billy to their keybase fork master

kbfsgit/runner.go, vendor/gopkg.in/src-d/go-git.v4/options.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/common.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/diff_delta.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/scanner.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/updreq.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/revlist/revlist.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/status.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/http/receive_pack.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go, vendor/gopkg.in/src-d/go-git.v4/remote.go, vendor/gopkg.in/src-d/go-git.v4/repository.go, vendor/gopkg.in/src-d/go-git.v4/submodule.go, vendor/gopkg.in/src-d/go-git.v4/worktree.go, vendor/gopkg.in/src-d/go-git.v4/worktree_status.go, vendor/vendor.json
Also re-vendor in go-git to include some minor master performance improvements, and a new status stage.
Issue: KBFS-2404
=> kbfsgit: add memory profiles for each stage when verbosity >= 3

libgit/repo.go, libgit/repo_test.go
=> libgit: fix repo name regex

kbfsgit/runner.go, kbfsgit/runner_test.go, libfs/fs.go
This doesn't solve the memory/performance problems of big `pull`s, but optimizing for `clone` is an easy win.
Issue: KBFS-2416
=> kbfsgit: optimize `clone` by copying the raw object files out of KBFS

libfuse/start.go
In some cases, /keybase was not being mounted for macOS users, although the kbfsfuse binary was running fine.  On investigation, it looked like the osxfuse_mount call was giving up silently after 2 minutes.
According to osxfuse developer Ben Fleischer:
> This is most likely the reason for the issue you are seeing. In rare cases mount(2) performs a FUSE_STATFS operation after mounting the volume, but before returning control to mount_osxfuse. In this case calling mount_osxfuse synchronously will result a file system deadlock. I've ran into the same issue some time ago. To fix this mount_osxfuse needs to be called asynchronously. See https://github.com/osxfuse/fuse/commit/13ee6ec98e51cb76e2a6cfe80993e74c6073fe87 for the relevant libfuse commit.
Instead, we'll wait for the mount to be ready …
=> libfuse: serve FS requests before the mounter is ready to fix hang

kbfsgit/git-remote-keybase/main.go
Since the logging code steals os.Stderr, any fatal errors were only being written to the log and the user couldn't tell why things were failing.
=> git-remote-keybase: print fatal errors to original stderr

kbfsgit/runner.go
But still prints the total number of bytes so far.
Issue: #1154
=> kbfsgit: `recursiveByteCount()` to returns only subdir bytes

kbfsgit/runner.go, libgit/repo.go, libkbfs/data_types.go, libkbfs/favorites.go, libkbfs/favorites_test.go, libkbfs/interfaces.go, libkbfs/kbfs_ops_test.go, libkbfs/kbpki_client.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_daemon_rpc.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/mocks_test.go
=> libgit: update repo MD on create and push

libfs/fs.go, libfs/fs_test.go
=> libfs: handle /-prefix in filename creates and lookups

kbfsgit/runner.go
And add some log messages about what we're printing to errput, so things will be easier to debug later.
Issue: KBFS-2390
=> kbfsgit: add per-stage CPU profiling for verbosity >= 4

env/context.go, libkbfs/context.go, vendor/github.com/keybase/client/go/externals/test_common.go, vendor/github.com/keybase/client/go/libkb/constants.go, vendor/github.com/keybase/client/go/libkb/env.go, vendor/github.com/keybase/client/go/libkb/errors.go, vendor/github.com/keybase/client/go/libkb/login_state.go, vendor/github.com/keybase/client/go/libkb/notify_router.go, vendor/github.com/keybase/client/go/libkb/post.go, vendor/github.com/keybase/client/go/libkb/rpc_exim.go, vendor/github.com/keybase/client/go/libkb/saltpack_dec.go, vendor/github.com/keybase/client/go/libkb/socket.go, vendor/github.com/keybase/client/go/libkb/socket_nix.go, vendor/github.com/keybase/client/go/libkb/socket_windows.go, vendor/github.com/keybase/client/go/libkb/version.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/git.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
I think this is ready for review except for waiting on vendoring to fix `libkb/test_common.go`. I need this in master before I can merge the `gobind` changes, and I need those before I can uncomment the new methods, and put up a PR for the actual KBFS service for kbgit to talk to (it's pending).
Blocked on keybase/client#8425
=> [KBFS-2336] Add a new socket for kbgit->kbfsfuse communication

libkbfs/tlf_journal_test.go
When the background worker converts the MD journal to a branch, it sends out a pause signal before it finishes and sends a `nil` error back to the background loop.  Most of the time the background loop processes the pause first, but sometimes it apparently sees the `nil` first and goes into idle mode before going into pause mode.
I didn't see a way to force the loop to process one or the other first, so I just made it possible to expect a set of signals rather than just a single one.
Issue: KBFS-2440
=> tlf_journal_test: sidestep signal race in singleOp test

circle.yml, libgit/init.go, libgit/repo.go, libgit/repo_test.go, libgit/rpc.go, vendor/github.com/keybase/client/go/protocol/keybase1/kbfs_git.go, vendor/vendor.json
And vendor in the protocol changes for it.
Depends on keybase/client#8478, will revendor once that's merged.
Issue: KBFS-2435
=> libgit: implement the delete repo RPC call

appveyor.yml, libdokan/mount_test.go, libfs/fs_test.go, libfs/time_equal.go
Also fix resulting test failures.
=> Update Appveyor to go 1.9

libgit/repo.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/vendor.json
This will let the GUI do nicer things with them once they come out on the other end with proper error codes.
r? @strib
=> make git errors exportable

libdokan/folderlist.go, libdokan/fs.go, libdokan/start.go
Makes diagnosing errors a little bit easier.
=> libdokan: Better logging around CreateFile

kbfsgit/runner.go, kbfsgit/runner_test.go, libgit/repo.go, libgit/repo_test.go
=> kbfsgit: no lazy creates for team or single-user private TLFs

vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/dotgit.go, vendor/vendor.json
=> vendor: update go-git to get close error fix

libkbfs/test_common.go
(let's see if this passes tests...)
=> no more libkb G references, it's going away

kbfsgit/runner.go
=> kbfsgit: add some comments on the push optimizations

libkbfs/folder_block_ops.go
=> folder_block_ops: minimal mode doesn't have a node cache

kbfsgit/runner.go
It took me a while but I think this works now!
=> fix printing

kbfsblock/context.go
=> kbfsblock: include right type for non-data blocks in strings

libkbfs/folder_update_prepper.go, test/journal_test.go
A user in the wild had this happen:
* Device A: Removed a bunch of files
* Device B: Removed a bunch of files
* Device A: Flush to server.
* Device B: Notice conflict, resolve to local journal.
* Device B: Connectivity failure, flush pauses.
* Device A: Perform QR.
* Device B: Re-run conflict resolution on top of QR.
* Device B: Flush new MD to server.
Unfortunately, the new MD pushed in the last step still had the root block pointer from the QR's MD.  Basically, the folder_update_prepper didn't do anything interesting in the final CR because the real conflicts had already been resolved in the previous MD, and as a result, it never updated the root block pointer to what it had previously computed.
To get around this, if we pull in an update from a previous unmerged resolutionOp, update …
=> folder_update_prepper: update new MD's root ID if needed

libkbfs/folder_branch_ops.go
This fixes a race:
* CR input loop notices new work, creates a context, and starts a goroutine to do the CR.
* A write operation comes in from the user, grabs the mdWriter lock, finishes and calls cr.ForceCancel(), which cancels the CR context we just made.
* The CR goroutine now gets the mdWriter lock, and calls SyncAll, which includes the latest write.
* After the SyncAll finishes, it checks its context, sees that its canceled, and stops further processing.
* If no other writes happen, CR never starts up again.
Issue: KBFS-2505
Issue: keybase/client#8915
=> folder_branch_ops: check context during `syncAllUnlocked`

libkbfs/conflict_resolver.go
I spent a long time trying to figure out how an invalid merged path got into `getActionsToMerge` in the first place, but wasn't able to come up with a good theory in time, and I timed out.  Adding in debugging in case this happens again, as well as a check that will avoid the panic.
Issue: KBFS-2507
Issue: keybase/client#8937
=> cr: add debugging and checks for invalid path

libgit/repo.go, libgit/repo_test.go, vendor/github.com/keybase/client/go/chat/types/interfaces.go, vendor/github.com/keybase/client/go/chat/types/types.go, vendor/github.com/keybase/client/go/libkb/api_stub.go, vendor/github.com/keybase/client/go/libkb/chain_link.go, vendor/github.com/keybase/client/go/libkb/checkers.go, vendor/github.com/keybase/client/go/libkb/constants.go, vendor/github.com/keybase/client/go/libkb/errors.go, vendor/github.com/keybase/client/go/libkb/globals.go, vendor/github.com/keybase/client/go/libkb/interfaces.go, vendor/github.com/keybase/client/go/libkb/kbsig.go, vendor/github.com/keybase/client/go/libkb/keyfamily.go, vendor/github.com/keybase/client/go/libkb/login_state.go, vendor/github.com/keybase/client/go/libkb/notify_router.go, vendor/github.com/keybase/client/go/libkb/resolve.go, vendor/github.com/keybase/client/go/libkb/rpc_exim.go, vendor/github.com/keybase/client/go/libkb/sync_secret.go, vendor/github.com/keybase/client/go/libkb/test_common.go, vendor/github.com/keybase/client/go/libkb/upak_loader.go, vendor/github.com/keybase/client/go/libkb/util.go, vendor/github.com/keybase/client/go/logger/redirect_stderr_linux.go, vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go, vendor/github.com/keybase/client/go/protocol/chat1/common.go, vendor/github.com/keybase/client/go/protocol/chat1/gregor.go, vendor/github.com/keybase/client/go/protocol/chat1/local.go, vendor/github.com/keybase/client/go/protocol/chat1/notify.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/vendor.json
=>  return libkb.RepoDoesntExistError when deleting a nonexistent repo

dokan/cgo.go, dokan/error_file.go, dokan/filesystem.go, dokan/testfs_test.go
=> dokan: use stdlib context

libkbfs/keybase_daemon_rpc.go
The whole point of the pings is to force quick reconnects of KBFS to the service, if the service restarts.  However, if a ping itself gets "stuck" in a connection to a daemon that has restarted, we need to make sure that pings gets canceled so the next one will be sent.  So use 1 second timeout for that.
Issue: KBFS-2478
=> keybase_daemon_rpc: put short timeouts on service pings

LICENSE, dokan/LICENSE, dokan/README.md
* Update LICENSE year 2016 -> 2016-2017
* Copy LICENSE to dokan/
* Add notes to dokan README.md about licencing
Please review the notes in README.md.
=> dokan readme license

env/context.go, libkbfs/config_local.go, libkbfs/init.go, libkbfs/kbfs_service.go
Create a KBFS Service to allow applications to connect to it.
Protocols coming in a later PR.
=> [KBFS-2336] KBFS Service

libkbfs/journal_server.go
If a user had viewed a team folder while logged in, and then later logged out, the background quota reclamation process would try to re-enable the journal for that team folder, but would cause a crash. Instead, don't allow journal auto-creation when logged out.
This also re-arranges some error-checking in the journal enabling code, to make a little more sense.  And it nixes the confusing error message when `EnableExistingJournals()` is called multiple times in a row with the same UID.
Issue: KBFS-2503
=> journal_server: disable journal auto-creation when logged out

env/context.go, libdokan/createfile_test.go, libgit/rpc.go, libkbfs/bserver_remote.go, libkbfs/init.go, libkbfs/keybase_service_util.go, libkbfs/mdserver_remote.go, libkbfs/test_common.go
Initialize it in main functions only. Remove test instances and
other unused instances.
Also fix build tag in dokan test file.
=> Remove global libkb.G

libkbfs/keybase_service_base.go
The RPC connection might end up calling `KeybaseDaemonRPC.OnDisconnected()` during the RPC (especially if this RPC is initializing the connection for the first time), which calls `KeybaseServiceBase.clearCaches()`, which takes the `sessionCacheLock`.
Issue: keybase/client#9093
=> keybase_service_base: don't hold the sessionCachelock across RPCs

libkbfs/kbfs_ops.go
Deadlock:
* First call to `KBFSOps.TeamNameChanged` takes `opsLock`.
* Calls `go FolderBranchOps.TeamNameChanged()`.
* Releases `opsLock`.
* `FolderBranchOps.TeamNameChanged()` takes `headLock`.
* Second call to `KBFSOps.TeamNameChanged` takes `opsLock`.
* Calls `FolderBranchOps.getRootNode`, which blocks trying to acquire `headLock`.
* `FolderBranchOps.TeamNameChanged()` calls `KBFSOps.changeHandle()`.
* `KBFSOps.changeHandle()` tries to acquire `opsLock`.
* DEADLOCK.
Instead, make sure we don't hold `opsLock` when calling `getRootNode`.
Issue: KBFS-2565
=> kbfs_ops: avoid a deadlock on concurrent TeamNameChanged calls

libkbfs/folder_block_ops.go
=> folder_block_ops: limit number of workers when getting block sizes

kbfsfuse/defaults_production.go, kbfsfuse/main.go, libfuse/mounter.go
=> Revert "use default mount type by default and reinstall mountdir if needed"

libdokan/folderlist.go, libfuse/folderlist.go, libkbfs/tlf_handle.go, libkbfs/tlf_handle_resolve.go, simplefs/simplefs.go, test/engine_fs_test.go, tlf/name.go, tlf/name_test.go
...so that server code can use it.
Also rename function to CanonicalToPreferredName.
=> Move CanonicalName logic to tlf

kbfsblock/bserver_errors.go, kbfsblock/protocol_utils.go, libkbfs/bserver_remote.go
This is so that it can be used by test clients on the server.
=> Move some block protocol logic into kbfsblock

kbfsfuse/defaults_production.go, kbfsfuse/main.go, libfuse/mounter.go, libfuse/mounter_non_osx.go, libfuse/mounter_osx.go, libfuse/start.go, vendor/github.com/keybase/client/go/install/libnativeinstaller/app.go, vendor/vendor.json
This supersedes https://github.com/keybase/kbfs/pull/1291 which was reverted.
=> default mount type for prod & reinstall mountdir if fail on darwin

env/context.go
This first cleans up any existing socket files before trying to bind to it.
I've tested this on my Linux localhost and it works great.
I'd like a review by @oconnor663 and one of the KBFS folks.
=> context: Add cleanup function for kbfs socket

libfuse/start.go, libkbfs/kbfs_service.go, vendor/github.com/coreos/go-systemd/LICENSE, vendor/github.com/coreos/go-systemd/activation/files.go, vendor/github.com/coreos/go-systemd/activation/listeners.go, vendor/github.com/coreos/go-systemd/activation/packetconns.go, vendor/github.com/coreos/go-systemd/daemon/sdnotify.go, vendor/github.com/coreos/go-systemd/daemon/watchdog.go, vendor/github.com/keybase/client/go/systemd/systemd_linux.go, vendor/github.com/keybase/client/go/systemd/systemd_other.go, vendor/vendor.json
r? @jzila 
Dummy commit will need to get revendored after https://github.com/keybase/client/pull/9325 lands. Also I don't think there's any conflict with https://github.com/keybase/kbfs/pull/1299, but I'll test to make sure.
=> initial systemd support

libkbfs/init.go
tested on staging and it works!
Will submit a different PR for prod after deploying the new certs that have the new names in the SAN, perhaps Monday.
=> switch to new DNS name on staging

kbfsmd/flags.go
This helps when doing kbfstool md dump.
=> Add string methods for flag types

kbfscrypto/root_certs.go, vendor/github.com/keybase/client/go/libkb/ca.go, vendor/github.com/keybase/client/go/libkb/env.go, vendor/github.com/keybase/client/go/libkb/globals.go, vendor/vendor.json
depends on: https://github.com/keybase/client/pull/9404
=> include new domain (keybaseapi.com)

kbfsgit/runner_test.go, libgit/repo.go, libgit/rpc.go, vendor/github.com/keybase/client/go/protocol/keybase1/git.go, vendor/github.com/keybase/client/go/protocol/keybase1/home.go, vendor/github.com/keybase/client/go/protocol/keybase1/kbfs_git.go, vendor/github.com/keybase/client/go/protocol/keybase1/rekey.go, vendor/vendor.json
=> libgit: vendor new git gc RPC and implement it

libkbfs/conflict_resolver.go, test/cr_complex_test.go
If a directory was modified and then deleted on the unmerged branch, but modified on the merged branch, we only need to replay the unmerged "remove" operations.  Anything else like setAttrs and syncs are irrelevant, since the nodes were deleted.
In the course of debugging I factored out some logic into its own function.  I didn't end up needing to do that, but I kept it anyway as a nice cleanup.  It's unrelated to the rest of this PR.
Issue: KBFS-1691
Issue: keybase/client#9478
=> cr: only resurrect deleted, unmerged rm ops

libkbfs/prefetcher.go
KBFS-2588 had a panic with "decrementPrefetch overstepped its bounds", but it's difficult to disentangle from the log what happened because we didn't log the details of that panic, and the block being prefetched doesn't appear anywhere else in the log.
To address this, we unroll and log the recursive stack of prefetcher operations when we panic, including the PFID for every prefetch in the stack. That should help us figure out a repro when this happens again.
=> [KBFS-2588] Add logging when the prefetcher panics

dokan/cgo.go, dokan/dokan_test.go, libdokan/file.go, libdokan/fso.go, test/cr_basic_conflicts_test.go, test/cr_multi_blocks_test.go
Handle zero times better in Dokan.
Noticed while going through user bugs.
=> Dokan zero time

libkbfs/config_local.go, libkbfs/data_types.go, libkbfs/interfaces.go, libkbfs/kbpki_client.go, libkbfs/kbpki_util_test.go, libkbfs/keybase_daemon_local.go, libkbfs/keybase_service_base.go, libkbfs/keybase_service_measured.go, libkbfs/mocks_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/identify.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_badges.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
This is PR 1/3 for implicit team handle stuff.
=>  libkbfs: add service implicit team methods

libkbfs/tlf_handle_resolve.go, libkbfs/tlf_handle_test.go
=> tlf_handle: don't call resolve implicit teams for now

libgit/rpc.go
Otherwise, a journal will be created for the TLF under the normal Config, and later journal calls on the git Config will fail due to a missing handle.
=> libgit: construct the git Config before getting the TLF handle

libkbfs/mdserver_remote.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/vendor.json
so that we can get these logs without turning on debug logging for KBFS on mobile.
=> change some Debug to Info and resolve a TODO

libkbfs/bserver_remote.go, libkbfs/constants.go, libkbfs/mdserver_remote.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/vendor.json
Depends on: https://github.com/keybase/go-framed-msgpack-rpc/pull/128
Will update vendor to master once that is in.
=> add a dialer timeout

libkbfs/journal_server.go, libkbfs/journal_server_test.go
So they don't stick around, cluttering up the directory and making future restarts slower.
Issue: KBFS-2644
=> journal_server: nuke empty journals on restart

libkbfs/keybase_service_base.go
=> keybase_service_base: pass tlf type to iteam creation

kbfsfuse/kbfsfuse.sh
=> kbfsfuse: update the md version for the startup script

kbfsgit/runner.go
Previously we were using the number of users in the handle, which breaks for implicit teams.  So instead use the type, and for private TLFs, use the full name and see if multiple users are listed.
=> kbfsgit: use handle type/name to check if tlf is managed by app

libkbfs/kbpki_client.go
The service returns a `libkb.NotFoundError` when trying to load a team if you're not a member of that team.  We don't want that error to propagate up to the rest of KBFS, since we might be checking writership in order to set permissions on a file in a public TLF, for example.  So ignore those errors in the public iteam case, and avoid trying to load the team at all if we're not logged in.
=> kbpki_client: handle errors during writer checks for public iteams

libfs/fs_notifications.go
Fixes https://keybase.atlassian.net/browse/KBFS-2461
=> fs_notifications: Fix potential panic due to closed channel

libgit/worktree_storer.go
=> libgit: documentation nits suggested by songgao

vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/kbfs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go, vendor/vendor.json
cc: @maxtaco 
Issue: CORE-6789
=> vendor: update keybase1 protocol to get new saltpack behavior

libkbfs/interfaces.go
=> interfaces: update WrapChild comment with jzila's text

libgit/repo.go
=> libgit: Fix commit hash encoding.

libfs/file.go, libgit/autogit_manager.go, libgit/autogit_manager_test.go, libgit/autogit_node_wrappers.go, libgit/autogit_node_wrappers_test.go, libkbfs/folder_branch_ops.go, libkbfs/key_manager_test.go, libkbfs/test_common.go
This depends on #1423 and that one should be reviewed before this one.
Issue: KBFS-2678
=> libgit: update autogit dir when corresponding repo is updated

libgit/worktree.go, libgit/worktree_test.go
=> libgit: optimization to avoid resets when already up-to-date

libfs/file.go, libkbfs/journal_server.go, libkbfs/tlf_journal.go
If we're not in single-op mode, we could have built up multiple revisions in the journal, and so calling `FinishSingleOp` isn't allowed in that case.
Issue: KBFS-2678
=>  libfs: don't use `FinishSingleOp` when not in single-op mode

tlf/handle.go
I need this to be able to check whether two handles are properly equal.
=> tlf: Add DeepEqual verifying method.

libgit/worktree.go
Variable renaming suggested by songgao.
=> libgit: remove HEAD file on reset error, and rename vars

libgit/autogit_manager.go, libgit/autogit_manager_test.go
=> libgit: give AutogitManager a `Delete` function

libgit/autogit_node_wrappers.go, libpages/root.go
Tested on staging and made sure it works for both team folder and team git.
=> kbp: fix team git site root

Makefile, kbfsgit/runner.go, kbfsgit/runner_test.go, libgit/repo.go, vendor/github.com/keybase/client/go/protocol/keybase1/delegate_ui_ctl.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/git.go, vendor/github.com/keybase/client/go/protocol/keybase1/home.go, vendor/github.com/keybase/client/go/protocol/keybase1/home_ui.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go, vendor/vendor.json
=> [KBFS-2730] Implement new Push Type RPC

libkbfs/keybase_daemon_rpc.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_team.go, vendor/vendor.json
needed for https://github.com/keybase/client/pull/10271 to pass circle ci
=> Vendor team notification protocol change, placeholder

vendor/github.com/keybase/client/go/protocol/keybase1/git.go, vendor/vendor.json
=> Revendor from master

kbfsgit/runner.go, kbfsgit/runner_test.go, libgit/repo.go
cc @patrickxb 
cc @keybase/kbfs-hackers
=> [KBFS-2730] Pass branch deletions to the GitLocalMetadata RPC

simplefs/simplefs.go, simplefs/simplefs_test.go
[Note that this PR is mostly just me getting my feet wet for SimpleFS -- for KBFS-2661 this code will be largely rewritten, but I thought it would be nice to have a working test in place before that happens.]
Issue: KBFS-2737
=> simplefs: fix CopyRecursive-to-local by not trying to open dirs

libkbfs/bserver_remote.go, libkbfs/mdserver_remote.go, libkbfs/shared_keybase_transport.go, vendor/github.com/keybase/client/go/logger/rpc_adapter_depthadder.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection_log.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection_test_util.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/log.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/reconnect_backoff.go, vendor/vendor.json
I had to merge client first to vendor from client master. So client master CircleCI will fail until this is merged.
=> update rpc and logger vendor

simplefs/simplefs.go, simplefs/simplefs_test.go
This is needed by https://github.com/keybase/client/pull/10483
=> support listing /keybase in simplefs

libkbfs/config_local.go
Noticed while debugging something else.
Issue: KBFS-2809
=> config_local: tiny code cleanup

redirector/main.go
Having an entry here will prevent other mounts from mounting over it, since it will be non-empty.  That means future `run_keybase` calls won't keep spinning up new redirector processes, due to the fact that the running-as-root mount process sees an empty mountpoint.
For now, I just did the simplest thing: a symlink called "KBFS_NOT_RUNNING" that points to /dev/null.  In the future, it might be nice to have it point to a README file somewhere on disk, but that would be a bigger undertaking.
Issue: #1510
=> redirector: add a /keybase entry when KBFS is not running

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/transport.go, vendor/vendor.json
Upstream PRs:
https://github.com/keybase/go-framed-msgpack-rpc/pull/136
https://github.com/keybase/go-framed-msgpack-rpc/pull/137
=> update rpc vendor; fixes keybase/client#10172

simplefs/simplefs.go, simplefs/simplefs_test.go
=> simplefs: address jzila feedback on progress tracking

simplefs/simplefs.go, simplefs/simplefs_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/ephemeral.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
CircleCI will fail until keybase/client#10996 is merged.
Issue: KBFS-2797
=> simplefs: add hidden file filter

kbfsgit/runner.go
=> kbfsgit: don't send MD updates for pushes that errored

circle.yml
Matches this soon-to-be-merged PR: https://github.com/keybase/client/pull/11122
=> Increase max java heapsize to match keybase/client changes

vendor/github.com/keybase/client/go/protocol/keybase1/crypto.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/pgp.go, vendor/vendor.json
=> vendor: update keybase1 for migration to real commit ID

libkbfs/conflict_resolver.go
This is an attempt to fix the automatic unstaging that happens when a user is so far out of date that they can no longer fetch some of the blocks necessary to run conflict resolution.
Issue: KBFS-2918
=> cr: always return `merged` from `buildChainsAndPaths`

libhttpserver/server.go
related: https://github.com/keybase/client/pull/11671
=> use higher ports for http server

libhttpserver/server.go, libhttpserver/server_test.go, simplefs/simplefs_test.go
=> handle backgroud properly in libhttpserver

dokan/bridge.c, dokan/bridge.h, dokan/cgo.go, dokan/loaddll.go
=> dokan: Move DLL loading logic from C to Go and add debugging

README.md
Suggested by 0mp.
Issue: #1576
=> README: mention FreeBSD support.

Jenkinsfile, appveyor.yml
Also reduce a few timeouts to 30s.
=> Run more tests in CI

libkbfs/folder_branch_ops.go
Otherwise the caller could cancel `ctx` after we return, and the block retriever will cancel the block fetch, and the bserver will log a warning about a context being canceled.
=> folder_branch_ops: use fresh ctx when prefetching TLF root block

kbfsedits/data_types.go, tlf/id.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/gpg_ui.go, vendor/github.com/keybase/client/go/protocol/keybase1/merkle.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
In the future, we'll write a json-encoded version of this message for each new operation, in a kbfs-edits chat channel.
Issue: KBFS-2992
=> kbfsedits: introduce `NotificationMessage`

libkbfs/chat_rpc.go, libkbfs/interfaces.go, libkbfs/keybase_daemon.go, libkbfs/mocks_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/extras.go, vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go, vendor/vendor.json
This is untested, but it's also unused.  Plumbing it through will require a bit more work, plus a client<->kbfs commit dance, so I thought we should get this piece reviewed first so the PR doesn't get too unwieldy.
Issue: KBFS-2993
=> libkbfs: add a chat interface and an initial RPC implementation

libdokan/start.go, libfuse/start.go, libkbfs/init.go, libkbfs/keybase_daemon.go, libkbfs/keybase_daemon_rpc.go
This would need to go in along with https://github.com/keybase/client/pull/12268
Circle CI will fail, but I tested an iOS build locally and it works.
=> fix protocol registration race and cleanup init code

libgit/init.go, libkbfs/config_local.go, libkbfs/config_mock_test.go, libkbfs/init.go, libkbfs/interfaces.go, libkbfs/keybase_daemon.go, libkbfs/mocks_test.go
Based on #1600.  Shouldn't be merged until keybase/client#12266 is merged.
Issue: KBFS-2993
=> libkbfs: make Chat instance and add it to Config

libkbfs/unflushed_path_cache.go, test/journal_test.go
Otherwise, it's impossible to know the tlf type of the folder with unflushed paths!
=> tlf_journal: report the full canonical path for unflushed files

libkbfs/chat_local.go, libkbfs/chat_rpc.go, libkbfs/interfaces.go, libkbfs/keybase_daemon.go, libkbfs/mocks_test.go, libkbfs/root_metadata.go, libkbfs/test_common.go, libkbfs/util.go
This is in preparation for having notification tests in libkbfs, though it is currently untested.
Issue: KBFS-2996
=> chat: implement local chat server, and tweak interface a bit

simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_badges.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
Related protocol change: https://github.com/keybase/client/pull/12523 Will re-vendor here after it's merged.
=> simplefs: populate writable

libkbfs/keybase_service_base.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_team.go, vendor/vendor.json
Client PR: https://github.com/keybase/client/pull/12547
=> Add KeybaseDaemonRPC.AvatarUpdated to satisfy NotifyTeamInterface

libkbfs/tlf_journal.go
(This is the real fix for KBFS-3101.)
Otherwise, if the journal flushes and the cache is cleared, we don't try to complete the initialization on the new instance of the object.
Issue: KBFS-3101
=> tlf_journal: save unflushedPathCache during initialization

vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
=> vendor: update keybase1 to get new simplefs methods

kbfsedits/read.go, libkbfs/chat_rpc.go, libkbfs/folder_branch_ops.go, libkbfs/kbfs_ops.go
(Depends on #1631.)
Issue: KBFS-3000
=> folder_branch_ops: enable notification messages

kbfsedits/tlf_history.go, kbfsedits/tlf_history_test.go, libkbfs/cr_chains.go, libkbfs/folder_branch_ops.go, test/edit_history_test.go
This PR adds support for renamed parent directories to `TlfHistory`, to make sure that the full paths of edited files reflect any renames on their parent directories.
Also, there was a bug with sending edit notifications for rename operations -- instead of a single rename, they were being sent as separated delete+create notifications.  This PR fixes that, and adds tests.
Issue: KBFS-3073
=> kbfsedits: handle renames of parent directories

libkbfs/kbfs_ops.go
Otherwise after a reconnection, the FBOs might have missed some edit notifications and wouldn't ever refresh their state.
Issue: KBFS-3136
=> kbfs_ops: trigger edit history re-inits in all FBOs

libkbfs/interfaces.go, libkbfs/mocks_test.go, libkbfs/reporter_kbpki.go, libkbfs/reporter_simple.go, simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/ephemeral.go, vendor/github.com/keybase/client/go/protocol/keybase1/gregor_ui.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
KBFS side of https://github.com/keybase/client/pull/12737
=> implement SimpleFSSuppressNotifications

simplefs/simplefs.go, simplefs/simplefs_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/constants.go, vendor/github.com/keybase/client/go/protocol/keybase1/kbfs.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
Will need to re-vendor from master when keybase/client#12682 is merged. CircleCI will fail until then.
This is ready for review. LMK if you'd like some tests to validate the refactor.
Reviewers: [w=1](https://github.com/keybase/kbfs/pull/1659/files?w=1) is your friend here.
=> [KBFS-3052] vendor: pull new SimpleFSRecursive API from client

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/packetizer.go, vendor/vendor.json
This fixes CORE-8323 and CORE-8311.
=> Vendor RPC

libkbfs/chat_rpc.go, vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go, vendor/github.com/keybase/client/go/protocol/chat1/common.go, vendor/github.com/keybase/client/go/protocol/chat1/extras.go, vendor/github.com/keybase/client/go/protocol/chat1/gregor.go, vendor/github.com/keybase/client/go/protocol/chat1/local.go, vendor/github.com/keybase/client/go/protocol/chat1/notify.go, vendor/vendor.json
Update `ChatRPC` to implement the `chat1.NotifyChatInterface` with the proposed changes in https://github.com/keybase/client/pull/12896
cc @mmaxim once the client since is approved i'll merge this so ci can pass on the client
=> vendor chat1 updates

libkbfs/chat_rpc.go, vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go, vendor/github.com/keybase/client/go/protocol/chat1/common.go, vendor/github.com/keybase/client/go/protocol/chat1/extras.go, vendor/github.com/keybase/client/go/protocol/chat1/gregor.go, vendor/github.com/keybase/client/go/protocol/chat1/local.go, vendor/github.com/keybase/client/go/protocol/chat1/notify.go, vendor/vendor.json
Once https://github.com/keybase/client/pull/12963 is merged will revendor to get the proper commit hashes
=> Vendor chat1 updates for ConvSettings

simplefs/simplefs.go
=> Revert "[KBFS-3240] Fix windows uploads"

simplefs/simplefs.go, simplefs/simplefs_test.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
This depends on #1706 and keybase/client#12998, and won't pass circle until keybase/client#12850 is also merged.
Issue: KBFS-3209
=> simplefs: support time-based archive branches

libkbfs/init.go
=> init: flip on mdv4 for prod

libkbfs/prev_revisions.go
jzila called it.
Some user reported an issue where the count can reach 255.  I can't repro it yet, but I suspect it has to do with removing revisions from the front of the list when running conflict resolution, and thereby letting the entries at the end of the list build up their count.
=> prev_revisions: avoid panic when count is about to overflow

simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/home.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
Will update vendor to master when merging. Client PR: https://github.com/keybase/client/pull/13165
=> add filter to SimpleFSSyncStatus

libkbfs/block_types.go, libkbfs/data_types.go
=> data_types: introduce new data type for indirect dir blocks

libkbfs/block_tree.go, libkbfs/file_data.go
(Depends on #1732.)
Another simple refactor, with no logic changes.
Issue: KBFS-3299
=> block_tree: refactor generic `getBlocksForOffsetRange` function

libkbfs/keybase_service_base.go, vendor/github.com/keybase/client/go/protocol/keybase1/account.go, vendor/github.com/keybase/client/go/protocol/keybase1/config.go, vendor/github.com/keybase/client/go/protocol/keybase1/ephemeral.go, vendor/github.com/keybase/client/go/protocol/keybase1/notify_team.go, vendor/github.com/keybase/client/go/protocol/keybase1/teams.go, vendor/vendor.json
cc @jzila || @strib for thumbs
=> Add NewlyAddedToTeam for NotifyTeamInterface

libkbfs/block_types.go
=> block_types: copy indirect ptrs on a dirblock deep copy

libkbfs/block_tree.go, libkbfs/file_data.go
Move them out of `fileData`, so that `dirData` can share them in a future commit.
=> block_tree: refactor methods for getting indirect infos

libkbfs/cr_chains.go
=> cr_chains: don't try to surgically cut the last op of a slice

env/context.go, kbpagesd/main.go, libdokan/start.go, libfuse/start.go, libhttpserver/server.go, libhttpserver/server_test.go, libkbfs/conflict_resolver_test.go, libkbfs/kbfs_ops_test.go, libkbfs/test_common.go, simplefs/simplefs.go, simplefs/simplefs_test.go
The remaining ones are in env.
Clean up AppStateUpdater a bit.
=> Remove dependencies on libkb.GlobalContext

libkbfs/chat_rpc.go, vendor/github.com/keybase/client/go/protocol/chat1/chat_ui.go, vendor/github.com/keybase/client/go/protocol/chat1/gregor.go, vendor/github.com/keybase/client/go/protocol/chat1/local.go, vendor/github.com/keybase/client/go/protocol/chat1/notify.go, vendor/vendor.json
TODO:
@keybase/kbfs-hackers can someone take a look?
=> Add ChatSubteamRename for ChatRPC

vendor/github.com/keybase/go-keychain/corefoundation_1.10.go, vendor/vendor.json
=> vendor go-keychain

kbpagesd/main.go
This models the same thing we do for kbfsfuse and kbfsdokan. `StartAutogit` installs a root wrapper that must be installed before any `folderBranchOps` instances are created.  And the edit history code can create `folderBranchOps` instances as soon as the RPC connection to the service is established.
[I know this is a bit of a hack.  A better way might be to have `StartAutogit` install its wrappers on every existing FBO, but that's not really easy because the relevant Nodes might already be created by that time.  Open to other suggestions.]
=> kbpagesd: initialize autogit before the service conn is complete

libhttpserver/server.go, vendor/github.com/keybase/client/go/kbhttp/srv.go, vendor/vendor.json
KBFS side of https://github.com/keybase/client/pull/13666
=> use different port if the pinned one is taken

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/connection_test_util.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/errors.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/log.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/log_test_util.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/packetizer.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/protocol.go, vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/transport.go, vendor/vendor.json
Some new debug stuff is coming along for the ride.
Issue: KBFS-3404
=> vendor: update go-framed-msgpack-rpc to get reconnect-on-retry fix

vendor/github.com/keybase/client/go/libkb/msgpack.go
this file was missing in the vendor package
=> Add missing libkb file

simplefs/simplefs.go
It could result in a deadlock, and is bad practice anyway.
Issue: KBFS-3440
=> simplefs: don't hold locks while processing BatchChanges callback

appveyor.yml, dokan/dokan_header/dokan.h, dokan/dokan_header/fileinfo.h
Appveyor passes, but let us wait with merging till everything is clear.
=> Dokan 1.2 and amd64 CI

simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
As discussed in kbchat, we should only hide system hidden files, thus the change.
This needs to go in with https://github.com/keybase/client/pull/13927 . After that's in, I'll update all commit hashes to master.
=> simplefs: add FILTER_SYSTEM_HIDDEN_2 to only filter system hidden files

Jenkinsfile
mirrors change in client: https://github.com/keybase/client/pull/14202/
=> fix golint

libkbfs/disk_block_cache.go, libkbfs/disk_block_cache_wrapped.go, libkbfs/leveldb.go
=> leveldb: factor out some code that will be useful for other DBs

libgit/browser.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go, vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/object.go, vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go, vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go, vendor/vendor.json
=> autogit: use `Tree.Size()` to speed up stats

libkbfs/disk_block_cache.go
=> disk_block_cache: address jzila review comments

libkbfs/backpressure_disk_limiter.go, libkbfs/config_local.go, libkbfs/init.go
=> libkbfs: set default sync block cache size to 100%

vendor/github.com/syndtr/goleveldb/leveldb/db.go, vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go, vendor/github.com/syndtr/goleveldb/leveldb/db_util.go, vendor/github.com/syndtr/goleveldb/leveldb/db_write.go, vendor/github.com/syndtr/goleveldb/leveldb/session.go, vendor/github.com/syndtr/goleveldb/leveldb/session_util.go, vendor/github.com/syndtr/goleveldb/leveldb/storage.go, vendor/github.com/syndtr/goleveldb/leveldb/table.go, vendor/github.com/syndtr/goleveldb/leveldb/util.go, vendor/vendor.json
mirrors https://github.com/keybase/client/pull/14557
=> govendor update leveldb

libkbfs/mdserver_remote.go
This RPC is on the critical path for parsing implicit team handles, so needs to be available offline.  But in the offline case, the latest cached MD should be good enough.  The call is only there to prevent using an old TLF ID from a TLF that's already been finalized.
With this PR, the offline mdserver test gets farther when enabled, though it still doesn't pass.
Issue: KBFS-3579
=> mdserver_remote: get latest handle from cache when disconnected

libkbfs/config_local.go
In the future, we'll need to add other fields in here to support partial syncing on a subfolder basis.
Issue: KBFS-3516
=> config_local: use a struct for values in the synced TLF DB

libkbfs/backpressure_disk_limiter.go, libkbfs/disk_block_cache.go, libkbfs/disk_limits_test.go, libkbfs/disk_limits_unix.go, libkbfs/disk_limits_windows.go, simplefs/simplefs.go, vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go, vendor/vendor.json
And return it in the SimpleFS folder sync status, so the GUI can show a warning if it wants.
Issue: KBFS-3518
=> disk_block_cache: include local disk availability in cache status

vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/message.go, vendor/vendor.json
Fix for decoding in `CallCompressed`
=> revendor rpc

libkbfs/chat_rpc.go
=> use proper chat identify mode for all file edit calls

libkbfs/data_types.go, libkbfs/prefetcher.go, libkbfs/prefetcher_test.go
When prefetching an indirect block and syncing is enabled, we should prefetch all the way down to the tail blocks, because it doesn't make sense to sync just part of a multi-block object.
This will be important for partially-synced paths.  For example, if syncing path `a/b/c`, and directory `a` is a multi-block directory, we should sync all of the blocks of `a`.  That way `ls a` can succeed while offline, while the user is navigating up to `a/b/c`.
=> prefetcher: prefetch up to tail blocks when syncing

libkbfs/folder_block_manager.go, libkbfs/folder_branch_ops.go, libkbfs/interfaces.go
Modify the background cleanout of the sync cache to also cleanout the working set cache.
=> disk_block_cache: clean out working set cache regularly

libfs/file_info.go, libfs/fs.go, libgit/autogit_manager.go, libgit/browser.go, libgit/browser_test.go, libgit/shared_browser_cache.go, libkbfs/folder_branch_ops.go, libpages/root.go, libpages/server.go
@strib I added a fast mode for Pages, hopefully temporary before we figure out a better solution that can benefit autogit itself too.
=> cache dirChildren in autogit and fast mode in libpages

libkbfs/mdserver_remote.go
This waits 500ms for a server response before giving up and using the cached MD if there is one.
In most cases `folderBranchOps` will roll forward to the latest revision without this fix, but in the meantime bad stuff can happen: if it's an unsynced TLF, the user can get "block not found" errors, or rekeys/upgrades can fail because of conflicts.
Issue: KBFS-3665
Issue: KBFS-3676
=> mdserver_remote: use short timeout to check server for latest TLF

libkbfs/chat_rpc.go
=> chat_rpc: only send edit notifications on favorited TLFs

libkbfs/file_data.go
This fixes test flakes that have increased recently (such as `TestTruncateLargeThenWriteToSmallerOffsetWithHoles`).
=> file_data: mark correct path dirty when clearing iptr sizes

libkbfs/prefetcher_test.go
=> prefetcher_test: get cache bytes under a lock

libkbfs/favorites.go, libkbfs/favorites_test.go
I realized this was never being created since the directory does not exist while working on another thing stored on disk.
=> favorites: create directory for favorites disk cache
